### PR TITLE
Boats: New nodebox rowing boat

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20190902_174849

screenshot_20190902_175844

boats_boat_inv256

^ Boat inventory and wield texture

The first intention is to improve the boat shape, from an ugly raft with a rudder but no visible means of propulsion, to a rowing boat with oars.

The second intention is to define the shape simply using a nodebox and 'visual = "item"', instead of using a model, to bring the mod back within the capabilities of most modders, and provide a vehicle coding example that is within the capabilities of most modders. The boat shape can be simply understood and altered by altering the nodeboxes dimensions.
I oppose using a model.

All dimensions of the boat are matched to 1/16th node dimensions, the thickness of the volumes is 1/8th node.
However, the way that the "default_wood.png" texture is mapped onto the nodebox causes it to be increased in size, so the texture doesn't match perfectly to 1/16th node dimensions.
I considered using custom textures to try to fix this, but then the boat mod would not automatically use "default_wood.png" as before, causing visual breakage when using texture packs. Also, it looks ok to me as it is.

The boat hull is 2 nodes long, 10/8 nodes wide, the width of the space inside is 1 node.
Note that visual_scale = 2 has to be used because a player attached to a visual = "item" object has, oddly, it's size altered according to visual_scale, the value 2 preserves attached player size.

The player visually appears backwards in the boat, as in a rowing boat.

It is reasonable for the oars to stick out sideways and not be in the water. If you consider the amount of time a rower spends resting, or drifting, or pausing between strokes, and the times when the boat is unmanned, it turns out that oars are out of the water 50+% of the time.

EDIT:
So, as far as i understand it, a nodebox is automatically converted to a mesh by MT, the difference being that internal faces remain, whereas a model has no internal faces, so the disadvantage of a nodebox is slightly lower rendering performance.
I considered that boats very rarely occur in large numbers, so i judged the benefits outweigh the disadvantages.

### CODE REVIEW

**Comment by SmallJoker** [comment]
A model with 45° (or so) rotated and thinner paddles would look way better here.

**Comment by benrob0329** [comment]
The nodebox will by default be less optimised than a model. Can you imagine if we had a thousand boats on screen at once? Those 8 extra polygons would surely bring the performance down immensly.

**Comment by DS-Minetest** [comment]
:-1: 
- >The first intention is to improve the boat shape, from an ugly raft with a rudder but no visible means of propulsion, to a rowing boat with oars.
  - Imo the current raft shape doesn't look that bad.
  - If the rudders don't move there's no propulsion either.
- >The second intention is to define the shape simply using a nodebox and 'visual = "item"', instead of using a model, to bring the mod back within the capabilities of most modders, and provide a vehicle coding example that is within the capabilities of most modders.
  - Not using a model means not using client-side animations, which means no rowing or similar.
  - Using nodeboxes larger than one node causes the texture to be repeated after one node length. Models allow much better mapping.
  - Modders who want to use textures have to be able to use tolls such as gimp and ones who want to use models have to be able to use blender (at least they have to be able to do basic stuff). Defining everything directly in code is not easier. Modifying nodeboxes also needs tools, such as a nodebox creator. Wavefront files could theoretically be modified with a text-editor, too.
Using models is clearly the better choice and learning very basic blender is not that hard. For people learning to use the minetest api, learning the basics about tools such as blender is not difficult.
- >Note that visual_scale = 2 has to be used because a player attached to a visual = "item" object has, oddly, it's size altered according to visual_scale, the value 2 preserves attached player size.

  Then resize the player.
- >The player visually appears backwards in the boat, as in a rowing boat.

  Ugh, this sounds awkward. People will normally still look forwards, hence Sam always has eyes on the back of his head.
- >It is reasonable for the oars to stick out sideways and not be in the water. If you consider the amount of time a rower spends resting, or drifting, or pausing between strokes, and the times when the boat is unmanned, it turns out that oars are out of the water 50+% of the time.

  Sam should row when the boat accelerates. Adding oars and not using them is very weird and ugly.

**Comment by tenplus1** [comment]
Personally I like the raft as a boat would mean more animations to have it look right and definitely more polygons to the models.

**Comment by paramat** [comment]
Heh yes i expected there to be requests for a model instead =)
I coded this partly for a game of my own, i wasn't too hopeful when opening a PR here.

So, as far as i understand it, a nodebox is automatically converted to a mesh by MT, the difference being that internal faces remain, whereas a model has no internal faces, so the disadvantage of a nodebox is slightly lower rendering performance.
I considered that boats very rarely occur in large numbers, so i judged the benefits outweigh the disadvantages.
Can anyone with the knowledge give an idea of the impact? I assume that for a few boats (almost all situations) the impact is insignificant.

benrob0329 that's very rare situation. Very large numbers of boats are a bad idea anyway due to the running of all the Lua 'on step' funcitons, so will already be a problem in other ways, and so won't be tolerated on a server.
By the way, for perspective, stairs are nodeboxes, and are far more likely to occur in large numbers.

SmallJoker, well, i can't model so i can't do anything about that. None of the active MTG core devs can model either as far as i know.
A boat with paddles in the water will look weird when moving, no less weird than my design.

If a contributor makes a model, the MTG core devs can't properly review it to check it was done right. This is one of the problems of using models in MTG, and why i feel they are best avoided for non-essential uses.
There are only a very few modelling contributors who are known to be trustworthy, the only ones i can think of are very absent.
Using models is very problematic if no MTG core devs model.

Anyway, if a model happens instead, that will be a new PR by someone else. But i get the feeling it may not happen for a long time.

This is the common and frustrating dev problem of:
* Contribute something simple but good and an improvement.
* Other core devs then request a fancy, idealistic and complex implementation instead.
* Because the request is complex, it doesn't get done. The requesters don't work on it.
* But also, the good contribution gets rejected.
* So no improvement happens. What's better, nothing or simple and good?
* Sigh.

Anyway, i'll go with the majority opinion, but will tag @Ezhh in a not very hopeful attempt to gain support for a nodebox boat.

This doesn't have to be forever, we could move to a model later if or when that eventually happens.

**Comment by LoneWolfHT** [comment]
IMO this is better than the current raft. But I'd prefer a model with animations over this PR's boat.

**Comment by paramat** [comment]
> If the rudders don't move there's no propulsion either.

Well, i did say 'visible means of propulsion', not 'animated'.
> Using nodeboxes larger than one node causes the texture to be repeated after one node length.

Not a big problem here, the texture tiles.
> Modders who want to use textures have to be able to use tolls such as gimp and ones who want to use models have to be able to use blender

Yes that's obvious, however, those who want to use nodeboxes don't need to use Blender, so your point is invalid.
> Defining everything directly in code is not easier.

That's a ridiculous statement. Defining a few nodeboxes is obviously far easier than using Blender. See the code.
> Modifying nodeboxes also needs tools, such as a nodebox creator.

No, look at the code here.
> For people learning to use the minetest api, learning the basics about tools such as blender is not difficult.

What you think modders 'should do' is somewhat irrelevant, few use Blender and this won't change whatever you think.
> Then resize the player.

It's far simpler to just scale the nodebox.
> Ugh, this sounds awkward. People will normally still look forwards,

Not really, would you prefer the player view is backward when moving forward? It's simply practical to have view forward. Besides, view direction is controlled by the mouse, you can look backwards if you want to.
> Sam should row when the boat accelerates. Adding oars and not using them is very weird and ugly.

A raft with no oars and no means of propulsion is weirder. You should compare to the current and see the improvement instead of comparing to an ideal.

Some very silly comments here, i get the feeling you're trying to hard to be negative about this for some reason, maybe due to recent arguments we've had.

**Comment by paramat** [comment]
LoneWolfHT, thanks, i respect your comment because at least you actually recognise there is some improvement.

**Comment by NathanSalapat** [comment]
If you built the model with the nodebox editor you can export as an obj and easily remove the unnecessary faces, though you would have to UV map a texture to use it.
I could easily compair the nodebox to a mesh and see what the difference in faces would be.

**Comment by DS-Minetest** [comment]
> So, as far as i understand it, a nodebox is automatically converted to a mesh by MT, the difference being that internal faces remain, whereas a model has no internal faces, so the disadvantage of a nodebox is slightly lower rendering performance.

If we had a nice (not hyper-realistic or something) model, there might be even more faces. I agree this is a pretty weak argument against this PR as it currently is. But it is by far not the only one.

> None of the active MTG core devs can model either as far as i know.

Hah, this _sounds_ somewhat ridiculous. \* Hey, let's create content for a 3D game without knowing how to create models! \* Anyway, it's understandable with the background that minetest doesn't require one to create models for everything. An exception, however, are mesh entities and mesh nodes. Former are much more common than entities with other drawtypes. (Common in the sense that mesh entities are more often registered in mods (eg. for vehicles or mobs), not in the sense that there were more mesh objects in the world.)

I'd like to note that minetest_game has to deal with models anyway because of Sam. (Well mtg could instead use a sprite or an unanimated creepily sliding body.)

> This is the common and frustrating dev problem of:
> 
>     ...

Isn't it common mtg practice to only merge stuff that perfectly suits into mtg? Everything has to be perfect (in the eyes of the person that exercises the most influence over mtg).

> This doesn't have to be forever, we could move to a model later if or when that eventually happens.

Well, imho the current raft model looks nicer than the boat in this PR.

> > If the ~rudders~ \*oars don't move there's no propulsion either.
> 
> Well, i did say 'visible means of propulsion', not 'animated'.

Are you suggesting that players should picture themselves how Sam uses these oars?

> > Using nodeboxes larger than one node causes the texture to be repeated after one node length.
> 
> Not a big problem here, the texture tiles.

How big the problem is depends on how much detail the texture should give. If the texture is just used to make the boat colorful and woody, it's probably ok.

> > Modders who want to use textures have to be able to use ~tolls~ \*tools such as gimp and ones who want to use models have to be able to use blender
> 
> Yes that's obvious, however, those who want to use nodeboxes don't need to use Blender, so your point is invalid.

But how can we assume that everyone can modify image files? If minetest had a way to specify textures via a lua table where you give for each pixel a color, should this be used?

> > Defining everything directly in code is not easier.
> 
> That's a ridiculous statement. Defining a few nodeboxes is obviously far easier than using Blender. See the code.
>
> > Modifying nodeboxes also needs tools, such as a nodebox creator.
> 
> No, look at the code here.

Well, I am a human[, and I guess you too](https://xkcd.com/1530/). And as such I can't directly see how the boat will look like by looking at the nodebox table. The code comments might help, but I still have to think for every box where it will be and remember all that stuff to finally get a picture of how the boat will look in-game. This process can take minutes, often fails and is mentally demanding.

Furthermore, the code is more complicated than just using the name of the model file.
(And yes, you can't see how the model looks like by looking into the code, but the same applies for textures.)

> > For people learning to use the minetest api, learning the basics about tools such as blender is not difficult.
> 
> What you think modders 'should do' is somewhat irrelevant, few use Blender and this won't change whatever you think.

You wrote that modders were not capable of using tools such as blender. Nearly every mobs or vehicles mod I've seen so far uses models. All these modders were able to learn blender (or similar).
What I wanted to say with the sentence you quoted is that very basic modeling is not an extremely difficult skill which is too hard to learn. @NathanSalapat for example made very nice tutorials on how to use blender.
I never said that everyone who does anything modding related in minetest has to learn blender (I just know some basics, too, btw.), but some modding fields grant you much more abilities if you have such skills.

> > Ugh, this sounds awkward. People will normally still look forwards,
> 
> Not really, would you prefer the player view is backward when moving forward? It's simply practical to have view forward. Besides, view direction is controlled by the mouse, you can look backwards if you want to.

But if you see another player approaching with a boat, they will look at you with the eyes in their back head. This is weird and creepy.

> > Sam should row when the boat accelerates. Adding oars and not using them is very weird and ugly.
> 
> A raft with no oars and no means of propulsion is weirder. You should compare to the current and see the improvement instead of comparing to an ideal.

There is no real improvement if the oars are not used. The boat is still just drifting along. But now there are those weird static oars.

> Some very silly comments here, i get the feeling you're trying to hard to be negative about this for some reason, maybe due to recent arguments we've had.

\*sight\* Don't try to annihilate the rational quintessences of my arguments like this. My arguments aren't directed against you. It is, however, possible that I bring up more arguments against things that you like as it can be hard to convince you (I've tried to avoid harsh expressions.).

**Comment by sofar** [comment]
The pixels are disproportionately large. Texture wise, this is almost as bad as the 2016 boat before I cleaned up the .obj.

Due to the chosen method of nodebox model, that is largely unsolvable. Therefore, I see this as a regression.

The existing model can certainly be improved with a better model, but, this is really the opposite.

Great for a mod, though.

**Comment by TumeniNodes** [comment]
I've always thought we should pop a lil sail on the current boat.
Nothing fancy... just something to fit into the overall theme, but enough to know it's a sail.

**Comment by paramat** [comment]
Sorry for being grumpy earlier.
It was my mistake for opening this in MTG, knowing it would be against the direction of most other core devs. I don't know why i did =)

**Pull request closed without merging**
