### PR TITLE
Bones: Improve bones textures

### PR DESCRIPTION
**Pull request by paramat**
Add mouth, remove jaw shadow, shade eyesockets.
Darker shading for spine and rotate texture using ^[transform2
instead of inverting texture.
Use 'node sound gravel defaults' for sounds.
////////////////////////////////////////////////

screenshot_20160731_012709

skull4_128

torso3_128

The mouth shading has the same contrast as Sam's mouth.
I have shaded the eyesockets properly instead of them being background dirt, there is a very subtle gradient to suggest the hollow of the socket.

Darker shading for spine to visually move it back away from the ribcage and pelvic bone front.

screenshot_20160709_192827

^ Current bones

### CODE REVIEW

**Comment by paramat** [comment]
Perhaps the eye sockets need to be slightly darker?

**Comment by Fixer-007** [comment]
You are ruining it with diagonal hands :/ I will not be able to make good roads anymore :/

**Comment by everamzah** [comment]
Unfortunately, this isn't a road node.

That said, I like the straight bone look, and am neutral.

**Comment by paramat** [comment]
We shouldn't be using bones for roads, sorry. Use a proper custom node. However i'm neutral about the arm change so maybe will leave it.

**Comment by DonBatman** [comment]
I don't care for the arms but I think the mouth should be added.

**Comment by paramat** [comment]
Yeah, i'll return to the straight arm and slightly darken the eyesockets.

**Comment by paramat** [comment]
Updated.

**Comment by paramat** [comment]
Will merge as a trivial texture improvement, it's not a big change.

**Comment by pithydon** [comment]
This may just be my OCD talking but sam is bigger than one block.
This texture looks like a dwarf skeleton and the old one looked compressed to fit one block.
On the bright side it does make a lot better roads.

**Comment by paramat** [comment]
Yeah since bones is a single node the skeleton is 'wrapped around' the node, with my texture (and to some degree the old one) the skull is near the shoulders, the legs near the pelvic bone, the arms to the sides, so it makes sense, the bones have seperated and moved around a bit.

**Comment by paramat** [comment]
4fba897a96a0fdd113632bc82a99a530c42e5c73

**Pull request closed without merging**
