### PR TITLE
Add moonflower mod

### PR DESCRIPTION
**Pull request by RealBadAngel**
Adding flower that opens only at night
Source of fluorescent dye (to come with separate patch)

### CODE REVIEW

**Comment by C1ffisme** [comment]
This dosen't need the "duplicate" label anymore. The duplicate has been closed.

**Comment by paramat** [comment]
Lovely idea but i think a mod thing, devs shall we close this now?

**Comment by MirceaKitsune** [comment]
Years ago when I implemented the initial Moonflower, it was intended for inclusion into minetest_game. It wanted it to be an unique item that gave the default Minetest a personality of its own, similar to what redstone or zombie pigmen are for Minecraft. With this considered, it's of course the choice of other developers whether it's good for default MTG or not.

**Comment by RHRhino** [comment]
It's ridiculous that minetest devs need **YEARS** to decide for pull requests and issues - moonflower mod is just one example for that ... :angry:

**Comment by MirceaKitsune** [comment]
@RHRhino Things do happen a bit slowly, I agree. I can understand caution in some decisions, but Minetest could advance a lot faster if pull requests were solved sooner.

**Comment by RHRhino** [comment]
A bit slowly? This pull request is from March 2013 - as slow as a dead snail would be more appropriate! I think it's just fustrating for people who try to help to develope minetest if they have to wait ages just to get their pull request merged or a clear answer that it doesn't fit into minetest or minetest_game.

**Comment by paramat** [comment]
Yes this is why today i'm giving old PRs some attention. The other MTGame devs seem to be very busy at the moment so i'm doing the work and asking for approvals.

**Comment by HybridDog** [comment]
>This pull request is from March 2013 - as slow as a dead snail would be more appropriate!

l think a dead snail disappears in less then a year.
If pull requests of people don't get attention, the people don't make new ones, e.g. because of possible conflicts.

**Comment by rubenwardy** [comment]
I like this, :+1:

**Comment by paramat** [comment]
Hi @RealBadAngel just notifiying you because it's over a year since your last comment.

**Comment by RHRhino** [comment]
@rubenwardy what does Jordach's PR have different?

**Comment by paramat** [comment]
Closing due to age of PR.

**Pull request closed without merging**
