### PR TITLE
Allow non-players to dig bones

### PR DESCRIPTION
**Pull request by MT-Modder**
This will fix https://github.com/minetest-technic/technic/pull/257. And probably any future problems involving Technic/Pipeworks Machines.

### CODE REVIEW

**Comment by NathanSalapat** [comment]
While I'm no expert this looks good to me. I was actually just about to start working on the exact same problem for the guys over at the Pixel Shadow.

**Comment by MT-Modder** [comment]
Looks like locked chests have similar code. I'll wait for devs to see if it should be included in this PR or not.

**Comment by PilzAdam** [comment]
Looks good, although the code can be shortened a bit.

**Comment by MT-Modder** [comment]
@PilzAdam I see it now :smile:. I'm gonna redo with the changes to locked chests and steel doors.

**Pull request closed without merging**
