### PR TITLE
Default: Add grey sand

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160821_025748

Add a 3rd sand colour, primarily for use in the upcoming cold desert biome.
Now we have 3 sand colours that are good compliments for the 3 stone types:
desert stone, desert sand
sandstone, sand
stone, grey sand
So 3 types of desert are now possible.
Might also be useful for use as moondust.

### CODE REVIEW

**Comment by paramat** [comment]
Will change name to silver_sand.

**Comment by sofar** [comment]
:+1: with the name change.

**Comment by paramat** [comment]
Updated.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
67fc2247fc8c846ac43775cc35862fa7b819398e

**Pull request closed without merging**
