### PR TITLE
Add marram grass for coastal sand dunes

### PR DESCRIPTION
**Pull request by paramat**
Use noise with 1 octave and flag 'absvalue' to create sand paths
in dunes.
///////////

screenshot_20180203_234353

WIP stuff to add

screenshot_20180124_130943

^ Example of occurence in mgv5

screenshot_20180124_115502

^ Noise is tuned to create sand paths

### CODE REVIEW

**Comment by benrob0329** [comment]
Future Idea: some kind of a (simple, well done to go with some current plans) mob that only follows sand paths/only hides in patches of sand grass, forcing the player to hide in the grass/only follow the paths.

Just an idea, PR looks nice 👍

**Comment by Ezhh** [comment]
I love this so far.  Will take a closer look when you are done working on it.

**Comment by TumeniNodes** [comment]
> @TumeniNodes textures are derived from your 'refreshed' texture pack, hope this is ok.

Of course it is. Always nice when something can be put to good use. Thank you.

**Comment by Fixer-007** [comment]
What is annoying is how patterny it is, grass itself is nice, it is just placed ideally, not with random small shifting.

**Comment by paramat** [comment]
Voxel worlds are patterny, all nodes are aligned in a 3D grid =)

**Comment by Ezhh** [comment]
The grass is only placed on y 4 to 5...  It's not going to be overly common to get a large enough area with so little height variance that the patterning will be too obvious.

**Comment by C1ffisme** [comment]
A few comments:

- The grass is a little bit too dense for me in these screenshots.
- While not entirely accurate, the grass could be a bit more yellowed to match the color scheme of the biome.
- Do we really need stages for this, or could we make it like Jungle Grass which has no stages?

**Comment by paramat** [comment]
Marram grass is very dense IRL, visually more so than this.
Marram grass IRL is grey-blue-green, there's no reason to yellow it to be closer to sand colour, that would look bad.
The 3 heights come at no mapgen performance cost or in-game cost. All one height looks not so good, especially when there are no jungletrees to distract you.

**Comment by Ezhh** [comment]
A slightly paler green (not more yellow) might be worth considering for the grass.

**Comment by paramat** [comment]
Will consider it.

**Comment by paramat** [comment]
Paler as in lighter and less colour saturation?

**Comment by C1ffisme** [comment]
> Marram grass IRL is grey-blue-green, there's no reason to yellow it to be closer to sand colour, that would look bad.

Yes, I know it's not realistic, but it's for the sake of making it look less contrasted, which it does now. If it was less dense, it wouldn't look so odd, but right now it just looks a little bit ugly...

**Comment by paramat** [comment]
Yes it was a little too dark.
Uppdated textures to be lighter and less colour saturation, new screenshot in first post.

**Comment by Ezhh** [comment]
Looks better to me now.

**Comment by paramat** [comment]
Ok i think the texture is good enough for now, will add the other stuff.

**Comment by paramat** [comment]
Other stuff added, no longer WIP.

**Comment by paramat** [comment]
For noise with no noise flags:

`noise = offset + scale * (octave1 + octave2 * persistence + octave3 * persistence^2 + octave4 * persistence^3 + ...)'

Where `octavex` is perlin noise varying precisely between -1 and 1.
Noise param 'octaves' determines hw many octaves are present inside the brackets.

**Comment by Ezhh** [comment]
Though the grass gets very dense in places, it seems like a good thing to me. The dense patches (testing on a v7 map) are rare enough that they add some nice variety. The textures are good as well.

:+1: from me. Will be really happy to see this added.

**Comment by paramat** [comment]
Might be obvious but this is inspired by childhood memories of visits to the beach and exploring the sand paths on the sand dunes. Between the paths were very thick areas of marram grass.

**Comment by TumeniNodes** [comment]
maybe someone will eventually add an edible property for this? would make some sense in a survival aspect.
it's nice to add new deco plantlife, but even better when it has some sort of useful property, whether for healing or related to hunger, or something?
just a thought waking up at 4:40 am when I don't need to be productive until around 8am

this looks really nice btw

**Comment by paramat** [comment]
7f3e9e65b38c3888ce4bfb2e559451adb6acbbb6

**Comment by Fixer-007** [comment]
Does it spread?

**Comment by paramat** [comment]
No it can't, it would destroy the sand paths. it's density would make the ABM a lot more intensive too.
I don't want to make that ABM even more of a disaster than it is already.

**Comment by srifqi** [comment]
Just some screenshots to show that it doesn't look "patterny".

marram grass among
^ Marram grasses among ferns (above).
screenshot_20180309_105918
^ Marram grasses among ferns.
screenshot_20180309_110032
^ Marram grasses scattered on multiple patches.

**Comment by srifqi** [comment]
Just some screenshots to show that it doesn't look "patterny".

marram grass among ferns (above)
^ Marram grasses among ferns (above).
marram grasses among ferns
^ Marram grasses among ferns.
marram grasses scattered on multiple patches
^ Marram grasses scattered on multiple patches.

**Comment by Fixer-007** [comment]
It does look patterny, especially with those small heights it has.

**Comment by paramat** [comment]
Well, everything else looks patterny too in a voxel world.

I am considering making these a little higher and wider using visual scale, marram grass grows to 1.2m.

**Comment by Ezhh** [comment]
They look fine to me as they are.

**Pull request closed without merging**
