### PR TITLE
Use stratum ore to add the missing sandstone types

### PR DESCRIPTION
**Pull request by paramat**
Add silver sandstone strata to cold desert.
Add sandstone and desert_sandstone strata to desert.
///////////////////

screenshot_20180423_062755

screenshot_20180423_060417

New version of #1998 
+-16 nodes of gentle undulation over a scale of 256 nodes.
I have minimised noise calculations by making sure this ore generation only happens in the surface layer of mapchunks (-32 to 47) instead of in 2 layers of mapchunks.
The strata appear from y = 3 to y = 46.
Profiling details below.

### CODE REVIEW

**Comment by Ezhh** [comment]
I love this as a concept and am hugely in favour of this being added, but it needs variation. The strata in the screenshot shown is much too uniform. Fewer strata with more variation is preferable.

**Comment by paramat** [comment]
Hmm i'll consider it. I might be ok with just height variation, not thickness variation too. With just height variation this will add 1 2D noise per stratum, which means 2-3 additional 2D noises in desert biomes. Not huge but a significant extra load. At least because these are desert mapgen will be less intensive in many other ways to compensate.
Well, i'll add a commit that adds variation to look at it then maybe i'll change my mind.

**Comment by paramat** [comment]
Ok agreed, working on it.

**Comment by paramat** [comment]
Updated to add noise variation.
Same basic strata patterns but with +-16 nodes of gentle undulation over a spread of 256 nodes.
I have minimised intensity by making sure this ore generation only happens in the surface layer of mapchunks (-32 to 47) instead of in 2 layers of mapchunks.
The strata appear from y = 3 to y = 46.

**Comment by paramat** [comment]
Profiling oregen in mgflat, for y = -32 mapchunks, seed 0, desert biome, ground level 48:
Master:
```
ores: 629micros
ores: 649micros
ores: 607micros
ores: 756micros
ores: 713micros
ores: 845micros
ores: 678micros
ores: 654micros
ores: 603micros
```
PR:

**Comment by paramat** [comment]
Master at y = -3000 (all ores placed):
```
ores: 2972micros
ores: 1582micros
ores: 2859micros
ores: 3804micros
ores: 3516micros
ores: 3497micros
ores: 3115micros
ores: 3644micros
ores: 2823micros
```
So deep underground oregen is more intensive than adding 3 strata to desert at the surface.

**Comment by paramat** [comment]
Ready for review.

**Comment by Ezhh** [comment]
Example of how unvarying the layers are over a large area:
mtg_layers

**Comment by paramat** [comment]
Hmm i should have warned, the variation is very gentle, maximum +-16 nodes over a 256 node scale, so yes often there are level sections and the variation is subtle. I like that but agree it's borderline too gentle. I can reduce the scale, let's try that first.

**Comment by paramat** [comment]
screenshot_20180427_214244

Reduced spreads to 128 nodes to make strata slopes twice as steep. There still will be some level sections but half the size.
Used amend sorry, latest change is
```
			spread = {x = 128, y = 128, z = 128},
```
for all 5 strata.

**Comment by Ezhh** [comment]
Much better. This looks much more natural (same area as previous screenshot):
mtg_layers2

:+1: from me as long as you keep these values.

**Comment by paramat** [comment]
I will.

**Pull request merged**
