### PR TITLE
Ferns: Add 3 sizes for coniferous forest biome

### PR DESCRIPTION
**Pull request by paramat**
Ferns: Add 3 sizes for coniferous forest biome

Remove flowers from coniferous forest.
Add 'dirt with coniferous litter' to farming mod overrides.
////////////////////

screenshot_20171224_023605

Implementation is identical to long grasses, but with 3 sizes.
Each size has a different noise distribution to generate a large variety of combinations and densities.
Flowers lok wrong here now, removed. Mushrooms remain.

screenshot_20171224_025934

^ Maximum density

### CODE REVIEW

**Comment by ThomasMonroe314** [comment]
the ferns look nice, but idk about the flowers, they seem out of place.

**Comment by paramat** [comment]
screenshot_20171224_025144

^ Maximum density

Yes they do rather, can remove those in a separate commit.

**Comment by paramat** [comment]
Updated:
Remove flowers from coniferous forest.
Add 'dirt with coniferous litter' to farming mod overrides.

**Comment by TumeniNodes** [comment]
Aside from being visually pleasing, this adds a new feel and future possibilities..., so this is great.
Some tweaks coming for ferns eventually, to show 3 stages of growth. I think using the fiddlehead is important for stage1 (it can be used as a quick food source in-game)

I actually think mossmanikin (or someone else) had added these in the undergrowth mod IIRC?

**Comment by Fixer-007** [comment]
Yes, flowers look somewhat strange in this setting, but maybe they need to be rare and some should grow ok, like violet ones, not completely removed, there is also that tall grass thing.

**Comment by Fixer-007** [comment]
>Remove flowers from coniferous forest.

Should be in separate commit or PR?

**Comment by paramat** [comment]
I can't be bothered to, it's closely related anyway since ferns are the new decoration replacing the old.
I will add activating nodes in a separate commit though.

**Comment by paramat** [comment]
d1db66bf4fca57c3ae2d020ba7f575e432901535

**Pull request closed without merging**
