### PR TITLE
Add new dirt texture by random-geek

### LINKED ISSUE #2193: New dirt/grass textures
The default dirt with grass textures currently seem unnecessarily bold and saturated, and thus end up overpowering the surrounding trees and plantlife. I fine-tuned the values a bit, and below are screenshots of my proposed modifications. In my opinion, these textures look significantly better and improve the general aesthetic.
I also changed the dirt texture to have less of a visible pattern, but I think it might be _too_ clean.

unknown 2
unknown
default_dirt
default_grass
default_grass_side

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20180821_195902

Closes #2193 
Texture creator is unable to make a PR.

I've disliked our previous dirt texture since 2014 when new dirt and grass textures by Neuromancer were added by BlockMen. The grass was especially grim and miserable and i eventually replaced that. It's good to finally move on from those bad textures. This is a big improvement.

:+1: as this is someone else's texture.

### CODE REVIEW

**Comment by TMcSquared** [comment]
It's definitely a huge improvement in the overall feel of the dirt :D

**Comment by paramat** [comment]
^ I agree

ditr256

There's also a 2nd group of 3 pixels (wrapping here) that could be reduced to 2.

**Comment by Ezhh** [comment]
The second group is better matched to the surrounding colours, so not too noticeable, whereas the group I previously pointed out is against a darker part of the surrounding dirt texture.

**Comment by paramat** [comment]
Agreed.

**Comment by paramat** [comment]
I'll edit it myself.

**Comment by paramat** [comment]
new_dirt_pixel_tweak256

**Comment by random-geek** [comment]
@paramat 
I would prefer you pick one of the already-used colors for the pixel in question; that way, we can keep with the 16-colour palette.
Also, the group of pixels is now the same shape as the one to the right, which I don't like.
Here's my revision:
default_dirt

**Comment by paramat** [comment]
Ok i didn't realise this was a restricted palette, will update.

**Comment by paramat** [comment]
Yes yours is also better because it is diagonal in the other orientation.

**Comment by paramat** [comment]
Updated PR. Much better than my edit.

**Comment by Ezhh** [comment]
:+1:

**Pull request merged**
