### PR TITLE
Fix misaligned waterlily texture

### PR DESCRIPTION
**Pull request by yyt16384**
Previously waterlily has misaligned top and bottom textures and looks different when viewed from below.

### CODE REVIEW

**Comment by paramat** [comment]
Interesting, will test.

**Comment by paramat** [comment]
It works but i realise the flower shouldn't show underneath.
Instead of using a transformation how about a dedicated texture for underneath that is already flipped and has no flower?

**Comment by yyt16384** [comment]
@paramat Updated.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Will merge as trivial soon.

**Comment by paramat** [comment]
e0bec501f224dbe93387c709c8257b90ae25dda7

**Pull request closed without merging**
