### PR TITLE
Improve flowers mod

### PR DESCRIPTION
**Pull request by Ombridride**
Improve of the Flowers minetest_game mod, the code is more smaller and
do the same thing. 

We fix a small mistake 2 weeks ago, now the code is clean and 100% functional.

We speak about this changes here : https://github.com/minetest/minetest_game/issues/469

(PS : the most important changes are from Davedevils who makes a very well optimisation work, the fixs are by the devs of MinetestForFun)

### CODE REVIEW

**Comment by PilzAdam** [comment]
* The new chance for the ABM should be 625 to have the same regrowing speed, if I'm not mistaking
* Don't have all these `if then return end` statements in one line, keep them in 3 lines
* Why don't all flowers use the new function to be registered?
* Use English comments (`Fleur Simple (une case)`)
* Remove the logging at the end of the mod
* Adding new flowers (lily pad) should be in a separate pull request

**Comment by LeMagnesium** [comment]
@PilzAdam , there are indeed a few mistakes from Ombridride's code, mainly because it's a draft written by @davedevils for his server, and because I have not took time yet to improve it. I will remove useless things, and change what you pointed. Thanks for your comment.

**Comment by Ombridride** [comment]
When we have more times, we will improve this code just for MT_game...

**Comment by LeMagnesium** [comment]
There it is : #494
I signed the commit as @Ombridride (I just need his mail) and solved the following problems : 
 - I put back the actual chance/interval in the ABM
 - I unwrapped lines containing returns
 - All flowers use the new function
 - Comments are in english
 - The logging and the lily pad have been erased

**Comment by Novatux** [comment]
Closing, since it is replaced by #494

**Pull request closed without merging**
