### PR TITLE
Beds: Add white simple and fancy beds

### PR DESCRIPTION
**Pull request by paramat**
Beds: Add white simple and fancy beds

Crafted from white wool so red dye is not required.
Describe red beds as 'Red'.
/////////////////////

screenshot_20180617_204841

For #475 so that red dye is not required to craft a bed (which is of course ridiculous).
Please see issue to consider the issues.
Adds a white bed, using textures by hkzorman from PR #2052 
Code is a simple copy-paste-edit of the existing bed.
Something more original for MT as an alternative to copying MC's red bed.

### CODE REVIEW

**Comment by Napiophelios** [comment]
jeez louise, you guys are taking the whole "vanilla" minetest idea way too seriously.
if you can't use hkzorman's PR right now,  just leave the mod alone
this is awful.....like completely awful.....it touches on horrendous

**Comment by paramat** [comment]
There is a reason why these are white.

**Comment by paramat** [comment]
1 more nodebox on the fancy bed will add a pillow without needing to change textures :)

**Comment by paramat** [comment]
We could even add a pillow to the simple bed too. Another PR though.

**Comment by paramat** [comment]
Updated to also describe red beds as 'Red'.

**Comment by 12Me21** [comment]
Perhaps you could use palettes to allow different bed colors without adding more nodes.

**Comment by paramat** [comment]
Any core dev opinions?

**Comment by Ezhh** [comment]
I'm really unsure what I think. It's silly that beds require dye, but on the other hand a white bed doesn't look great (and beds of every colour always felt excessive to me). 

Wouldn't it be more interesting to have something like a sleeping bag as the simple/no-dye sleeping option, then you progress to beds a bit later? Sure, the beds would still need dye that way, but you could set a sleeping spot without needing to meet the dye requirement.

**Comment by LoneWolfHT** [comment]
Why not redo the bed model or change the textures?

**Comment by paramat** [comment]
Although i like the sleeping bag idea, it would require changes to player position when sleeping, which is not definable when registering. For a low priority issue i can't be bothered to code that, so i'll stick with a white bed.
I know it doesn't look great but it's only for those occasions where a player doesn't have red dye, in which case they will be glad to have a white bed available.

The other alternative i would consider is to not require red wool for the red bed, but that might conflict with recipes of some bed mods, and seems a little weird as red wool seems intuitive for a red bed.

**Comment by LoneWolfHT** [comment]
Why not a black bed? Coal isn't hard to find

**Comment by paramat** [comment]
Closing because 'meh ..' :) Very minor issue and not sure i want to add a new bed to solve it.

**Comment by paramat** [comment]
Well, still unsure so re-opening for consideration.

**Comment by LoneWolfHT** [comment]
I would be fine with a white bed. If you don't like the color you could make/use a mod that adds some more colors or changes the current color

**Comment by paramat** [comment]
Here's a simpler alternative i possibly prefer https://github.com/minetest/minetest_game/issues/475#issuecomment-461891614

**Pull request closed without merging**
