### PR TITLE
Add more types of fences and move fences to seperate mod

### PR DESCRIPTION
**Pull request by sfan5**
Pull for #273

### CODE REVIEW

**Comment by C1ffisme** [comment]
This pull hasn't recieved a lot of attention since 2014, and it is controversial. Can we please close it?

**Comment by paramat** [comment]
Cobble fence makes no sense because the fence structure is thin. The others look fine to me and a good addition.

**Comment by C1ffisme** [comment]
If we want cobblestone **walls**, then we should add those in a similar method to glass panes.

**Comment by Sokomine** [comment]
Some mods add further fence types which is OK for them. As for the normal MT game, I agree with paramat - diffrent wood types for fences would be welcome and enrich the world.
Providing more options to the fenclike drawtype - as ShadowNinja suggested - would of course be great but cannot be reached withhin minetest_game.
I've created stone walls by adding options to xpanes, similar to what C1ffisme suggested, and would like that extension of xpanes to get merged eventually. Screenshot:

**Comment by HybridDog** [comment]
>I've created stone walls by adding options to xpanes, similar to what C1ffisme suggested,[…]

Does xpanes still register lots of nodes instead of using facedir?

**Comment by C1ffisme** [comment]
Cool! Thanks @Sokomine !

**Comment by Sokomine** [comment]
[url=https://forum.minetest.net/viewtopic.php?f=9&t=12882] adds more fences and walls. It can also handle xpanes. The mod only uses 5-6 nodes instead of the 15 xpanes needs. If anyone's intrested...

**Comment by paramat** [comment]
See the new issue and PR.

**Comment by paramat** [comment]
Hi @sfan5 notifying because an old PR.

**Comment by paramat** [comment]
See #663 and #665 discussion can continue there.

**Pull request closed without merging**
