### PR TITLE
Re-doing boat after null player check with player strings

### PR DESCRIPTION
**Pull request by misterskullz**

### CODE REVIEW

**Comment by misterskullz** [comment]
I opted for player name string and then a re-lookup.  Its 6 of one, half a dozen of another.  Either the clicker object is nil or the minetest.get_player_by_name function is foobar.

_OMG Travis, is called readability._

**Comment by misterskullz** [comment]
Whitespace cleaned up, Travis is being picky.  If you would like me to make him happy, no issue.

I'll just let #2347 be.

**Comment by DS-Minetest** [comment]
Do not create PRs from your master branch.
This might be helpful:
https://forum.minetest.net/viewtopic.php?f=3&t=14262&p=211498#p211501

**Comment by misterskullz** [comment]
Would you like me to close these out and resubmit as three different branches / pull requests?

**Comment by DS-Minetest** [comment]
Afaik there should be one thing done per PR, not two or three at once. This PR should probably only do the boat thing, not the dungeon thing.
I don't know what's the best to do now.

**Comment by misterskullz** [comment]
Ill back them out and redo if needed. The dungeon will need to be merged or accpeted after the mod.conf one due to the new dependency. Whatever works for you folks. One merge per issue is sane.

**Comment by paramat** [comment]
This seems like good work, but please split the boats changes (the smaller part of this PR) off into a separate PR.
Be careful to avoid indentation using spaces.

**Comment by misterskullz** [comment]
Will do

**Comment by misterskullz** [comment]
Moved to #2350 and #2351

**Pull request closed without merging**
