### PR TITLE
Add tin

### PR DESCRIPTION
**Pull request by Zeg9**
It replaces steel in bronze crafting.

### CODE REVIEW

**Comment by HybridDog** [comment]
https://github.com/HybridDog/minetest_game/commit/4812980d97b7e7d0f42cb913a370a339dc86fab3

**Comment by C1ffisme** [comment]
Maybe tin should have another use, like making buckets or the locks on locked chests? (Definetely the later one. On some PVP servers, you can never get steel because you die so quickly.)

**Comment by HybridDog** [comment]
>the locks on locked chests

tin is too squashy l think

**Comment by C1ffisme** [comment]
@HybridDog I don't think reality matters in this game. when did you see a random pop-tart cat with a rainbow coming out of it IRL? ;)

**Comment by HybridDog** [comment]
in my opinion you need to try to make minetest realistic, if you don't, the nyancat would loose its virtue, which would make me sad ;¬{

**Comment by C1ffisme** [comment]
We can make other uses for tin. I don't know at the moment. Maybe tin should make certain decorative items? And if tin is used to make bronze, why not make bronze make bells or something?

**Comment by HybridDog** [comment]
and tin could also be used for thin glass
http://en.wikipedia.org/wiki/Float_glass

**Comment by nerzhul** [comment]
@C1ffisme seems legitimate, but we need usage

**Comment by HybridDog** [comment]
>but we need usage

by default rails, vessels, gold, … don't have a usage

**Comment by C1ffisme** [comment]
@HybridDog :

Vessels can be a decoration, and are support for mods.

Rails are also decoration, if you need another use, download the carts mod, or do a carts pull request.

Gold is, well, gold. Gold in minecraft is only useful if you have apples or brewing stands, so gold is a must-have. Also, gold blocks can, again, be used for decoration.

**Comment by HybridDog** [comment]
so tin has usages, too:
· it is used to craft bronze
· maybe float glass
· deco: low contrast buildings and similar
· the technic mod uses it

**Comment by C1ffisme** [comment]
Yeah! This may make it to the game!

**Comment by nerzhul** [comment]
I think this is a good idea too

**Comment by BlockMen** [comment]
We have enough ores. And even the existing are not used enough. Copper is just usefull for bronze, gold is not usefull at all and mese is like diamond just with less uses.

**Comment by C1ffisme** [comment]
@BlockMen Copper is also used for technic. A lot of these ores are for mod support. After all, if you added an ores mod, none of these ores would generate nearby. So if ores are generated in your old world by default, you can just make a new world, and add mods later.

**Comment by C1ffisme** [comment]
Hey Zeg9, apparently you need to rebase this.

**Comment by HybridDog** [comment]
So this doesn't work? https://github.com/HybridDog/minetest_game/commit/4812980d97b7e7d0f42cb913a370a339dc86fab3

**Comment by BlockMen** [comment]
@C1ffisme not necessary until there is made a decision.

**Comment by paramat** [comment]
-1 from PilzAdam and myself, devs shall we close this?

**Comment by HybridDog** [comment]
>rebase needed

maybe you could take that
https://github.com/HybridDog/minetest_game/commit/4ee11e046a40d6ed445333f42fa1b9a9e4f031a5

**Comment by paramat** [comment]
Closing because not popular and:

> no comments from the author for 2 years

**Comment by HybridDog** [comment]
> Tin is too boring, is not 'fundamental' enough and has too few uses. Bronze itself was controversial and is not a good enough justification for tin. Gold is fundamental and essential in this game even without practical uses, because it's gold.

Why did you change your opinion?

**Comment by paramat** [comment]
It would be much much worse to never change my opinions :)

**Pull request closed without merging**
