### PR TITLE
Smooth boat turning to reach player yaw as he accelerates forward

### PR DESCRIPTION
**Pull request by beyondlimits**
This allows player to just look left or right to slowly turn his/her boat in the respective direction.

### CODE REVIEW

**Comment by JBBgameich** [comment]
Yes i like this. The boat like its right now is not really good

On 27. November 2015 00:34:15 MEZ, beyondlimits <notifications@github.com> wrote:
>This allows player to just look left or right to slowly turn his/her
>boat in the respective direction.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/minetest/minetest_game/pull/731
>
>-- Commit Summary --
>
>* Smooth boat turning to player reach player yaw as he accelerates
>forward
>
>-- File Changes --
>
>    M mods/boats/init.lua (36)
>
>-- Patch Links --
>
>https://github.com/minetest/minetest_game/pull/731.patch
>https://github.com/minetest/minetest_game/pull/731.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/pull/731

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by 0-afflatus** [comment]
This would have to be configurable. I like the old behaviour. The direction of travel is affected by the way you row a boat and tides; or sail and rudder. I find it useful to be able to look 90 degrees to the direction of travel. Boats do not naturally follow line of sight.

**Comment by PilzAdam** [comment]
I don't like this, since player may just want to look to the side without changing the movement direction.

Even if you would make it configurable, it would be a server-side setting, so it's forced on every client.

:-1:

**Comment by paramat** [comment]
:-1: I always need to look around without affecting boat direction, the AD keys are already there for boat control we don't need a second system, even as an option.

**Comment by JBBgameich** [comment]
I think  we need a completele different steereng for the boat. Not like discribed gete but not lile its right know. I think for  example, the boat has to rotate faster wenn you press the error key. Probably watch at other games how the vehicles are there.

**Comment by sofar** [comment]
I'd prefer a solution where the boat has a bit more angle control, this approach makes boats hard to use when looking around.

**Comment by paramat** [comment]
-1 from sfan5 on IRC.

**Comment by everamzah** [comment]
The lower the dedicated_server_step, the faster the boat will turn.

**Comment by HybridDog** [comment]
>The lower the dedicated_server_step, the faster the boat will turn.

this is one of the reasons l don't use the boat

**Comment by 0-afflatus** [comment]
@everamzah thanks, I didn't know that.

**Pull request closed without merging**
