### PR TITLE
Don't show item overlay if slot is occupied (bookshelf, vessels shelf)

### LINKED ISSUE #1359: New shelf overlays don't line up
@sofar are you having a laugh?  :)

screenshot_20161031_023050
screenshot_20161031_023054

big1
big2

In my own personal opinion, 0acd9a2ccb2f766de5237964a5da046148075d79 is distasteful.

### PR DESCRIPTION
**Pull request by sfan5**
Implements the idea by @Rui-Minetest and fixes #1359.

screenshot_20161106_213549

screenshot_20161106_213554

### CODE REVIEW

**Comment by sofar** [comment]
Yeah, that's nice. :+1: on the idea, didn't see the code.

**Comment by paramat** [comment]
Good idea.

**Comment by Wuzzy2** [comment]
Oh, I haven't realized this is even possible. But when I look at the code, it all seems so obvious now. :D
Thank you..

**Comment by Fixer-007** [comment]
Very nice idea :)

**Comment by Rui-Minetest** [comment]
👍 
Thanks, @sfan5.

**Comment by paramat** [comment]
:+1:

**Comment by sofar** [comment]
:+1:

**Comment by sfan5** [comment]
7fbf25d6ca96c32ba8642e23fa2560031766206e

**Pull request closed without merging**
