### PR TITLE
reexport player model

### LINKED ISSUE #1846: Player model needs improvement
screenshot_20170724_203939

@TeTpaAka 
See https://github.com/minetest/minetest/pull/6165#issuecomment-317520359
>Oh, the latest Git version seems to have a different player model now... someone might want to reexport it with split edges?
In Blender, do:
    Add "Edge Split" modifier
    Apply modifier
    Export with normals enabled

### PR DESCRIPTION
**Pull request by DS-Minetest**
Fixes #1846.
Edit: Oops, there is already a PR for this, sorry. >\_<
Edit2: But this one was chosen. ¯\\\_(ツ)_/¯

### CODE REVIEW

**Comment by paramat** [comment]
screenshot_20170725_222235

This also works, and includes both files and less editing, so this may be best.

**Comment by JurajVajda** [comment]
`build: 201707250702-0~31b84ce~ubuntu17.04.1`
Is it just me or am i missing something ? ..when you are below y = 0 the character becomes very dark, tried with these models and also with current one in dev. If its a known issue then you can disregard this comment.

screenshot_20170726_005113-min
screenshot_20170726_005122-min

**Comment by paramat** [comment]
Will test, not a known bug.

**Comment by paramat** [comment]
Confirmed, thanks.

**Comment by paramat** [comment]
#1852

**Comment by JurajVajda** [comment]
@paramat no problem,thanks for creating an issue for it.

**Pull request merged**
