### PR TITLE
Slow down fire spread a bit

### PR DESCRIPTION
**Pull request by MT-Modder**
Helps with #408. The speed of fire spreading is too fast. It's almost like everything is made of cardboard.

### CODE REVIEW

**Comment by 0-afflatus** [comment]
:+1:
possibly slightly greater values for the group:igniter abm
It makes it possible to fight the fire and stop the spread.

**Comment by paramat** [comment]
Yes please.

**Comment by Calinou** [comment]
:+1:

**Comment by C1ffisme** [comment]
:+1:

**Comment by BlockMen** [comment]
525f467057cd9ea94c39452379f80ab5c9c6fe8f

**Pull request closed without merging**
