### PR TITLE
Fixed bug for players which use /home while sitting

### PR DESCRIPTION
**Pull request by amadin**
Was added to mod sethome:

player:set_eye_offset({x=0,y=0,z=0}, {x=0,y=0,z=0})
default.player_set_animation(player, "stand" , 30)

### CODE REVIEW

**Comment by tenplus1** [comment]
Problem is, while sitting the player is usually attached to an object like a chair or boat so changing eye-level and animation then teleporting home wouldn't work properly without detaching player first.

Maybe an addition of /stand /sit /lay commands for players to use would be more useful.

**Comment by amadin** [comment]
Many players had troubles with changing eye-level and animation on my server because i used chair from xdecor mod, but most servers have boat, cart and sethome mods. Maybe i don't know something (I don't know what you mean about "work properly") but i used this fix on "Russian ama" 0.4.13 server for a month (minimum) and i did't saw any troubles. Also i used this fix for /spawn command. Is any way to add detaching player to /home command?.

**Comment by tenplus1** [comment]
Adding a mod like cozy would be the better way to fix any animation problems: https://forum.minetest.net/viewtopic.php?f=11&t=14143

**Comment by paramat** [comment]
I don't think teleporting home should be allowed when sitting or laying down.

**Comment by rubenwardy** [comment]
I agree that it shouldn't be possible to teleport whilst attached to an object. Are players attached to an object whilst sitting on a chair?

**Comment by paramat** [comment]
So, is a player automatically detached from an object when teleported home? It may be necessary to add a 'detach' in this.

**Comment by t4im** [comment]
I completely agree with you two.

An attached player (boat, spectating player, chair, car etc.) will have a lot of different attributes set that will have to change back on detachment.

Unless you can make sure you really reset **everthing**, you should leave the detachment-cleanup responsibility to the attaching mod.
Otherwise things like https://github.com/minetest-mods/xdecor/issues/55 happen.

**Comment by paramat** [comment]
Ok so, prevent teleport if the player is attached to anything.

**Pull request closed without merging**
