### PR TITLE
Creative: Fix missing item bug

### PR DESCRIPTION
**Pull request by tenplus1**
This fixes the missing item for the following issue with creative menu: https://github.com/minetest/minetest_game/issues/1381

### CODE REVIEW

**Comment by rubenwardy** [comment]
Shouldn't start_i refer to the index of the first item visible?

**Comment by tenplus1** [comment]
@rubenwardy - which is 0.

**Comment by rubenwardy** [comment]
Arrays in Lua are indexed from 1 - are inventories inconsistent?

**Comment by rubenwardy** [comment]
:+1:

I do not like how the Lua API documentation calls it the starting index when it's clearly an offset, but that's not an issue here.

**Comment by sofar** [comment]
Interesting. If we're using a 0-index array here, that would certainly explain the confusion. Perhaps add a comment that it is indeed 0-indexed, or convert it entirely to 1-indexed instead?

This bug is just going to happen again :)

**Comment by paramat** [comment]
Tested, PR fixes the problem.
If it's an offset then 0 is acceptable.

**Comment by paramat** [comment]
022d22cecaa902827cbf05ca70e63ad342b51acf

**Pull request closed without merging**
