### PR TITLE
Add hurt sound

### PR DESCRIPTION
**Pull request by Snipie**
I saw this on the TODO list. http://dev.minetest.net/TODO#Sounds
Although fellow mates on IRC didn't like this, I decided to submit it.

### CODE REVIEW

**Comment by BlockMen** [comment]
Not the sound in this pull request. Either this pull gets updated with better sound (e.g. like @HybridDog s sound) or this PR will be closed shortly.

**Comment by MirceaKitsune** [comment]
I agree with @BlockMen. Although I wouldn't suggest ignoring the pull altogether... just replace the sound file with the one linked by @HybridDog before pulling. The person who opened this might no longer be around at all, and this is a good feature to add.

**Comment by tenplus1** [comment]
The bone crunch sounds better than a grunt, especially if female players get hurt in game :)

**Comment by paramat** [comment]
Not the grunt sound, the crunch is okay. Please update the PR.

**Comment by paramat** [comment]
@Snipie if you want to update this PR please do within a month, otherwise it will be closed.

**Comment by paramat** [comment]
Closing, see issue #715 for further discussion.

**Pull request closed without merging**
