### PR TITLE
Creative: Re-implement constant hand dig times, add comment

### PR DESCRIPTION
**Pull request by paramat**
Addresses #1419

### CODE REVIEW

**Comment by Fixer-007** [comment]
I have suggestion, match dig time with walking speed (4 nodes per seconds), this way you can constantly mine horizontally / vertically without bumping into the blocks.

**Comment by Fixer-007** [comment]
Also: all types of rail are digged slower than stone currently.

**Comment by rubenwardy** [comment]
:+1:

I'd say you could just merge a rebase correction without a PR (as it was agreed as such)

**Comment by paramat** [comment]
fa17fe31d6e3014728dc6d4e7aa8618ee77601e1

**Pull request closed without merging**
