### PR TITLE
Default: New snow textures by Gambit

### PR DESCRIPTION
**Pull request by paramat**
From PixelBOX2 texture pack.
Brightness increased for 'snow' and 'snow side'.
////////////////////////////////////

screenshot_20160913_023630

Issue #1287 
Snowball unchanged, snow and snow-side +63 brightness in Gimp. Snow side fringe pattern and shadow unchanged.

6da1a144-7959-11e6-88cd-e583c7a30a70

default_snow_gambit_bp63_128

### CODE REVIEW

**Comment by everamzah** [comment]
screenshot_20160913_094433
screenshot_20160913_094505

Looks good to me!

**Comment by sofar** [comment]
I love it, but the swirl really looks a lot like the sand texture ...

**Comment by Fixer-007** [comment]
Hmm, looks interesting, but I agree about swirl in general.

**Comment by paramat** [comment]
Compared to the original, increasing brightness had the effect of decreasing contrst, and the original contrast of the swirl was certainly too high. I tried decreasing contrst further but this started to make the whole texture look bad. I like the little ripples and don't see the similarity with sand a problem/

**Comment by sofar** [comment]
Anyway, big step forward so :+1: from me.

**Comment by paramat** [comment]
34c768d394276e78d657a22fac9bf127f95a7152

**Pull request closed without merging**
