### PR TITLE
Added on_blast to default chest

### PR DESCRIPTION
**Pull request by tenplus1**
Added on_blast function to default chest so that tnt explosions or mob blasts do not destroy it.  Also tidied some code.

### CODE REVIEW

**Comment by sofar** [comment]
I only see the cleanups.

**Comment by sofar** [comment]
This isn't what we discussed on IRC. The mobs API currently "ejects" all items in the chest. This is what should be done as well.

**Comment by sofar** [comment]
We should also make sure the chest itself is dropped.

**Comment by tenplus1** [comment]
The chest will be destroyed in blast so would not drop, only it's contents.

**Comment by sofar** [comment]
Why are you randomly ejecting items from the chest? The TNT API should take care of that. I think you actually want to return the items from the chest instead of dropping them.... This way the TNT API takes care of everything.

**Comment by sofar** [comment]
You want to return the chest item as well as return value.

**Comment by sofar** [comment]
I'll submit a patch that does this for all the "containers" in a nice and uniform way. Sorry for making you spend time on this - please close this.

**Comment by sofar** [comment]
Replaced by #1039

**Pull request closed without merging**
