### PR TITLE
Creative: Add myself in credits

### PR DESCRIPTION
**Pull request by kilbith**
Some people borrowed the creative code for their sub-games with an exclusive attribution to celeron55.

This is frustrating since I've largely rewritten, redesigned and carefully maintained this mod for the last months.

I claim my right to be credited.

### CODE REVIEW

**Comment by Ekdohibs** [comment]
:+1:

**Comment by PilzAdam** [comment]
:+1:

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
9a6cb2d7c8a7fb185ccc82cec40f28eea815be50

**Pull request closed without merging**
