### PR TITLE
Fix torch model rendering in `model[]` formspec element

### PR DESCRIPTION
**Pull request by OgelGames**
Fixes the torch models so they render correctly when used in the `model[]` formspec element. There is no change to rendering of the nodes.

Before:

After:

### CODE REVIEW

**Comment by sfan5** [comment]
So what does this actually change about the model? What was the issue?

**Comment by OgelGames** [comment]
The only thing I did to fix them was recalculate the normals, so there must have been something wrong with the normals.

**Comment by sfan5** [comment]
I debugged this a bit and it was the material commands, no need to rewrite the whole file. It's fixed now.

**Comment by OgelGames** [comment]
Ah, that makes more sense, thanks.

**Pull request closed without merging**
