### PR TITLE
Increase (ocean) water opacity to 191

### PR DESCRIPTION
**Pull request by lhofhansl**
See #2513 for discussion.

Also related to https://github.com/minetest/minetest/pull/8994, the waves also look much nicer when the water is a bit more solid.

Also note that this does not touch river water. If we want that to be the same I can make the change too, but I feel there the transparency is no detriment to immersion.

### CODE REVIEW

**Comment by paramat** [comment]
I agree river water is a different case, besides, in real life river water can be very clear. That can be considered separately.
:+1:

**Comment by lhofhansl** [comment]
I cannot merge into MTG, someone will have to do the honors.

**Comment by sfan5** [comment]
We're currently in feature freeze so it'll have to wait anyway.

**Comment by paramat** [comment]
lhofhansl, also, you are not a core dev for MTG (yet) so your approval doesn't count towards the 2 needed. I'm fairly certain another MTG core dev will +1.

**Comment by lhofhansl** [comment]
Forgot that we have separate core devs for MT-engine and MT-Game. My apologies.

Thanks for merging!

**Pull request merged**
