### PR TITLE
Fix screwdriver and beds

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by PilzAdam** [comment]
I'd call this workaround hacky.

A better way would be a on_rotate callback in the nodedef of beds / doors and calling this from the screwdriver if present.

**Comment by HybridDog** [comment]
but that wouldn't fix pushing beds with a mesecons piston

**Comment by HybridDog** [comment]
sorry that l touched your bed

**Comment by HybridDog** [comment]
l forgot the screenshot
HELLOIFYOUREADTHISTHESCREENSHOTDIDNTLOADYET

**Comment by HybridDog** [comment]
and l forgot to reference this https://github.com/minetest/minetest_game/issues/451

**Pull request closed without merging**
