### PR TITLE
Add creative.is_enabled_for

### PR DESCRIPTION
**Pull request by rubenwardy**
Makes it easier to make per player creative mode mods

It may be worth caching the setting

### CODE REVIEW

**Comment by ShadowNinja** [comment]
Also see Unified Inventory's implementation of player-specific creative access.

**Comment by rubenwardy** [comment]
Unified Inventory creates its own creative inventory so doesn't need to override the `creative` mod

**Comment by paramat** [comment]
bee5b316a86abba55ddb3bf97eab3cb9fb5803b5

**Comment by paramat** [comment]
@rubenwardy why not added here https://github.com/minetest/minetest_game/blob/master/mods/creative/init.lua#L17 ?

**Pull request closed without merging**
