### PR TITLE
Biomes: Add 'dirt with coniferous litter' node for coniferous forest

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20171222_034120

Tested.
A layer of grey and orange dead pine needles.
We could add ferns in a later commit, i would like to.

### CODE REVIEW

**Comment by Ezhh** [comment]
Would love to see ferns added. :)

**Comment by TumeniNodes** [comment]
> Would love to see ferns added.
Yep, with variable sizes would be great (same as grass 1-5 is done)

**Comment by NewbProgrammer101** [comment]
Try adding just a teensy bit of brown-ish green grass scattered around the forest floor.

**Comment by NewbProgrammer101** [comment]
An example: https://github.com/D00Med/farlands/blob/master/mods/mapgen/textures/mapgen_leafy_grass.png

**Comment by TekhnaeRaav** [comment]
I just said this in the issue, thought I should put it in here to just in case
But I am wondering if the 'forest litter' should kind of drop off at the bottom side of the block revealing some of the dirt.

**Comment by paramat** [comment]
If you reveal some dirt in the texture that dirt patch will then repeat every node which will look too repetitive.

**Comment by ThomasMonroe314** [comment]
Nice addition :)

**Comment by paramat** [comment]
8ab7c54d760b53cdc952657fa0125fd977ce97f9
Ferns next.

**Comment by Fixer-007** [comment]
It is non-activatable as with rainforest litter? Say I want to add this litter in my artificial coniferous forest.

**Comment by paramat** [comment]
I guess you mean 'seeding' the node somewhere by placing a decoration on top?
We forgot that for rainforest litter bu tcould be done for that and this.

**Pull request closed without merging**
