### PR TITLE
Change the registered name of the bed

### PR DESCRIPTION
**Pull request by Rui914**
Can register the bed from the other mods.

### CODE REVIEW

**Comment by PilzAdam** [comment]
This is not needed; beds can be registered by other mods if they use their proper mod-prefix in the name.

**Comment by Rui914** [comment]
It is, registration is possible, but the recipe is not properly registered.

**Comment by LeMagnesium** [comment]
> but the recipe is not properly registered.

What do you mean by this? You've not modified anything related to the recipes.

**Comment by Rui914** [comment]
https://www.dropbox.com/s/ezh88iifjg03q0q/Carpets.zip?dl=0
In this, error in carpet_tools.

**Comment by LeMagnesium** [comment]
Ok. First, it's not a craft recipe, it's a register_node which breaks, and second, you used the wrong prefix for your itemstring, it should be `carpet_tools` and not `carpet`.

**Pull request closed without merging**
