### PR TITLE
Carts speed

### PR DESCRIPTION
**Pull request by sofar**
Changes the max cart speed based on the slope:
    
- 6 for uphill
- 7 for horizontal - unchanged
- 8 for downhill

*Note: Krock's PR is underneath here since it should be merged first, and this would need a massive rebase otherwise, so it's just easier to review this way - just look at the last commit only*

**Merge only after #1412 **

### CODE REVIEW

**Comment by paramat** [comment]
:+1: but need to test.

**Comment by sofar** [comment]
You know, it still bothers me.

Horizontal speed is set to 7 by default. Because the way the code works, that means that the actual limit to velocity on slopes is `math.sqrt(2) * 7` which is 9.9 n/s.

So by default the code already makes carts go 40% faster uphill and downhill than horizontally.

I think we should tweak it to make the absolute speed  effectively do what we intended:

downhill: 5.25 * 1.41 = ~6
uphill: 5.70 * 1.41 = ~8

that would result in a true 6/7/8 speed

**Comment by sofar** [comment]
Meh, the problem is that on an angle change, the velocity vector isn't converted. So if the cart comes downhill at 8m/s (5.75m/s x/z velocity) it is put at a horizontal velocity of 5.75m/s velocity and so it loses 2.25m/s velocity.

The angle change should not result in a velocity loss.

**Comment by sofar** [comment]
still, 5.25 and 5.70 values look pretty good even though the math is off.

**Comment by paramat** [comment]
6 / 1.41 = 4.25, i think that's too slow, that's less horizontal speed than a boat.

> So by default the code already makes carts go 40% faster uphill and downhill than horizontally.

Yeah i've been thinking about this and whether to tune speeds as you suggest.
Curently i think it's best to not worry about this until carts are possibly in future updated to conserve absolute velocity instead of conserving horizontal velocity, otherwise other weird things happen.

This weird behaviour is consistent with player walking which as far as i know conserves horizontal velocity when going up steps, so i don't think it's a big problem to solve right now.

**Comment by sofar** [comment]
> 6 / 1.41 = 4.25, i think that's too slow, that's less horizontal speed than a boat.

at 7m/s horizontal the cart makes more than up for that.

**Comment by paramat** [comment]
:-1: Due to lower speeds now used.

**Comment by paramat** [comment]
I should mention, i noticed that in creative mode the rails take a long time to dig.

**Comment by sofar** [comment]
The dig problem has been discussed in other PRs, seems not specific to carts.

**Comment by paramat** [comment]
Alternatively you could increase the level speed to 7 * 1.41.

One thing that bothers me about differing speeds is the behaviour when going from level to uphill.
When hitting the start of the climb at max speed, 7, horizontal speed is conserved, so absolute speed jumps to 7 * 1.41, and then, i assume, slowly reduces to 6 * 1.41, or does it reduce instantly?
With your proposed reduction of uphill speed to 4.25 horizontal this will be even more noticeable.

So i'm a little concerned about odd behaviour, perhaps it's best to stay with a single horizontal speed throughout until a future change that conserves absolute velocity. Or, at least, go with 6, 7, 8.

**Comment by paramat** [comment]
I feel that the slowing due to friction / wind resistence could be a little smaller, trains tend to roll very efficiently.

My other off topic request is a stronger handbrake. It's almost useless at the moment and is barely noticeable when used. Perhaps equal to brake rails at -3?

**Comment by sofar** [comment]
Let's close this for now, I think I want to tweak the acceleration values instead.

**Pull request closed without merging**
