### PR TITLE
[translate] brasilian portuguese, and portuguese of Portugal.

### PR DESCRIPTION
**Pull request by Lunovox**
* Update translate files '*.pt_BR.tr' to brasilian portuguese. (Just some semantic improvements in the translation)
* Create any translate files '*.pt.tr' to portuguese of portugal. (Why did no exist none files to portuguese of portugal?)

### CODE REVIEW

**Review by appgurueu — COMMENTED** [review]
Looks legit, but I can't really judge since I'm not a native speaker; I'm limited to automatic translation. Do you (or anyone else) perhaps happen to know any speakers who could give this a look?

**Comment by Lunovox** [comment]
> appgurueu say:
> "Do you (or anyone else) perhaps happen to know any speakers who could give this a look?x"

Unfortunately I don't know anyone involved in the 'minetest_game' project who knows how to speak my native language, Brazilian Portuguese.

 What is the official procedure used in the 'minetest_game' project for accepting translation contributions?

**Comment by appgurueu** [comment]
> What is the official procedure used in the 'minetest_game' project for accepting translation contributions?

Well, we try to find Minetest community members who can give the translations a look.

But if we don't and the translation does not contain anything blatantly wrong, we will ultimately merge it anyways, trusting your judgement.

**Comment by Lunovox** [comment]
> But if we don't and the translation does not contain anything blatantly wrong, we will ultimately merge it anyways, trusting your judgement.

I didn't understand.  What do I need to do for my translation to be approved?

**Comment by appgurueu** [comment]
> I didn't understand. What do I need to do for my translation to be approved?

Nothing, just wait. Hopefully someone who speaks portuguese comes along and reviews it. If not, we'll merge it anyways.

Thanks for the translation.

**Comment by JoseDouglas26** [comment]
> Unfortunately I don't know anyone involved in the 'minetest_game' project who knows how to speak my native language, Brazilian Portuguese.

Hi!

**Comment by appgurueu** [comment]
> Hi!

Would you be interested in reviewing this?

**Comment by Lunovox** [comment]
I would like to thank everyone for their trust in my translation proposal. 

To use in the minetest game.  I used a contextual translation for the word "wool", rather than a literal translation.  I am always willing to explain the reason for my choice to anyone who still has questions.

Thank you!

**Pull request merged**
