### PR TITLE
buckets won't run out of water/lava in creative mode

### PR DESCRIPTION
**Pull request by cdqwertz**
https://github.com/minetest/minetest_game/issues/1133

### CODE REVIEW

**Comment by paramat** [comment]
:-1:

**Comment by tenplus1** [comment]
Even in creative mode the need to empty and fill buckets is important.

**Comment by cdqwertz** [comment]
Why is it important to fill and empty buckets in creative mode? I think it is just annoying.

**Comment by yyt16384** [comment]
Remember that there can always be something that depends on buckets getting empty, like deployers in pipeworks.

**Comment by paramat** [comment]
I see it this way: creative supplies infinite bucket items, if you want infinite liquid sources then the nodes themselves are elsewhere in creative. The bucket items are not the way to access infinite liquid sources.

**Comment by cdqwertz** [comment]
What do you think about a setting which allows the user to enable/disable this?

**Comment by yyt16384** [comment]
Is there any reason not to use water source nodes?

**Comment by paramat** [comment]
A setting is unnecessary complexity.

**Pull request closed without merging**
