### PR TITLE
alias moreores tin

### PR DESCRIPTION
**Pull request by DS-Minetest**

### CODE REVIEW

**Comment by Thomas--S** [comment]
`minetest.register_alias_force` is better here, I think. It avoids having both versions of tin in the same world.

**Comment by DS-Minetest** [comment]
Done.
The bigger question is if this has any chance to be included to minetest_game since moreores is from 3rd party. But moreores had tin before minetest_game had and so, many people used it and it's a bit like with the old naming convention.
Why wasn't copper or diamond aliased as they were added?

**Comment by Ferk** [comment]
Wouldn't it make more sense to add the alias to moreores?
https://github.com/minetest-mods/moreores

**Comment by paramat** [comment]
:-1: We don't add aliases for the sake of external mods, as most servers probably have not used moreores and aliases are best avoided if possible. Better to add the aliases in a separate optional mod for those who used moreores.

> Why weren't copper or diamond aliased as they were added?

Same reason.
There are very many other new nodes that have been added to MTG that could have had aliases added due to previous use in mods, but imagine the mess, and all those aliases running mostly for no reason.

**Comment by sofar** [comment]
>Wouldn't it make more sense to add the alias to moreores?
>https://github.com/minetest-mods/moreores

Yes

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DS-Minetest** [comment]
I agree, the alias shouldn't be in minetest_game but in moreores.

**Pull request closed without merging**
