### PR TITLE
Changed snow to walkable = false

### PR DESCRIPTION
**Pull request by DonBatman**
For issue #1233 

@paramat

### CODE REVIEW

**Comment by paramat** [comment]
Thanks much appreciated, but it should be:
```
	walkable = false,
```
Sometimes 'walkable' confuses me too.

**Comment by paramat** [comment]
:+1: once fixed.

**Comment by paramat** [comment]
I can squash these commits during merge if you cannot.

**Comment by rubenwardy** [comment]
:+1:

**Comment by paramat** [comment]
61a197ffd87aa0f813479012f93cc5965eb9017d

**Pull request closed without merging**
