### PR TITLE
Default: New mese block texture

### PR DESCRIPTION
**Pull request by paramat**
See discussion in #1066 

default_mese2_128

^ Submitted

default_mese_crystal128

^ Current mese crystal

default_mese_2nd128

default_mese_1st128

^ Second and first texures

default_mese_block128

^ Current

My texture combines the pure yellow node of our first texture with the font/shadow style and raised symbols of the second, but with more abstract symbols to be suitable as a node of unknown/alien/ancient origin.
The symbols are meant to look a little like MESE while also being abstract enough to be unknown/alien/ancient symbols, the origin of the word is therefore explained as what the symbols resemble.
Symbol shading is sampled from a heavily used shading on the crystal texture.

### CODE REVIEW

**Comment by benrob0329** [comment]
I like it, but I think that the shading is a bit too bright.

**Comment by paramat** [comment]
I need to experiment further.

**Comment by sofar** [comment]
I wouldn't be opposed to making the textures animated for this block. If it is such a special one, let's see if we can pimp it out. We should even add a node sound (through an entity) if possible.

**Comment by paramat** [comment]
Shading along the edges is a bit awkward in-game. Also i'm working on darker shading under the letters.

**Comment by paramat** [comment]
screenshot_20160504_223827

No edge shading.

**Comment by sofar** [comment]
Needs accents around the glyphs to make it look less flat.

**Comment by RHRhino** [comment]
@paramat how about useing the old one with the yellow colors?
default_mese_block_128

**Comment by benrob0329** [comment]
That just looks like deteriorated Mese...

I like the shading of the current texture, but the alien feel of paramat's.

**Comment by paramat** [comment]
PilzAdam, my approach is explained here https://github.com/minetest/minetest_game/issues/1066#issuecomment-216320032
sofar, i tried that but it becomes too messy and harder to see the structure of the symbols. Also i am copying the simple 'top down' shading of the dark golden texture.

**Comment by paramat** [comment]
Updated. See first comment. Please also consider the alternative with darker symbol shading at the end of the first comment.

**Comment by sofar** [comment]
I think it has potential, but it needs to be taken way further. The flatness is still bothersome to me.

**Comment by Fixer-007** [comment]
I think current mtg texture is best, no need to change it.

**Comment by Ekdohibs** [comment]
I also prefer the current texture.

**Comment by paramat** [comment]
With apologies, the current texture is crap.

**Comment by sofar** [comment]
I agree with @paramat that the current texture is probably the worst texture in the game right now... It's terrible and non-translatable.

**Comment by benrob0329** [comment]
I prefer the shading of the current texture, but the alien-esque feel of the proposed one.

**Comment by paramat** [comment]
Updated, submitted the version with darker shading.

**Comment by benrob0329** [comment]
mese old vs new

I like it, but it feels more like a control panel to me...though, if it has alien origin maybe that's a good thing :laughing:

**Comment by ExeterDad** [comment]
I agree with the control panel observation. Why not have a meaningful glyph on the faces? They look ancient, or even alien and no need to translate. This is a odd picture for a example, but it's a "moon glyph" supposedly meaning "energy"
energy

**Comment by C1ffisme** [comment]
Hmmm... Those symbols remind me of alchemy, and I'm thinking, what if Mese is some kind of "Philosopher's Stone"?

**Comment by paramat** [comment]
The idea is the symbols look a little like MESE.

**Comment by C1ffisme** [comment]
@parmat That's true, but I'm not sure that an alien or ancient culture would have the same writing style that we have. If you were to look at an Asian language, it would look nothing like any western language, since they have adopted a different form of writing ever since they thought one up.

I suppose it's okay to look slightly like the word "MESE", though, but maybe make it a bit harder to see? (Maybe tilted sideways?)

**Comment by paramat** [comment]
The symbols are not obviously Terran: 3 vertical lines, 3 horizontal lines and a snake shape. They're designed to look like MESE in the classic formation while also being capable of being alien or ancient hieroglyphics.

**Comment by Thomas--S** [comment]
How about this?



If you want to use the texture, it is completely made by me and published under the CC0 license.

**Comment by sofar** [comment]
@paramat I don't think the back story should even exist. I also think that we should `minetest.register_alias(`default:mese`, `default:SomeWordWhereTheMLetterDoesNotStandForMicrosoft`)` and replace all occurences in the game that way. I'd go as far as saying we should call it `carnotite` or if you like odd names, Kuovoho (after the chemical formula for Carnotite)`. There, a better name for mese. KILL IT WITH FIRE.

@Thomas--S that's a very decent texture. Swap the "M" and "E" in the top row and I think you have a winner. 

I still think at least the mese block should be animated, as well. It should be super rare and special, in many ways.

**Comment by Ekdohibs** [comment]
@Thomas--S I like this texture a lot; though I prefered the colors of the current one. Since it's CC0, I might try changing the current one to use your glyphs instead :).

**Comment by Thomas--S** [comment]
@sofar, @Ekdohibs:

How about this one?

**Comment by Ekdohibs** [comment]
@Thomas--S the current one is still a bit brighter: 
screenshot_20160508_093200
If you change the colors to match those of the current texture, your texture will clearly be my favourite :).

**Comment by Thomas--S** [comment]
@Ekdohibs: Is this better?

**Comment by Ekdohibs** [comment]
@Thomas--S: what about this one?
mese

**Comment by Thomas--S** [comment]
Looks good to me. :+1:

**Comment by Ekdohibs** [comment]
Opened a pull request for it: #1082.

**Comment by Fixer-007** [comment]
Can we leave default MESE texture alone? :(

**Comment by benrob0329** [comment]
@sofar maybe once mods can define custom shaders it could have a a glowy hazy effect?

**Comment by paramat** [comment]
Closed as unpopular, i support everamzah's texture #1093

**Pull request closed without merging**
