### PR TITLE
Change ore generation to a non-uniform distribution.

### PR DESCRIPTION
**Pull request by Ekdohibs**
screenshot_3665078645

### CODE REVIEW

**Comment by paramat** [comment]
I quite like the idea of makng ores optionally patchy, but the implementation should be discussed with hmmmm as he designs the ore distributions.

**Comment by C1ffisme** [comment]
I think this is a good idea, but make it more like different biomes having different ores. Also, you could have ores have higher bounds in certain biomes, like diamonds being common in snowy mountains or something.

**Comment by paramat** [comment]
Ores are now actually per biome, hmmmm made a commit recently.

**Comment by paramat** [comment]
Sorry i don't like this, too much additional use of noise, not worth it.

**Comment by C1ffisme** [comment]
One thing I don't like is that this seems to use a new config file. But this file is also in a **read-only** directory. Either the pull should use minetest.conf, or be made a mapgen flag.

**Comment by paramat** [comment]
3 octaves is unnecessary for ores, 1 is enough and much lighter.

**Comment by ShadowNinja** [comment]
@C1ffisme: Actually, the world path is writable.
I'd prefer this in minetest.conf though.

**Comment by Ekdohibs** [comment]
@ShadowNinja: the problem is that this needs to be enabled or disabled in a per-world basis, to keep mapgen consistent. What would be best would be to have a per-world additional minetest.conf that would override other settings of the minetest.conf's in other places, however it is how it works right now.
@paramat: why do you think it is not a good idea if it is configurable?

**Comment by paramat** [comment]
Although i quite like the concept of ores being linked to location, 3D noise is heavy and we would need 15 3D noises to do this, i don't think it's justified. My attitude to options is that making something optional is no excuse =)

**Comment by C1ffisme** [comment]
@ShadowNinja Sorry for the bump, but for clarification I was talking about line 39 of init.lua. There is a new file inside of default called conf.lua.

Actually, speaking of bumping this, we should really consider moving this into minetest or keeping it out.

IMHO I think this may make minetest be a bit more about exploration, and less about being far down enough that all ores are very common. It also makes owning a chest full of every ore be also about shipping the ore from mining projects far away.

**Comment by 0-afflatus** [comment]
I don't think this would significantly improve the game, although I like the idea. My only issue with ores is how to get rid of the spikes in sheet ores, but that's another matter.

**Comment by C1ffisme** [comment]
Well, we need to close this, or continue discussion. Considering it's controversial, I would probably say to just close this.

**Comment by paramat** [comment]
We close with a majority disapproval of the 5 mtgame devs.

**Comment by Fixer-007** [comment]
release as separate mod?

**Comment by PilzAdam** [comment]
:-1:, as this leads to unnecessary frustration of players. If we want this then we should also add some kind of ore radar, which would fundamentally change the game.

**Comment by sfan5** [comment]
:-1:

**Comment by paramat** [comment]
There's no way 15 3D noises are justifiable, even for a nice idea, 3D noise is very heavy.

**Comment by proller** [comment]
but merged to freeminer

**Pull request closed without merging**
