### PR TITLE
Italian localisation

### PR DESCRIPTION
**Pull request by h4ml3t**
Added:
Italian locale files.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
FYI: A few strings have been changed or added after your translation. If string freeze gets confirmed by core devs, I will tell you which ones. I will also update the few missing strings in German.

**Comment by h4ml3t** [comment]
> FYI: A few strings have been changed or added after your translation. If string freeze gets confirmed by core devs, I will tell you which ones. I will also update the few missing strings in German.

Thank you, this is much appreciated :)

**Comment by h4ml3t** [comment]
For the record: https://forum.minetest.net/viewtopic.php?f=18&t=23386&p=358558#p358558

**Comment by Wuzzy2** [comment]
@h4ml3t: The translation templates were updated today. Please consider these changes for your translation. In this link you will see the changes:

https://github.com/minetest/minetest_game/commit/8c9821b227da5e71aa4e863c78cb413b8c2a00f4

**Comment by h4ml3t** [comment]
@Wuzzy2 Thanks for the info!
@sfan5 @paramat Translations updated, does GitHub allow you to squash the commits?

**Pull request merged**
