### PR TITLE
Fix smooth lighting

### PR DESCRIPTION
**Pull request by numberZero**
This patch fixes this smooth lighting bug:
bug
@Fixer-007 please check this.

### CODE REVIEW

**Comment by Fixer-007** [comment]
Sure

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Approval from sofar http://irc.minetest.net/minetest-dev/2017-01-26#i_4796406

**Comment by paramat** [comment]
38500da6556860dca2d6197749f457a64f56f934

**Pull request closed without merging**
