### PR TITLE
nodebox -> node_box

### PR DESCRIPTION
**Pull request by Thomas--S**
Seems like this was a typo

### CODE REVIEW

**Comment by SmallJoker** [comment]
Since this is an invisible node that's required to make the player collide with it, the while `node_box` definition could be omitted.

**Comment by C1ffisme** [comment]
Wait, do both of these work? I would think that the previous code was broken.

**Comment by sofar** [comment]
Nah, this is cosmetic since the texture is blank, and the collision box is what this is about. This is a good fix though :)

**Comment by Thomas--S** [comment]
Thanks for merging!

**Pull request merged**
