### PR TITLE
add food groups to blueberries

### PR DESCRIPTION
**Pull request by tenplus1**
add {food_blueberries = 1, food_berry = 1} groups to blueberries item.

### CODE REVIEW

**Comment by paramat** [comment]
Please can you explain why?

**Comment by paramat** [comment]
I'm guessing for mod recipes, but i can't find an issue mentioning this. I'm not necessarily opposed but the uses and need should be explained somewhere.
While you're at it, why not add food groups to all MTG food items?

**Comment by tenplus1** [comment]
Food groups exist already for apple and mushroom and wheat.

**Comment by paramat** [comment]
Just seen they do, sorry.
Is 2 groups necessary? After all we don't have 'mushroom' and 'brown mushroom'? How about just 'food_berry'?

**Comment by Ezhh** [comment]
Two makes sense in this case. There are mods that add specific types of berry related food, so unless you have both, this doesn't work.

**Comment by paramat** [comment]
I don't think mods should dictate excessive group usage in MTG, it should be the other way around. Burt not dissapproving and it has 2 approvals.

**Comment by Ezhh** [comment]
Just to add some thoughts, this is not a case of mods dictating what happens with MTG; this is a case of MTG adding groups to make the game easier to extend. MTG is used as a base by many people, so this makes complete sense and isn't excessive. 

I noted there are specific mods using berries because I've previously seen the argument that things shouldn't be added unless there's a real use case for them.

**Comment by paramat** [comment]
@tenplus1 we just noticed that you based this PR on 'stable-5' branch instead of 'master', and we merged it to 'stable-5' without noticing this. Please remember, it's very important to only ever base a PR on 'master' branch. And we need to remember to check the branch being merged to.

**Pull request merged**
