### PR TITLE
Fix missing papyrus in savanna, add a dry dirt version

### LINKED ISSUE #2577: Papyrus wants default:dirt but only default:dry_dirt exists in savanna_shore biome
Unless I'm completely missing something, 5.1.0 generates no papyrus at all, since it includes #2422 (which broke this) but not #2535 (which added an alternative).

### PR DESCRIPTION
**Pull request by paramat**
Papyrus was missing from the dry dirt 'savanna_shore' biome due to
only being placed on dirt. A mistake made when changing savanna
dirt to dry dirt.

Rename existing papyrus schematic to 'papyrus_on_dirt' and only
place in the 'rainforest_swamp' biome.
Add a new papyrus schematic 'papyrus_on_dry_dirt', placed in the
'savanna' biome.

//////////////////////////

screenshot_20200203_200245

screenshot_20200203_200656

Closes #2577

Summary of changes:
* Existing papyrus schematic, which contains dirt nodes, is renamed to 'papyrus_on_dirt'.
* New papyrus schematic 'papyrus_on_dry_dirt' is added, containing dry dirt nodes.
* The existing decoration registration for papyrus is duplicated, and both have their 'name', 'place on', 'biomes' and 'schematic' fields edited.

How to test:
Add these lines to .conf:
```
mg_biome_np_heat = {
    offset      = 100,
    scale       = 0,
    spread      = (1000, 1000, 1000),
    seed        = 5349,
    octaves     = 3,
    persistence = 0.5,
    lacunarity  = 2.0,
    flags       = eased
}
mg_biome_np_humidity = {
    offset      = 55,
    scale       = 10,
    spread      = (1000, 1000, 1000),
    seed        = 842,
    octaves     = 3,
    persistence = 0.5,
    lacunarity  = 2.0,
    flags       = eased
}
```
These settings will make a world only have savanna and rainforest biomes.
Fly / teleport around to check papyrus is present in both biomes (keep in mind it is placed in patches, not everywhere).

### CODE REVIEW

**Comment by TumeniNodes** [comment]
I am both ashamed and surprised we missed this

**Comment by tuedel** [comment]
So there is supposed to be "dry" dirt surrounded by water?
I'd suggest just placing dirt(_with_dry_grass) instead of dry_dirt(_with_dry_grass) at or below sea level for the savanna_shore biome.

**Comment by LoneWolfHT** [comment]
> So there is supposed to be "dry" dirt surrounded by water?

It's more of a sand/clay IIRC

**Comment by paramat** [comment]
tuedel, good point, i was thinking about this, however we did decide to use the so-called 'dry' dirt in water as it is, and looks, more suitable for savanna. Although it is called 'dry' it is just a different dirt type with a reddish colour suitable for drier biomes, the node does not have to actually be 'dry'.

So now we have dry-looking wet dry dirt, and in the farming mod we have wet dry soil =D

**Comment by TumeniNodes** [comment]
we should have gone with arid_dirt or even savanna_dirt

**Pull request merged**
