### PR TITLE
Default: Add 'acacia leaves simple' texture

### PR DESCRIPTION
**Pull request by paramat**
A deeper, darker level of leaves is created by tiling the texture
2 by 2, reducing brightness and offsetting this.
For a denser leaf appearence with the 'simple leaves' setting.
Also used for acacia bush leaves.
//////////////////////////////////////////////

default_acacia_leaves_simple3_darker128

Addresses #1362 
Tested.

screenshot_20161105_082610

screenshot_20161105_082523

screenshot_20161105_082821

screenshot_20161105_082750

screenshot_20161105_082851

### CODE REVIEW

**Comment by Fixer-007** [comment]
Texture looks somewhat repetitive on on screenshot 4 and 5.

**Comment by paramat** [comment]
There's a reason for that :]

**Comment by paramat** [comment]
@sofar @sfan5 @rubenwardy

**Comment by paramat** [comment]
Will darken underlayer more.

**Comment by paramat** [comment]
Updated.

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.net/minetest-dev/2016-11-05#i_4737593

**Comment by paramat** [comment]
c7e2d594610cacfb4bb7ed0e3b950eeed58b7d01

**Pull request closed without merging**
