### PR TITLE
xpanes add new steel bar door sounds

### PR DESCRIPTION
**Pull request by TumeniNodes**
Suggested by @Wuzzy2 to change the open/close sounds for the new steel bar doors
https://github.com/minetest/minetest_game/issues/2495

I definitely agree the current steel door sounds via default do not fit the character of the new steel bar doors at all.
So these are the sounds I have created/produced for those new doors.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
^^

**Comment by paramat** [comment]
They're more suitable than current sounds i agree.

**Comment by TumeniNodes** [comment]
I had mentioned possibly changing these sounds a bit but, I'm going to stick with these. They work well and I like them.

**Comment by paramat** [comment]
TumeniNodes are you happy with the sounds? It would be good to merge the intended sounds for 5.1.0.

**Comment by TumeniNodes** [comment]
> TumeniNodes are you happy with the sounds? It would be good to merge the intended sounds for 5.1.0.

Yes I am.
I was unsure at first but after using them for a while and even some feed back from a couple people outside of the community, I am happy with them.

**Comment by paramat** [comment]
Screenshot from 2019-09-27 18-32-01

The close sound is fine, but i'm not happy with the open sound. Looks like it is 2 bits of sound heavily edited and joined, the first sound ending abruptly (see image). This gives it a very abstract 'creak-creak' sound.
The opening creaking sound has potential, just not as heavily edited/processed as this.

**Comment by TumeniNodes** [comment]
I made some more adjustments, try this (it definitely sounds and works better)

**Comment by paramat** [comment]
Ooh this has potential.

**Comment by paramat** [comment]
:+1: Very good sounds when tried in-game, levels are good too.

**Comment by TumeniNodes** [comment]
Thank you

**Comment by TumeniNodes** [comment]
Thank you

**Comment by TumeniNodes** [comment]
Thank you both

**Pull request merged**
