### PR TITLE
Licenses: Change WTFPL to MIT (part 1)

### PR DESCRIPTION
**Pull request by paramat**
Part 1: All mods except default and xpanes.
Add license.txt files.
Add missing README.txt files.
Check and update copyright years for all contributors.
Improve text format and make more consistent.
/////////////////////////////////////

WIP
**** Please don't merge anything that creates a conflict with this ***
This has turned out to be a huge task.
See #1259 for discussion and details of intentions.

### CODE REVIEW

**Comment by sofar** [comment]
But it looks great. :+1:

**Comment by paramat** [comment]
I'll merge this once done to avoid delay or conflicts, as it has been discussed fully.

**Comment by paramat** [comment]
To do: Find who is the author of tnt textures, anyone know?

**Comment by paramat** [comment]
e9d26e2ee31b4687c91f3e9a811f49b905a3a529

**Pull request closed without merging**
