### PR TITLE
Flowers: Make waterlily floodable

### PR DESCRIPTION
**Pull request by paramat**
When waterlilies are placed near river water source make flowing river
water remove waterlilies instead of flowing around them in an ugly way
////////////////////////////////////////////////////////

Fix for #1166

### CODE REVIEW

**Comment by sofar** [comment]
Agreed, this is a sensible way to solve it. :+1:

You could argue that mapgen shouldn't "destroy" stuff but I think that's fair game if intentional.

**Comment by paramat** [comment]
f4f9e58ef2b537a65654c76ad99486cf4e7e497a

**Comment by MarkuBu** [comment]
Thanks. Good idea

**Comment by yyt16384** [comment]
Now players will lose their waterlilies if they place water near them :(

Not a big problem, but since waterlilies can't be grown manually losing them will be annoying.

**Pull request closed without merging**
