### PR TITLE
Add max_hear_distance for fire

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by MT-Modder** [comment]
:+1: Better than default.

**Comment by paramat** [comment]
Perhaps also, to reduce the sound overload of a large forest fire, we could make a single fire node emit a sound less often, just the occasional crackle?

**Comment by Rui914** [comment]
After resolving the lag problems, to open.

**Comment by Rui914** [comment]
Yes.

**Comment by sfan5** [comment]
9c15ebccab09208886ebe9639c75199ba83d89c3

**Pull request closed without merging**
