### PR TITLE
mtg mods use " " instead of ' ' for item names

### PR DESCRIPTION
**Pull request by TumeniNodes**
Continuation of #2430 
This concludes, covering all the other mods within MTG

### CODE REVIEW

**Comment by paramat** [comment]
Will review, test and merge ASAP.

**Comment by sfan5** [comment]
Note that these changes do not fall under the "trivial" merging rule and require two coredev approvals.

**Comment by paramat** [comment]
Actually, they do, clearly, there's almost nothing more simple and trivial than a straightforward ' -> ".
Requiring the time of 2 core devs over something like this is a waste of precious time.

**Comment by sfan5** [comment]
Please join IRC so we can discuss this first.

**Comment by paramat** [comment]
:+1: reviewed and tested.
Will merge as this clearly only requires the attention of 1 core dev. Also because this needs merging quickly to avoid conflicts or rebase.

**Comment by paramat** [comment]
sfan5, sorry, due to my daily schedule i am often busy and can't be on IRC until late evening UK time, by which time many Europeans, who are 1+ hours ahead, are in bed. We can discuss this here in the thread, i can't see why it needs to be discussed in IRC.

This clearly only needs the attention of a single core dev. It's beyond my comprehension why you don't realise this.
The concept is obviously approved, and the code changes are extremely simple, mind-numbingly so.
I would instantly trust any core dev to attend to this by themselves.

**Comment by paramat** [comment]
From IRC:

08:45 sfan5      ~tell paramat the "trivial" rule applies to small patches, 263 line changes is not a small patch

The wording of the 'trivial rule' cannot possibly cover all situations, so interpreting it literally and strictly is not a good idea. We use good judgement to know when something does not require the standard rules.

The 'trivial rule' text is:
"If you have a small patch, fixing some compiler error or other trivial mistake, notify about fixing it on #minetest-dev, wait for 5...15 minutes and push it."
The text is not really applicable to this PR, by adding the 'trivial' label i do not necessarily mean to refer to this text, what i mean by the label is, this PR only requires the attention of 1 core dev.

In MT development we often use good judgement and common sense to bend the rules to work fast and efficiently. This is even more important recently considering the critical lack of core dev time and only having 1 active MTG core dev.

**Comment by sfan5** [comment]
WHAT THE FUCK ARE YOU DOING?
I explicitly asked you to come to IRC <b>first</b> to discuss this, but you just post your view at 3am and just go ahead one hour later without me every having had a chance to say anything.

> due to my daily schedule i am often busy

you disagree with me on github within 5 minutes of posting my comment but when I ask you to come  to IRC you disappear for the rest of the day
shit don't add up

**Comment by sfan5** [comment]
Now, let's have discussion:

> paramat merged commit 7f83012 into minetest:master 10 hours ago

"I did not consider your concern important and did it anyway without consulting anyone"
Is this what you're trying to say here?
Imagine if everyone behaved this way. Would you want to be treated like this?

> sorry, due to my daily schedule i am often busy and can't be on IRC until late evening UK time, by which time many Europeans, who are 1+ hours ahead, are in bed

You not having the opportunity to coordinate with other coredevs does not allow you to skip this coordination. This is not an excuse.

> The wording of the 'trivial rule' cannot possibly cover all situations, so interpreting it literally and strictly is not a good idea. We use good judgement to know when something does not require the standard rules.

We should use good judgement to know when to ignore rules?
Really? Are you sure? Rules are not made to be broken when convenient.

> But every line consists of nothing other than ' -> ", 'small patches' assumes lines of standard complexity.
> The 'trivial rule' text is:
> "If you have a small patch, fixing some compiler error or other trivial mistake, notify about fixing it on #minetest-dev, wait for 5...15 minutes and push it."

The "small" refers to the lines of code changes, irregardless of complexity. Bulk changes such as #2430 never have and do not fall under this.
Pre-2015 "less than 5 LOC" was even part of the rule. This was changed for more flexibility, but the intention remains the same.

Next, when the rule says "trivial mistake" it means <i>bug</i> fixes or single style fixes to stop clang-format/luacheck/whatever from complaining.
General changes in code style were never intended to be covered, nor was the rule ever applied this way.

By the way, how do you use this to justify #2400?

> Tell people openly what you do, and if someone finds a problem in what you do, allow resolving to take its time. 

While we're on the topic of rules, take a look at this one.

Someone (me) had a concern, you disagreed and merged it any less than 12 hours later in a quiet moment while nobody was around.
Do you believe the 6 hours I was asleep were enough time to resolve my concern? Do you believe you have followed this rule appropriately?

> notify about fixing it on #minetest-dev, wait for 5...15 minutes and push it

Next one, `#minetest-dev` was unusually quiet while you pushed this patch:
file
What's your excuse?

<hr />
Lastly:

> This clearly only needs the attention of a single core dev. I don't understand why you don't realise this.

I <b>agree</b> (yes) with you on this point.
Things as simple as code style changes do not require the full-time attention of two developers,
however rules exist, and they exist for a reason, they are made to be followed and you can't ignore them when you feel like it even if the end result is ultimately better.

**Comment by sfan5** [comment]
By the way, the reason I disagree with this PR is:

The style changes are useless (no improvement to readability or anything) and will cause existing PRs that touch item names to need a rebase, which is a pretty big disadvantage for essentially zero advantage.

But its not like I had the chance to voice my concerns before you merged this or the other one ¯\\\_(ツ)_/¯

**Comment by TumeniNodes** [comment]
>The style changes are useless (no improvement to readability or anything) and will cause existing >PRs that touch item names to need a rebase, which is a pretty big disadvantage for essentially >zero advantage.

Not wanting to get into the middle of this disagreement, I just want to add something here.

The two reasons I felt a need to take on this extremely monotonous, tedious task...
A - it provides a uniform look/style throughout all the code.
B - it saves people doing future PRs from getting a request to change ' > " , because they may not know this quotes are to be used instead of single quotes.
Now, it will be clear throughout.

The instances were extremely random, and spread out all over...

If style is not so important, then why bother people about "use 4 tabs please", or line breaks, etc.?
Just let them use the style they're comfortable with or used to using.

Well, because then the code looks messy and can be a little confusing for new comers.

As for the second part of your disagreement, I do apologize, I had not thought about the impact but, please also consider the time this will save in the future when a contributor can clearly see what to use, if they have an extensive PR, using all single quotes rather than quotes.

Anyway, sorry for the hassle this has caused, but in the end I personally feel it was needed and worth doing... and no one else was going to be bored enough to sit and do it completely through, any time soon.

**Comment by SmallJoker** [comment]
@paramat The PR does not contain any functional changes, but if you're already asked to
> Please join IRC so we can discuss this first.

then please do that. Even though you're an important contributor of minetest_game, it does not grant anarchy for you. #minetest-dev is logged, and two bots in there support leaving messages for certain people - there's even MemoServ that can be used by registered users.

More communication please.

**Comment by paramat** [comment]
sfan5, if you had a problem with this PR (which you did) i would have preferred you add a comment explaining that, instead of asking for a real time discussion / argument on IRC (which i found intimidating and threatening and made me very much not want to be on IRC). This is why i lost my patience and merged it. If you explained a concern in the thread i might have waited.

I am a very introverted person with physical and mental health issues. Often i can't bear to be on IRC because it is real time communication, like a phone call, so often causes me stress and difficulty concentrating. This is why i'm on IRC less than other core devs. Before i became a core dev you may remember i avoided IRC, it was for the same reason.
Keeping that in mind, when communication is possible in a thread i don't think it's reasonable to insist on IRC discussion.

Your concern about PR rebasing was a valid point, however i disagree that should stop this PR, it had to be done at some point, was long overdue, and MTG doesn't have many PRs that are affected, development is quiet currently so it's a relatively good time.
It does have significant benefit despite beng functionally identical, the previous form was causing people to open PRs using the apostrophes, and generally the inconsistency made a mess of MTG code.

**Pull request merged**
