### PR TITLE
Add binoculars mod with binoculars item to allow zoom

### PR DESCRIPTION
**Pull request by paramat**
Add binoculars mod with binoculars item to allow zoom

Uses the new player object property 'can zoom'.
In survival mode, use of zoom requires the binoculars item in
inventory.
Zoom is automatically allowed in creative mode and for players with
the 'creative' privilege.
The binoculars.update_player_property() function is global so can be
redefined by a mod for alternative behaviour.
/////////////////

screenshot_20171003_235801

Addresses #1788 

"Crafting
binoculars:binoculars

default:obsidian_glass O
default:bronze_ingot B

O_O
BBB
O_O

Usage
In survival mode, use of zoom requires the binoculars item in your inventory.
It can take up to 5 seconds for adding to or removal from inventory to have an
effect, however to instantly allow the use of zoom 'use' (leftclick) the item.

Zoom is automatically allowed in creative mode and for any player with the
'creative' privilege.

The 'binoculars.update_player_property()' function is global so can be
redefined by a mod for alternative behaviour."

Behaviour is not ideal yet, but we intend to add inventory callbacks later so that adding and removal have instant effect, for now i have used a short update interval.

binoculars128

ka026-2

### CODE REVIEW

**Comment by TumeniNodes** [comment]
I feel as though the telescope texture would look better with a brassy color. Just a personal opinion.
I like this entire idea though, nice.

**Comment by tenplus1** [comment]
+1 but change recipe to use bronze, giving the ingots an excuse to be used.

**Comment by DS-Minetest** [comment]
It would be easy to keep the zoom priv.

**Comment by paramat** [comment]
Yes i'll use bronze, good idea, i used to have an antique gold coloured telescope.

**Comment by rubenwardy** [comment]
I'd prefer binoculars, as it's zoom. Telescope is usually for the heavens

**Comment by paramat** [comment]
Telescope is more period and genre-universal, binoculars are more modern.
This is meant to be a small telescope for landscape / sea use.

**Comment by TumeniNodes** [comment]
Well, binoculars have been around since approx. 1820's? I believe but, I like the use of a telescope more.

**Comment by Fixer-007** [comment]
Will it look like this?
flashpointresistance2014-02-1900-09-20-81

**Comment by JurajVajda** [comment]
Isn't telescope used for looking at the stars/space/planets due to its higher magnification and bigger lense while binoculars have lover magnification therefore they are used for magnifying i.e. sport events, hunting, military targets?

**Comment by Fixer-007** [comment]
Yes, good binoculars are awesome (trust me).

**Comment by paramat** [comment]
Updated to bronze, engine PR merged.

ka026-2

I didn't realise binoculars went so far back, these ones are Victorian and bronze, and look very 'steampunk' so yes i'll redo the texture to be these.

**Comment by rubenwardy** [comment]
I suggest making a monocular(?) craft item (ie: one of the shafts) and then produce a binocular by combining too of them.

ie:

```
binoculal:

# # #
|   |
# # # 

# - steel/bronze
| glass


binocular

shapeless,
BB

B=monocular
```

I'm not that fussed though

**Comment by paramat** [comment]
Yes good idea.

**Comment by rubenwardy** [comment]
Maybe Binocular Tube would be a better name

**Comment by jastevenson303** [comment]
I always called it a spyglass.

**Comment by jastevenson303** [comment]
Does this need, uhh, testing or something?  I might put start using it now because I'm getting anxious for this, and the map item.  :)  (I'll test.)

**Comment by paramat** [comment]
I'll be working on the bronze binocular texture soon, i'm still enthusiastic about this and will complete it soon.

**Comment by C1ffisme** [comment]
I don't like the idea of a monocular tube. Unless you plan on using it in other recipes (like an astronomy telescope or a scope for a weapon) craftitems for the sake of crafting are bad. It just raises the obvious question: Why couldn't I just craft the goal item without making a transition item?

**Comment by jastevenson303** [comment]
this is a base subgame with the purpose of expansion.  your point is lawed cl1ffisme.

**Comment by paramat** [comment]
> Why couldn't I just craft the goal item without making a transition item?

Because look at the crafting for a telescope, it is not possible to craft 2 telescope tubes side by side on a 3x3 grid, that's the only reason.

**Comment by C1ffisme** [comment]
@jastevenson303 
> this is a base subgame with the purpose of expansion.

That is still up for debate.

> your point is lawed cl1ffisme.

How is repetitive, unnecessary gameplay allowable just because the game is meant to be expanded upon?

@paramat 
> Because look at the crafting for a telescope, it is not possible to craft 2 telescope tubes side by side on a 3x3 grid, that's the only reason.

You can _almost_ make a crafting recipe for two tubes, it just looks ugly:
Binocular Craft

(Just so you know, I would gladly accept a monocular tube if you could craft a telescope or other item from it, because then it becomes "necessary". Maybe if you made a more general purpose "lense" item?)

**Comment by TumeniNodes** [comment]
The "purpose", is to add an item to the zoom feature, which I feel is better than just having, seemingly , bionic eyes.
I don't see an issue with adding a bit of character to the game here & there. As a side note, "telescopes", had their specific uses on the low-end in military & topography, aside from astronomical uses with higher powered lenses.
For this reason, I see the telescope as a proper use in relation to Minetest Game

**Comment by paramat** [comment]
Yes i'll consider a single stage crafting, otherwise binoculars would require 6+6+1/2 ingots, which is a lot.

**Comment by GreenXenith** [comment]
Tin still has few uses (none). Perhaps both bronze and tin could be used to craft? 2 bronze and a tin? Or visa-versa?

**Comment by paramat** [comment]
Tin is already in bronze.

**Comment by GreenXenith** [comment]
> Tin is already in bronze

Whoops I knew that..

**Comment by jastevenson303** [comment]
I got an issue that there's no feedback on this, in-game when a player attempts to zoom and fails without the item.  I'll likely file it on the tracker once this is merged, but it may be an engine issue.

How frustrating it would be, to set the zoom key in the settings menu, and then go to use it and wonder why it's not working.

**Comment by paramat** [comment]
That's probably because we are using 'player object properties' for zoom and these are otherwise not used for enabling an action, so there is no need for messages.
But maybe i can add feedback in the engine.

**Comment by paramat** [comment]
Code updated to binoculars and in a form consistent with map mod.
Just need to make a texture.

**Comment by Fixer-007** [comment]
Before merging this i don't want to see same debacle as with mapkit, i'm proposing to make it work like this: you craft it, place it in your inventory, _selecting_ binoculars in inventory turns on zoom immediately (there is no need for key presses or clicking anything).

**Comment by paramat** [comment]
I have just made the discussed improvements that were made to map mod.
No need to shout with bold font.
Your suggestion needs changes in the engine and we already plan to add inventory callbacks for instant response.
I disagree, see https://github.com/minetest/minetest_game/pull/1877#issuecomment-333921001
Zoom should remain the 'Z' key as it is more usable than shifting hotbar selection, and players will usually want to keep a particular tool or weapon in hand while also being able to use zoom, as they can do now.

**Comment by Fixer-007** [comment]
How can you look in binoculars and do something else at the same time, that's hardly possible (I have binoculars IRL).

**Comment by paramat** [comment]
Added texture and tested, ready for review.

These victorian linear field glasses are small, can use in one hand.
Also, currently in MT players can use zoom while wielding something else, i feel we should keep that.

**Comment by jastevenson303** [comment]
@Fixer-007 What you say is interesting, and in terms of gameplay makes sense.  However, this is too much for the sub-game; it's enough to ask the survivalist to at least have the item present.

TBF, zooming (which is really just an FOV change!) shouldn't ever be restricted or missing in the first place.  And _why_ we have to exit the game to change the FOV anyway is beyond my comprehension.

**Comment by paramat** [comment]
The texture is brassy and shiny, but doesn't match the colour of other bronze items, the colouring could be changed to be more consistent if requested.

**Comment by paramat** [comment]
WIP a few final changes to make.

**Comment by TumeniNodes** [comment]
@paramat  just wanted to say, I wish I was aware the textures for this and map tool could be more than 16px ha but, want to say these textures you have done for both these PRs are very nice.

**Comment by paramat** [comment]
Thanks. 32 pixel textures are not acceptable when the rest are 16 pixels.

**Comment by paramat** [comment]
Updated.

For the map mod we intend to add an API that will display the minimap when the item is 'used'. However zoom is only in effect when the key is presed, so doing the same here is not a good idea.
So i have re-added the instant allowance on item 'use', and therefore have increased the cyclic update interval to 5s as this now becomes less critical (actually 4.7 to be a prime of 0.1 and reduce syncing with other cycles).

**Comment by paramat** [comment]
cc371ac726305cfca64fad257b2c5cd37afd80cb

**Pull request closed without merging**
