### PR TITLE
Remove dupe aliases, fixes minetest/minetest_game#438

### PR DESCRIPTION
**Pull request by thatgraemeguy**

### CODE REVIEW

**Comment by PilzAdam** [comment]
The extra blank lines are there for a reason, don't remove them.

**Comment by thatgraemeguy** [comment]
What's the reason?

**Comment by PilzAdam** [comment]
It's there to visually separate "groups" of nodes.

**Comment by thatgraemeguy** [comment]
thanks (y)

Fixed it.

**Comment by C1ffisme** [comment]
Why has this not been merged? I :+1: it!

**Comment by BlockMen** [comment]
e604d8d7f32dcd194a126780f9f06cc50951bc9f

**Pull request closed without merging**
