### PR TITLE
Update Malay translations

### PR DESCRIPTION
**Pull request by mnh48**
This PR updates the Malay translations
It adds missing translations in existing files, as well as one file that was not translated before.
There are also some word choice changes that had been reconsidered and subsequently proceeded.

This PR is ready for review.

### CODE REVIEW

**Comment by appgurueu** [comment]
Would you happen to know any Malay speakers who could give this a look? I'd ideally hope we could get a review here as well. (I'd also be fine with merging this without a review, though.)

**Comment by mnh48** [comment]
maybe could pull @nisasyazwani to give it a look?
I'm not sure if she's new to the project in general or if she just created github and weblate to contribute
but she suggested some changes to Malay translation on weblate earlier (which I accepted)
for reference: https://hosted.weblate.org/changes/?user=nisasyazwani&action=4
also over on IRC early on: https://irc.minetest.net/minetest/2023-11-30#i_6136233

**Comment by nisasyazwani** [comment]
I will have you know that I'm not actually *that* new in the project, I had been around for a while
in fact I'm also in Minetest Discord, didn't you notice me chatting there before??

I just decided to make github account now just in case I decide to make some game for the upcoming game jam

**Review by nisasyazwani — APPROVED** [review]
anyway, I've reviewed it anyway, the translations looked fine and matched the intended meaning

**Comment by mnh48** [comment]
lol, I don't know you're in there
also checking chat history there, you don't really talk that much to begin with

thank you for taking your time looking through it then 😄

**Comment by appgurueu** [comment]
Thanks for the review!

> I just decided to make github account now just in case I decide to make some game for the upcoming game jam

In case you decide to make a game: Good luck! 😄

**Pull request merged**
