### PR TITLE
Option to disable bones.

### PR DESCRIPTION
**Pull request by tenplus1**
A much needed option to disable bones mod so that mods like dropondie can work properly.

### CODE REVIEW

**Comment by sofar** [comment]
I've got a patch pending that will allow you to do:

```
load_mod_bones = false
```

in world.mt

That's much more generic than adding yet-another-option-to-disable-a-mod.

#2198

**Comment by paramat** [comment]
There's another PR for this https://github.com/minetest/minetest_game/pull/203

**Comment by ShadowNinja** [comment]
The conditional that this uses seems to be inverted.  Shouldn't it be `if not disable_bones then` (or `if enable_bones` for a bit less confusion).

**Comment by davisonio** [comment]
:-1: How about simply disabling the mod from the main menu? Or using `load_mod_bones = false` manually.

Also, `enable_bones` would be better than `disable_bones`

**Comment by HybridDog** [comment]
>How about simply disabling the mod from the main menu?

You can't disable the blue ones.

**Comment by red-001** [comment]
@HybridDog It should be made possibly imo.

**Comment by HybridDog** [comment]
@red-001 They don't even want to merge my change which makes dependencies get activated automatically if the mod becomes enabled.
https://github.com/minetest/minetest/pull/3473

**Comment by paramat** [comment]
With those changes this PR will be better than #203

**Comment by paramat** [comment]
Also add documentation to MTGame minetest.conf.example.

**Pull request closed without merging**
