### PR TITLE
Better jungle wood and jungle tree top textures

### PR DESCRIPTION
**Pull request by VanessaE**
Jungle tree wood candidate from kilbith

Jungle tree top derived from the existing image combined with the original 0.3.x image, and a candidate image from @LazyJ, with color adjustments and other manipulations as needed to combine them smoothly and make them match the current jungle tree side.

See also issue #611.

### CODE REVIEW

**Comment by est31** [comment]
:+1: fwiw

**Comment by paramat** [comment]
I like the core of this but would like to edit the inner ring layers to suggest a strangler vine around a dark-barked host tree.

**Comment by kilbith** [comment]
Who deleted my comment expressing my disagreement ? That's censorship and the owner of this repo himself already said he was against that.

**Comment by Ekdohibs** [comment]
This looks good!
@kilbith are you sure it was not this comment? https://github.com/minetest/minetest_game/pull/618#issuecomment-129260643 (since both PRs have exactly the same name)

**Comment by kilbith** [comment]
Ah oops, sorry - confused.

**Comment by PilzAdam** [comment]
:+1:

**Comment by paramat** [comment]
2 devs like it and it looks okay to me as it is so go ahead +1.

**Comment by paramat** [comment]
Sorry i don't like this latest version.

**Pull request closed without merging**
