### PR TITLE
Add Backgrounds for Formspecs

### PR DESCRIPTION
**Pull request by C1ffisme**
Have you ever gotten tired of that bad-style background for formspecs? This fixes that problem. This also allows people to **change the background of formspecs with texture packs**.
 
Here are the backgrounds. Yes I know, **they are not good ones**, but I want **you** to suggest new ones by **posting them in your comment**: (No Screenshots, sorry, I don't have an available image site.)

Chest Background

Furnace Background

Inventory Background

Suggest new ones, but **do not use a free culture license** and **make sure they are apropriate for all ages**.

### CODE REVIEW

**Comment by Jordach** [comment]
These are moderately low quality and do not fit the style of inventory and
formspecs used by Minetest Game.

**Comment by C1ffisme** [comment]
@Jordach Yeah I thought so. I will allow anyone to propose different backgrounds, if they want (As long as they are appropriate for younger players, keep in mind.).

These were backgrounds I spent about 5 minutes making. So I can understand. This is more of a proposal than trying to redecorate minetest. If you want to make some better ones, go ahead.

**Comment by C1ffisme** [comment]
Bump!

**Comment by C1ffisme** [comment]
So... I'm guessing not many people want to suggest textures?

**Comment by HybridDog** [comment]
May you show screenshots?

**Comment by CraigyDavi** [comment]
minetest opengl 3 0 _052
minetest opengl 3 0 _053
minetest opengl 3 0 _054
minetest opengl 3 0 _055

**Comment by C1ffisme** [comment]
Thank you, @CraigyDavi .

**Comment by ShadowNinja** [comment]
I don't like the textures at all.  The text should be a formspec element, not in the image, if it's even added.  The items also clash with the background in a few places.

With a better texture maybe though...

**Comment by HybridDog** [comment]
What do you think about removing the text and removing the colour behind the itemslots?

**Comment by 0-afflatus** [comment]
It is such a matter of personal taste that I think this should be customisable per-user. Personally I don't see anything wrong with the current formspec backgrounds. I know other people dislike them. We're basically choosing wallpaper here.

**Comment by C1ffisme** [comment]
@0-afflatus Yeah, It's like changing the desktop background on a computer server with 20 people.

**Comment by BlockMen** [comment]
Maybe we should use 1 default formspec background, and all chests,etc get a ^formspec_bg_<nodename>.png overlay, that is blank by default. Then this game uses the same for everything but ppl can costumize with texturepacks.

**Comment by C1ffisme** [comment]
@BlockMen That sounds like a good idea, but can we make that ^formspec_bg_.png look good? Thats basically the idea of the pull request. I want to make minetest look better.

**Comment by BlockMen** [comment]
@C1ffisme for me the current is fine. But IMO the suggested backgrounds here are no improvement at all

**Comment by C1ffisme** [comment]
@BlockMen What I want is for people to suggest new backgrounds and I put them in my pull request. I want to encourage people to play this game, and people like pretty textures.

**Comment by C1ffisme** [comment]
Bump.

**Comment by C1ffisme** [comment]
Bumpety bump bump bump.

Hey people. I seem to have not demonstrated the fact enough yet. Here is what I want:
**Make your own textures**
I will use yours, not mine.

**Comment by C1ffisme** [comment]
Is anyone actually making textures, or ignoring this post?

Please show your progress!

**Comment by C1ffisme** [comment]
I'm going to close this now. I made a branch and will merge that.

**Comment by C1ffisme** [comment]
All conversation continues on #444 .

**Pull request closed without merging**
