### PR TITLE
Fix door volume level.

### PR DESCRIPTION
**Pull request by sofar**
Playing stereo sounds positionally in OpenAL causes it to play
the sounds unattenuated - same volume for all distances. This
shouldn't happen, and makes door sounds unneccesarily loud from
very far away.

Convert all door samples to mono, 22kHz 64kbit.

### CODE REVIEW

**Comment by paramat** [comment]
:+1: Will merge later.

**Comment by paramat** [comment]
Playing the door close sound i noticed a large section of silence at the end, please could you trim this to just after the reverberation stops?

**Comment by sofar** [comment]
Trimmed both door samples to remove lead, trail silence. They both had a +/- 1 frame audio lead of silence for no reason. These are both now sub 0.5s samples.

**Comment by paramat** [comment]
:+1: Nicely trimmed, will merge soon.

**Comment by paramat** [comment]
481d1758ad799b1e8af835053c2e7a4562598f4b

**Pull request closed without merging**
