### PR TITLE
chest: fix open chest after player leave

### PR DESCRIPTION
**Pull request by tenplus1**
This should fix the chest staying open when a player disconnects while still inside, it also closes chest after.

### CODE REVIEW

**Comment by Ferk** [comment]
This doesn't really swap the node from the open to the closed one, doesn't it?

**Comment by tenplus1** [comment]
It removes the offending player from the list so that any other player can open chest and it closes properly instead of staying open permenantly.

**Comment by Ferk** [comment]
Oh, I had the impression this was possible already from @sofar's comment: https://github.com/minetest/minetest_game/pull/793#issuecomment-195546419

**Comment by DS-Minetest** [comment]
>This should fix the chest staying open when a player disconnects while inside.

AfaIcs, this makes the chest closeable when the opener leaves the game. But the chest will still stay open as long as nobody touches it. :+1: 
Fixes #1769.

**Comment by Ferk** [comment]
@DS-Minetest I'm not sure if that's the same issue, though. I think it's complaining about the chest being left open, not about not being possible to open and close it afterwards.

Specifically the part where it says: "Resetting the server dose not fix this issue"
Resetting the server would clear the "open_chests" table, if resetting the server doesn't fix the issue, this PR wouldn't fix it either.

**Comment by DS-Minetest** [comment]
@Ferk Yes, but https://github.com/minetest/minetest/issues/6155 was marked as duplicate of #1769 and to #1769 the thing that here is fixed was added (https://github.com/minetest/minetest_game/issues/1769#issuecomment-307471210).

**Comment by DS-Minetest** [comment]
I'm against that last commit since it's good to have a way to let the chest stay open as decoration. And open, closable chests don't hurt anyone.

**Comment by paramat** [comment]
@sofar

**Comment by paramat** [comment]
@tenplus1 does it fix this reported behaviour? https://github.com/minetest/minetest_game/issues/1769#issuecomment-307471210

**Comment by Ferk** [comment]
Now it does seem to fix both issues, at least by looking at the code.

Imho, having the players disconnect and reconnect in order to leave the chest open is not a nice way to do it, whether or not you agree with wanting to have open chests for decoration.

I'd say it wouldn't have been worth it to fix if it wasn't for the unclosable chests bug, but if it's gonna be fixed better fix it all the way like it is now, imho.

**Comment by paramat** [comment]
Leaving chests open for decoration is unintended and might cause issues, so let's not consider that.

**Comment by tenplus1** [comment]
@paramat - yes, it fixes those issues by removing username from list and closing the chest.

**Comment by paramat** [comment]
I'd stil like @sofar to look at this since it's chest stuff.

**Comment by paramat** [comment]
:+1:

**Pull request merged**
