### PR TITLE
Simpler skins

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20171207_070142

WIP Many skins to add but works.

Attends to #1965 
Code is a simplified and altered version of 'simple skins' by Tenplus1.

Use F7 to select third person view to see yourself, then open inventory and select the 'skins' tab.

Textures and metadata are loaded into the skins tab selection table until a gap of 100 is detected in the skin numbers. This allows non-selectable skins to be stored after the gap as 'character_1001' etc., these skins are for player's personal skins that are applied to a player by server admin using the provided chat command. I've added Jordach's skin as 'character_1001' to test this.

### CODE REVIEW

**Comment by CloudyProton** [comment]
Rather than require players use F7 to view skins, it might be worth showing a preview next to entries. Example is this customization I've made to indriApollo's wardrobe mod.
257 - dfxd8j6

**Comment by Napiophelios** [comment]
well I understand why you do it it, but I don't like how the formspec is 
resized and shifted to the left of the screen.

I think the skins formspec should not be resized and should stay stationary 
and just work out a way to have a preview of the skin in the formspec itself
similar to Stu's 3D armor mod.

other than that it's pretty cool to have a skins tab :)

**Comment by C1ffisme** [comment]
@CloudyProton The thing is, I don't like the idea of showing a raw skin texture file. I'd much rather see what it looks like from the front and possibly the back and sides.

Maybe if opening this specific formspec automatically triggered F7 mode and then deactivated it when the player exits the formspec, that might work better.

**Comment by paramat** [comment]
> Rather than require players use F7 to view skins, it might be worth showing a preview next to entries.

No, and those previews are unclear anyway. The reason this and 'simple skins' has no previews is to reduce folder size, making more room for more skins. In-game F7 preview does the job.

> well I understand why you do it it, but I don't like how the formspec is
resized and shifted to the left of the screen.

Too bad, it's a clever and effective solution.

> work out a way to have a preview

No, see above.

> Maybe if opening this specific formspec automatically triggered F7 mode

That's not possible, and it wouldn't know if you wanted front or rear view.
We're not going to add complex engine code to do this.

Now please stop suggesting complex ideas, this is meant to be simple and works fine.

**Comment by Napiophelios** [comment]
too bad? Sorry dude, I was just giving my opinion.
you don't have to be a cunt about it.

**Comment by paramat** [comment]
No need for that language, 'too bad' is not an extreme insult, just me being firm and decisive about it. I still appreciate your suggestions, but disagree.

**Comment by MarkuBu** [comment]
It works, but it is impractical. Isn't it possible to do this with one key?

**Comment by paramat** [comment]
It's not impractical, that's a very silly statement =)
It's not possible to do with one key hit, and would not be justified anyway.
Sometimes you may not need to use third person view, if you know how the skin looks.
A single key cannot select the desired view (front or back) and the desired angle of view.
This uses sfinv, which is for adding custom tabs to inventory, therefore you need to open the inventory first, then click the tab, that's how it works.
You would need to add another key binding especially for this.

**Comment by MarkuBu** [comment]
> It's not impractical, that's a very silly statement =)

Maybe I misunderstand this line, but my first impression is, that you insult me and you are happy about it.

I don't know if something is currently technical possible, I just told you, what good usability means.

**Comment by paramat** [comment]
No it's not an insult, i am saying the statement is silly, not you.

**Comment by GreenXenith** [comment]
Not sure if you mean the skins in that list in the screenshot are the ones that are being added with the mod... I caught "you put in Jordach's skin as an example" but that is a bit confusing to me :P
But if so, not sure adding slenderman as a skin is a good idea, frankly from the fact that it's slenderman in general, but he is also copyrighted and owned by Mythology Entertainment and the creator Knudsen.

Otherwise, :+1: I think this is great!

**Comment by paramat** [comment]
Sorry, i was being intolerant, and took 'impractical' to mean 'unusable'.

Auto third person will need a new API, we'll consider adding it, it would be nice.

The skins in it currently are placeholders, i'll remove slenderman and some others.

**Comment by paramat** [comment]
Concerning the naming of textures and meta, the 'correct' way is for the textures names to start with the mod name, so for shortness perhaps "skins_1.png" etc. However, if we use the same naming system as 'simple skins' ("character_1.png", "character_1.txt") then people can easily copy their textures and meta from that mod into this.
Not sure which to do.

**Comment by ExeterDad** [comment]
I based our skins solution off of simple_skins using sfinv. Originally I solved the "preview" by moving the skins list to the left as tight as possible and making a custom background texture with the center transparent. It resembled a picture frame. I was able to change the camera angle, height and distance (without F7) to show the player face on through a normal centered sfinv formspec when the "skins" tab was clicked. However I abandoned it all in favor of generated player previews.  I can't remember clearly, but I think I wasn't able to return the camera view on exit even though it seemed like it should be trivial.

**Comment by paramat** [comment]
> I wasn't able to return the camera view on exit

Yes i discovered this too, when i tried adjusting camera offset when using the skins tab. The 'on leave' function only works if you change to a different tab first before closing inventory.

**Comment by ExeterDad** [comment]
@paramat One thing I wanted to try is to register each skin as a meshnode and not have them show in creative inventory. Then see if I could display the rendered inventory image as a preview. But I had lost interest and moved on rather than try it out.

**Comment by paramat** [comment]
Updated to use a clear background when using the skins menu. Removed copyrighted slenderman and some other skins.

**Comment by paramat** [comment]
Returned texture names and metadata filenames to 'character_n.png/txt'. Since this is so similar to the 'simple skins' mod this allows textures and metadata to be copied into this mod.

**Comment by NewbProgrammer101** [comment]
It would be nice to have a folder for skins for the player or modder to add. e.g.
~/.minetest/skins/

**Comment by paramat** [comment]
There will be in the mod folder.

**Comment by paramat** [comment]
Closing until i make some more progress, just need to sort through the database and add a variety of skins.

**Comment by paramat** [comment]
The code is somewhat finished, this just needs skins added now. I am searching through the skins database and have selected female skins, just need to select male skins and 'weird' skins.

**Comment by JurajVajda** [comment]
Woohoo go paramat..thanks

**Comment by bell07** [comment]
Just for reference, the [skinsdb](https://github.com/minetest-mods/skinsdb) have some addititional functionalities that I miss in this mod:
- Reading textures folder: Use  minetest.get_dir_list() instead of probing all names
- show skin preview in sfinv plugin
- show skins metadata: At least the skins author and copyright should be shown, because it is expected more skins are installed on servers than provided
- Support for per-player "private" skins
- Flexible Skins-API used in 3d_armor and character_creator

Maybe you check if you like to port some of the features to your mod?

**Comment by Fixer-007** [comment]
>A really user friendly solution would

Totally not user friendly, user friendly is pressing visible button that automatically opens needed view and you just select proper skin and close formspec that opens normal view on its own, without need of fiddling with F^ keys, lets not make it like flight simulator 3 page checklist.

**Comment by paramat** [comment]
> Reading textures folder: Use minetest.get_dir_list() instead of probing all names

Good idea, wasn't aware of that. Although that would break compatibility with 'simple skins' file format.
> show skin preview in sfinv plugin

> Flexible Skins-API used in 3d_armor and character_creator

This is intentionally simple, and preview is by using third person views.
> Support for per-player "private" skins

Already done.

**Comment by bell07** [comment]
> Although that would break compatibility with 'simple skins' file format.

Why? Same file names, same file content, just not poll the folder till the io.open fails 100 times.

**Comment by rubenwardy** [comment]
Here's how you do that, from ctf_maps:

```lua
do
	local files_hash = {}

    -- Find the name of all maps (filename without extension)
	local dirs = minetest.get_dir_list(mapdir, true)
	table.insert(dirs, ".")
	for _, dir in pairs(dirs) do
		local files = minetest.get_dir_list(mapdir .. dir, false)
		for i=1, #files do
			files_hash[dir .. "/" .. files[i]:split(".")[1]] = true
		end
	end

    -- Add to table
	ctf_map.available_maps = {}
	for key, _ in pairs(files_hash) do
		table.insert(ctf_map.available_maps, key)
	end
	print(dump(ctf_map.available_maps))
end
```

Each map has two files, rather like skins. That code makes sure the name only appears once, rather than for each file. You could also check that the extension is correct in the first loop

**Comment by paramat** [comment]
bell07 sorry i misunderstood, that's useful then.

**Comment by bell07** [comment]
> Although that would break compatibility with 'simple skins' file format.

By the way, why simple skins is the preferred file format? I personally like more the "player_bell07_1.png "instead of "character_1034.png" for private skins. That allow more easier to assign private skins to players just by file renaming. And multiple private skins per player possible. In skinsdb the private skins are applied to the database, but marked as private that means listed in inventory for the owner only. The player see his private skins in sfinv page next to the public skins and can choose between them.
In the current implementation I see the issue a player with private skin can choose a public skin in sfinv, then he do not have a way to choose the private skin back.


By the way 2: You do not need the skins_skins table because you always can access this data from player attribute

**Comment by paramat** [comment]
Yes the private skins feature probably needs improving, we're not insisting on the simple skins format an di can see good reasons to use something else now.
I have to admit i have just copied and simplified 'simple skins' here without much understanding of how to make a good skins mod, and can see this can be much improved. I also consider a skins mod not high priority for MTG.
If i proceed with this PR i will work on changing and improving it, thanks for your input.

**Comment by JurajVajda** [comment]
Good idea to escape the meta attributes in formspec, maybe others too...

**Comment by paramat** [comment]
@bell07 good input.
I think your points below would be good for this skin mod, however i'm not interested enough to implement all this, and it's an area of code i'm not expert at. So i'm putting this up for adoption.
I agree with the below as long as the mod stays as simple as possible and keeps the 'third person camera' previewing i have developed.
> Reading textures folder: Use minetest.get_dir_list() instead of probing all names

> Support for per-player "private" skins

>  I personally like more the "player_bell07_1.png" instead of "character_1034.png" for private skins. That allow more easier to assign private skins to players just by file renaming. And multiple private skins per player possible.

> You do not need the skins_skins table because you always can access this data from player attribute

>  There is no direct access to the skins_list. Other mods should be able to add additional skins to the list. Maybe in addition a global accessable reference skins.list = skins_list ?

**Comment by bell07** [comment]
Agree with direction the mtg-skins should be as simple as possible. I look the mod should be enhance-able to allow not simple things from other mods.

1. Beside the skins_list, the skins_meta needs to be accessible trough global reference (skins.meta ?)
2. To avoid "insecure access" from other mods the mod should look for each skin file found in textures folder for "*_preview.png" file in the same folder. If not found, do nothing, if found, just add them to the `skins.meta[skin].preview` attribute. You do not need to use it, but just read it for compatibility, like you does it with metadata.

**Comment by bell07** [comment]
> T2. o avoid "insecure access" from other mods the mod should look for each skin file found in textures folder for "*_preview.png" file in the same folder. ..just add them to the skins.meta[skin].preview attribute.

Then it is not a big deal to show them on formspec ;-)
But I can do it without verifying the file exists, by `skins_skins[playername] .. "preview.png"`. So you just need to ignore this files in the simplest version.

Both ways, the preview using third person camera and preview using preview-texture, both are workarounds with advantages and disadvantages. 

Using the camera you need to try out the skins before you can see them. All other players can see your tries too. A visual skins overview is not possible.

Using textures is more work on skins creators site to create the preview textures.

The ideally way would be a formspec element that is able to show a entity on formspec like done in http://minetest.fensta.bplaced.net/ viewer at the left site, with interactivity to zoom and rotate. Is such formspec element already planned in core?

**Comment by paramat** [comment]
Closing for now, i'm not interested in improving this and probably not the best person to do so, also a skins mod seems low priority for MTG, skins mods are possibly more suited to be optional mods.

**Comment by paramat** [comment]
Replaced by #2122

**Pull request closed without merging**
