### PR TITLE
Add 'creative' privelage to non-creative game

### PR DESCRIPTION
**Pull request by tenplus1**
This pull adds a 'creative' privelage for players on non-creative servers so that they can access the creative inventory and place nodes without the count going down.

### CODE REVIEW

**Comment by paramat** [comment]
I'm not sure about adding a priviledge for this.

**Comment by sofar** [comment]
with minetest#4155 merged, I'd rather see a player attribute used for gamemode, and have it be a string, not a bool, so we can later expand to include adventure mode or whatever else people come up with.

**Comment by tenplus1** [comment]
@paramat - The privelage is handy for builders on survival servers and makes use of the already checking for creative handle_node_drops.

**Comment by sofar** [comment]
```
diff --git a/mods/creative/init.lua b/mods/creative/init.lua
index cd9e2b49..0e20a439 100644
--- a/mods/creative/init.lua
+++ b/mods/creative/init.lua
@@ -1,7 +1,8 @@
 creative = {}
 
 function creative.is_enabled_for(name)
-	return minetest.setting_getbool("creative_mode")
+	-- deprecated, use player:get_attribute("gamemode") directly - warn after future release
+	return minetest.get_player_by_name(name):get_attribute("gamemode") == "creative"
 end
 
 dofile(minetest.get_modpath("creative") .. "/inventory.lua")
@@ -38,7 +39,7 @@ end
 
 -- Unlimited node placement
 minetest.register_on_placenode(function(pos, newnode, placer, oldnode, itemstack)
-	return creative.is_enabled_for(placer:get_player_name())
+	return placer:get_attribute("gamemode") == "creative"
 end)
 
 -- Don't pick up if the item is already in the inventory
@@ -47,7 +48,7 @@ function minetest.handle_node_drops(pos, drops, digger)
 	if not digger or not digger:is_player() then
 		return
 	end
-	if not creative.is_enabled_for(digger:get_player_name()) then
+	if digger:get_attribute("gamemode") ~= "creative" then
 		return old_handle_node_drops(pos, drops, digger)
 	end
 	local inv = digger:get_inventory()
```

it's actually more efficient, since we don't need to lookup the name for a player as often.

**Comment by tenplus1** [comment]
@sofar  - please include your above changes in a different pull as it breaks functionality of my own changes.

**Comment by sofar** [comment]
It would replace your changes, not be in addition to your changes.

I don't feel like making a PR myself, I want you to actually consider the alternative approach instead.

**Comment by paramat** [comment]
While we consider privs / attributes i'll quickly cache this setting now.

**Comment by paramat** [comment]
:-1: I disagree with a priv. The function is designed to be overriden by redefining in a mod.

**Pull request closed without merging**
