### PR TITLE
Add a crosshair texture

### PR DESCRIPTION
**Pull request by Calinou**
Redesign of #401.

This makes the crosshair easier to see when pointing light surfaces. It also has a more compact profile.

Unlike #401, the black outline uses 50% alpha as to be less intense.

## Preview

Crosshair with dark background

Crosshair with medium background

Crosshair with light background

### CODE REVIEW

**Comment by paramat** [comment]
crosshair128

This is very similar to the previous PR, the crosshair design is unchanged apart from the edge alpha, it is still very thick and visually obtrusive, which is more of a problem than it being hard to see against white surfaces. Selection boxes help in seeing what has been selected :-1:

**Comment by paramat** [comment]
Yes i assumed that was the reason, but i do not think 0.5 screen pixels off is a problematic offset.
Your design is the way it is for good reason, but i find it visually very obtrusive. This is a difficult task.

**Comment by Calinou** [comment]
@paramat Would it be OK if I made the white part slightly transparent (like 10-20%)?

**Comment by paramat** [comment]
That wouldn't help in my opinion. The issue for me is that a wide crosshair with a dark border seems to float in front of the screen and is very distracting.
Personally i would try a 1-pixel wide cross consisting of alternating black/white pixels.

Here's a good idea that keeps the crosshair shape unchanged. but unfortunately might depend on shaders being enabled:
> kilbith
14:46 		better inverting the colors in a fragment shader for the crosshair
14:46 		you bind another RTT from the current frame and you pass it to the shader

**Pull request closed without merging**
