### PR TITLE
default_desert_cobble.png with darker mortar

### PR DESCRIPTION
**Pull request by TumeniNodes**
This is a result of #1801. The difference is very slight but, just enough to check the light,pink color.
I dare not go any darker than this, as it begins to blur the definition of the cobble and IMO looks horrible.

### CODE REVIEW

**Comment by Napiophelios** [comment]
you dare not? hehehe.

**Comment by TumeniNodes** [comment]
A little Shakespeare in the morning is good for you, plus I was in a goofy mood. Just go with it.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Not sure abou this now, the mortar is now too close in colour, maybe it can be changed in colour but in a way that keeps a contrast?

**Comment by TumeniNodes** [comment]
Indian giver... haha.
Well, I can work on it and see what I can do. Difficult to keep a happy medium between those who like it as is, and those who would like it a bit darker.
I'll put a few variants together tonight

**Comment by paramat** [comment]
It's difficult, i don't know what to suggest, all i know is that it doesn't look quite right. Maybe we need to research mortar colours that would be used for old desert stone buildings, maybe a non-red/pink colour.

**Comment by TumeniNodes** [comment]
can you give this a try paramat?
https://image.ibb.co/mpEnra/default_desert_cobble1.png

**Comment by paramat** [comment]
Looks better, so yes this is what i suggested, same lightness but different hue. I'll try it in-game.

**Comment by paramat** [comment]
screenshot_20170805_223301

Still not quite right somehow. This is going to be a difficult texture.

**Comment by TumeniNodes** [comment]
this is a lighter version
default_desert_cobble2

I like this one more. It looks nice.
first version is on the right, second version on the left

desert cobble test

**Comment by TumeniNodes** [comment]
3rd, the lightest I think it should go (my personal opinion)
desert cobble 3

newest cobble3 is on far left
desert cobble test 2

**Comment by paramat** [comment]
This one has potential https://github.com/minetest/minetest_game/pull/1859#issuecomment-320472849
Need more opinions.

**Comment by paramat** [comment]
Problem is i just don't like the basic texture so i don't like any of the edits. I would prefer there to be no mortar and for the stones to have more shading and definition like the stone cobble texture.
So i'm neutral on these textures.

**Comment by TumeniNodes** [comment]
I'll see what I can come up with over the next day or two. I know what you mean, a flatstone look with no mortar.
I'm just not sure how well an entirely new texture will go over with the majority. We'll see.

**Comment by TumeniNodes** [comment]
Can't sleep (insomnia) so figured I would see how you like this.
I know it is prob not exactly what you had in mind but, I think trying not to stray too far fro the original design will go over better in the user-base. Harsh changes tend to gain negative reactions.

It is the original texture (slightly modified), with no mortar. I think going much darker on the definition shading will start to look like dark mortar.

Anyway, give this a try. Let me know if it is in the right direction.
desert cobble 4

quick demo
desert cobble test 3

**Comment by paramat** [comment]
Dark mortar looks much better.

**Comment by TumeniNodes** [comment]
Well, it's supposed to be no mortar and the shading is simply to give definition to the stones but, it is very difficult to define a group of flat stone with rounded edges, in a 16x16px field (smiley face here)

I do like this look better though. I have done a couple other variations with darker lines but, they all just look... wrong somehow. There has to be just the right balance and I feel this is it.

Of course, I am willing to make more changes if desired but again, I think it is best trying not to make too drastic of a change. Many do not adjust well to complete change.

**Comment by Napiophelios** [comment]
the newest/ darker texture looks great in the accompanying screenshots,
but not so good in the game.
I prefer the very first texture posted in this thread so far.

**Comment by TumeniNodes** [comment]
@Napiophelios , it looks great ingame from a distance, if you squint. ha
Turns out desert cobble is a real PIA with 16px and I know what you mean and agree with you.
The darker examples I have made look even worse though. I did 2 with completely new textures and those also look horrible enough that I instantly scrapped them.

I think most are going to want to stick to the lighter mortar (or it may even split 50/50) The best place to get opinions on this sort of change would probably be from server owners, as they will hear some reactions from players. IDK... I do know this texture is a &itch to work with haha

**Comment by TumeniNodes** [comment]
can people try this one please?
cobble6

**Comment by paramat** [comment]
People can always use a texture pack if they don't like this.
I think what makes stone cobble look so good is the highlights at stone top and shading at stone bottom, makes them look more 3D. Adding that shading to desert cobble would be my personal ideal. I think at this point we should give up on trying to keep it very similar to before, as the old texture is not good in my opinion.

**Comment by paramat** [comment]
screenshot_20170806_235325

Latest version. Dark join lines are good, but highlights would make it look more 3D.

**Comment by TumeniNodes** [comment]
yeh, looks pretty flat right now.
ok, I will work on it more either tonight or early eve tomorrow then.

Best way to address those who do not like the changes, is to copy the current TP, label it 0.4.16 so they can d/l it.

**Comment by TumeniNodes** [comment]
with highlights (just enough to not make it look plastic), and a couple extra detail/texture pixels.
I can brighten the highlights a "bit" more, but not much because, as stated, it begins to look like plastic, especially with the redish/brown color of the stone.
cobble 8

**Comment by paramat** [comment]
screenshot_20170807_020151

Looking better, thanks.

**Comment by TumeniNodes** [comment]
> I appreciate your effort with this. textures are very hard work.

Thank you. And it is np, I enjoy being able to contribute/give back with open-source projects.
I'm $hit at coding but, I've been working with  freelance graphics design, art, and consulting here and there for a long time. 
But pixel art is new to me on the 16px gaming level. It has definitely caused me to have much more appreciation for the art and what is involved. I honestly used to mock it, but no longer.

**Comment by paramat** [comment]
:+1:

**Comment by jastevenson303** [comment]
It looks really good, and I like it.  The bottom two rows of pixels almost look as though they belong on top, however.

**Comment by paramat** [comment]
Since you have edited this significantly you can now credit yourself for the texture in default/README.txt like this:
```
TumeniNodes (CC BY-SA 4.0):
default_desert_cobble.png -- Derived from a texture by brunob.santos (CC BY-SA 4.0)
```
Also add yourself under the CC BY-SA 4.0 licence here https://github.com/minetest/minetest_game/blob/master/mods/default/license.txt#L79 replacing brunob.santos:
`Copyright (C) 2017 TumeniNodes`

**Comment by paramat** [comment]
I'm +1 on this texture if you add it to the PR.

**Comment by DS-Minetest** [comment]
Somehow the mortar of this texture looks like dirt. :confused:

**Comment by TumeniNodes** [comment]
@paramat I will add this texture and creds later tonight. this branch is 7 commits behind master though.
Do I need to redo the PR? or just proceed as usual. (damn github)

@DS-Minetest I don't see how? Completely different color and no similarity to dirt in any way.

**Comment by paramat** [comment]
Nah it doesn't look like dirt.
No need to rebase, only pay attention to the box below where it says 'This branch has no conflicts with the base branch'.

**Comment by TumeniNodes** [comment]
heh, forgot to strip it down before I added it to the PR.
all set now. it is considerably larger in file size now due to the addition of more colors

**Comment by paramat** [comment]
Please can you remove the alpha channel and make it indexed colour?

**Comment by paramat** [comment]
Sorry, just checked again it is ok now.

**Comment by TumeniNodes** [comment]
oh, ok I thought I might have missed something. because I removed alpha, set for index 256, then used -strip all and the slow -o7 method.
I don't think there is much more pngcrush could do either, I will look into it

**Comment by paramat** [comment]
Size is fine, i appreciate your careful optimisation, most texture creators don't do this and also leave metadata in.

**Comment by TumeniNodes** [comment]
Any other input on this?

**Comment by sfan5** [comment]
Better than the old texture, :+1:

**Comment by TumeniNodes** [comment]
Thank you

**Comment by sofar** [comment]
I'm happy with the results. Please squash on merge?

:+1:

**Comment by TumeniNodes** [comment]
Thank you (yeh, I get commit happy)

**Comment by paramat** [comment]
Yes we'll squash on merge.

**Pull request merged**
