### PR TITLE
Default/player.lua: Remove outdated comment

### PR DESCRIPTION
**Pull request by DS-Minetest**
correction for issue #1296

### CODE REVIEW

**Comment by paramat** [comment]
Now that 'sit' is in widespread use i think just remove the comment completely, there's no need to call it 'extra'.

**Comment by DS-Minetest** [comment]
done

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
36a78c87d71b4513c03e3400e916d787bd3c5dce

**Pull request closed without merging**
