### PR TITLE
Remove empty minetest.conf file

### PR DESCRIPTION
**Pull request by davisonio**

### CODE REVIEW

**Comment by paramat** [comment]
It's needed even when empty.

**Comment by davisonio** [comment]
Really? That shouldn't be the case

**Comment by rubenwardy** [comment]
I don't think that's true.

**Comment by rubenwardy** [comment]
But I guess it's good for documentation.

**Comment by davisonio** [comment]
Well, if I ever wanted to modify values via the game `minetest.conf` I would usually move the `.example` file but keeping the empty file creates more of a problem.

**Comment by paramat** [comment]
Well what i mean is the game might work without it but it's good to have it there if settings need to be added. It's an important part of the game even if empty at certain times.

**Pull request closed without merging**
