### PR TITLE
Accelerate water and river water animations.

### PR DESCRIPTION
**Pull request by Andrey2470T**
A minor PR that accelerates velocity of water/river water animation playing and makes it more alive.
water_animation

### CODE REVIEW

**Comment by Fixer-007** [comment]
Seems too noisy for me.

**Comment by LoneWolfHT** [comment]
I think that's a little *too* fast. Although I think the water definitely would look nicer if it was moving faster.
Looks like some unrelated commits have crept into your PR btw

**Comment by Andrey2470T** [comment]
I dont understand why each created PR by me includes also some unrelated commits if I pushed into the branch only related and those are actually in other ones!

**Comment by paramat** [comment]
I disagree with increasing the speed of the water source animations, it is fine as it is.
4 times faster for flowing water is too fast. A subtle increase might be ok.
-1 for current code.

**Comment by paramat** [comment]
A little faster for flowing would be good actually. If you watch a falling column of flowing water, the visual flow is slower than how fast the column descends. I suggest tuning it to match, i wuold support that.

**Comment by paramat** [comment]
Ok ... i will move my suggestion to an issue as it is a good idea.

**Pull request closed without merging**
