### PR TITLE
These numbers didn't come from nowhere

### PR DESCRIPTION
**Pull request by beyondlimits**

### CODE REVIEW

**Comment by rubenwardy** [comment]
as lua is interpretted, it can't optimise - you're doing a global look up then a table look up there.

This only makes sense if you want more readability, in which case a comment or local is fine.

Also the commit message isn't very good.

    Use PI variable rather than unclear constant.

**Comment by PilzAdam** [comment]
:+1:

@rubenwardy reading a local variable here is no problem at all.

**Comment by rubenwardy** [comment]
You misread, my comment was before he made it into a local variable.

**Comment by PilzAdam** [comment]
@rubenwardy this isn't called very often, though, so accessing global tables isn't a problem.

**Comment by paramat** [comment]
-1. Surely a constant is better because it avoids unnecessary / or * with PI?

**Comment by PilzAdam** [comment]
@paramat this is not performance critical code, and constants are way more clearer when reading the code.

**Comment by paramat** [comment]
I consider all lua code performance critical because it is so slow.
When i clean up code i always replace unnecessary calculations with constants.

**Comment by beyondlimits** [comment]
@rubenwardy and @paramat, please note that
- most mods make a global look up for `minetest`
- `local function get_look_yaw(pos)` is local and calls to it are relatively rare

**Comment by paramat** [comment]
Okay i'm not too bothered so not opposed, but other devs will have to +1 it.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Will merge this soon.

**Comment by paramat** [comment]
b292975fbced72bbd9aea470241b1f626110bf2d

**Pull request closed without merging**
