### PR TITLE
New mineral textures

### PR DESCRIPTION
**Pull request by CraigyDavi**
This pull request ads new mineral textures for coal, copper, diamond, gold and iron. Mese has been left unchanged as it already has an unique texture.

The textures were avaliable at [this forum topic](https://forum.minetest.net/viewtopic.php?id=8677) and were made by rubberduck.

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by C1ffisme** [comment]
I would like it if @CraigyDavi got his textures fixed to not have cut edges. Then I would suggest a merge.

**Comment by paramat** [comment]
The problem with the original pull is that the ores are not horizontally stratified as the stone clearly is, so they don't look embedded in the stone node, this is why the current ores have the form of horizontal lines and why HybridDog's textures are more suitable.

**Comment by paramat** [comment]
-1. HybridDog's gold and diamond are good i would support those.

**Comment by CraigyDavi** [comment]
> Hi @CraigyDavi this commit has some issues, is unpopular with the devs and you haven't commented in a year, do you want to update this or can it perhaps be closed?

I'll close this and suggest @HybridDog creates a pull-request instead.

**Pull request closed without merging**
