### PR TITLE
Changed the deprecated "current_name" to "context"

### PR DESCRIPTION
**Pull request by farooghkz**

### CODE REVIEW

**Comment by tenplus1** [comment]
How many mod formspecs will this break in the process ?

**Comment by farooghkz** [comment]
@tenplus1: I don't get you, this? and why break?

**Comment by tenplus1** [comment]
My bad, was worried it would affect other mods that use chest/furnace.

**Comment by farooghkz** [comment]
@tenplus1: As defined in the API, they are the same thing but "current_name" is deprecated, any problem?

**Comment by paramat** [comment]
2c666891a8171a33a305246c991edd458206cab0

**Pull request closed without merging**
