### PR TITLE
Default: Add 'group:cools_lava', add to snowblock and ice 

### PR DESCRIPTION
**Pull request by paramat**
Make lava cooling ABM use a new group 'group:cools_lava'.
Nodes other than water can cool lava. We assume snowblock and ice melt,
turn to water and cool lava.
Leave 'group:water' present temporarily to not break mod liquids.
////////////////////////////////////////////////////////

See https://github.com/minetest/minetest_game/issues/1005#issuecomment-259122325

### CODE REVIEW

**Comment by paramat** [comment]
Updated.

**Comment by Fixer-007** [comment]
:+1: it is very simple but probably good compromise instead of melting water and then cooling lava.

**Comment by paramat** [comment]
Allowing ice and snow to melt is problematic, it can then cause floods, that's why Freeminer is such a mess.

**Comment by paramat** [comment]
There was discussion on IRC where it was suggested that lava would vapourise ice and snowblock without being cooled, realistically yes. However in-game we would have to make ice and snowblock 'floodable' meaning water would remove these too, which is unacceptable for ice, maybe for snowblock too, and would make an ugly mess in cold biomes if water is spilt.

Realistically water would be vapourised by lava too, but in-game water cools lava, so it is consistent to have snowblock and ice cool lava too.

**Comment by sofar** [comment]
This is fine :+1:

**Comment by paramat** [comment]
c3f3406e8ee0a4c8523863a4b69ecda7c2be48b2

**Pull request closed without merging**
