### PR TITLE
Stairs improved

### PR DESCRIPTION
**Pull request by MarkuBu**

### CODE REVIEW

**Comment by MarkuBu** [comment]
Replaces #1581

**Comment by paramat** [comment]
Tested and ready for merge?

**Comment by MarkuBu** [comment]
I have tested it. Can be merged.

**Comment by paramat** [comment]
Tested, will merge now.

**Comment by paramat** [comment]
e6d0d775e3533b7b91b292e13c800b9737e057fd

Thanks, excellent contribution.

**Pull request closed without merging**
