### PR TITLE
Created TNT mod's namespace

### PR DESCRIPTION
**Pull request by LeMagnesium**
- Created a namespace called `tnt` for the TNT mod, containing
   variables and functions of this mod to be used in other mods

(Was created for issue #500)

### CODE REVIEW

**Comment by LeMagnesium** [comment]
I think it should be done later. I will do it, but after this is merged (or not). It is a separated feature.

**Comment by ShadowNinja** [comment]
This needs to use more localizations.  For example `local def = cid_data[cid]` does one hash lookup (get `cid_data` by local index, look up `cid` in `cid_data`) wheras `local def = tnt.cid_data[cid]` does *three* (look up `tnt` in `_G`, look up `cid_data` in `tnt`, look up `cid` in `cid_data`).

**Comment by LeMagnesium** [comment]
Among the values, tables and variables I added to my localization PR, and after you pointed `cid_data`, I agreed this table is not useful to stock in the namespace (knowing that it contains content ids, and they are not needed outside of the mod). I still have a doubt about the last table in the namespace, containing the probabilities to be destroyed instead of dropped. I thought that any mod that would need to create its own blast system might want to use these values.
So to reduce calls, I will just include functions in the namespace, not variables or tables.

**Comment by LeMagnesium** [comment]
Rebased after 4bd1094619f8001fa4418465a03aecbeb7f93b5b.

**Comment by LeMagnesium** [comment]
I fixed variables which had become global (thanks @ShadowNinja ) and squashed my commits into one because.. well.. three commits for just 2 variables is a bit too much.

**Comment by ObaniGemini** [comment]
Is anyone for ? Anyone against ?

**Comment by MT-Modder** [comment]
:+1:  This is a very good idea.

**Comment by sofar** [comment]
This is superseded/partially included by #862 (and others, before that).

**Pull request closed without merging**
