### PR TITLE
register_trapdoor: Improve on_blast

### PR DESCRIPTION
**Pull request by Thomas--S**
I think the removed line was a little copy&paste mistake.

### CODE REVIEW

**Comment by paramat** [comment]
@sofar ?

**Comment by sofar** [comment]
No, this removal is intentional, and shouldn't be merged.

**Comment by tenplus1** [comment]
@sofar ??? am I missing something as I see no reason for removing a node above a trapdoor ?

**Comment by t4im** [comment]
@tenplus1  for the same reasons like https://github.com/minetest-mods/homedecor_modpack/issues/292

The solution there was to use "palceholder nodes", that need to be removed with the expanded node (refrigerator, sofa etc), too.

However, @sofar, isn't its removal `on_destruct` enough here?

**Comment by t4im** [comment]
@tenplus1  for the same reasons like https://github.com/minetest-mods/homedecor_modpack/issues/292

The solution is to use "palceholder nodes", that need to be removed with the expanded meshnode (door, refrigerator, sofa etc), too.

However, @sofar, isn't its removal `on_destruct` enough here?

**Comment by Thomas--S** [comment]
@t4im Afaik, trapdoors don't have a placeholder node.

**Comment by t4im** [comment]
@Thomas--S you're right.
I was looking at the door code, where it can probably be removed too.

But for trapdoors the effect is even destructive (although probably not noticed :boom: ).
Nice catch.

**Comment by Thomas--S** [comment]
It's perfectly ok for me, if this doesn't get merged.
However, I would be really interested, why this line is needed.
@sofar Can you please tell me the reason?

Thanks for your efforts.

**Comment by sofar** [comment]
Misread, rereading.

**Comment by sofar** [comment]
So I completely misread this, thinking it was `register_door`. Indeed this isn't needed for the trapdoor, and this patch is :+1:

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
f018e06d9b7c8e8b14034c4dc8ac2dcffe5e0eab

**Comment by Thomas--S** [comment]
Thank you very much!

**Pull request closed without merging**
