### PR TITLE
Revise footstep sounds (snow, dirt)

### PR DESCRIPTION
**Pull request by Anth0rx**
Every footstep node now has 5 samples.
Default samples got replaced by more realistic ones

### CODE REVIEW

**Comment by paramat** [comment]
Erm, i only just added water footstep sounds myself, which are fine and seem liked, but i'll listen to the new ones.
Note that 'default_dig_choppy' has priority as a chopping sound, it should not be footstep-like.

**Comment by Anth0rx** [comment]
Oh, I didn't keep one water footstep silent. Does it matter which one it is?

It seems I accidentially added the chopping sound, since I am experimenting with different sounds at the moment. I think I'll remove that sound and add it in another ```digging_sounds``` branch.

Do you have a tip for volume balancing? Maybe the snow footsteps are a little bit too loud at the moment but the others are quite balanced I think.

All other sounds are in the public domain so I didn't credit them.

**Comment by rubenwardy** [comment]
> All other sounds are in the public domain so I didn't credit them.

It would be better to credit them even though you're not required to - it's polite
Or at least note that they're public domain

Note that public domain isn't a valid license, you should say "cc0" or whatever they actually used

**Comment by Anth0rx** [comment]
> It would be better to credit them even though you're not required to - it's polite
Or at least note that they're public domain

I got all the samples from freesound.org. So you mean I should list all the filenames and mention that they're public domain?

**Comment by rubenwardy** [comment]
You should list all the file names, that they're from freesound.org, and their license (eg: cc0, cc-by-sa, **NOT** public domain)

Ideally you should also list the authors, however I realise that this would be time consuming to re-find

**Comment by Anth0rx** [comment]
@rubenwardy I updated the license file. Is it okay that way?

**Comment by paramat** [comment]
> Oh, I didn't keep one water footstep silent. Does it matter which one it is?

No.

**Comment by sofar** [comment]
1) We should verify the origin and license of every sound sample added.
2) I can't verify the license or origin of any of the sounds, since "freesound.org" contains thousands of sound files and possibly unusable licenses (freesound.org has some licenses which are "free" but -NC, which we can't use), and it doesn't show which one is which.

Conclusion: this way of attributing does not work. Please specify for each sound file, what the exact freesound URL was where it came from.

If that isn't done, this should be rejected due to the inability to verify the original license.

(I know it sucks, I've done this many times now myself and it's a lot of extra work)

**Comment by Anth0rx** [comment]
@sofar Okay, thanks for your advise. I will look for the licenses and the links and add them.

**Comment by paramat** [comment]
Aw you have a cute avatar.

**Comment by NathanSalapat** [comment]
If you have an account on freesound, which I think you need one to download the sounds, in your profile settings there should be a link that will bring you to a page with the URL for ever sound clip you've ever downloaded, and from there you can find the license for every clip.

**Comment by Anth0rx** [comment]
> there you can find the license for every clip
@NathanSalapat Absolutely right. I'm on it ;)

**Comment by Anth0rx** [comment]
> Please specify for each sound file, what the exact freesound URL was where it came from

@sofar Does this only concern files from the public domain? Since the rest of the LICENCE.txt file is only mentioning ```Copyright (C) <year> <name>```

**Comment by paramat** [comment]
The credit and link for the sounds are added to the README.

**Comment by sofar** [comment]
Right. Did you remove the sand footstep sounds? 

This is a good start though, aside from the sand ones you have the origin documented and the files listed as CC0

**Comment by Anth0rx** [comment]
The sand footstep sound samples are taken from [here](http://freesound.org/people/n_audioman/sounds/321841/) as mentioned in line 151: ```Copyright (C) 2015 n_audioman: Samples are taken from file: http://freesound.org/people/n_audioman/sounds/321841/```

> The credit and link for the sounds are added to the README.

And what is in the license.txt file? Just the license itself? But why are there some names mentioned?

**Comment by sofar** [comment]
IMHO `license.txt` is a fine place for this. I did the same for `carts`.

**Comment by paramat** [comment]
> Do you have a tip for volume balancing?

Don't bother yet as we probably only want some of these sounds, fine tune gains once we choose.

There are 9 sets of sounds added but only credits for 7 sets of sounds.

> And what is in the license.txt file? Just the license itself? But why are there some names mentioned?

The list of sound files should be added to the README where all the other sound file lists are, license.txt is for the license text only, plus the relevant authors for each licence.
In the README you need to remove the sound credits from other authors for the files you change.

However don't worry about correcting documentation yet, wait until we choose the sounds we want, then correct it.

> IMHO license.txt is a fine place for this.

Certainly, but we have to be consistent with existing documentation.

**Comment by paramat** [comment]
Now testing, my first impressions.

Water:
I have only just added water footsteps so woud prefer the current sounds stay for a while for players to get used to them or otherwise.
PR sounds are short while mine are longer and overlap creating a more continuous sound.
PR sounds have a crunchy sound in one of them.

Sand:
I like these, a big improvement. Our current sounds are too harsh for sand and certainly need improvement.

Snow:
An improvement, has potential, one of these sounds is quiet but the sound samples themselves can be volume-balanced later.
Our current snow sounds are okay but one of the sounds has a weird double-attack that sounds to me like a door slamming.

Gravel:
Not sure, possibly, sounds a little weird. The current sounds are not great but not bad either.

Glass:
Nope, sorry. This is walking on broken glass so unsuitable. Our current sound is cute and humourous.

Grass:
Not sure. Grass is also used for walking on leaves so the leaves footstep sound now sounds wrong. Dry grass uses the grass sound at a higher volume but now doesn't suond crispy enough.

Dirt:
Seems good. Our current soild sound is a bit harsh.

Metal:
Seems good, less harsh than our current sounds. Sofar recently added the metal sounds so input needed from him.

Wood:
I prefer the existing sounds which are ok. These new sounds have an odd deep sound to them.

**Comment by paramat** [comment]
I noticed you haven't changed any gains, did you know they are set in default/functions.lua?

**Comment by DS-Minetest** [comment]
I don't like these gravel sounds, I prefer the current ones.

**Comment by paramat** [comment]
Ah i see water and asnd are from
```
+Copyright (C) 2014 Motion_S: Samples are taken from file: http://freesound.org/people/Motion_S/sounds/221764/
+Copyright (C) 2015 n_audioman: Samples are taken from file: http://freesound.org/people/n_audioman/sounds/321841/
```

**Comment by Anth0rx** [comment]
@paramat Thanks for your feedback. Sorry, I was busy so I didn't reply. I'm kinda new to audio editing. If you want to fine tune the gains, please do so.

**Comment by sfan5** [comment]
Feedback:
* the glass sounds sound nothing like walking on glass
* the grass sounds are too quiet
* the gravel sounds are too loud

**Comment by Anth0rx** [comment]
@sfan5 The thing with the glass sound is that glass and ice nodes make use of the same sound files. Maybe it would be better to differentiate between glass and ice. I think for ice nodes it is suitable.

**Comment by paramat** [comment]
I still intend to go through these one by one and submit the ones we want in new PRs, i'm confident with sound editing and many of these need editing in Audacity.
There are too many issues to merge multiple sounds in one PR.
I think i'll start with sand as it seems the most needed.
I really appreciate that you have searched and found these sounds for us, that is the most time consuming part.

**Comment by Anth0rx** [comment]
@paramat I'm glad I could help. If you need any help, please tell me ;)

**Comment by paramat** [comment]
Started work on sand, but found the samples have a lot of subsonic frequency content. So will start with snow instead.

**Comment by paramat** [comment]
Snow and sand PRs coming.

**Comment by paramat** [comment]
:-1: for the metal sounds, too rattly, clangy like thin metal panelling, steel ladders and metal blocks need a very strong solid sound.
The gravel samples in this PR are a bit too long, but going back to the source there are others that could be used, but current gravel sounds are not too bad so not a high priority.
So i will start with sand and snow, then maybe dirt later.

**Comment by paramat** [comment]
-1 for sand sounds. In Audacity i noticed very high amplitude very low frequency oscillation, and distortion, i think we can find better.
Snow sounds are good and our current onesare too few (3) and 1 sounds like a slamming door, so new ones are needed. Then maybe dirt later.

**Comment by paramat** [comment]
I will work on snow sounds during feature freeze, since sounds have no risk for release.

**Comment by paramat** [comment]
Since these are unusable and i plan to redo snow sounds from the original samples, closing.

**Pull request closed without merging**
