### PR TITLE
Enable animation when Right Click

### PR DESCRIPTION
**Pull request by MoNTE48**
Shows the player animation when the player clicks right-click (action or placement), too.

### CODE REVIEW

**Comment by paramat** [comment]
Good idea, i will approve this once i test it.

**Comment by An0n3m0us** [comment]
Isn't this already implemented?

**Comment by Desour** [comment]
Afaik this won't affect how the own player is animated when rightclicking, as that is predicted client-side. For testing one would have to watch another player.

**Comment by MoNTE48** [comment]
This was implemented client-side in the engine. But not for server

**Comment by MoNTE48** [comment]
_(@sfan5, because it will definitely break something and MTG 5.2 already has too much new!)_

**Comment by sfan5** [comment]
No, the reason for this is that the both the engine and MTG are in feature freeze since more than 2 weeks.

**Comment by sorcerykid** [comment]
It's about time :) I'm very excited to see this is finally implemented!

**Pull request merged**
