### PR TITLE
Fix endless trapdoor bug.

### LINKED ISSUE #770: Unlimited steel trapdoors
Craft a steel trapdoor and then place until your fingers hurt, they never end :) This is in the latest build.

### PR DESCRIPTION
**Pull request by sofar**
Closes #770 - thanks to @tenplus1, @kilbith

### CODE REVIEW

**Comment by everamzah** [comment]
The steel doors do it this way: https://github.com/minetest/minetest_game/blob/master/mods/doors/init.lua#L94

Would it be beneficial to make them consistent?

**Comment by sofar** [comment]
Steel doors have the code in the on_place() handler, since it needs to modify the placed node before it is placed on the map (it needs to place a bottom door part), and the API for on_place and after_place are just different.

This fix is nice and small, and correct.

**Comment by paramat** [comment]
Will merge soon as is trivial.

**Comment by paramat** [comment]
9542d119f609eba8cee422f6c5bcf6f0a112f12b

**Pull request closed without merging**
