### PR TITLE
Update tnt.burn info

### PR DESCRIPTION
**Pull request by tenplus1**
update tnt.burn information with nodename addition for use with pull: https://github.com/minetest/minetest_game/pull/1308

### CODE REVIEW

**Comment by paramat** [comment]
This gets +1 from me if i +1 #1308

**Comment by sofar** [comment]
This needs to be part of #1308, and not a separate PR. If you change the API, the documentation for that API change should go into the same commit.

**Comment by paramat** [comment]
True, once we come to an agreement in #1308 please open a new  PR to combine.

**Comment by tenplus1** [comment]
Dunno how...

**Comment by sofar** [comment]
just review #1313 which replaces #1308 and this one in one pr.

**Comment by paramat** [comment]
I don't mean combine, i mean start a fresh new commit.

**Pull request closed without merging**
