### PR TITLE
Add on_burn code that happens upon burning.

### PR DESCRIPTION
**Pull request by HybridDog**
and short code

doc about the flammable group should be taken from lua_api.txt…

### CODE REVIEW

**Comment by C1ffisme** [comment]
Your title is way too long, maybe just:

```Add on_burn code that happens upon burning.```

**Comment by HybridDog** [comment]
fixed, thanks

**Comment by sofar** [comment]
+1 on the idea and implementation of the actual on_burn() code.

But I really don't like seeing a 15 line change with 85 lines of cleanup. That should just be 2 commits. :(

**Comment by paramat** [comment]
Related PR #794

**Comment by paramat** [comment]
Lots of useful optimisatins, but i don't like the way 'register node' has been combined for the 2 flame types, it's clever and short, but having 2 seperate simple node definitions is much clearer and easier to work with.

**Comment by sofar** [comment]
>Related PR #794

Conflicting, even.

**Comment by sofar** [comment]
@HybridDog you changed the title of the PR, but not the commit message. It should be the other way around.

**Comment by HybridDog** [comment]
>Related PR #794

sorry, obviously l did a duplicate

**Comment by sofar** [comment]
Please push all the cleanups though!

I think your implementation may be better - maybe work with @red-001 ?

**Comment by paramat** [comment]
Yes there's lots of good improvements here and it's possibly better than #794 so we should consider this.

**Comment by paramat** [comment]
The way a string is checked for a replacing node is clever but i prefer a simple callback.

**Comment by tenplus1** [comment]
HybridDog: Love the new code and the on_burn function is very handy...  I added changes to Xanadu server's fire mod with chest drops (on_burn) and some minor tweaking and sound removal (ambiance handles fire sounds) https://github.com/tenplus1/fire

**Comment by HybridDog** [comment]
thanks

**Comment by paramat** [comment]
Why re-opened? The sound code is out of date and we already have 'on burn'.

**Comment by HybridDog** [comment]
rebased

**Comment by paramat** [comment]
The sound code has been replaced, this PR edits the old sound code.
I disapprove of using a register function for flames when there are only 2 flame nodes, it's much clearer kept as 2 normal registrations.
:-1:

**Pull request closed without merging**
