### PR TITLE
Biomes: Remove some warm and humid biomes at altitude

### PR DESCRIPTION
**Pull request by paramat**
Biomes: Remove some warm and humid biomes at altitude

Remove:
Rainforest at y = 128 (roughly cloud level).
Deciduous forest at y = 192.
Savanna at y = 256.

Edit corresponding decoration limits.

Makes biomes at altitude a little more suitable for high altitude.
Coniferous forests remain to provide plenty of wood resources.
///////////////

screenshot_20171225_203803

screenshot_20171225_205430

screenshot_20171225_210200

WIP needs reconsideration and rework due to biome blending feature.
Attends to #1993

### CODE REVIEW

**Comment by paramat** [comment]
Closing for now while i reconsider falloff.

**Comment by paramat** [comment]
Closing for now as needs reconsideration.

**Comment by sfan5** [comment]
still WIP?

**Comment by paramat** [comment]
Yes, "needs reconsideration and rework due to biome blending feature".

**Comment by paramat** [comment]
This will need rewriting based on vertical biome blend so closing.

**Comment by paramat** [comment]
I will still do this, i'm fed up with tops of stunning mountains being spoiled by unsuitable biomes, like rainforest. New PR coming.

**Comment by paramat** [comment]
New PR now with vertical blend #2018

**Pull request closed without merging**
