### PR TITLE
Ores: Add tin ore, lump, ingot and block

### PR DESCRIPTION
**Pull request by paramat**
Use textures from 'moreores' mod.
Craft bronze from tin and copper instead of steel and copper.
Match ore density to moreores but start ore at a depth of y = -32 to
be part of the depth progression of other ores.
///////////////////////////////////////////////

PR bronze recipe is 8 copper, 1 tin = 11% tin, close to realistic and fills the crafting grid nicely.
Concept approvals:
http://irc.minetest.net/minetest-dev/2017-04-18#i_4881966 the question
http://irc.minetest.net/minetest-dev/2017-04-18#i_4881983
http://irc.minetest.net/minetest-dev/2017-04-18#i_4882007
http://irc.minetest.net/minetest-dev/2017-04-18#i_4882061

### CODE REVIEW

**Comment by Fixer-007** [comment]
```
2017-04-19 15:38:14: ERROR[Main]: ModError: Failed to load and run script from D:\Newprog\minetest\bin\..\games\minetest_game_tin\mods\default\init.lua:
2017-04-19 15:38:14: ERROR[Main]: ...bin\..\games\minetest_game_tin\mods\default/crafting.lua:449: '}' expected (to close '{' at line 443) near ')'
2017-04-19 15:38:14: ERROR[Main]: stack traceback:
2017-04-19 15:38:14: ERROR[Main]: 	[C]: in function 'dofile'
2017-04-19 15:38:14: ERROR[Main]: 	...est\bin\..\games\minetest_game_tin\mods\default\init.lua:48: in main chunk
```

**Comment by Fixer-007** [comment]
General look:
default
New bronze receipe:
default

**Comment by Fixer-007** [comment]
>There are many different bronze alloys, but typically modern bronze is 88% copper and 12% tin.

Your recipe is opposite of that.

This can be probably used in automation/other purposes. Bronze tools is still a big problem in my opinion, they need to be made unique in some way since they are pretty expensive and cumbersome to make, my proposal was to make twice as much durability as for steel for example: https://github.com/minetest/minetest_game/issues/1681

**Comment by tenplus1** [comment]
Never noticed that before...  I douwl recommend reversing the bronze recipe to 8x copper and 1x tin = 9x bronze...  also bronze tools in general are same strength as steel but twice as durable.

**Comment by Fixer-007** [comment]
They are not twice as durable, I checked at least shovels.

**Comment by cx384** [comment]
I think a recipe which needs  3 copper and 1 tin would be justified for bronze.

**Comment by paramat** [comment]
Oops i went by what VanessaE wrote in IRC, she must have got it reversed.

**Comment by paramat** [comment]
Fixed brackets and bronze recipe.
I have matched ore density to that of moreores, but started tin ore at y = -32 instead of y = 8, firstly to stop tin ore making above-ground stne ook more messy, but also as -32 fits nicely into the depth/value progression of ores: 64, 0, -16, (-32). -64. -128. -1024.

**Comment by DS-Minetest** [comment]
Instead of giving bronze a big advantage, steel could be made weaker. Eg. give bronze tools the same level as stone tools but make them faster and generate iron ore deeper or make it hard to burn.

**Comment by paramat** [comment]
Added texture credits and tested. Ready for review.

**Comment by paramat** [comment]
@DS-Minetest please don't use the 'approval' feature as that may add an 'approved' note to the PR list, which would be confused with a core dev approval, thanks.

**Comment by DS-Minetest** [comment]
@paramat Sorry, didn't know. >_<

**Comment by paramat** [comment]
No problem :)

**Comment by paramat** [comment]
26686196383df71e5634ee4c5af479668d83ee7e

**Comment by Ferk** [comment]
This is awesome.

IMHO, it's ok for steel to be similar to bronce (and making steel weaker or bronce stronger would go against logic).

Steel has a lot of more uses so there's incentive for people to use bronce tools now that they can save steel when doing it (no longer required to craft bronze).

**Pull request closed without merging**
