### PR TITLE
Add footsteps for water - swimming sounds.

### PR DESCRIPTION
**Pull request by sofar**
This is a redo of #436.

I've taken a single, longer audio sample and extracted 3 samples
of 2.0 length, and gave them all a 0.5 sec fade-in and fade-out.

I added a 4th sample that's essentially a nearly-quiet version of
one of the prior sounds.

This combined with the rate of footstep sounds results in a
randomly changing underwater sound that blends in and out somewhat
nicely.

Code entirely by @MirceaKitsune.

### CODE REVIEW

**Comment by paramat** [comment]
I really like the implementation and the quiet 4th sound to break up the regularity.
While these sounds are okay for underwater we need sounds suitable for surface swimming too, gentle bubbly sloshing sounds that are not so bassy. I found it's best to use above-water sounds but one's that are gentle, these seem to work underwater too.

**Comment by MirceaKitsune** [comment]
:+1: Thanks for looking into this! Sadly I didn't have the patience to edit the sound files as requested in my pull request. Especially since I remember doing so initially, but everyone kept saying it doesn't sound right to them... I don't like redoing something continuously while having no guarantee it isn't in vain. Hopefully this one works out better!

**Comment by kilbith** [comment]
While you're on the footsteps, can you address https://github.com/minetest/minetest_game/issues/900 in your PR please ?

**Comment by Ekdohibs** [comment]
:+1:

**Comment by tenplus1** [comment]
If it helps in the meantime, ambience mod plays water sloshing sounds when player is moving in water, and an underwater sound when submerged, as well as running water sounds for both types in game: https://github.com/tenplus1/ambience

**Comment by Fixer-007** [comment]
Just merge this https://github.com/tenplus1/ambience entirely into MTG and start improving it, I did some mod profiling and cpu use was very low.

**Comment by paramat** [comment]
That has potential for fire and running water sounds and we'll consider it in modified form to remove all the unnecessary wildlife. Water footsteps are best done using footstep sounds instead of lua code.

**Comment by paramat** [comment]
Sofar, i'm now searching for new sounds to get this done, is it ok if i open a new PR with different sounds (but which uses this good idea of longish samples plus silent sounds to randomise the ambience)?
I'm searching for gentle 'sloshing' sounds that are primarily suitable for surface swimming but which are reasonably suitable for underwater too.

**Comment by sofar** [comment]
Go ahead - the hardest part is finding usable sound samples anyway :)

**Comment by C1ffisme** [comment]
> While these sounds are okay for underwater we need sounds suitable for surface swimming too, gentle bubbly sloshing sounds that are not so bassy.

Just an idea, but would it be possible to muffle sounds while inside of certain blocks (Or add an API feature that allows this)? That might solve the problem.

**Comment by paramat** [comment]
New PR #1391 
Hope you don't mind me closing this.

**Comment by MirceaKitsune** [comment]
I'd only mind to see the feature thrown away altogether. Glad that someone else could improve it... I'll take a look at the other PR.

**Comment by paramat** [comment]
Don't worry, i consider swimming sounds essential, i can't believe they've been left out so long.

**Pull request closed without merging**
