### PR TITLE
Sounds: Add missing function call gravel sounds

### PR DESCRIPTION
**Pull request by jhcole**
I would like to use this for castles:rubble. Seems like it should have been available but was forgotten.

### CODE REVIEW

**Comment by sofar** [comment]
If you add this, you should also attach these sounds to ```default:gravel``` instead.

**Comment by jhcole** [comment]
I thought these are the sounds attached to `default:gravel`. Maybe I don't understand what you're mean.

**Comment by sofar** [comment]
Yeah, this looks good to me.

**Comment by paramat** [comment]
This is correct, but many nodes use modifications of existing sound default tables, so i am undecided.

**Comment by 0-afflatus** [comment]
Think in terms of basic sound types. This is logical and the right way to do it.

**Comment by C1ffisme** [comment]
@paramat Minetest Game is now the main subgame for modding, (Most, if not all mods on the Minetest Forum are specifically meant for Minetest Game, with the exception of non-subgame games, such as WorldEdit.)

I think Minetest Game should try to support mods a bit better, and this is one way of doing that.

**Comment by paramat** [comment]
Yeah this makes sense :+1:

**Comment by paramat** [comment]
Approved by nore and sfan5 http://irc.minetest.ru/minetest-dev/2016-04-29#i_4597363

**Comment by paramat** [comment]
1a6298958e14782eca4feb51ef623479ddaaf9c6

**Pull request closed without merging**
