### PR TITLE
Readd stairs registration

### PR DESCRIPTION
**Pull request by MarkuBu**
This PR re adds the accidentally removed stair and slab registration

### CODE REVIEW

**Comment by paramat** [comment]
What's this for?

**Comment by MarkuBu** [comment]
Some stair registrations where deleted in my stairs version. Sofar wants a separate PR to add them again

**Comment by paramat** [comment]
That makes no sense, see my comment in the other PR.

**Comment by MarkuBu** [comment]
I assume he wants to compare it with the original version if everything is complete

**Comment by paramat** [comment]
There was a misunderstanding, this belongs in the original PR as the 3rd commit.

**Pull request closed without merging**
