### PR TITLE
Allow non-players to dig bones, locked chests, and steel doors.

### PR DESCRIPTION
**Pull request by MT-Modder**
Fixes: https://github.com/minetest-technic/technic/pull/257
Fixes issues with Technic/Pipeworks Machines.

### CODE REVIEW

**Comment by PilzAdam** [comment]
:+1:, according to `lua_api.txt` the `player` argument of `nodedef.can_dig` can be `nil`.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
0410b5e0ca6d0f2ff58171b3f1a88e7f5996060d
ac843f8fe72bd90a0ee50ab3a9592f1ab271742f
29252c6fb2f767172e2d637b6ca784958ddbc392

**Pull request closed without merging**
