### PR TITLE
Default: Lower grass_side and snow_side textures

### PR DESCRIPTION
**Pull request by paramat**
Half coverage for a more grassy appearance
Make snow_side universal by removing green pixels
Move KevDoy's heart texture credit to above sound credits
//////////////////////////////////////////////

screenshot_20160504_012628

screenshot_20160504_013021

screenshot_20160504_011927

Grass fringes are the same but moved to an average of halfway down.
'Snow side' has green pixels removed to make it usable for more purposes, it has a fringe structure similar to the other two and is intended to be frosty/snowy grass.

grass_vox7_side_dirt128

dry_grass_side_dirt128

snow_side12_dirt128

### CODE REVIEW

**Comment by PilzAdam** [comment]
And grass textures again...

**Comment by paramat** [comment]
That's enough grumpy comments PA :P

**Comment by kwolekr** [comment]
I'm not sure I like these new textures...

**Comment by sofar** [comment]
First impression to me is positive.

**Comment by Ekdohibs** [comment]
These screenshots give a good impression to me, I am however wondering if a 1-pixel-shorter texture would be better. Anyway, savannas definitely look good :).

**Comment by paramat** [comment]
Yeah i have wondered where to measure to before, top of fringe? base of fringe? So here i decided the average, which appears halfway down when seen from a distance.

**Comment by paramat** [comment]
This may not be ready in time for release. I'm considering if 3/4 covered would actually look better, and be more effective at making hills appear grassy from the side. Need to experiment.

311c4670-7b62-11e5-8c0a-2ca685a0ee29

**Comment by paramat** [comment]
Updated to have 3/4 coverage, new screenshots coming.

**Comment by Ekdohibs** [comment]
IMHO, 1/2 coverage looked better; of course, this needs to be discussed with other devs as well

**Comment by tobyplowy** [comment]
@paramat instead of changing the grass texture you could actually do something like this it would require some coding but it looks a lot better http://i.imgur.com/BAYY4.png By the way This is a Minecraft Mod

**Comment by C1ffisme** [comment]
@tobyplowy That could be done as a different drawtype... I was thinking about suggesting something similar, but with slopes.

**Comment by paramat** [comment]
The coding is the problem, it's good to avoid a coded solution. There's very little advantage in a coded solution that keeps a short fringe on some sides and solid grass on others, i would consider it not worth the extra complexity. I'm only considering this because it is done by texture.

Ekdohibs, ok i'll submit both, devs can then decide.

**Comment by tobyplowy** [comment]
@C1ffisme that should be cool but I think you should keep the Blocky feeling :/

**Comment by tobyplowy** [comment]
@paramat I don't like these long side grass textures :/

**Comment by C1ffisme** [comment]
@tobyplowy It would only be a 45 degree slope. Plants use 45 degree angles, and 3d torches would use even smaller angles.

Besides that, it would "differentiate" us from Minecraft.

**Comment by tobyplowy** [comment]
@C1ffisme I don't think The slopes would Fit the vannila game but for a mod It Would Be awesome (I would definitely try it)

**Comment by paramat** [comment]
Updated and back to half coverage, improved 'snow side' texture, new screenshots.

**Comment by tobyplowy** [comment]
@C1ffisme Could you actually make in a mod that due this grass I just want it so bad. and i can't program Good Enough to do it :cry:

**Comment by paramat** [comment]
There's a mod by BlockMen that does that, called 'landscape' i think?

**Comment by tobyplowy** [comment]
@paramat Yes That's exactly What I want. thank you!! Sorry for going of topic I just need this mod :smile: (btw) can't this mod be added to the default game?

**Comment by tobyplowy** [comment]
@paramat the new texture looks better than previous one you made (I don't like these long side grass textures but I could live with this one) good job @paramat :smile:

**Comment by tobyplowy** [comment]
@paramat The landscape mod doesn't work (disappointment) :cry:

**Comment by C1ffisme** [comment]
@tobyplowy He can't, he quit Minetest a while ago...

**Comment by tobyplowy** [comment]
@C1ffisme NNNNOOOoooooooooo!!!!!!! Can you please fix it for me. please :cry:

**Comment by PilzAdam** [comment]
Removed offtopic comments.

**Comment by benrob0329** [comment]
+1

**Comment by paramat** [comment]
Added texture previews to first post.

**Comment by paramat** [comment]
Harmless and can be part of new grass, might as well merge for release.

**Comment by paramat** [comment]
Approval by nore/ekdohibs http://irc.minetest.ru/minetest-dev/2016-05-05#i_4602463

**Comment by sofar** [comment]
Past freeze, this shouldn't go into 0.4.14.

**Comment by paramat** [comment]
Textures are harmless, this is also the second part of 'new grass'. We are being flexible about 'freeze' where it makes sense.

**Comment by paramat** [comment]
de3adb5859bf2817c5a46e052200759e7a491213

**Pull request closed without merging**
