### PR TITLE
Snowblock: propagate light like snow slab and ice

### PR DESCRIPTION
**Pull request by paramat**

### CODE REVIEW

**Comment by SmallJoker** [comment]
Ice: https://static01.nyt.com/images/2017/01/31/science/31jewelice02/31jewelice02-superJumbo.jpg
Snow: https://80d2853cc4def76b377d-54344bc01a8b066c84096a8e7a3499ac.ssl.cf1.rackcdn.com/original/312383.jpg

Thin layers of snow would probably let some light through - but not a 1m solid node of snow. Ice in the other hand can usually propagate light.  Sorry but that's a :-1: from me.

**Comment by paramat** [comment]
Snow is ice particles, which transmit diffuse light just like solid ice does.
The images don't prove anything as any glow in shadow will be drowned out by daylight.
Additionally it helps to be consistent with existing snow and ice and enables beautiful light effects.

**Comment by paramat** [comment]
screenshot_20180325_060932

^ In iceshelf under 1 layer of snowblocks and 1 layer of ice

screenshot_20180325_061229

^ Dungeons in iceshelf are illuminated by light coming through snowblocks and ice

screenshot_20180325_062239

^ Tunnel below 1 layer of snow blocks and 4 layers of ice

**Comment by HybridDog** [comment]
snow may let light pass but you can't see through it (in comparison to glass, ice and water), so it shouldn't let sunlight pass but spray a bit light (similar to torches) when lighted by sunshine

**Comment by paramat** [comment]
@Ezhh

**Comment by Ezhh** [comment]
I'm a bit torn on this one. I like it, and I'm definitely not against it, but it makes less sense when you have too many layers of snow, so I've been hoping to see more opinions.

**Comment by paramat** [comment]
Yeah, i don't feel strongly on this, more input needed.

**Comment by jastevenson303** [comment]
An inch of snow or less on my windshield completely obscures my view.  In Minetest Game I think an opaque solid object should not propagate light.

It would be interesting to be able to set degrees of light propagation instead of off or on.  Further, two nodes with 50% light propagation could result in 25% propagation.  Just some thoughts.

Trapdoors should, however, because they're partially transparent.

**Comment by paramat** [comment]
Obscuring view is not the same as blocking all light.
'Opaque' seems to be defined as 'not transmitting any light', so i agree on that, but snow does transmit some light.
Trapdoors and doors transmitting light is dependent on the texture including a window.

I guess a metre of snow would be closer to dark than 'slight attenuation of light'.
I'm fairly neutral on this now.

**Comment by paramat** [comment]
Well meh, closing as opinion is slightly against :]

**Comment by jastevenson303** [comment]
>Obscuring view is not the same as blocking all light.
'Opaque' seems to be defined as 'not transmitting any light', so i agree on that, but snow does transmit some light.
Trapdoors and doors transmitting light should be dependent on the texture including a window.

>I guess a metre of snow would be closer to dark than 'slight attenuation of light'.
I'm fairly neutral on this now.

Yes, but that's not currently how it is, paramat...  Currently, doors propagate sunlight and trapdoors don't; but, trapdoors and doors both have see-through textures.

**Pull request closed without merging**
