### PR TITLE
Unlink character.png from b3d export

### PR DESCRIPTION
**Pull request by stujones11**
Fixes Irrlicht: Could not open file of texture: character.png warning

### CODE REVIEW

**Comment by sofar** [comment]
Can you explain to me how you did this? I've attempted to do this in blender but have come up empty handed every time.

**Comment by stujones11** [comment]
Select the entire mesh in edit mode then remove the texture reference from the UV layout editor by clicking the 'X' next to the image combo. Next you need to remove the texture from the material, however, I have sometimes found it necessary to delete the material altogether then add a new one otherwise the model will load transparent. I have no idea why that is...

**Comment by stujones11** [comment]
Note: I would have done this some time ago but thought that some might complain that the model is more difficult to edit without the image. Since the image has now been removed from the models directory the model was linked to a non-existent file anyway.

**Comment by sofar** [comment]
Can we modify the b3d export script to omit the texture? That would solve the problem, right?

**Comment by stujones11** [comment]
> Can we modify the b3d export script to omit the texture?

We do not supply the export script, do we? Even if we did that is not a proper solution IMO.  If people need the texture it is easily added back by re-selecting it in the UV image combo. The texture associated with the material is only required for renders.

**Comment by sofar** [comment]
I've been strongly contemplating that we should package the b3d export script as there have been upstream changes to it that have broken it. It would be really helpful for folks if they knew where the right version would be. Then, if we are distributing it, we can modify it to not include the exported texture (or make that an option that is disabled by default).

**Comment by stujones11** [comment]
I do not think that it is our responibility but if the exporter were to be included we should definitely not break it to accommodate some obscure use case.

**Comment by sofar** [comment]
I'm not proposing to break it, just (1) distribute a version that isn't broken by upstream and (2) has options to make exporting for minetest easier.

**Comment by stujones11** [comment]
There is only one b3d model in the game (afaik) which very rarely changes so this is totally unnecessary. Also, where does it end, what about DirectX or other supported formats.

If you want to include custom exporters with minetest then I think that should be a separate issue.

**Comment by sofar** [comment]
I don't understand your resistance. You've exposed a problem for anyone making minetest models with animations, and instead provide only a short term solution that will get broken once the next person re-exports the model. I'm not saying that it shouldn't be done, but the resistance to a long-term solution is weird. At least provide a documentation patch or a wiki link with the steps you took so it can be reproduced?

**Comment by stujones11** [comment]
It is not a problem for me and I would hardly class myself as an expert. A note in the wiki sounds like a reasonable solution.  What I do not use understand is why such a trivial fix ends up becoming such a big deal.

This is not a short-term solution, the error will only come back if someone re-adds the (non-existent) texture. That would be wrong and consequently up to the game maintainers to reject such a change.

**Comment by sofar** [comment]
Replaced by #931
Additionally, see https://github.com/minetest/minetest/pull/3865 (stash a copy of b3dexport.py that does this properly)

**Comment by sofar** [comment]
We now have: https://github.com/minetest/B3Dexport

**Comment by paramat** [comment]
931 merged.

**Pull request closed without merging**
