### PR TITLE
Farming: Various straw, wheat and fuel modifications

### PR DESCRIPTION
**Pull request by paramat**
Craft 9 drygrass into straw
1 straw from 9 wheat instead of 3 straw, for consistency
Remove 'wheat from straw' recipe to avoid wheat from dry grass
Make straw a fuel
Make wheat and cotton fuels
//////////////////////

Implements #884 plus these additional changes:
1 straw from 9 wheat instead of 3 straw, for consistency
Make wheat and cotton fuels

@PilzAdam

### CODE REVIEW

**Comment by sofar** [comment]
+1 for all this. Perhaps @Wuzzy2 wants to comment?

**Comment by Wuzzy2** [comment]
Why only 1 straw for 9 wheat now? I don't like that.
Consistency is a bad reason IMO.

The idea was that the player can still get straw from dry grass, but less than with using wheat. Using wheat would be more efficient, so I intentionally did not suggest to change the output of 9 wheat.

**Comment by tenplus1** [comment]
-1 ... Don't break the already used wheat -> straw -> wheat system, it works well for players wanting to store wheat in blocks...  Add grass matts or something decorative for dry grass if need be which can also be used as fuel.

**Comment by C1ffisme** [comment]
@Wuzzy2 Since wheat takes more time to get, I think wheat should produce about 4 straw, and dry grass should produce 2 straw.

**Comment by Wuzzy2** [comment]
Shit, I think tenplus1 is right.
Players who specifically crafted wheat for better storage will be screwed by the next update.

I guess this means the only part of this PR we can now agree on are the fuel recipes, I guess.
Because dry grass → wheat recipe would be bad if we keep straw to wheat because dry grass could then be easily turned into wheat.

**Comment by paramat** [comment]
Good points.

**Comment by C1ffisme** [comment]
This is why we need the ability to set a crafting recipe based on metadata. We would just need to change the metadata of the straw depending on what material is used to craft it.

**Comment by paramat** [comment]
Straw has been badly implemented, straw is not wheat, it's just the stalks. It should have been called wheat_block and look like a solid cubic bundle of wheat (with heads).
We could change the trxture and use the straw texture for a 'dry grass block'.
Straw is expensive to get from wheat, now that we can use grass blocks as fall damage reducers perhaps we need a seperate dry grass block.

**Comment by 0-afflatus** [comment]
> Straw has been badly implemented

Yeah, if I were you I wouldn't start from here.

**Pull request closed without merging**
