### PR TITLE
Amend empty drop from "" to {}

### PR DESCRIPTION
**Pull request by tenplus1**
Changes empty drops from returning empty string to empty table.

### CODE REVIEW

**Comment by SmallJoker** [comment]
What's the difference of these two values?

**Comment by tenplus1** [comment]
@SmallJoker - for some reason get_node_drops returned tnt:tnt_burning as a drop item instead of an empty drop, this fixed it.

**Comment by SmallJoker** [comment]
@tenplus1 Then it's the wrong place to fix this issue. Please create a core PR for this bug.

**Comment by tenplus1** [comment]
@SmallJoker - https://github.com/minetest/minetest/pull/7592

**Pull request closed without merging**
