### PR TITLE
Remove unused TNT & torch textures

### PR DESCRIPTION
**Pull request by CraigyDavi**
This PR removes the following textures as they are not used:
```
mods/default/textures/default_tnt_bottom.png
mods/default/textures/default_tnt_side.png
mods/default/textures/default_tnt_top.png
mods/default/textures/default_torch.png
mods/default/textures/default_torch_on_ceiling.png
```

### CODE REVIEW

**Comment by PilzAdam** [comment]
Some people experienced problems in #544.

**Comment by CraigyDavi** [comment]
> Some people experienced problems in #544.

I've had a look at the screenshot posted there and it looks like they're using other mods (which could be redefining tnt?).

I've tested this on the latest fresh minetest_game and it works correctly.

@ExcaliburZero could you see if you still experience problems when not using any mods?

**Comment by ExcaliburZero** [comment]
@CraigyDavi 

Sorry for the late reply.

I tested out the pull request on a neutral world, and it seems to work without causing the texture issue.

**Comment by paramat** [comment]
I'll test and merge this.

**Comment by paramat** [comment]
+1 if no problems.

**Comment by paramat** [comment]
Will merge this soon.

**Comment by paramat** [comment]
7c0abe93664dca2ae87ae2e4bb83e30febd6c06a

**Pull request closed without merging**
