### PR TITLE
Fix TNT drops being placed inside nodes

### LINKED ISSUE #483: TNT blows item entities into/through nodes
screenshot_20150404_125337

Two ways to solve : 

- Put all exploded blocks into a bone-like block (cheap, but also stops lag)
- Change the engine to make entities potentially avoid being inside nodes. (At least, in a way that allows modding capability. Whether or not an entity gets out of nodes or not should be settable.)

### PR DESCRIPTION
**Pull request by ShadowNinja**
Seems to fix #483.

### CODE REVIEW

**Comment by PilzAdam** [comment]
Maybe check for `not walkable` instead of air. Items can be dropped in water, too.

**Comment by ShadowNinja** [comment]
@PilzAdam: Done.  I've noticed that the bug still happens if you detonate multiple TNT nodes next to each other.  This seems to be an engine issue though.

**Comment by paramat** [comment]
:+1: Will merge.

**Comment by paramat** [comment]
c76a91943cfc6c464f984ffa02c848c7f4c76294

**Pull request closed without merging**
