### PR TITLE
doors: Remove unnecessary nodebox and empty texture

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by paramat** [comment]
Did not test but :+1:

**Comment by TumeniNodes** [comment]
@sfan5 so how is 

> can't use airlike otherwise falling nodes will turn to entities
	drawtype = "airlike",
	-- and will be forever stuck until door is removed

resolved here?
just asking because I've not been keeping up lately

**Comment by TumeniNodes** [comment]
@sfan5 
ahhhhh, nevermind... just realized
disregard

**Comment by sfan5** [comment]
The answer is that the falling code doesn't care about drawtype, what matters is that the node is walkable.

**Pull request merged**
