### PR TITLE
Boats: Fix Boat yaw when entering boat

### PR DESCRIPTION
**Pull request by pilino1234**
Align boat with drivers yaw when entering, would previously turn
boat yaw by player's yaw + 90° to the right.

### CODE REVIEW

**Comment by paramat** [comment]
I would have thought aligning the player to the boat's yaw would make more sense?

**Comment by sofar** [comment]
I agree with paramat - the boat shouldn't turn with the player - the player should turn with the boat. You "get in" the boat. Same way the rail cart will not rotate when you get in...

**Comment by paramat** [comment]
Yes i think i would prefer player aligning to the boat.

**Comment by pilino1234** [comment]
Ok, I don't know so much lua though, any ideas/hints as to have I can achieve that? Aligning player yaw would indeed make more sense, as long as it stops doing the 90° turn that it does now I'm satisfied :)

**Comment by Fixer-007** [comment]
I like how it is now, I can look while going into other direction on a boat.

**Comment by pilino1234** [comment]
@Fixer-007 This PR only affects the initial yaw when entering the boat, you can still look around while driving it.

**Comment by sofar** [comment]
I *think* the code is OK, but the commit message and title are wrong now :)

**Comment by pilino1234** [comment]
@sofar Not any more ;)

**Comment by paramat** [comment]
Tested, does feel better than previous behaviour :+1:

**Comment by DS-Minetest** [comment]
i think, its good like it is now
turning boat takes much time and is annoying
before entering the player pushes the boat into the right direction from land, its a small lightweight boat and it makes no sense to turn it with paddles after sitting in instead

**Comment by pilino1234** [comment]
@DS-Minetest Yes, that is how I had changed it originally. But the way it is right now (in current MT Game; without this PR) needs to be changed since it makes no sense at all.

**Comment by DS-Minetest** [comment]
i mean its good like its now in the current mt game

**Comment by pilino1234** [comment]
@DS-Minetest Wut? Have you even tested it?? It's completely broken (if I may say so).

**Comment by DS-Minetest** [comment]
ok, ive tested it now, you r right

**Comment by pilino1234** [comment]
Hmm, yes. Indeed it does make more sense to turn the boat in the right direction before getting in. @paramat @sofar should I change it back?

**Comment by sofar** [comment]
No, please don't rotate the boat when the player gets in. Carts also will not rotate when the player gets in. 

When you get in to a car in the real world, the car also does not rotate.

**Comment by paramat** [comment]
Boats are always orientated in the same direction when placed, can we consider the boat being orientated away from the player when placed? (it would take the player's yaw). A player would usually want to travel in the direction faced when placing the boat (away from land).
Player taking the boat's yaw when entering the boat, as in this PR, would be unchanged.

**Comment by pilino1234** [comment]
@sofar But carts are large things made of steel, while the boat is a tiny raft made of wood. They are quite different, it is certainly possible to turn a boat like this by hand before getting in. 
I like @paramat's solution, it sounds sensible. I'll have a look at that later today.

**Comment by paramat** [comment]
To be clear i still want the player to align with the boat when attaching.

**Comment by pilino1234** [comment]
@paramat done

**Comment by DS-Minetest** [comment]
:+1: 
> But carts are large things made of steel, while the boat is a tiny raft made of wood. They are quite different, it is certainly possible to turn a boat like this by hand before getting in. 

also carts are not turnable because of the rails

but at placing its not needed to have the boat turned into the drive direction

**Comment by pilino1234** [comment]
> but at placing its not needed to have the boat turned into the drive direction
Well, it's slightly better than placing it in an arbitrary direction, since, as you said above, it takes a long time and is annoying to turn the boat. So, placing the boat in the direction that the player wants to go in is the most useful and intuitive alternative.

**Comment by sofar** [comment]
:+1:

**Comment by paramat** [comment]
Tested and good :+1:

**Comment by paramat** [comment]
2c122052d4332aa54b631091e718ba42500ec70a

Thanks for a rare good commit message, usually i have to edit them on merge.

**Pull request closed without merging**
