### PR TITLE
Move hotbar code/textures, and damage sound, from player_api to default 

### LINKED ISSUE #2444: Hotbar textures and code are out of place in player_api mod
The setting of hotbar textures is out of place in player_api mod.
From player_api init.lua:
```
-- Update appearance when the player joins
minetest.register_on_joinplayer(function(player)
	player_api.player_attached[player:get_player_name()] = false
	player_api.set_model(player, "character.b3d")
	player:set_local_animation(
		{x = 0,   y = 79},
		{x = 168, y = 187},
		{x = 189, y = 198},
		{x = 200, y = 219},
		30
	)
	player:hud_set_hotbar_image("gui_hotbar.png")
	player:hud_set_hotbar_selected_image("gui_hotbar_selected.png")
end)
```
This function sets the model and animation, but then also sets the hotbar images, which are unrelated to the player_api mod.
These HUD textures belong in default mod together with the other HUD textures: 'bubble', 'heart', 'gui_hb_bg' (the hotbar background texture).
The code belongs together with `default.get_hotbar_bg` and the `GUI related stuff` here:
https://github.com/minetest/minetest_game/blob/4eadf806349e9acfc817db8cdcdc85bc879c1558/mods/default/init.lua#L11
There's even a `minetest.register_on_joinplayer` function present it can be moved to.

Looking at older MTG versions, it looks like this code is only here because it was here when all this code was part of default.
I'll make a PR soon to move it back into default ... and yes i know moving stuff into default is best avoided, but in this case it is the only proper place for this code.

Again i noticed this through working on a very simple game of my own, creating a logical mod structure, and removing this code due to it obviously being in the wrong place.
player_api is (along with creative and sfinv) a mod highly likely to be used in new games, so should only contain relevant content. A priority for this mod is being in a form usable in new games.

### PR DESCRIPTION
**Pull request by paramat**
These are unrelated to the Player API and player object.
All other GUI/HUD code and textures are in default.
All other engine hardcoded sounds are in default.
The player_api mod is highly likely to be used unchanged in new games,
so logical grouping of content will help the creation of new games.
////////////////////////////////////////////////////

Closes #2444 

The 2 lines of code that set the custom hotbar textures, and the 2 hotbar textures, are out of place and unrelated to, the player_api mod. All the other GUI/HUD/hotbar code and textures are in default.
player_api mod is a mod very likely to be used in other games unaltered, so it needs to be in a clean state with content grouped logically. This clean up will really help new game creation.
I am creating 2 new minimal games currently and the current illogical grouping of content in MTG mods is making new game creation messy and more confusing.

The 'player_damage' sound is also out of place and unrelated to the player_api, the only logical place is in default with other basic sounds. All other engine hardcoded sounds such as 'default_dig_cracky' etc. are in default.
Note: sonictechtonic is already mentioned under the CC BY license in default.

### CODE REVIEW

**Comment by rubenwardy** [comment]
I intentionally added these things to the player api mod as they're related to players

**Comment by paramat** [comment]
Ok, i suspected it was intentional because you created the mod. But this hotbar stuff is no more related to players than all the other GUI/HUD/hotbar code and textures still in default. Even if that stuff is in a non-ideal place (default) it's best to keep stuff logically grouped together for now.
I think player_api is best focussed on individual player appearence, models, animation, 99% of it is only those things.

**Comment by TumeniNodes** [comment]
Can't "hud" be set up as a new mod, to store these?

**Comment by paramat** [comment]
Well, that's ideal, but is part of the 'splitting up default' issue. Doing so while maintaining compatibility may require compatibility code, and splitting up default is controversial and may not happen, so your suggestion is best left to a separate PR.

**Comment by paramat** [comment]
This is a tiny change and seems very obvious, can anyone approve?

**Comment by paramat** [comment]
@rubenwardy i have a suggestion.
I'm so keen to clean up player_api, how about i create a new mod called 'gui' or something, move all GUI/HUD stuff from default and player_api into it, and add compatibility code? Then this PR will do a little of the splitting up you want to do.
However, the player damage sound will still be moved to default, as i can't see any other place it could go.

**Comment by TumeniNodes** [comment]
> However, the player damage sound will still be moved to default, as i can't see any other place it could go.

as it is relative/exclusive to the player, my opinion is that it should remain in the player api.

**Comment by benrob0329** [comment]
New mods that are MTG specific should go under the `mtg_` naming scheme as-per @rubenwardy 's suggestions with the CDB and by-name mod compatibility.

**Comment by paramat** [comment]
> as it is relative/exclusive to the player, my opinion is that it should remain in the player api.

Well =) as in my response to rubenwardy, the damage sound is related to the client in the same way that footstep and digging sounds are: sounds that respond to player events. It is not actually related to the player_api at all.

**Comment by paramat** [comment]
I could potentially agree to move the damage sound to a new mod, just as long as it isn't in player_api.
In one of my own ultra-minimal games i have it in a mod called 'media' which is for various media that don't have a home anywhere else, together with 'crack_anylength'.
I'm also ok with separate HUD and GUI mods if requested by other core devs, the 2 just seem similar enough to possibly be 1 mod.

**Comment by paramat** [comment]
@SmallJoker what are your thoughts on this? I would like to merge it as it is, but i could create a new mod for GUI/HUD stuff if that is preferred.

**Comment by paramat** [comment]
@Ezhh i am wondering if you would be able to support this once it is rebased? I cannot get further responses from any other MTG core dev.

**Comment by paramat** [comment]
Added a comment to player_api README as requested by SmallJoker, to clarify what belongs here.
Although it seems obvious from the mod name and the existing comment:
`Provides an API to allow multiple mods to set player models and textures.
Also sets the default model, texture, and player flags.`

**Pull request merged**
