### PR TITLE
Flowers: New texture for yellow dandelion

### PR DESCRIPTION
**Pull request by paramat**
Derived from the white dandelion texture.
////////////////////

screenshot_20170525_155654

flowers_dandelion_yellow128

^ PR

Somewhat addresses #1734
Uses colours of the current yellow dandelion flower, with a form derived from, and stem colours of, the white dandelion.
The current yellow dandelion texture is too big and occurs as one flower, bunches are more suitable.

flowers_dandelion_yellow_old128

^ Current

### CODE REVIEW

**Comment by octacian** [comment]
:+1: Looks way nicer than the previous one, specifically, more realistic. Thanks, paramat! :D

**Comment by paramat** [comment]
No problem, you had something meaningful to say so it's fine.

**Comment by C1ffisme** [comment]
I like it. In my front yard in the spring, I can see clumps of tiny yellow dandelions, and this seems similar enough.

**Comment by ForbiddenJ** [comment]
The property I live on has tiny yellow flowers here and there once in a while. I think this makes a bit of sense.

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.net/minetest-dev/2017-06-08#i_4965202

**Comment by paramat** [comment]
c714d43319a089dfd7c2250e618f48db18fa8980

**Pull request closed without merging**
