### PR TITLE
Notify of bone coordinate 

### PR DESCRIPTION
**Pull request by Rui914**
#403
Add show_bone_pos = (true/false)

### CODE REVIEW

**Comment by kilbith** [comment]
This is a duplicate... you should suggest your ideas on the previous PR instead of increasing the list.

**Comment by Novatux** [comment]
Looks good

**Comment by PilzAdam** [comment]
I am against sending it just in chat, see #403.

**Comment by Rui914** [comment]
Please put your mind at ease.
By default, it is disabled.

**Comment by FreeLikeGNU** [comment]
Its a good idea and gives kids (and adults) a reason to learn how coords work.  They get pissed off enough when they die in game.

**Comment by Rui914** [comment]
#633

**Pull request closed without merging**
