### PR TITLE
Stone sword texture fix

### PR DESCRIPTION
**Pull request by Iniquitatis**
Fixed broken pixel in the stone sword texture.

### CODE REVIEW

**Comment by C1ffisme** [comment]
That may be intended, I mean, it makes the stone sword look sort of, not meant to be used. It looks broken or chipped and needs to be replaced. That, or for some people it looks kind of cool.

**Comment by BlockMen** [comment]
It was indeed intentional. You can see it that way and that way. When I made that texture I had in mind, that it wouldn't be that easy to make a spiky stone or that its spike would break easier than metal or wood would do.

But if ppl want it spiky aswell (in sense of continualness or too much realism) i would be fine aswell. But I would like to hear more opinions on that before changing.

**Comment by C1ffisme** [comment]
@BlockMen Yeah, I thought so. You can whittle wood swords and sharpen metal ones, but stone isn't very pliable. It's more like a club.

**Comment by paramat** [comment]
I agree with BlockMen and feel we should stay with the intnded texture, closing.

**Pull request closed without merging**
