### PR TITLE
Chests: Keep old textures for mod compability

### PR DESCRIPTION
**Pull request by SmallJoker**
Prevents generating ugly looking dummy images for mods that weren't updated yet.

### CODE REVIEW

**Comment by tenplus1** [comment]
Thanks dude, much needed :)

**Comment by DS-Minetest** [comment]
- The crack of the chest would still be ugly.
- The closed chest could use this textures again and doesn't have to use a cubic mesh.

I suggest deleting the new uv chest textures (but add the interior texture[s] in [an] extra file[s]) and change the model of the chest, so, that it doesn't use one texture but for each side one.

**Comment by tenplus1** [comment]
That sounds a better idea DS-Minetest.

**Comment by VanessaE** [comment]
I suggested before this mesh-based chest went in to use a cube mesh with 5 images:  top, bottom, front, back, and one image for the sides (identical, X-flip one of them via UV-map in the model).

The open chest would be done exactly the same way, but with a sixth texture providing the inside-top and inside-bottom images.

**Comment by Ferk** [comment]
> The open chest would be done exactly the same way, but with a sixth texture providing the inside-top and inside-bottom images.

Backwards compatibility of the textures won't fully work, though. Any texture for which the crack to open the chest doesn't match the same position as the one in MTG will be cut-off incorrectly when the chest opens.

**Comment by VanessaE** [comment]
The simple way to solve that would be to allow a texture pack author to supply an alternate model for the open chest also, one that matches his/her new textures.

**Comment by Ferk** [comment]
I think for that the engine would need to be changed for texture packs to be able to include meshes.

**Comment by tenplus1** [comment]
For now a simple fix would include changing closed chest back into a normal nodebox using original textures and a remapped open chest .obj file which uses same textures for each side and a new one for inside lid.

**Comment by DS-Minetest** [comment]
Btw. related: #793 

Another thing to think about: Should the closed chest keep "light" as paramtype1? Else eg. if the chest is placed somewhere in the roof of a house, the light has to be updated every time, a player opens or closes it.

**Comment by paramat** [comment]
Having open and closed chests with differing light behaviour is not good, causes light updates.

**Comment by paramat** [comment]
Not sure about this PR, it would cover up a mod issue and delay mods updating.

**Comment by sofar** [comment]
> Another thing to think about: Should the closed chest keep "light" as paramtype1? Else eg. if the chest is placed somewhere in the roof of a house, the light has to be updated every time, a player opens or closes it.

it's a mesh node, we don't want it to show as a black cube?

**Comment by sofar** [comment]
Trivial, and I have no issues with carrying extra textures to fix other mods.

**Pull request merged**
