### PR TITLE
Default: New grass textures, new footsteps overlay texture

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150813_002219

The long out-of-date 'Dirt with grass footsteps' node now uses the 'default grass' texture plus a new transparent / translucent square-footprint overlay texture, so now it will always stay up to date with texture changes.

screenshot_20150813_034911

default_grass0411_128 Current

default_grass0410_128 Previous 0.4.10 texture

philipbenr_original_bp24_cp24_hp12_sn8_rgb128 My submission

### CODE REVIEW

**Comment by paramat** [comment]
WIP
Will redo the grass texture with a little less noise/contrast.
The footstep texture should perhaps have just 1 footstep per node to match a player's stride, although this would not create the zig-zag left-right pattern.

**Comment by FreeLikeGNU** [comment]
@paramat  footsteps would be cool :D  It would also be nice if mob mods had access to the footprint feature!  Hunting and tracking!

**Comment by paramat** [comment]
Updated with new texture, slightly less contrast for a smoother appearence.

FreeLikeGNU you might be interested in my trail mod (the textures are out of date though) https://github.com/paramat/trail

**Comment by paramat** [comment]
WIP will tweak this again.

**Comment by paramat** [comment]
Discussion http://irc.minetest.ru/minetest-dev/2015-08-13#i_4364295

**Comment by paramat** [comment]
c7b9e734ffd815e9b86b1fcceba2293e3067785e

**Pull request closed without merging**
