### PR TITLE
Dry shrub: Use plantlike meshoption for bushy appearence

### PR DESCRIPTION
**Pull request by paramat**
Dry shrub: Use plantlike meshoption for bushy appearence

Adjust selectionbox width for a better fit and consistency with other
grasses.
/////////////

screenshot_20180101_093056

screenshot_20180101_093752

@sofar 
Uses meshoption 4 for 4 faces leaning outwards.
Dry shrubs are always at low density so extra faces are not a problem.

### CODE REVIEW

**Comment by SmallJoker** [comment]
These dry shrubs look nice. How about generating them in this style in mgv6 too?

**Comment by paramat** [comment]
Heheh i completely forgot about mgv6, will do.

**Comment by paramat** [comment]
Done.

**Comment by Fixer-007** [comment]
What about other kinds of grass?

**Comment by paramat** [comment]
Other grasses have too high density to double their faces.

**Comment by paramat** [comment]
223562d687da721729a4295f8a5030a2c7ed3a2f

**Comment by sofar** [comment]
this turned out really pretty!

**Pull request closed without merging**
