### PR TITLE
Doors: Allow falling nodes to fall onto doors.

### PR DESCRIPTION
**Pull request by sofar**
We were cleverly attempting to use an airlike node as the
top half of the doors, but as airlike nodes are not walkable,
falling nodes would not stop falling and thus remain an entity
stuck on top of a door.

After inspecting the builtin/game/falling.lua code, I considered
the remaining options: (a) revert doors such that the top part is
actually the door, (b) play with nodedef fields and see if other
flags may work, or (c) modify the hidden door part to another
drawtype that properly prevents this issue.

(a) seemed way over the top for now, although it would solve the
issue, it would cause a rewrite of most of the code including the
old-door-conversion.

(b) turned up nothing.

(c) turned out to be relatively simple.

So, here's the implementation where I turn the hidden door top
into a tiny, non-targetable but walkable nodebox that is entirely
inside the door hinge. It's entirely transparent, so you still
can't see it, can't hit it, nor can you place anything in it or
make liquids flow through it. The top part is placed in the right
position on placement and not touched further.

Falling nodes will properly stop on top of these doors. I've
adjusted the door conversion code to properly account for the
issue as well, so the only thing remaining is people who have
been running a git branch - those can upgrade by re-placing the
door.

### CODE REVIEW

**Comment by sofar** [comment]
Fixes #923

**Comment by sofar** [comment]
@paramat 0.4.14 tag please.

**Comment by paramat** [comment]
Would a walkable airlike node work?

**Comment by paramat** [comment]
:+1:

**Comment by C1ffisme** [comment]
Nice one, that's a fix I would have never thought of!

**Comment by sofar** [comment]
yes, walkable airlike doesn't work - air is a floating node so sand attempts to fall into it.

**Comment by sofar** [comment]
Updated style.

**Comment by Fixer-007** [comment]
Works for me.

**Comment by Rui914** [comment]
Isn't it the core (falling nodes) side bug?

**Comment by sofar** [comment]
@rui914 without more information, I have no idea

**Comment by Rui914** [comment]
I think falling nodes should be added checking the flag like "no_replace_falling".

**Comment by sofar** [comment]
@Rui914 that would make things even more complex. I don't see why it would be needed right now?

**Comment by Rui914** [comment]
>that would make things even more complex.

Okay, if you say so.

>I don't see why it would be needed right now?

I just thought it useful for other airlike nodes.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by Ekdohibs** [comment]
I was thinking though: maybe you could try to fix #954 at the same time (by making the hidden node have a collision box about the same as the door, and rotating it with the door.

**Comment by sofar** [comment]
The whole idea of making doors meshnodes is that you don't ever have to change 2 nodes at the same time anymore. Fixing the game engine is far more powerful instead.

**Comment by paramat** [comment]
9de43cdf7d7391a929ec8e89ba615c01355926b3

**Pull request closed without merging**
