### PR TITLE
Doors: Add dedicated sounds for glass doors

### PR DESCRIPTION
**Pull request by paramat**
Changed node sounds for steel door/trapdoor to stone
defaults instead of wood defaults
////////////////////////////////////////

Concerning general node sounds (digging, dug etc.) currently glass doors use wooden defaults which sound very obviously wrong, stone defaults are used elsewhere for a 'hard' sound for metals and are acceptable.

### CODE REVIEW

**Comment by everamzah** [comment]
Is it possible to use a SimpleSoundSpec with a gain parameter so the audio files aren't duplicated?

**Comment by paramat** [comment]
Not in the current code, when we find a dedicated sound we won't need to use gain anyway.

**Comment by paramat** [comment]
I'll look for new sounds, so WIP.

**Comment by paramat** [comment]
It would be good to have sound gain as a parameter in the doors API, for easier balancing of various doors. Currently i will have to adjust gain in Audacity.

**Comment by paramat** [comment]
Updated with dedicated glass door sounds from freesound.org.
Ready for review.

**Comment by sofar** [comment]
I'm pretty sure I listened to that sound before, and it's a very nice one, so :+1:

**Comment by paramat** [comment]
f796194c6959ca4e560bfcb03f173e06a94755de

**Pull request closed without merging**
