### PR TITLE
Add mirror recipes for both axe and hoe

### PR DESCRIPTION
**Pull request by heav-4**
These recipes can't be flipped, they really ought to be able to.

### CODE REVIEW

**Comment by paramat** [comment]
:-1: Sorry, we actually used to have duplicated recipes and decided to remove one. See #1752 and #1777 for reasons.

**Comment by Df458** [comment]
Yeah, I'm gonna need to hear a better explanation. Seriously, stop and *think* about how bad of a decision this was. It's already hard enough for new players to work out recipes, and this is just an arbitrary extra layer of confusion to top it off. And for what?

> In MT generally there will be many non-symmetrical recipes, doubling the recipes for all of these would would be excessive.

This is the only actual reason given in the original issue/PR. Every other coredev opinion involved in the decision was just some variant of "sure whatever" with no strong support or argument, so this stands alone...

With that established, let's take a look at every crafting recipe that actually exists in MTG. To my knowledge, the **only** horizontally-asymmetrical crafting recipes are:
- Fancy bed
- Stairs
- Axe
- Hoe

This is very little to actually add from a code standpoint, and solves a real source of friction when players craft (*especially* new players who haven't memorized all the recipes yet, and are the most likely to get frustrated and leave). And your response is that "well people might make a lot of asymmetrical recipes in their mods, and it would sure be a lot of recipes"? Frankly, I think that's really weak argument compared to annoying people all the time.

I would like to hear a more detailed explanation as to why you think this excess is an actual problem, and how that balances against the possibility of a new player trying to make a basic tool, getting 0 feedback that they put it in backwards, and potentially missing an entire game mechanic in the process.

**Comment by heav-4** [comment]
yeah as a new player this initially confused me (wait, are the axe recipes completely different in this game?) and after i figured it out it just seemed like a bad development decision. 2 more recipes aren't excessive, and there's literally no reason not to add this

**Comment by paramat** [comment]
Also this reason in the PR:
> to be consistent with stairs

Also see similar done to stairs #1741 and #1758 . Note in all 4 issues/PRs i have linked there were no objections, only a lot of support.

This was done for stairs because the stairs mod registers stairs for a large number of MTG nodes, and therefore creates a large number of recipes. The duplication was hugely increasing the number of recipes, especially considering all the non-MTG nodes using the API to register stairs.
Recipe count is often very large considering how many items are registered on a server (can be as much as 32000) so getting recipe count under control is a good idea.
Axes and hoes were then de-duplicated for consistency.

heav-4, so it is not just 2 more recipes, for consistency it would have to be done for all MTG mods and stairs mod too, causing 100s of extra recipes on a server. Also for all other MTG mods and all future items and APIs added, which could add very large numbers of recipes.

I can see both of your points, and i accept it may at first seem counter-intuitive, but this is the result of long term development experience, and had a lot of support an dno objections in 2 separate issue/PRs.
It is not a big issue to learn the correct recipes, and they match the appearence in inventory. On balance i think the benefits are worth it.

**Comment by Df458** [comment]
I will express my disagreement by re-implementing the feature as a mod then, that seems to be the simplest solution.

**Comment by sfan5** [comment]
I'm with @Df458 here, adding flipped recipes has <i>zero</i> downsides and improves the experience for new players considerably because they won't have to try to guess the correct recipe or look it up somewhere

> Recipe count is often very large [...] so getting recipe count under control is a good idea.

I'm not aware of any performance problems with crafting recipes, are there any?
Re-adding flipped stair, hoe & axes would add less than 70 crafting recipes.

> and had a lot of support and no objections in 2 separate issue/PRs

User support is good indicator of course, but it would be interesting to hear the reasons why people supported the removal.
For me, "improved UX for inexperienced players" is a much better argument than "recipe does not exactly match item texture".

Also, user support evidently isn't as clear cut since #2168 and this PR exist.

**Comment by Df458** [comment]
> I'm not aware of any performance problems with crafting recipes, are there any?

I wasn't going to bring this up, but I implemented the complete change as a mod (as I implied above) and ran some *extremely unscientific* load timing tests with various mod configurations. On my relatively powerful PC I saw no visible difference with/without the extra recipes, even when inflating the recipe count by a large margin (using mods like moreblocks) or adding a craftguide that had to scan them all.

To truly trust these results, we would need to test with numerous PC configs, lots of repetition, more accurate (ie code-based) timing methods, and we would need to be testing a 'cold load' situation... I don't really have the time or motivation to go to those lengths to get accurate timing information, but I will be publishing my mod and we may find out when users get their hands on it.

**Comment by paramat** [comment]
2 points i forgot:

We are intending to add a crafting guide to MTG, see #1435 and #2396 , it is just waiting for review. This will solve the issue of remembering crafting recipes in MTG.

For outside of MTG, it seems better to have an engine solution.
I suggest that crafting also accepts the flipped recipe as long as that does not result in a different item (some recipes may intentionally result in differing items when flipped).
With this the issue will be solved for all mods and games, without needing to add flipped recipe definitions or increase recipe number.
I will support that in the engine if you want to open an issue there.

**Pull request closed without merging**
