### PR TITLE
Make empty buckets stackable

### PR DESCRIPTION
**Pull request by MT-Modder**
Code by tenplus1

### CODE REVIEW

**Comment by rubenwardy** [comment]
Use should sign it for tenplus1, if you can get his/her GitHub email.

It is easy with git.

**Comment by rubenwardy** [comment]
*you

**Comment by rubenwardy** [comment]
git commit --author="tenplus1<email@example.com>" -m "some fix"

You can open the shell from the menu in the top right if using windows GitHub client, I believe.

**Comment by C1ffisme** [comment]
:+1:

**Comment by CraigyDavi** [comment]
whoever@users.noreply.github.com always works with any user

**Comment by MT-Modder** [comment]
Okay this was a mistake because I have no idea how to use the shell correctly. Sorry.

**Pull request closed without merging**
