### PR TITLE
tweak xpane bars texture

### PR DESCRIPTION
**Pull request by Napiophelios**
Its just a matter of opinion, but it seems like xpane bars need to be altered;
they just look weird in the game.
tweaked_xpanes_bar

a slight tweak of the original texture would give a better look.
xpanes_bar

of course this can be changed with texture packs,
so it isn't that important. Just thought I would put it out there :)

### CODE REVIEW

**Comment by paramat** [comment]
Looks better, will test in-game.

**Comment by sofar** [comment]
I'm a fan. Looks good even in between 2 blocks attaching to it.

:+1:

**Comment by paramat** [comment]
:+1: Perfect.

**Comment by paramat** [comment]
e67a60376f3c44efed8f0d1e86a232b87f2c557d

**Pull request closed without merging**
