### PR TITLE
Keep a bucket of liquid in creative mode

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by C1ffisme** [comment]
Hold on, make it use proper indentation. The return needs to be moved up with a Tab.

**Comment by Rui914** [comment]
Fixed.

**Comment by PilzAdam** [comment]
Whats the usecase for this? You can just get the liquid source blocks if you want to place them a lot.

**Comment by BlockMen** [comment]
@PilzAdam but why then having buckets at all in creative mode? Should get added IMO

**Comment by PilzAdam** [comment]
@BlockMen maybe to remove liquids, so picking up liquids in creative could leave the bucket empty.

**Pull request closed without merging**
