### PR TITLE
Default: Add 'permafrost', 'permafrost with moss' nodes for tundra

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160819_231640

default_permafrost128

Issue #1260 
A quick first attempt with moss derived from dry grass (darker, redder), permafrost derived from dirt (darker, less saturation, more contrast). Moss texture is somewhat of a placeholder and probably needs extra work and maybe a little frostyness. I'm fairly happy with the permafrost though.
Makes a nice contrast against icesheet biome.
Permafrost is tough stuff so made it 'cracky = 3' like ice, and with a hard 'stone' footstep.
Updated functions are tested.

screenshot_20160819_231324

090220-alaska-coast-melting_big

### CODE REVIEW

**Comment by C1ffisme** [comment]
Moss needs to look different from grass, but this is an interesting idea.

**Comment by paramat** [comment]
Anyone want to make a better moss texture?
However i feel we can merge this and improve the textures later.

**Comment by Fixer-007** [comment]
Seems as a good start.

**Comment by paramat** [comment]
It's directly derived form the dry grass texture, so needs work or redoing. The texture was just a quick placeholder.

**Comment by sofar** [comment]
The color looks very similar to dry grass, perhaps we could try a more blue/cyan tint?

Screenshot of all the color tints together may be helpful.

**Comment by paramat** [comment]
Yes other mossy colours are fine, i think it would be nice to have something not grass-green though, for some variation. Here i was inspired by red-brown moss.

**Comment by paramat** [comment]
dsc_2102

Bright lemon-green moss.

**Comment by paramat** [comment]
Realised i can use simple decorations to place patchy snow on tundra.

**Comment by paramat** [comment]
screenshot_20160823_233743

Another quick attempt at moss. Looking at pictures moss often looked like a soft rolling carpet, so i overlaid our sand pattern with dry grass pattern (for pixel noise), side textures not updated here though.

**Comment by tobyplowy** [comment]
I'm not sure about the sand overlay (i preferred the Orange grass texture)

**Comment by tobyplowy** [comment]
Also another idea maybe you could make dead bushes spawn instead of grass (plant Not node)

**Comment by tobyplowy** [comment]
also the Orange that's not the grass that's actually flowers see [this](http://polarfield.wpengine.netdna-cdn.com/wp-content/uploads/2009/09/toolik-013.jpg) also [this](http://www.soulofthegarden.com/Images/ColoradoTrailRidgeTundra.jpg) is a nice screenshot to get the feel

**Comment by paramat** [comment]
Yes i'm not happy with this latest attempt.

**Comment by Fixer-007** [comment]
Maybe add a bit more colour variation, like here: http://polarfield.wpengine.netdna-cdn.com/wp-content/uploads/2009/09/toolik-013.jpg

**Comment by paramat** [comment]
What to do for tundra surface is difficult to decide, this is very WIP.

**Comment by sofar** [comment]
@paramat can we place "depressions" in schematics that "carve" down into the landscape? That way, we could place schematic based "pingos" or "pingo craters". It's not a plant deco per se.

Another idea would be to place gravel or clay blobs at the surface to vary the landscape.

Side idea: sink holes in tropical biomes?

**Comment by tobyplowy** [comment]
@sofar I really do like the sinkhole idea

**Comment by paramat** [comment]
Depressions can be done with air schematics but they will not have the correct surface since they're placed after biome nodes.

**Comment by paramat** [comment]
I might try dark green moss.

**Comment by tobyplowy** [comment]
The base game grass should just be dark and the moss should be light green

**Comment by Fixer-007** [comment]
I really miss lakes on non-0 height.

**Comment by C1ffisme** [comment]
Maybe the moss should look more like the moss on cobblestone, rather than grass? You could make it look as if vines are crawling on the dirt.

**Comment by paramat** [comment]
screenshot_20160901_002258

I prefer this to the brown attempt above. Patchy snow is placed as a decoration.

**Comment by Fixer-007** [comment]
>Maybe the moss should look more like the moss on cobblestone, rather than grass?

or maybe just use default "cobble with moss"?

**Comment by paramat** [comment]
The moss texture can be improved later, this is good enough for now so i'll update the PR.

**Comment by tobyplowy** [comment]
@paramat I prefer the brown grass (it looks more like the actual biome) i also really like @C1ffisme 's idea about vines on the dirt. It could be patches not just the whole biome (the grass really needs to be Brown)

**Comment by paramat** [comment]
Note these new nodes will not be in use for a while, as to avoid disruption i'm considering making the big biome update all at once, before 0.4.15. So there's time to improve the moss texture.

**Comment by paramat** [comment]
I'm making some more attempts at moss, for something a little more subtle than that screenshot.

**Comment by paramat** [comment]
screenshot_20160901_043553

**Comment by Fixer-007** [comment]
^^ texture is very repetitive and feels downscaled a lot, don't like ti

**Comment by tobyplowy** [comment]
@Fixer-007 yeah it's pretty bad but he said it's a temporary texture.

**Comment by tobyplowy** [comment]
@paramat will this big biome update include the corals?

**Comment by paramat** [comment]
Well, you know there is a reason for the repetition :}
The surface node can't be patchy because 'node top' is continuous.

Corals too yes probably.

**Comment by tobyplowy** [comment]
@paramat i made a moss texture its not perfect but it looks like moss (bdw it uses default_grass.png as bace)
wool_green

**Comment by tobyplowy** [comment]
@paramat also the bace grass is to briht

i propose a new bace grass texture
naamloos
default_grass_side
default_grass

**Comment by Wayward1** [comment]
@tobyplowy That proposal would be best in a new issue, as it is off topic for this one.

**Comment by paramat** [comment]
Thanks for the moss submission, but i think it looks too much like grass, i'm trying to create the effect of smooth, soft, rolling mounds of moss.

**Comment by tobyplowy** [comment]
@paramat that's the point that it tiles with grass :D you know what I think you should use the grass that we have now as moss because it's really bright and moss is Bright, and just change the grass color to be a little bit darker

**Comment by paramat** [comment]
The idea with moss is to make it visually different from grass, otherwise tundra will just look like grassland, which is exactly what i'm trying to avoid.

**Comment by paramat** [comment]
Hm so i'm not sure about moss everywhere, it's a bit much. I feel like rethinking what sort of surface we use in tundra.

**Comment by paramat** [comment]
I'm thinking moss can be patchy, as slabs placed as decorations.

For surface, 'permafrost' just means frozen ground, that could be gravel or soil, we could even have bare stone.

**Comment by tobyplowy** [comment]
@paramat yeah I think it would be better if this is a actual object you can please like the snow in the tundra biomes ( this not only looks better it would also be better for Building reasons) By the way I know there Not called objects but they are not a full block of Snow

**Comment by rubenwardy** [comment]
I'm quite positive about adding more cold biomes such as tundra

**Comment by tobyplowy** [comment]
@rubenwardy don't we have a tundra already?

**Comment by paramat** [comment]
Icesheet is tundra in a way too, so we have 2, one of my biome system suggestions has 3 tundras https://github.com/minetest/minetest_game/pull/1022#issuecomment-242594227

I'm closing this as it's easier to start again with something that doesn't touch grass spread ABM.

**Comment by paramat** [comment]
#2073 merged.

**Pull request closed without merging**
