### PR TITLE
Add corner stairs part3

### PR DESCRIPTION
**Pull request by TumeniNodes**
I have now hopefully fixed the requested changes from the last PR.

I also removed the new nodes from the last PR, and if this gets through ok, will open another PR to add those stair sets

### CODE REVIEW

**Comment by TumeniNodes** [comment]
OMG, I swear I must be completely braindead.
I deleted the original stairs init.lua prior to uploading my changes.
I am really sorry about this... round 4?

**Comment by TumeniNodes** [comment]
closing, because I am an idiot.
stay tuned, more open/close abuse to come.

**Comment by SmallJoker** [comment]
It would be possible to correct this mistake by moving the file to its right place and using a few git commands to cover this mistake behind a new commit history. However, only works as long the repository and branch exists.

**Comment by TumeniNodes** [comment]
Im really sorry to be such a pia with these mistakes. I am completely
novice with all this, and trying to read up on info.
I promise I wont be doing any PRs ever after this one, I have no business
doing it. I just want to see this one through

**Pull request closed without merging**
