### PR TITLE
Fencegate: prevent y-fighting at top.

### PR DESCRIPTION
**Pull request by sofar**
We raise the height of the fencegate node by 0.0001 to make the
fencegate post stop fighting with node blocks. This makes the
gate pole appear to be cut through the node, and doesn't leave
a gap when stacking fencegates, which would look odd.

### CODE REVIEW

**Comment by NathanSalapat** [comment]
+1

**Comment by C1ffisme** [comment]
That's a pretty bad bug to have. :+1:

**Comment by Fixer-007** [comment]
:+1:

**Comment by paramat** [comment]
:+1:

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
7c966db4bc90f2e38431084873dc8bafd64d7e90

**Pull request closed without merging**
