### PR TITLE
Doors: Clean up nodedef usage.

### PR DESCRIPTION
**Pull request by sofar**
Allows for more properties to be passed through. Somewhat simplifies
the code as well.

### CODE REVIEW

**Comment by PilzAdam** [comment]
If you want that properties can be passed through, then you should only override the ones that are `nil`.

**Comment by paramat** [comment]
Needed for release?

**Comment by sofar** [comment]
no, this is just a code cleanup for later.

**Comment by sofar** [comment]
This can be merged as-is.

@pilzadam only the most basic things are set, I'm leaving it in the middle a bit since I don't think there will be too many people overriding the basic properties of doors, I was more thinking of mods like mesecons passing through extra nodedef table entries.

**Comment by Ekdohibs** [comment]
@sofar Looks good, however, did you check minetest.registered_nodes to ensure that meshes are not set to the same value, since you share the definition?

**Comment by sofar** [comment]
Confirmed OK. It seems that node registration makes a copy of `nodedef`, so changing `def` is without issues.

**Comment by paramat** [comment]
Approved by sfan5 http://irc.minetest.ru/minetest-dev/2016-06-20#i_4635533

**Comment by paramat** [comment]
3e9afe097c74b0dd32d3983a3de37c66946a42d3

**Comment by t4im** [comment]
For future references @sofar there is no copies being made during registration (that would be way too wasteful as well).

@Ekdohibs was quite right. _a and _b doors are sharing at least their names in the table now.

**Pull request closed without merging**
