### PR TITLE
Textures: Darker, richer dirt texture

### PR DESCRIPTION
**Pull request by paramat**
Derived from a texture by Neuromancer from the Natural Beauty
Texture Pack.
////////////////////////////////////////////////

screenshot_20170227_024232

screenshot_20170227_024302

^ With tone mapping

default_dirt_bn48_cp16_sn20_ind128

Existing texture made darker, more contrast and less saturation to reduce redness caused by the first 2 alterations.
Gimp: brightness -48 contrast +16 saturation -20.

I find the current light brown dirt texture ugly, it's a survivor from the 'grim and depressing' stage of MT dirt and grass textures (0.4.11 to 0.4.13). A darker texture is deliciously rich and fertile and brings contrast to the landscape. Looks lovely against stone grey and grass green, especially on cliffs.

### CODE REVIEW

**Comment by tobyplowy** [comment]
@paramat I think that is way to darck

**Comment by C1ffisme** [comment]
I'm not really sure whether or not I prefer dark, fertile-looking soil or orange retro dirt. (Reminiscent of some of the Sonic the Hedgehog games.) On one hand, the dark soil doesn't seem to fit in with many of the other textures, which seem rather bright. On the other, it's nicer and a bit more realistic than bright orange dirt.

**Comment by numberZero** [comment]
@paramat It looks acceptable by itself but doesn't fit the style, e.g. grass texture looks too smooth now.
Also test both textures with tone mapping enabled, it makes things look way better.

**Comment by DS-Minetest** [comment]
This doesn't fit to the stone texture. Some sort of `stone_with_dirt` node would be needed to make it look acceptable at the border of dirt and stone.

**Comment by paramat** [comment]
We're not going to add a stone-with-dirt, that's not needed with the current texture either.

**Comment by Fixer-007** [comment]
Feels too dark

**Comment by Thomas--S** [comment]
I also think that this is a bit too dark. Maybe an average version between the old one and the new one would be good.

**Comment by numberZero** [comment]
@paramat Actually orange dirt is rather common. I see it often when walking around my town.
The dark, fertile dirt your texture represents is usually covered by grass and other plants. It would be nice to see it when digging, hoeing, maybe in forests, but not in plains and certainly not at cliffs (that’s mapgen problem actually).

P.S. See also https://duckduckgo.com/?q=dirt&iax=1&ia=images

**Comment by paramat** [comment]
I'm not concerned with strict realism, the light brown dirt just looks bad.
Dirt showing on cliffs is just due to mapgen simplicity, it's not easy to solve and doesn't really need to be, it's not a problem.
I will work on a slightly lighter texture in response to the comments.

**Comment by paramat** [comment]
screenshot_20170202_174007

Lighter version.

**Comment by tobyplowy** [comment]
@paramat still a bit dark

**Comment by numberZero** [comment]
Well, this orange dirt is really not the orange dirt I saw near my town...
So, here are several variants: (brighter screenshots are those with tone mapping enabled)
default_dirt_0 №0 (default)
screenshot_20170202_0_tm
screenshot_20170202_0_notm
***
default_dirt_2 №2
screenshot_20170202_2_tm
***
default_dirt_3 №3
screenshot_20170202_3_tm
screenshot_20170202_3_notm
***
default_dirt_4 №4
screenshot_20170202_4_tm
screenshot_20170202_4_notm

**Comment by numberZero** [comment]
Darker textures conflict with green grass, it should look more natural (but not grayish as without tone mapping). Also @paramat, your texture looks very nice under dry grass) But sadly it becomes too dark with tone mapping, which is necessary for nice look of everything.

**Comment by octacian** [comment]
IMO, this looks really nice.

:+1:

**Comment by C1ffisme** [comment]
@numberZero I kind-of like the slightly desaturated dirt.

**Comment by DS-Minetest** [comment]
I thought, the change shouldn't be too drastical:
default_dirt

without tone mapping:
with current texture:
screenshot_20170203_154716
with this texture:
screenshot_20170203_155208

with tone mapping:
with current texture:
screenshot_20170203_155723
with this texture:
screenshot_20170203_155609

**Comment by paramat** [comment]
I'll test with tone mapping.
The contrast with grass is what looks so good to me.

**Comment by Zeno-** [comment]
I'm sorry, but I think this new texture looks like a deliciously rich cow turd.

**Comment by paramat** [comment]
Sorry i don't like any of the submissions above, either too light or too saturated or too desaturated.

I've updated the PR with the lighter version, tone mappng screenshot in the first post. No longer WIP.

**Comment by paramat** [comment]
Hmm this will be a difficult one, like grass, more experimentation needed. The darkness is unpopular with some.

**Pull request closed without merging**
