### PR TITLE
Settings: Use new settings object

### PR DESCRIPTION
**Pull request by paramat**
Update all setting calls to the new 'settings' object. This stops deprecation messages.

By the way @ShadowNinja where do the deprecation messages appear? I cannot find them anywhere, not even in verbose debug.txt. This makes this PR difficut to test as i don't know if i updated all settings.

### CODE REVIEW

**Comment by ShadowNinja** [comment]
@paramat: The "deprecated" log level is special.  There's a setting (`deprecated_lua_api_handling`) to determine what it does.  By default it's ignored, but it can also log a warning with a backtrace, or even issue a fatal error.

**Comment by paramat** [comment]
Ok tested with deprecation logging enabled, seems i got them all.

**Comment by paramat** [comment]
Used grep and discovered i had missed one in bones.

**Comment by paramat** [comment]
eec1c5a03bae544e5ac149d5affa2a1b5e229e31

**Pull request closed without merging**
