### PR TITLE
Carts: switching the drivers's yaw to the cart's

### PR DESCRIPTION
**Pull request by yquemener**
This is a proposal to make the player's look direction follow the direction of the cart when the cart turns. That makes roller coasters circuits much more enjoyable and easier to follow.

### CODE REVIEW

**Comment by SmallJoker** [comment]
There's a reason why it does not exist yet:
  * The engine should turn the plyaer's view if the model is rotated
  * With camera smoothing (cinematic mode), it might rotate into the wrong direction which makes it look very unpleasant.

**Comment by paramat** [comment]
:-1: sorry.
* A player will often want to be looking around at things of interest and not in the direction of travel.
* When going through very common 'dogleg' sections (for example a quick right-left-right), the player will want to stay looking in the general direction of travel instead of having their view pointlessly rapidly changed.
* Rapid view changes when travelling through winding or diagonal sections are uncomfortable and disorientating.
* The player doesn't have much to do, so moving the view around is not a problem and keeps the player active.

> The engine should turn the player's view if the model is rotated

I disagree for the reasons above, if so, only as an option.

**Comment by DS-Minetest** [comment]
The player view shouldn't always be rotated to the front. The rotation should be added to the head rotation.
This probably isn't too difficult. Just take the old cart yaw and the old player look_horizontal and calculate with these value an offset.

**Comment by SmallJoker** [comment]
@DS-Minetest That's the idea, but will require a new network packet so that you can compensate the lag. If you'd use `set_yaw(get_yaw() + math.pi / 2)` for the 90° curve, it would overwrite the player's view change for the timespan where the packet is sent.

**Comment by yquemener** [comment]
I guess it is a matter of taste. I have found the "add the current rotation" solution to be more disorienting than anything. I can see how you may want to look at another thing though. How about a mode where by default the front view is used but if the player has moved the view enough, say of 30 degrees or more, then the view is not change by the carts' turns?

**Comment by DS-Minetest** [comment]
This change can of course be very inconvenient as stated above before. If something like this gets added anyway, there should be something like hold sneak to not be shaken around.

**Comment by paramat** [comment]
> The rotation should be added to the head rotation.

That's just as bad and has the same problems.

A new network packet is not justified.

> How about a mode where by default the front view is used but if the player has moved the view enough, say of 30 degrees or more, then the view is not change by the carts' turns?

That doesn't solve the problems and is more complex.

**Comment by sorcerykid** [comment]
I'm of the opinion that if the player's position is already being overridden by an attachment, then there should be an option to override the player's yaw as well. It only makes sense. I'm afraid I don't agree with the argument that it's disorienting because merely being attached to an object that is moving at high velocity up, down, and around is already extremely disorienting by itself.

In real life, when you are riding in a vehicle (say a bike or a car) and you turn your head slightly 20 degrees, then your head will maintain that yaw relative to the the vehicle, not the world,

**Comment by DS-Minetest** [comment]
>I'm of the opinion that if the player's position is already being overridden by an attachment, then there should be an option to override the player's yaw as well.

Attachment position updating is done client-side.

**Comment by sorcerykid** [comment]
Exactly, that is why I imagine it would be very easy to implement since the client already tracks the yaw of the parent object at all times. There is no client-server interaction even required.

**Comment by DS-Minetest** [comment]
Yes, but that would need an engine change.

**Comment by sorcerykid** [comment]
Indeed, hopefully @yquemener will consider opening an issue on https://github.com/minetest/minetest if this feature is still wanted.

**Comment by paramat** [comment]
> I'm of the opinion that if the player's position is already being overridden by an attachment, then there should be an option to override the player's yaw as well.

That's possibly useful and yes an engine issue.

**Comment by rubenwardy** [comment]
I support attached objects rotating with their parent

**Comment by DS-Minetest** [comment]
> I support attached objects rotating with their parent

Afaik, attached objects already rotate with their parents, however the player sight yaw doesn't change.

**Comment by paramat** [comment]
I'm fine with rotating view with parent as an option, default off.

**Comment by rubenwardy** [comment]
I think it should default to on, because that makes sense

**Comment by paramat** [comment]
Off seems more usable due to the reasons i explained above.
Also because that is current behaviour. If it defaults to on that will break existing behaviour, which is actually wanted by many mods. If a vehicle mod wants view turning with the vehicle they will have already coded that, as i have in my mesecar mod.

**Pull request closed without merging**
