### PR TITLE
Farming: Override dirt_with_dry_grass to enable cultivation

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160406_230535

Addresses #1018 
When i added dirt with dry grass i didn't edit farming to enable cultivation.
(I considered making dirt with snow cultivable too but these nodes occur in freezing biomes like tundra).
Tested, adding own approval.

### CODE REVIEW

**Comment by Napiophelios** [comment]
shouldn't dirt with dry grass that close to water turn to normal grass?

**Comment by NathanSalapat** [comment]
I agree with Napiophelios, dry grass near water should turn into normal grass if we're going to allow plants to be planted on it.

**Comment by MT-Modder** [comment]
@Napiophelios 
@NathanSalapat 
Kinda related: https://github.com/minetest/minetest_game/pull/999

**Comment by paramat** [comment]
Valid point, but i'm not sure it's worth another ABM.

**Comment by MT-Modder** [comment]
Even if it's optimized as much as possible?

**Comment by Napiophelios** [comment]
<Valid point, but i'm not sure it's worth another ABM.>

Yeah, I can't argue with that. Would still be a nice effect :)

**Comment by 0-afflatus** [comment]
I think it would be more than a nice effect. It's good gameplay and logical that a little extra effort is required to farm dirt_with_dry_grass - irrigate first, then have to wait for the nodes to convert to dirt_with_grass before you can hoe. The point to consider is whether that sort of gameplay is too complex / realistic for MTG.

**Comment by paramat** [comment]
The hoed dirt turning to wet soil is what makes it cultivable. no need to wait for a change to dirt-with-grass. These ideas can be in another PR.

**Comment by sofar** [comment]
Excellent change, I would have made this PR myself.

Maybe even add this for dirt_with_snow?

**Comment by paramat** [comment]
I considered, but is growing crops in sub-zero tundra and taiga realistic? The ground would often be frozen. However the player could always dig to get dirt and then hoe that, i guess that would simulate breaking up the frozen dirt.

**Comment by sofar** [comment]
Fine with me, Let's just get the patch as-is merged then.

**Comment by paramat** [comment]
be05441e77b2e17f2c30b877847c7498338e1e1a

**Pull request closed without merging**
