### PR TITLE
Remove type="shapeless" from single-item recipes

### PR DESCRIPTION
**Pull request by pauloue**

### CODE REVIEW

**Comment by pauloue** [comment]
Forgot to add extra braces, see force-push.

Reason for this is to prevent the recipes being shown as shapeless in a craft guide.

**Comment by pauloue** [comment]
It wasn't intended to improve performance. It just unnecessary to mark a single-item recipe as shapeless and it might be confusing if it's displayed as shapeless in a craft guide since there's no way it could be shaped.

**Comment by paramat** [comment]
So it's now tested?

**Comment by pauloue** [comment]
Yes, it's tested.

**Pull request merged**
