### PR TITLE
Add drowning to sand and gravel

### PR DESCRIPTION
**Pull request by MT-Modder**
Discussion can be found here: #473

### CODE REVIEW

**Comment by PilzAdam** [comment]
So you get damage when placing some nodes inside yourself with noclip enabled? Seems inconsistent to me.

**Comment by kilbith** [comment]
:-1: I'm against, sorry.

1. Totally unrealistic : you can normally walk over sand or gravel.
2. Bad for gameplay : walking on desert biome would be annoying and gravel is often used as garden path.

If you want drowning sand, add it exclusively under the form of quicksand and generate it in deserts as ore blobs (@paramat is best qualified for that).

**Comment by MT-Modder** [comment]
No it pretty much only happens when a bunch falls on you. Like when you're mining. IDK seemed to be a wanted feature by some players. I could care less :smile:. I definitely see both your points.

**Comment by paramat** [comment]
> happens when a bunch falls on you

Seems a good enough reason to add. Mapgen often creates large unstable masses of sand, this adds some challenge to digging your way out within 20 secinds.

**Comment by PilzAdam** [comment]
I'm not sure if you understood my point right.

It does not only happen when sand falls on you. You can legitimately place any node you want inside yourself (with noclip enabled; no flying needed). This PR would result in some random nodes dealing damage to you then, while it's perfectly fine to stand inside of any other node in the game. This is rather inconsistent.

So either add suffocation damage to all solid nodes (which would basically make flying with noclip and damage enabled useless (like probably many moderators on servers do)) or do not add this at all.

:-1: from me.

**Comment by tenplus1** [comment]
PlayerPlus mod adds suffocation inside of default: solid nodes.
https://github.com/tenplus1/playerplus

**Comment by paramat** [comment]
I see, i'm neutral on this now.

**Comment by paramat** [comment]
:-1:

**Comment by sfan5** [comment]
as already said causes a problem with noclip :-1:

**Comment by paramat** [comment]
Closing due to a :-1: majority.

**Pull request closed without merging**
