### PR TITLE
Allow for shift+clicking inventory from bones

### PR DESCRIPTION
**Pull request by Rui914**
#930

### CODE REVIEW

**Comment by Fixer-007** [comment]
Will be nice to have it (taking out individual items much faster, if I don't take entire bone).

**Comment by PilzAdam** [comment]
:+1: (if it works correctly).

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
8fdcfea9f9a7efa753787b83967b921ac595cc9b

**Pull request closed without merging**
