### PR TITLE
Revert "shorter and better abm's"

### PR DESCRIPTION
**Pull request by DS-Minetest**
See #1761 for details.

### CODE REVIEW

**Comment by paramat** [comment]
The other 4 commits should be removed or removed on merge.

**Comment by DS-Minetest** [comment]
I used the `Revert` button of github. The other commits were done in the same sequence, they got "reverted" again. https://github.com/minetest/minetest_game/commits/master Most likely github looked for diffs at the same place and didn't find anything but still added the commits, empty.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
626cd8e9c7c2a5d5c907a12abbaa6066b6d5f2ff

**Pull request closed without merging**
