### PR TITLE
Make some nodes floodable, to work with minetest commit b3e3048d3ee6e…

### PR DESCRIPTION
**Pull request by cyisfor**
… https://github.com/minetest/minetest/pull/4130/commits/b3e3048d3ee6e20991561741fd26c0a4afa460bd

Couldn't do this before, since they'd just get replaced with air. But with the commit to the main engine, they can "safely" be set floodable and all it will do is drop all your torches plunging you into darkness. How fun!

### CODE REVIEW

**Comment by Thomas--S** [comment]
I suggest to make this configurable. Your suggestion can help griefers.

**Comment by paramat** [comment]
:-1: I oppose plants or crops beng dropped by water, will link to discussion when i find it.

**Comment by C1ffisme** [comment]
Why is sandstone set to `crumbly = 2`?

**Comment by paramat** [comment]
Yes that should be a seperate PR.

**Comment by paramat** [comment]
As discussed in #829 we prefer an on_flood callback. That commit is the place for that work, so closing.

**Pull request closed without merging**
