### PR TITLE
Adding Russian translation for mtg_craftguide

### PR DESCRIPTION
**Pull request by RichardTry**
Btw, shouldn't things like "Search", "Reset", "Previous page" and "Next page" take translation from sfinv?

### CODE REVIEW

**Comment by sfan5** [comment]
Translations are generally not shared between mods even if it would make sense in this case.

**Comment by Wuzzy2** [comment]
@quarthex: Rebase needed. Also, the translation for "G" is missing. The letter G is used in the craft guide as a symbol on items that stand for group crafts. You can see it e.g. for the furnace craft. The "G" stands for "group". Feel free to use the appropriate letter in Russian (for example, the first letter of whatever "group" translates to in Russian).

**Comment by Wuzzy2** [comment]
Oh, and a release is planned for July 31, 2022.

**Comment by quarthex** [comment]
@RichardTry is the right recipient of your message, I guess.

**Comment by Wuzzy2** [comment]
Yes, sorry. Also, look out for #2972, it's still pending.

**Comment by RichardTry** [comment]
Why current bad mtg_craftguide translation was merged instead of my correct? :D

**Comment by RichardTry** [comment]
> @quarthex: Rebase needed. Also, the translation for "G" is missing. The letter G is used in the craft guide as a symbol on items that stand for group crafts. You can see it e.g. for the furnace craft. The "G" stands for "group". Feel free to use the appropriate letter in Russian (for example, the first letter of whatever "group" translates to in Russian).

What do you mean by "rebase"? Template did not changed.

**Comment by appgurueu** [comment]
Rebasing is a way to resolve merge conflicts. You must resolve the merge conflicts to make your PR mergeable. 
Bildschirmfoto von 2022-07-29 15-00-41; resolving the conflicts through a merge in GH's web editor probably suffices.

**Review by appgurueu — APPROVED** [review]
A certain proprietary online translation service says this is fine.

**Pull request merged**
