### PR TITLE
Metal sounds

### PR DESCRIPTION
**Pull request by sofar**
2 commits:

- add default metal node sounds, including
  - digging sound
  - dug sound
  - footstep sound
  - place node sound

- make all metal nodes use the default metal sounds

### CODE REVIEW

**Comment by sofar** [comment]
I intend to use this in the #1318 PR, hence a separate PR
- fairly trivial
- will consider alternative sounds (I'm not entirely happy with all of them yet)
- applied to steel door, trapdoor, steel/copper/bronze blocks and steel ladder and sign

**Comment by sofar** [comment]
- sound volume (gain) most likely will need adjustment (it's probably too loud?)

**Comment by paramat** [comment]
The footstep ones don't seem right somehow. Others are good.

**Comment by paramat** [comment]
I'll try them in-game.

**Comment by paramat** [comment]
I think the 'dig' sound should be called 'default_dig_metal' as 'break' suggests 'dug'. For example 'break glass' is the final shattering sound.

**Comment by paramat** [comment]
Your 'break metal' sound has an unnecessary '.1' in the name.

**Comment by sofar** [comment]
Yes, I really wanted to find another alternative sound sample (have 2-3 as much as possible).

**Comment by paramat** [comment]
Testing in-game. The footsteps, which i were at first unsure of, are ok at low volume.
The only one i dislike is the dug metal sound, it has a piercing ring to it which i find hard on the ears.

**Comment by paramat** [comment]
Addresses #887

**Comment by Fixer-007** [comment]
Those are somewhat strange to me:
default_break_metal.1.ogg 
default_metal_footstep.1.ogg
default_metal_footstep.2.ogg
default_place_node_metal.1.ogg
default_place_node_metal.2.ogg

**Comment by sofar** [comment]
Yes, these are very crude sound samples. They're mostly just placeholders until someone proposes or finds better sound samples. I wanted to make sure that (1) we'd get a full sound scape implemented for metal nodes (so cover footstep, dig/dug and place) and (2) make sure to use it in all the nodes.

If you have good and usable metal sounds you'd like to propose, please link in this thread.

**Comment by Fixer-007** [comment]
Hmmmmmmm, maybe freesounds has something useful

**Comment by JurajVajda** [comment]
So we are going to have iron, steel and metal now..? :) or is the metal sounds also for nodes like gold, copper, bronze...?

**Comment by Fixer-007** [comment]
How about that ones?
https://www.freesound.org/people/jorickhoofd/sounds/160045/
https://www.freesound.org/people/xMETALCORERx/sounds/347779/

more search here: https://www.freesound.org/search/?q=steel&f=&s=score+desc&advanced=0&g=1

**Comment by paramat** [comment]
Sounds tend to be difficult to agree on, so i'm trying to not be too fussy. Many of our sounds are humorously crude so let's not be too perfectionist. I might look for an alternative dug sound.

**Comment by sofar** [comment]
@JurajVajda iron is a metal, steel is a metal, gold is a metal, bronze is a metal....

**Comment by paramat** [comment]
Here's a possible metal break sound https://www.freesound.org/people/JoelAudio/sounds/135465/

**Comment by sofar** [comment]
Entirely redone - updated licenses and origin, used many of the suggestions above.

This is fairly decent now! please try these in-game and check volume levels. I think it's all OK now.

**Comment by paramat** [comment]
Both dug sounds are too loud. Others seem okay in volume.

**Comment by sofar** [comment]
Lowered dug sounds to `gain = 0.5` down from `1.0`.

**Comment by paramat** [comment]
:+1:

**Comment by Fixer-007** [comment]
place node sounds volume is a bit high? at least I get impression while playing with your carts

**Comment by Fixer-007** [comment]
+ no metal sounds when walking on steel slab/stair

**Comment by sofar** [comment]
I'll see why slab/stair for metal nodes isn't getting these sounds, I thought it would be inherited.

**Comment by sofar** [comment]
Fixed metal sounds for stair/slabs for (copper/steel/bronze/gold) block derived versions.

**Comment by paramat** [comment]
:+1:

**Comment by Fixer-007** [comment]
Seems good now. :+1:

**Comment by paramat** [comment]
fa9a34554b96d2223cce2a9a53991ebe3c5bedc0
fbac9be51cb8acf23b9c1983d2f21dca87209306

**Pull request closed without merging**
