### PR TITLE
Add new, longer 'default_grass_side' texture

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20190715_235113

^ PR texture has 3/4 side coverage

Follow-up PR to update the grass side texture to match the new top texture. The new top texture makes a much better side texture, and is of course more visually consistent.
I'm taking this chance to again propose that grass covers more of the side, for a greener look to hills.
So this PR has a side texture that covers 3/4 of the side, instead of the previous 1/2.

screenshot_20190715_235305

^ 1/2 side coverage texture for comparison. I think this looks worse.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
YES! I use the [lessdirt texturepack](https://content.minetest.net/packages/DrFrankenstone/lessdirt/) and IMO it looks a lot better. +1

**Comment by TumeniNodes** [comment]
I _somewhat_ recall the length of grass_sides being changed.
I prefer the longer sides as well (though I still love the original texture for sides better) but, I'm giving this a thumbs up. (even though I mostly prefer full grass sides, but they become a problem when they go full dirt in darkness)

**Comment by paramat** [comment]
@Ezhh do you prefer 1/2 or 3/4 side coverage?

**Comment by Ezhh** [comment]
No objections to longer sides. I quite like it. :)

:+1:

**Pull request merged**
