### PR TITLE
Default: New 'dirt with grass' textures

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160426_142233v7

v ^ Proposed texture (variation vox7)

default_grass_vox7_ind128

screenshot_20160428_175554

Our current texture has an unnecessary alpha channel so needs updating for release, i'll do that in this PR whether or not the appearence is changed.

I searched through all subgames and texture packs for good grass textures, there were surprisingly few good ones, the best was Casimir's Voxelgarden texture, but this has dark diagonal lines.
I used Gimp's 'dodge and burn' tool to very subtly brighten the dark lines.
I then colourised the texture to match the hue, saturation and brightness of the current texture.
The side texture is almost identical in structure (1 pixel added).

screenshot_20160419_055636

^ Current texture

screenshot_20160419_075909

^ Original Voxelgarden texture

### CODE REVIEW

**Comment by paramat** [comment]
Seems unpopular, will make it darker.

**Comment by MoNTE48** [comment]
you like to change the texture of the grass! :)

**Comment by C1ffisme** [comment]
@MoNTE48 The texture never seems to be good enough, so we keep on changing it and trying again and again.

**Comment by MoNTE48** [comment]
that's why I've been using the services of professional designers or free texture packs for minecr**t. Offtop.

**Comment by paramat** [comment]
screenshot_20160418_073734

Voxelgarden texture modified to remove dark lines.

**Comment by paramat** [comment]
This can be merged during freeze.

Updated, now working on the Voxelgarden texture, subtly editing to remove the dark lines.

**Comment by Fixer-007** [comment]
I like current texture as it is.

**Comment by C1ffisme** [comment]
I'm starting to wonder if we should have just never changed the texture from the 0.4.9 one. I don't think we ever had any discussions about the texture before 0.4.10. (At least, after 0.4.0)

**Comment by paramat** [comment]
That has occured to me in desperate moments.
Here's the long running 0.4.dev texture that replaced the first (pre-github) grass texture:

screenshot_20160420_105455

And later this was edited to have more saturation in Spring 2014 and was used until Autumn 2014:

screenshot_20160420_110245

Not so obvious here but both these have a strong grid appearence.

**Comment by paramat** [comment]
screenshot_20160421_114229

^ 0.4.10 texture

v Same texture with Gimp's 'make seamless' applied.

screenshot_20160421_114305

screenshot_20160421_114350

**Comment by C1ffisme** [comment]
@paramat I might make it a little less flashy, it's a bit painful on the eyes because of the contrast.

**Comment by Fixer-007** [comment]
Nah. Just leave default texture alone :)

**Comment by paramat** [comment]
I'm not proposing the 0.4.10 texture, just thought it interesting to show it here. It is hard on the eyes.

**Comment by everamzah** [comment]
Be bold, @paramat

**Comment by Jordach** [comment]
There's a much better solution - and it uses GIMP.

Get a base layer of grass green.

Add a new layer, set it's mode to overlay.

Using filters, go use RGB noise, and link RGB channels. (Don't forget to
set alpha to 0.3!)

Use the filter a few times for the best results.

Using gaussian blur - set it's method to 1px, and use RLE. Set layer
opacity to a lower level. You'll understand why.

Add another layer. It's mode should also be overlay.

Use the RGB noise again - same settings, just not as many repeats.

This part is optional. From the filters menu, invoke Tilable Blur - and set
it to 1px. Do a similar thing for the grass side.

This method has reasonably nice looking grass, without the problems of
having grid like repeats. With some layer opacity tweaking, it can look
fantastic.

**Comment by tobyplowy** [comment]
I think the current grass texture looks better :/

**Comment by paramat** [comment]
screenshot_20160426_135136v6

^ Variation 'vox6' with a little more contrast. Might go with this one.

**Comment by paramat** [comment]
screenshot_20160426_142233v7

^ Version 'vox7', darker and more contrast

v Current

screenshot_20160419_055636

**Comment by tobyplowy** [comment]
This one looks okay :smile: https://cloud.githubusercontent.com/assets/3686677/14822443/aa6a886c-0bc6-11e6-9fa1-9fa0a67fba23.png

**Comment by paramat** [comment]
That's the one i'm going to submit :)

**Comment by paramat** [comment]
Updated with new proposal.

**Comment by Ryan-Nolan** [comment]
The following suggestion has probably already been suggested in the past and it kinda would mean some core changes but what about this:

make it so that a node could be provided with a texture that looks like the ones you would use for animated textures.... but instead of animating them it would pick at random one of the faces on the 1 texture.

this would then help to maybe get rid of repetivines of some of the large terrains and large surface areas...

just an idea?

**Comment by paramat** [comment]
Yes we have a feature request for that, clever idea https://github.com/minetest/minetest/issues/2746

**Comment by paramat** [comment]
Approved by Ekdohibs / nore http://irc.minetest.ru/minetest-dev/2016-04-28#i_4596873

**Comment by paramat** [comment]
fafbe2c26850b78e129767f7d81704af19e766a2

**Pull request closed without merging**
