### PR TITLE
Use mod.conf, remove depends.txt. Move loot registration to individual mods

### LINKED ISSUE #2340: Use mod.conf and modpack.conf; remove corresponding deprecated files
I hope this isn't a duplicate issue, but I don't see `mod.conf` or `modpack.conf` being used in MTG. Being the official game bundled with Minetest, shouldn't this have been the first to adopt the new, official approach? Is there a specific reason for not doing this yet?

### PR DESCRIPTION
**Pull request by misterskullz**
Fixes #2340 and #2334 

Added all of the mod.conf files, moved dungeon loot registration from dungeon_loot to respective mods (except for default's which dungeon_loot depends on).

### CODE REVIEW

**Comment by paramat** [comment]
Are the depends.txt files needed? If not it's best to remove them.

**Comment by misterskullz** [comment]
Stale depends.txt removed.

**Comment by HybridDog** [comment]
I doubt that the nil check in after works. clicker is a local variable because it's an argument of the on_rightclick function. As far as I know, there's nothing which sets it to nil at any point in time and if a method of clicker is invoked after the player which clicker points to disappears, minetest behaves undefined, am I wrong?

**Comment by sfan5** [comment]
There's lots of unneeded commits in your PR, also please don't fix two unrelated issues in a single pull request.

**Comment by paramat** [comment]
The mod.conf change is big so this is best split into 2 separate PRs.

**Comment by paramat** [comment]
@misterskullz

**Comment by paramat** [comment]
No response.

**Pull request closed without merging**
