### PR TITLE
Default: Add water footstep sounds

### PR DESCRIPTION
**Pull request by paramat**
New version of #901 with new sounds.
As in sofar's original, 3 sounds of 2s long plus 1 silent sound to break up the repetition.
Low volume to not become irritating, sound level may need fine tuning.
No dig, dug or place sounds yet, those will need a different sound sample.

### CODE REVIEW

**Comment by Fixer-007** [comment]
Those sounds sound nice to me.

**Comment by paramat** [comment]
Sounds might be improved WIP.

**Comment by paramat** [comment]
Improved 1 of the sounds. Added sound credits.

**Comment by paramat** [comment]
Rebased.

**Comment by sofar** [comment]
:+1:

**Comment by paramat** [comment]
Using headphones i raised the gain to 0.2 to balance it against other sounds.

**Comment by paramat** [comment]
ec95f470215a5547d62aa7f4d23c9a19a47d2119

**Pull request closed without merging**
