### PR TITLE
Change the look of some tool textures

### PR DESCRIPTION
**Pull request by HybridDog**
my textures have a smaller file size

### CODE REVIEW

**Comment by C1ffisme** [comment]
But, they are all the old textures! I like the new ones!

**Comment by HybridDog** [comment]
I thought a combination of both would be good to have more variety.

**Comment by BlockMen** [comment]
Except some textures or minor pixels at some its reverting the tool textures to the old. The diamond tools are not acceptable at all.

**Comment by C1ffisme** [comment]
Yeah, the diamond ones are too BRIGHT. They don't fit the theme of the diamond texture.

**Comment by BlockMen** [comment]
Closing since it won't be added. Second vote on closing: f86ac2fdffba76621935e2ea62038107f5269daf

**Comment by HybridDog** [comment]
ok, sorry

**Pull request closed without merging**
