### PR TITLE
New cobblestone/mossycobblestone and furnace textures 

### PR DESCRIPTION
**Pull request by tobyplowy**
i didn't like the current cobblestone texture so i made a new one
(NOTE)i hope it looks good i did my best to mimic the minetest style 
default_mossycobble
default_cobble
default_desert_cobble

### CODE REVIEW

**Comment by tobyplowy** [comment]
@asl97 thanks for the help I really appreciate it :)

**Comment by tobyplowy** [comment]
i also made a new furnace texture.
default_furnace_front_active
default_furnace_side
default_furnace_top
default_furnace_bottom
default_furnace_front

**Comment by asl97** [comment]
@tobyplowy personally, I would split the changes into two pull request but since you already change the title, I will just add it into this pull request for you. (since it is on my repo)

also, I don't really like the new furnace top, I prefer the old top.
____
disclaimer: I don't endorse this pull request.

**Comment by tobyplowy** [comment]
@asl97 yes I also prefer the old top texture but i made it Just Too Matsh the rest of the design What do you think of the new furnace front and side? Its to fix the old cobblestone texture on the furnace

**Comment by ShadowNinja** [comment]
I think the desert cobble texture looks better, I'm not sure about the others.

**Comment by tobyplowy** [comment]
@ShadowNinja thank you i apreciate the feedback ;)

**Comment by sofar** [comment]
I'd like it if the desert cobble is more of a colorized version of the normal cobble, that is for sure an improvement. I'm not saying these are bad textures, but I'm not a fan yet. The glow effect is actually pretty neat, though.

**Comment by tobyplowy** [comment]
@sofar thanks ;) also What do you mean by (more of a colorized version) More colorized like red or more like Orange?

**Comment by sofar** [comment]
Colorizing is the whole image operation where you change the color values, but not the brightness of pixels (all at once). It's a gimp filter, for instance.

**Comment by tobyplowy** [comment]
@sofar I will take a look at it (Bdw i use GIMP)

**Comment by tobyplowy** [comment]
@sofar is this good?
default_desert_cobble
red stone

**Comment by tobyplowy** [comment]
@asl97 i have inproved the sand stone texture can u pleas update the comit i downt have push access 
default_desert_cobble
red stone

**Comment by tobyplowy** [comment]
@asl97 thanks your the best

**Comment by sofar** [comment]
Yes, that's a nicely fitting set of textures.

**Comment by tobyplowy** [comment]
@sofar thank you :)

**Comment by paramat** [comment]
I prefer the current cobble textures, they are aquarer and have more definition.

**Comment by Napiophelios** [comment]
the patterns in the cobble look way too uniform/round.
And the cobble lines in the furnace texture are too thick.
Love the glow effect though on the furnace.

**Comment by tobyplowy** [comment]
@paramat cobblestone ar rownd this picture is Straight From wikimedia https://upload.wikimedia.org/wikipedia/commons/b/be/Ancient_road_surface.jpg

**Comment by tobyplowy** [comment]
@Napiophelios  cobblestone ar rownd https://upload.wikimedia.org/wikipedia/commons/b/be/Ancient_road_surface.jpg No One seems to like the furnace but they All like the glow effect :) thanks for the feedback

**Comment by tobyplowy** [comment]
@paramat @asl97 so what will happen with this? will it be added or can this issue be closed also if you don't like certain textures you don't have to add all of them ( like the furnace top texture for example)

**Comment by rubenwardy** [comment]
I like how the fire in the new furnace texture looks more ember/coal like (real furnaces wouldn't be flamey but embery afaik). I'm neutral about the new top

**Comment by tobyplowy** [comment]
@rubenwardy thank you i did my best :D

**Comment by paramat** [comment]
Sorry i don't like any of them.
The cobblestone lacks highlights and shadows on each cobble which currently gives a 3D look.
I prefer to keep the current desert stone cobble that has different shaped elements.
As noted above i'm not keen on the simulated 'bloom' around the flame, i think that's best left to shaders.

**Comment by tobyplowy** [comment]
@paramat would you like the furnace more without the glow And the cobblestone with shading? (I Can redo them)

**Comment by paramat** [comment]
No, i prefer the slightly squarer shape of the current cobbles. But don't let me stop you if you want to experiment.

**Comment by paramat** [comment]
Cobble, mossycobble and desert cobble have unnecessary alpha channels.

default_cobble128

default_cobbleold128

default_desert_cobble128

default_desert_cobbleold128

default_mossycobble128

default_mossycobbleold128

^ Submitted above current

Sorry but i feel these are much lower quality.
Same for the furnace, the cobbles packed inside the top square look weird, and i'm not keen on simulated bloom for the fire.

@sofar @rubenwardy ?

**Comment by tobyplowy** [comment]
@paramat (my textures have unnecessary alpha channels) why is that so bad?

**Comment by sfan5** [comment]
:+1: for new furnace texture

not sure about the others

**Comment by Fixer-007** [comment]
i dislike furnace top texture, it looks odd

**Comment by tobyplowy** [comment]
@Fixer-007 you can also only accept the side textures If you don't like the rest

**Comment by paramat** [comment]
The furnace textures are derived from the cobble texture so perhaps cannot be considered separately, and have the same issues, lack of highlights and shadow, lack of definition and too light.
Unnecessary alpha channel is unnecessary data, even if that extra data is small it's just sloppy to leave it in.

**Comment by tobyplowy** [comment]
@paramat sorry for my textures being "sloppy"

**Comment by paramat** [comment]
They're not necessarily sloppy, only if the alpha channels are deliberately left in, you may have left them in by accident, i've done that many times, even quite recently.

**Comment by tobyplowy** [comment]
@paramat again sorry (also I'm probably not going to change the textures because no one seems to want them so there's not really a point)

**Comment by paramat** [comment]
Hey no problem.

**Comment by paramat** [comment]
Ok i'll close this then, but feel free to reopen if you decide to work on this again.

**Comment by tobyplowy** [comment]
@paramat now that I know how to make pr's should I give this another try?

**Comment by paramat** [comment]
You are free to of course, but our current cobblestone textures are very good and not priority for improvement, so any replacements would have to be extremely good.

**Comment by tobyplowy** [comment]
@paramat probably a waste of time so I probably won't be

**Pull request closed without merging**
