### PR TITLE
Add key tool to flip between door states

### PR DESCRIPTION
**Pull request by tenplus1**
doors_key
Added a key tool to flip doors between open, locked and protected.

### CODE REVIEW

**Comment by DonBatman** [comment]
+1 from me even though my +1 don't count.

**Comment by tenplus1** [comment]
Thanks Don, everyone's vote counts :)

**Comment by rubenwardy** [comment]
this potentially conflicts with https://github.com/minetest/minetest_game/pull/1054

**Comment by tenplus1** [comment]
@rubenwardy - so far pull #1054 needs changes to the engine and a rebase to work properly...  The above key tool works already and has backwards compatibility...  It has been in use on Xanadu server since April and players have been easily using it to switch door modes.

**Comment by sofar** [comment]
:-1: since "keys" don't magically create "locks" out of thin air, thereby making it possible to make locked doors without steel ingots.

#1054 only needs a rebase, the code works correctly without the engine change.

**Comment by rubenwardy** [comment]
:-1: due to magic appearance of a lock, and calling it a "key". If this was to be added, it should be a lock fitter or something

**Comment by DonBatman** [comment]
How about making it a locksmithing tool? 
Maybe something like one of these.
[](http://www.myautotoolstore.com/images/v/201306/b/13716123102.jpg)

**Comment by tenplus1** [comment]
Player crafts door, player uses key tool to lock door, or protect door, or open to public again...  Instead of crafting an actual lock it takes a doors mod door and simply allows the player to use the key tool to do the work instead of adding locks...  A lot easier.

**Comment by C1ffisme** [comment]
Maybe if the player crafted the door with a piece of iron, and it had the appearance of a locked door, but would only switch between states if you used a key on it?

**Comment by tobyplowy** [comment]
@tenplus1 This is really cool and all but what is the point of a locked door you can just break the wall around it? (but still cool nonetheless)

**Comment by tenplus1** [comment]
@tobyplowy - any locked door can be subverted by breaking the wall around it, but... the protected doors can be used with a protection mod like (Areas, Protector Redo, Simple Protection) which not only locks the door but protected the walls around it.

**Comment by tenplus1** [comment]
@rubenwardy - needs improvement how ?

**Comment by everamzah** [comment]
https://github.com/minetest/minetest_game/pull/1262#issuecomment-241519040
https://github.com/minetest/minetest_game/pull/1262#issuecomment-241604710
>:-1: due to magic appearance of a lock, and calling it a "key". If this was to be added, it should be a lock fitter or something

**Comment by rubenwardy** [comment]
1. Calling it a key conflicts with the other pr, and isn't accurate

2. Adding a lock without spending a iron ingot

**Comment by tenplus1** [comment]
Wait a second, who says that you need to spend an iron ingot to lock a door that's already been made ?  Steel doors are 6 ingots and definitely don't spend an extra ingot to lock them...  My proposal is to create a door (wood, steel or glass) which can be flipped between 3 different states by using a KEY tool which is already made from 5x steel ingots and has 50 uses.  There is NO magic involved in that process, only the ability of the key tool to lock/protect a door, or open it to the public like you would in real life.

**Comment by sofar** [comment]
I'm counting -2 in approvals atm. You'd need 4 mtg devs to approve to get this approved, which is highly unlikely. @paramat, perhaps you can mark this 'possible close' or 'won't add'?

**Comment by paramat** [comment]
:-1: I seem to remember the author saying this was suggested before and rejected.

**Pull request closed without merging**
