### PR TITLE
Add wild cotton plant in savanna as a source of cotton seeds

### LINKED ISSUE #2551: Add wild cotton as source of agricultural cotton seed
Cotton seed from junglegrass makes no sense (the species are very different) and is based on old Mapgen V6 biomes where the variety of flora was very limited and mostly hardcoded. Wheat seed came from grass so cotton seed was chosen to come from junglegrass.

In the farming mod i suggest adding a 'wild cotton' decoration to the suitable biome(s).
It should have lowish density so that use of the farming mod does not overcrowd decorations, and so that it is not too easy to find.
Cotton from junglegrass may unfortunately still have to happen to avoid disruption.
A benefit is that, assuming junglegrass still drops cotton seed, having these seeds available in multiple biomes makes them a little easier to find.

I can do the work but would like concept approval and support from a core dev first.

### LINKED ISSUE #2679: Wool is too difficult to obtain
When one begins a Minetest game, they must bear the burden of having to do things at night for an inordinate amount of time. The journey to find cotton seeds, which may only be found in a jungle, may be long and burdensome. I suspect that most players would prefer being able to start building comfortably in a more reasonable time frame.

### PR DESCRIPTION
**Pull request by paramat**
Junglegrass is unchanged as a source of cotton seeds for now, but
probably should be removed as a source in future, as players get
used to the new source.
///////////////////////////////////

screenshot_20200306_205200

Closes #2551
Closes #2679 

Small patches of wild cotton plant appear in savanna, each patch separated by roughly 200 nodes. Each wild cotton plant drops 1 seed item, just like junglegrass has a chance of doing.
Seed dropping behaviour of junglegrass is unchanged, for now. Maybe that could be removed in future.
Adds some welcome variation to savanna.
Also add missing license section for CC BY-SA 3.0 and add Napiophelios to it.

Texture by @Extex101, thanks, i have assumed CC BY-SA 3.0 as with your other MTG textures, i hope this is ok for you.

1000x1000 node map below shows wild cotton plants as red dots, best to view at 200% zoom to see the dots clearly.
Distribution can be tuned if necessary, but seems ok to me.

wildcotton

### CODE REVIEW

**Comment by sfan5** [comment]
> Plant is in the 'flora' group so is subject to automatic spreading (by our horrible spreading ABM).

I don't know how fast flowers spread currently, but I do think cotton shouldn't spread as fast.

**Comment by paramat** [comment]
Unfortunately, due to how the flora spreading ABM works (badly), all flora spread at equal rates.
Perhaps wild cotton should not be in the 'flora' group? Only one seed item is needed to start cotton agriculture. Not sure which is worse.

**Comment by sfan5** [comment]
I'd prefer if it didn't spread at all then, this can always be changed in the future.

**Comment by paramat** [comment]
That is fine with me. I loathe what the spreading ABM does to plant distribution, as the eventual outcome is uniform density everywhere. I will update this.

Ideally, i think all plants should be reproducable by seeds/sapling, using nodetimers, no ABMs (as i suggested for flowers in the past, and as we had for mushrooms before that was unfortunately changed to a spreading ABM).
Then all plants can be farmed at high density if desired. For spreading when dug in the wild, each dug plant auto-plants 1 seedling nearby to maintain a constant population.
Sometimes i think about a plant spread API to take care of all plant and tree reproduction.

**Comment by paramat** [comment]
Happily removed wild cotton from 'flora' group, no longer WIP.

Crazy how the 'flora' spreading ABM is in the 'flowers' mod and was originally only meant for flowers, but then was applied to many other decorations.

**Comment by TumeniNodes** [comment]
I hope not to seem rude or insulting as this is definitely not my intention, but I would like to just mention that, while this original texture is "ok", it feels a bit "off?"

Contrast is a bit on the heavy side and the original request for the texture was
> The plant should fill the full height (16 pixels) but be a little narrower than 16 pixels wide.

... which this texture does the exact opposite.
Just my own opinion and a suggestion, couldn't this texture be based off of the existing dry shrub texture, just bring life to it and add the cotton plumes?

In my mind, this gives a feeling of, "this is where dry shrubs comes from, where they dried up and died over time" (if that makes sense)

I know Extex101 is a decent pixel artist and can improve on this current texture.

And I definitely agree that these cotton sources should be quite rare but not impossible to find.

So, again... just my own input from observation, and I hope it is not taken as an insult or anything like that.

**Comment by Extex101** [comment]
> I hope not to seem rude or insulting as this is definitely not my intention, but I would like to just mention that, while this original texture is "ok", it feels a bit "off?"

I actually completely agree with you
When I saw the screenshot I thought it looked a little off too.

> Just my own opinion and a suggestion, couldn't this texture be based off of the existing dry shrub texture, just bring life to it and add the cotton plumes?
Hmm. Interesting idea gonna try it

**Comment by paramat** [comment]
The contrast seems perfect to me, better than being washed-out, the lack of contrast in savanna may be causing this perception. Try placing it in forest or grassland. Also compare to the high contrast of acacia trees and bushes.

16 pixels high would be good but i do not insist on that.
I know i suggested narrower than 16 pixels but that does not matter as it is a bush.
However, if you want to make it 16 pixels high that is welcome, but please otherwise keep it as similar as possible to current appearence, and without reducing contrst.

> Just my own opinion and a suggestion, couldn't this texture be based off of the existing dry shrub texture, just bring life to it and add the cotton plumes?

No thanks, the dry shrub has an unsuitable structure and has nothing to do with cotton.
> In my mind, this gives a feeling of, "this is where dry shrubs comes from, where they dried up and died over time" (if that makes sense)

There are no dry shrubs in savanna. Dry shrubs are not dead plants, they are just plants that can withstand very dry biomes.

**Comment by Extex101** [comment]
When I was making it I noticed some errors with dry shrub in the process so I fixed them up

I've made this to show what was wrong
e g
Stray pixels are a big no-no I'm every pixel artists book. I extended them down into new mini branches
And I fixed the shading because it was almost like the light was coming from below
I also thickened some of the branches

New dry shrub (I kept the original pallete)
0 - dry shrub

Cotton shrub
0 - cotten shrub

**Comment by paramat** [comment]
I like the new dry shrub texture, a much needed improvement, if you are happy to submit that as a PR i will support that.

I do not like the 'cotton shrub' texture as wild cotton, branches are no longer purple, colours are pale, contrast is too low. The structure and drawtype no longer resemble the fully grown domesticated cotton plant, which is what makes the previous texture so suitable:

screenshot_20200309_225645

**Comment by Extex101** [comment]
> branches are no longer purple

Oh yeah forgot that XD
cotton shrub large


How's this?
Screenshot_2020-03-09-16-39-50-1

**Comment by paramat** [comment]
The branches may now be purple but it is still unsuitable for the other reasons.
The first texture you created is excellent, perfect.
It makes no sense for wild cotton to look like a dry shrub when it should obviously look like an agricultural cotton plant. The association to dry shrub made no sense either.

**Comment by TumeniNodes** [comment]
The original texture is much fuller, when I mentioned basing it off dry shrubs, I didn't mean to use the exact texture.
My rough idea related to the dry bush, I had the idea they were basically dead bushes. I was mistaken.
In short, in viewing these two together, the original _is_ indeed the better.
Sorry for creating extra work/time for you Extex but there is a positive out of it... you fixed the dry bush texture and now those will look better as well.
win - win

**Comment by tenplus1** [comment]
Silly thought but how about having "farming:cotton_6" appear in the savannah region instead of a new node/shrub ?  This way it can still be harvested with a chance of seeds and cotton but on a lower scale than actually farming.

**Comment by sfan5** [comment]
@Extex101
You forgot to recolor a row of pixels at the bottom: (or is this intentional?)
pic

I prefer this texture over the previous one (though I'd also be okay with it).
The fact that is was made from the dry shrub texture is not a problem either, they don't look alike.

**Comment by Extex101** [comment]
That was intentional.
I was trying to make it blend with the grass..
And It still doesn't match up XD

**Comment by sfan5** [comment]
@paramat is there a reason this should not be in 5.3.0 or do you just not consider it to be a priority?

**Comment by paramat** [comment]
@sfan5 i cannot remember why i removed this from the 5.3.0 milestone, it might have been a mistake.
I would like this merged as soon as possible, if it is approved.
This PR is ready for review/merge.

**Pull request merged**
