### PR TITLE
Use 9-slice background in formspec theme

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by DS-Minetest** [comment]
On servers there will be a visible difference for old clients. (They won't see the background and get an error message instead.) As this is only visual, :+1:.

**Comment by paramat** [comment]
> On servers there will be a visible difference for old clients. (They won't see the background and get an error message instead.)

? If so how can this be merged?

**Comment by rubenwardy** [comment]
The error has been fixed, but not in a particularly nice way. Formspecs really suck

**Comment by paramat** [comment]
:+1: quite trivial.

**Comment by DS-Minetest** [comment]
A visual difference doesn't really hurt and an error message (the game won't crash btw.) is just like a little reminder that the client should be updated.
Drawing two backgrounds is a little weird.

**Comment by paramat** [comment]
That would be breaking old-new client/server compatibility, that can't be done casually.

Presumably the 9-slice background will completely hide the old background because the corners will not be stretched?

**Comment by rubenwardy** [comment]
> Presumably the 9-slice background will completely hide the old background because the corners will not be stretched?

This is correct

**Pull request merged**
