### PR TITLE
Flowers: More flowers

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20170628_122337

Flying around for 15mins this is roughly the highest density i saw.
Areas of a certain flower are larger, so a particular colour is easier to find, and maximum density of flowers has roughly doubled.
We were really lacking flowers.

### CODE REVIEW

**Comment by C1ffisme** [comment]
IMHO, They should appear in dense clumps of 15 to 25 flowers, but each clump should be distant from each other by about 50-200 blocks. And occasionally a smaller clump of 2-3 flowers will spawn with about the same consistency.

**Comment by Fixer-007** [comment]
What about grass?

**Comment by paramat** [comment]
C1ffisme that already happens because each of the 6 flowers has a different perlin noise distribution. Each flower occurs in areas that cover 1/4 of the land, and with varying density within each area. Combined you get an ever-changing combinations of flowers, including areas of no flowers and rare areas of high density of multiple colours.

**Comment by paramat** [comment]
Grass is fine it gets quite dense already.

**Comment by paramat** [comment]
bae17cd88c0562e8eb9c7b043848ec4c20e14eeb

**Pull request closed without merging**
