### PR TITLE
Add new grassy_dirt group

### PR DESCRIPTION
**Pull request by tenplus1**
This adds a new "grassy_dirt" group to dirt_with_grass, dirt_with_dry_grass and dirt_with_snow nodes for use with the new grass spreading function: https://github.com/minetest/minetest_game/pull/1286

### CODE REVIEW

**Comment by paramat** [comment]
Why seperate?
:-1: because it's for 1286.

**Comment by tenplus1** [comment]
Separate cause I don't know how to merge using web interface, but still necessary.

**Comment by rubenwardy** [comment]
The name is okay, but maybe "dirt_with_topping" would be better

**Comment by tenplus1** [comment]
Sounds more like a dessert :)  'grassy_dirt' sounded more like what it was and is easy enough for mod makers to remember I thought.

**Comment by rubenwardy** [comment]
I guess. It just isn't always grass (i.e: snow)

**Comment by tenplus1** [comment]
You mean snowy grass :)) lol

**Comment by paramat** [comment]
Yes 'dirt_with_snow' is actually 'dirt_with_green_grass_and_snow'.

**Comment by paramat** [comment]
Replaced by #1291 which is merged.

**Pull request closed without merging**
