### PR TITLE
rename junglewood to rosewood

### PR DESCRIPTION
**Pull request by DS-Minetest**
The descriptions of jungle tree and co. are changed to rosewood.
Related: #1817

### CODE REVIEW

**Comment by tenplus1** [comment]
This will just confuse players who are use to jungle wood and it's current descriptions.

**Comment by Ezhh** [comment]
I am strongly against this. It's too confusing and it's needless since there is only one kind of Jungle tree and "Jungle" itself is the modifier.

**Comment by SmallJoker** [comment]
Jungles need jungle trees. If we had more tropical tree types, this was fine but that's not the case right now. -1 from my side as well.

**Comment by paramat** [comment]
However we don't have jungle now, it's called rainforest.
This was my suggestion but even i'm concerned about confusion, neutral.
Should be 'Rosewood Tree' in descriptions.

**Comment by Ezhh** [comment]
We have jungle trees and jungle grass. Everyone calls it jungle on servers as well. Trying to change this feels completely unnecessary.

**Comment by paramat** [comment]
Sorry that last line was easy to misunderstand, edited.

**Comment by Ezhh** [comment]
The PR also misses the gate.

**Pull request closed without merging**
