### PR TITLE
Improve descriptions

### PR DESCRIPTION
**Pull request by Ezhh**
Addresses some consistency issues previously discussed in #1473 and #1817.

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by Napiophelios** [comment]
I think you should lose all the 'colour' descriptions.

**Comment by TumeniNodes** [comment]
I agree with Napiophelios in regards to adding colour names to stone types. I feel that is unnecessary.
If, in the future more stone types are added, then those could be given descriptive naming.

I do like defining Apple tree and products of it.

I'm sort of undecided in regards to adding "red" to rose.

**Comment by Ezhh** [comment]
We already have another type of stone, so "Grey Stone" is to move away from a generic "Stone", which should be the name of the group, not of an individual node. I'd be happy with an alternative name if you can suggest one, but for consistency it does need a name.

"Red Rose" is because a rose can be multiple colours, and every other flower that can be multiple colours already includes the colour in its name.  I don't think anyone has ever asked for the colours to be removed, so I'm not sure why added the colour for rose would be an issue now.

**Comment by paramat** [comment]
The colours are part of the whole intention, which is to have multiples of a node type distinguished by extra words instead of generic-plus-additions. So not having 'sand' plus 'desert sand' and 'silver sand', similarly for stone, sandstone and woods. Every node described in a consistent way.

Red rose is consistent with the many flower colour descriptions, and would be useful if i add a black rose, which i intend to do.
Maybe we can use 'Violet Viola' since violas come in many colours? Or, just use tthe other name for the flower: 'Violet'?

**Comment by TumeniNodes** [comment]
While I can understand the reasoning, it just seems like over doing it when it gets into the stone materials. Pretty much everyone IRL understands what "stone" is, as well as "sand", and the difference between "sand" and "sandstone", etc..
Would it not make sense, in the case of stone descriptions, to rename the group itself? So, instead of just "group stone", rename the group to "stone-like", this way stone can remain as "stone", cobblestone can remain as "cobblestone"
All the other naming changes I get and they make sense.

If stone is renamed to gray/grey stone, then why not also "red_desert_stone", because not all desert stones are redish, and that theory could go on forever. "caramel_desert_sandstone"

I do realize my argument sounds petty, and insignificant, and I do understand the idea and objective behind this but, I just feel renaming stone materials under this process is taking a very basic/simple piece, and over complicating it. When simply renaming the group would make the current names for stone-like nodes a non-issue.

**Comment by paramat** [comment]
Not a good idea to rename the stone group, it breaks mods and the group name becomes less intuitive and longer for typing. This is not being done due to the 'stone' group name.
'red desert stone' would indeed be going too far but is not needed because it is 'stone' plus a descriptive word which is the consistency we're going for.

**Comment by TumeniNodes** [comment]
hornfels_stone? [https://flexiblelearning.auckland.ac.nz/rocks_minerals/rocks/images/hornfels4.jpg](url)

Other than this, I cannot think of any other means to argue with. A couple others seem opposed to using a colour as a descriptive word, maybe they can make a better argument than me.

desert_stone, uses a locational description, which is sensible. More sensible than it would have been to name it "red_stone". That is my point.
But it is difficult to put a locational description to a type of stone which is most commonly seen across most of the globe.

**Comment by Ezhh** [comment]
One point about good descriptions is that they should be easily recognisable for the target audience, and for MT this includes children. "Desert Stone" is good, because it's "stone that is found in deserts" and most people will know what a desert is, or at least learn quickly, but as you say, the grey stone is in too many locations for the description to come from location. 

"Hornfels Stone" would probably lead to some head-scratching, because "Hornfels" isn't likely to mean anything to a lot of people, quite possibly including adults. It would make more sense if we had multiple types of real stone in the game, since that would set an expectation and normalise such a name, but we don't. 

This only really leaves us with modifiers such as Grey (Gray isn't an option, because Grey is already used in MTG), or Common or Plain as suggested in #1473.

**Comment by TumeniNodes** [comment]
I do agree with "common_stone", it seems more in-line with a naming scheme such as "desert_stone" and is more logical and in-line with this objective.
It also leaves more flexibility for TP's not being bound to a specific color for basic stone.

I had edited my comment above to add that, but you had probably already read it. And I missed that suggestion when reading #1473.

**Comment by Ezhh** [comment]
I don't have a strong preference between the two, but "Grey" seemed to be favoured in #1473 either way, so I'll defer to paramat and change or not based on what he decides.

**Comment by paramat** [comment]
Common stone is a vague description, 'grey' is better.

**Comment by paramat** [comment]
@Ezhh Maybe we can use 'Violet Viola' since violas come in many colours? Then all flowers have colour descriptions and the colour of each flower is made obvious, useful if a recipe requires you to search for it.

**Comment by Napiophelios** [comment]
The flower and wood descriptions seem fitting I guess,
but all the grey and golden descriptions are very cringy and awkward.

**Comment by paramat** [comment]
See http://irc.minetest.net/minetest-dev/2017-07-22#i_5016740
Seems the other devs are not keen on the changes to stone and sandstone.

**Comment by paramat** [comment]
See http://irc.minetest.net/minetest-dev/2017-07-22#i_5017056
SmallJoker prefers no changes to stone, sandstone and sand, and for me those are the less important parts of this PR.

**Comment by Ezhh** [comment]
Updated to remove stone/sand changes.

**Comment by paramat** [comment]
:+1:

**Pull request merged**
