### PR TITLE
Biomes: New surface node for rainforest 

### PR DESCRIPTION
**Pull request by paramat**
Moist rainforest plant litter.
Textures by npx.
////////////////////////////////////////////////

screenshot_20170227_033814

jungle_cp8bp8_ind128

Textures by npx, see https://forum.minetest.net/viewtopic.php?p=248241#p248241 onwards, i used the 2nd texture which seems popular and boosted contrast very slightly.
Tested.

### CODE REVIEW

**Comment by C1ffisme** [comment]
I like it. I suppose the green leaves on the texture could look just a bit less repetitive, but I really like it.

**Comment by sofar** [comment]
Pretty good, see if you can offset the leaves a bit, otherwise I really like the deep color and it fits well.

**Comment by paramat** [comment]
I dare not try moving leaves around, they seem ok, but i might try boosting contrast a little.

**Comment by paramat** [comment]
Updated. Raised contrast slightly (by 8 in Gimp). New screenshot.

**Comment by DS-Minetest** [comment]
(Perhaps it would be good to have a nice sound for this, something more muddy than grass.)

**Comment by paramat** [comment]
Updated to use a more suitable name 'rainforest litter', retested.
Approval from sofar http://irc.minetest.net/minetest-dev/2017-02-28#i_4821844

**Comment by paramat** [comment]
d1b132555b47fa83d6b1cbe0d2c6dd6e48fa54b4

**Pull request closed without merging**
