### PR TITLE
Small russian translation update

### PR DESCRIPTION
**Pull request by RichardTry**
Anyway, it was better and minimalistic :D

### CODE REVIEW

**Comment by RichardTry** [comment]
Так же, возможно стоит вернуть "кликните" на "нажмите"

**Comment by appgurueu** [comment]
Could you please merge https://github.com/minetest/minetest_game/pull/2974 into this?

**Comment by appgurueu** [comment]
@Andrey2470T please review.

**Comment by Andrey2470T** [comment]
Generally I support both variants (the old and new), but the new one looks like more shortened, so I approve this PR 👍

**Comment by appgurueu** [comment]
> Could you please merge #2974 into this?

@RichardTry

**Pull request merged**
