### PR TITLE
Fix typo in survival formspec & create legacy file

### PR DESCRIPTION
**Pull request by CraigyDavi**

### CODE REVIEW

**Comment by CraigyDavi** [comment]
> The legacy code might be unnecessary, but if not it should be in a legacy.lua file so that it can easily be removed later.

Updated.

* Created legacy.lua and moved aliases there + old typo survival formspec
* Moved snow alias into legacy.lua
* Moved mese block alias into legacy.lua and made the alias go in the correct order

**Comment by PilzAdam** [comment]
Some of the aliases in the alias.lua files are not there for backwards compatibility (e.g. `STSword`), so putting them in legacy.lua is wrong.

**Comment by CraigyDavi** [comment]
> Some of the aliases in the alias.lua files are not there for backwards compatibility (e.g. STSword), so putting them in legacy.lua is wrong.

I presume this is the full list of *not for backwards compatibility* aliases:
```
minetest.register_alias("WPick", "default:pick_wood")
minetest.register_alias("STPick", "default:pick_stone")
minetest.register_alias("SteelPick", "default:pick_steel")
minetest.register_alias("MesePick", "default:pick_mese")
minetest.register_alias("WShovel", "default:shovel_wood")
minetest.register_alias("STShovel", "default:shovel_stone")
minetest.register_alias("SteelShovel", "default:shovel_steel")
minetest.register_alias("WAxe", "default:axe_wood")
minetest.register_alias("STAxe", "default:axe_stone")
minetest.register_alias("SteelAxe", "default:axe_steel")
minetest.register_alias("WSword", "default:sword_wood")
minetest.register_alias("STSword", "default:sword_stone")
minetest.register_alias("SteelSword", "default:sword_steel")
```
Should I create an `aliases.lua` file specifically for aliases like these or remove them?

**Comment by PilzAdam** [comment]
@CraigyDavi other aliases (like `stone`) are there for backward compatibility *and* for helping with chatcommands. I don't know if they should be moved into a separate file. I'd just keep them in `aliases.lua`.

**Comment by CraigyDavi** [comment]
> @CraigyDavi other aliases (like stone) are there for backward compatibility and for helping with chatcommands. I don't know if they should be moved into a separate file. I'd just keep them in aliases.lua.

Got it, I've updated the commit.
* Moved some legacy falling node stuff over to`legacy.lua`
* Moved the aliases back to `aliases.lua`

**Comment by BlockMen** [comment]
a9137e8c212a5d9da20311a0cae549858ffe535c

**Pull request closed without merging**
