### PR TITLE
Player model: Remove vertical stretch of body and limbs, remove cape

### PR DESCRIPTION
**Pull request by paramat**
Previously, body and limbs were stretched vertically by 1.125, creating
rectangular pixels on side faces. Head was unstretched.
Remove stretch of body and limbs, leaving the head unchanged.
No other change would excessively shorten the model, so also scale up
the model slightly, by * 1.05, such that the reduction factor for height is
equal to the increasing factor for width. This minimises the changes to
height and width.

Remove cape support.

Update the collisionbox to match.

Add missing license.txt.
/////////////

screenshot_20171027_114456

Addresses #1411 

*** Note: Skins with capes will still be usable by using a simple mod, which i can provide if necessary.

Now it will match what you see in an image editor, in a MC skin editor, and will have the proportions of MC players, No weird and ugly rectangular pixels only on some parts of the skin.
It will look short for a while of course because we are used to the former.

////////////

Concerning the removal of the cape:

Imagine MC had never had a cape, and someone suggested adding a tiny superhero cape to our player model, it would be considered a strange, fairly random and not very useful idea, the cape is very short and certainly a cheesy superhero cape instead of a long and more useful coat.
Out of all the possible additions that could have been made to the model many others would have been more useful.

It was approved only because MC has capes and for no other reason.
Additionally, adding capes to copy MC was tasteless and disrespectful as MC capes are an exclusive for those attending MineCon, so are very much a MC-culture-exclusive-thing. It was like another game copying MT's mese.

The cape caused problems with MC version 1.0 skins, as some of these have signatures or whatever in that region, VanessaE asked for the cape PR to be reverted, MirceaKitsune agreed, see #201

"After a huge and mostly fruitless discussion on IRC, I have to recommend that this pull be reverted and replaced with a plain model, but with the new Sam II skin. The caped model uses part of the Minecraft skin format that was either not used or which was reserved for data that is not consistent with the idea of a cape.

Some 75% of the skins in my players' database have gibberish, signatures, partial data, have some kind of algorithmic data, or are simply some opaque, solid color in the "cape" area as defined by this model, basically rendering this cape idea useless and indeed breaking most of the skins in my database."

The PR had little support, 3 including the author and core devs. me disapproving (while not a dev) and 2 asking for a revert for good reason, but it never was. Seems like a mistake and now is a good time to fix it.

////////////

However some server admin may like to use a caped version, so it is provided in a folder for easy use.

screenshot_20171027_113925

^ Collisionbox checked

### CODE REVIEW

**Comment by paramat** [comment]
By the way how do i get capes to work? I added to the texture but nothing appears.

**Comment by stujones11** [comment]
> I added to the texture but nothing appears.

You are using the correct model? Note that I did not label them very clearly, offset_1.70-cape is the one without the cape. I will check this again later myself.

**Comment by paramat** [comment]
I'll try again, yes i knew that 'cape' is the one without.

**Comment by paramat** [comment]
Some other points.

#201 was merged without the approval of another core dev.

The cape could have been 4 pixels longer to completely use the space in the skin texture. It's too short, as PilzAdam complained in the PR thread, so it looks rather comical like a spoof superhero.

The cape was, amazingly, given a 3D thickness instead of being a single flat quad, a single layer of material should be flat.

In the simple skins mod, out of 31 skins none use a cape.

It has been pointed out that most players use a MC skin editor to create their skin, these will not support the creation of capes.

So i am going to remove the file that contains the caped version, as it will only encourage this mistake to continue. If people want to use a cape model they can use a simple mod that provides a caped version.

**Comment by paramat** [comment]
Updated and retested.

**Comment by SmallJoker** [comment]
comparison

The model is quite smaller now, but I think that's fine.

**Comment by paramat** [comment]
Height has reduced from 1.77 to 1.7 nodes.
Your screenshots are taken at an angle that makes the body look extra short due to foreshortening, just pointing this out =)

**Comment by paramat** [comment]
Because i'm working on a skins mod for MTG i am actually finding some skins that are broken due to the cape, because the cape area is non-transparent for various reasons.

**Comment by stujones11** [comment]
One way the cape could remain without effecting skins would be to move it to another material layer. The downside with that is that you would need to supply two separate textures for the player model, albeit only `blank.png` for no cape. I personally don't think it's worth it, just pointing out that there are alternatives if there is much objection over the cape removal, the fixing of the pixel scaling is more important IMO.

**Comment by paramat** [comment]
Messy and not justified =)

For anyone who wants to continue using capes, a simple mod can be used to apply the caped version of the model, i can provide the code if anyone doesn't know how to code this.

**Comment by paramat** [comment]
In working on a skin mod i have now worked through roughly 170 skins, only about 4 use the cape (less than i expected) and a similar number are broken by it, so this will not cause much disriuption.

**Comment by paramat** [comment]
@SmallJoker @rubenwardy are you able to support? I would like 3 +1s for this change. Please read the whole thread for the various points.

**Comment by HybridDog** [comment]
I think you need to ensure that the eyes are 1.625 above player.get_pos().y because this offset is hardcoded and when facing another player from very near, the eyes are on the same height, thus you don't look down on or up to each other.

**Comment by paramat** [comment]
Yes, i will lower eye height in the engine if this is merged, i actually plan to make eye height a player property that is set when the model is set, to allow players to become different sizes and have the correct eye height.

**Comment by HybridDog** [comment]
Actually there already is such a player property https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3604, you could set the player eye height when a player joins in lua in builtin and remove the hardcoded offset.

**Comment by paramat** [comment]
That's not technically a 'player object property' but yes i decided to not use that as eye offsets should still be usable to offset from the normal eye position, which itself should be set according to player model height. Otherwise eye offset becomes complex to use due to becoming a combination.
My intention is explained here #6216

**Comment by paramat** [comment]
Correction: In processing 13 skins for a sin mod, none of these use the cape.

**Comment by DS-Minetest** [comment]
>134 skins

I wonder from where these skins are. Many of [Addis Open MT-Skin Database](http://minetest.fensta.bplaced.net/) have capes.

**Comment by HybridDog** [comment]
I'm in favour of removing capes, it looks like Sam is walking around with a plate attached on the neck.
For comparison: https://www.youtube.com/embed/KBfxnayIlOY

**Comment by asl97** [comment]
Going through the first 10 pages of Addis Open MT-Skin Database, I saw a lot of the corner pixel, random pixel and gibberish cape.

But I also saw [cape being use as hair](http://minetest.fensta.bplaced.net/#!page:1,filtertype:Id,filter:36). I saw embedded cape (cape which was drawn directly on the body layer) as well as embedded weapon, if the cape layer actually turn it into a 3d layer rather than just the edge pixel, it could be use to a rather amazing effect.
___

As it stands, it would probably get removed, hopefully with a mod being provided by @paramat.

**Comment by paramat** [comment]
The 134 skins i have processed so far are all the npc, skin and mob mods i could find. Next i will look through the skin database and yes i expect to find some cape usage there.
I'm very happy to write and provide a simple mod that provides the caped version of the model for those who want to use it.

**Comment by twoelk** [comment]
actually I always thought the cape should be a mod of it's own if at all. Similar to armor, jerseys or such. It would be cool if players could be grouped by wearing a team cape or jersey over their normal skin. Such could be usefull for many things and if we ever have an educational edition be included out of the box. So while I absolutely agree to make our skins as compatible as possible to the widespread defacto standard that makes many tools out there useable for Minetest, I would really like to see some skin layering system present in mtg

**Comment by benrob0329** [comment]
I don't mind removing capes. They always look wrong, and should be done with proper animations if done at all.

**Comment by paramat** [comment]
9596d00a18390ef4e5d6e332b8dce9b306dcf26b

**Comment by Extex101** [comment]
I liked the player model because of how tall he is and the fact he has a cape
Now it looks like the MC player which is :-1: 
Also being a skin maker the removal of capes is a BIG problem
screenshot_2018-11-30-12-18-41-1
screenshot_2018-11-30-12-12-23-1
The height of the player makes him look more dignified than the MC player but now he's short and stubby and no longer can be taken seriously

I call for a revert

**Comment by jastevenson303** [comment]
haha capes were removed!?

**Comment by paramat** [comment]
Extex101 using the player API you can easily add a taller model with a cape using a mod. All you need to do is take the old model and get someone to reset the vertical offset by 1 node to make it usable in MT 5.0.0.

**Comment by Extex101** [comment]
The thing is I don't run a server so no matter what I play on it will have the short stubby MC-like model

**Comment by Extex101** [comment]
Maybe have it so models can be set client side in a texture pack?

**Comment by Extex101** [comment]
IMO the new player model looks squashed

**Comment by NathanSalapat** [comment]
@Extex101 You can use a mod in singleplayer to change the player model.

**Comment by paramat** [comment]
It's just new to you so you'll likely get used to it in a few months. The old model looks awkward and stretched to me now. Having some pixels square and some stretched on one model is really ugly.

On a server most of the content is, rightly, decided by the server, especially the models. The philosophy of MT is that the server has 'all possible control' according to celeron55. The recent allowing of clients to increasingly modify the server experience when connected to a server (client-provided CSM) was a big mistake.
If you don't like it you can either gain some support and ask the server admin to use the old model, or find a server that uses the old model.

Clients cant set the models used because server mod code depends on models being certain known dimensions.

**Pull request closed without merging**
