### PR TITLE
Default/mapgen: Re-add dune biomes. Correct  'noise threshhold'. Flowers/mapgen: Slighly more flowers

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20151215_013803

Re-adds the MT 0.4.13 grassy sand dune biomes at y = 5 that make a nice transition from grass biome to beach. I had removed these for simplicity but started to miss them. Added below both grasslands and coniferous forest.

### CODE REVIEW

**Comment by sofar** [comment]
Absolutely, please, yes.

**Comment by MoNTE48** [comment]
:+1:

**Comment by 0-afflatus** [comment]
Nice.

**Comment by sofar** [comment]
Can you add dry shrubs to warmer beach biomes too? i.e. the ones next to a savannah? And dead bushes on beaches next to a desert?

**Comment by paramat** [comment]
I'll consider, but savanna has no beaches it extends to the water where it changes to swamp.

**Comment by paramat** [comment]
Added a commit 'Correct spelling of 'noise threshhold' in 'register ore'', see #746

**Comment by paramat** [comment]
Added another small tweak commit 'Flowers/mapgen: Slightly more flowers in mgv5/v7/flat/fractal'

**Comment by paramat** [comment]
a1b8b68e92ac37e767f9ae0f8b88691039fd3141
c3a1545ca1dda4b94bfecc281097ab0cdc3e565b
8704afe5b1683d8e10929aee20dea8f8580144e7

**Pull request closed without merging**
