### PR TITLE
Dirt sounds: Remove extreme sub frequencies, trim for zero amplitude starts

### PR DESCRIPTION
**Pull request by paramat**
screenshot from 2017-12-14 20-03-45

screenshot from 2017-12-14 20-04-23

^ PR waveforms

Replaces #1977 thanks to jastevenson303 for highlighting these problematic sub frequencies.

These both had extreme amplitude sub frequencies. Since the audible sound was relatively small these sounds are being used at high gain, so the sub frequencies may be causing problems.
I used a HPF at 20Hz 48dB roll off, then trimmed the waveform starts by a tiny amount such that they start at zero amplitude (note the waveforms still look like they have non-zero starts above, that's an illusion).
Audibly there is no change in volume.

### CODE REVIEW

**Comment by ThomasMonroe314** [comment]
:+1:  sounds good (pardon the pun)

**Comment by Fixer-007** [comment]
Much better, it is indeed was annoying (headphone user).

**Comment by jastevenson303** [comment]
Haven't tested but yes that was very annoying.

**Comment by TumeniNodes** [comment]
I still don't like the "spleck" sound to it. Sounds somewhat like a whip.
sand and grass have the same problem.
At least this seems to address the incredibly annoying "click" between the loops? which all footstep and leaves sounds have

**Comment by paramat** [comment]
Yes not great sounds, harsh, best to replace with 5 new sounds later.

**Comment by paramat** [comment]
d603707e1a5177211ba5d6ea5852a740e2ae24ef

**Pull request closed without merging**
