### PR TITLE
Backport 0.4

### PR DESCRIPTION
**Pull request by rubenwardy**
List of commits that were backported to the `backport-0.4` branch

<b>Last updated</b>: 2018-05-18
- 180518: Added `Stairs: unbind table groups`

Guidelines:
* no non-trivial refactoring
* no new nodes / items
* no purely cosmetic changes

Bugfixes:
* Default: Revert "Default: Shorter and better ABMs"
https://github.com/minetest/minetest_game/commit/626cd8e9c7c2a5d5c907a12abbaa6066b6d5f2ff
* Books: Add nil value checks to the book formspec handler
https://github.com/minetest/minetest_game/commit/da7e8e4810784951ab45f3c556e885be4e9e4721
* Chests: Check 'def' of node above chest to avoid crash
https://github.com/minetest/minetest_game/commit/120e96938ddf7db55849a87bce5d5313733d95ce
* Stairs: Add backface culling to stair meshes
https://github.com/minetest/minetest_game/commit/7b46d3b6afa7c14a6ed26368820334b1adfc5e4d
* Carts: Do not connect rails with gunpowder (#1812)
https://github.com/minetest/minetest_game/commit/c51ebcb74a1f7086ec339414039d7860af9112d2
* Add backface_culling to open chests and fencegates
https://github.com/minetest/minetest_game/commit/2e413b521ab472d94b92de76e33b83b168d37187
* Saplings: Reduce grow time to ABM equivalent
https://github.com/minetest/minetest_game/commit/0cdee1d8f5c19271abc1a30a250afa5eb4547393
* Crafting: Remove duplicate reversed recipes (#1777)
https://github.com/minetest/minetest_game/commit/1d5bc15f9adc6fc05d401ebc66822685b50447e3
* Correct farming/stairs dependency (#1838)
https://github.com/minetest/minetest_game/commit/c2f3c99cad9c9a5c090ab76e653fa6b90b08215c
* Creative: Prevent unauthorized item access (#1840)
https://github.com/minetest/minetest_game/commit/a1d35f3d69dbed8cd9ce317a11f2bd2f7c816c75
* TNT: Only burn visually connected powder (#1857)
https://github.com/minetest/minetest_game/commit/fa4c77feba6164a51be639713e129fd661cdb2ba
* Carts: Check for last pathfinder predition too
https://github.com/minetest/minetest_game/commit/8f1f3760f03fd25ca9912020ae607d7849cc425b
* Lava cooling: Increase interval to 2
https://github.com/minetest/minetest_game/commit/7ffd176f48c4c74a9e5a14e700f720f279dcee9f
* Beds: Do not crash when placing in an unknown node
https://github.com/minetest/minetest_game/commit/67c01a44c2a32eb47709a1fdc8ac25eb36bb37eb
* TNT's tnt:boom cleanup (#1868)
https://github.com/minetest/minetest_game/commit/c5e97867f31f9ea0590a0a415da58af5c0c609e1
* Register fence: Allow setting nodedefs to 'false'
https://github.com/minetest/minetest_game/commit/f92878094660d8a25ea7f9d06a9b2a98ebdf0fad
* Chests: Fix open chest after player leave (#1884)
https://github.com/minetest/minetest_game/commit/c5c9e423caf901d8a9a97ce959f4ee31cadbf7a0
* Chests: Fix locked chest protection against explosions (#1886)
https://github.com/minetest/minetest_game/commit/f33cc02080fe6636d4d00b9c3cb045ad3a76df58
* Sfinv: Rename navigation tabs to reduce chance of a conflict
https://github.com/minetest/minetest_game/commit/db08c0d721e056862adf4af4ac19bd800c747f6a
* Sfinv: Remove possibility of infinite loop when homepage doesn't exist
https://github.com/minetest/minetest_game/commit/a4b94a334754e5e7a5343e5d3caafdd76b94daff
* Flowers: Add waterlily right-click checks
https://github.com/minetest/minetest_game/commit/2d8207a924905bbb764ca7b0e2fc5af1e1a7cf7a
* Books: Convert \r to \n
https://github.com/minetest/minetest_game/commit/045abbd6d7bac8d4706731cb36c1c15dd98fdf13
* Creative: Make handle_node_drops override work for non-player diggers
https://github.com/minetest/minetest_game/commit/319b9eeeaff57dcb40212c34f8c1ebfad1d9ce8f
* Creative: Make the placenode registration check for non-player placers
https://github.com/minetest/minetest_game/commit/8b5ad0f02813cefada44d93d31b2556d8277b5bf
* Add nil checks for placer
https://github.com/minetest/minetest_game/commit/a2d7678ffd532dd82dcaa108eac3dace61ac94a2
* Default: Make burntimes more rational and consistent
https://github.com/minetest/minetest_game/commit/ed83e30d6826083f273ca323420402485c260cdc
* Book textures: Reset colour profiles to remove warnings
https://github.com/minetest/minetest_game/commit/62d5d5954ed2f6a503bb0c0460af2f298618ac1f
* Furnace: Fix being able to cook items without enough fuel
https://github.com/minetest/minetest_game/commit/bd0c627a207b70975dd020dbaa33e0e3a58037bc
* default:dirt_with_snow: Re-add to soil group
https://github.com/minetest/minetest_game/commit/a6aa68d5b4ed0abb8dd27ca62c8de670313a2e1a
* Stairs: unbind table groups
https://github.com/minetest/minetest_game/commit/5f121b586d5427098febd32dcc7b700d3d240800
* Doors: Avoid crash on nil player in 'can dig door'
https://github.com/minetest/minetest_game/commit/d5907d5f1e5dedb7ecc7a20e740e971403cf0f5a
* Flower spread ABM: Optimise
https://github.com/minetest/minetest_game/commit/a587972010d8ecf83f10010ada91d43db06f976c
* Prevent divide by zero
https://github.com/minetest/minetest_game/commit/8c71f3d82604b36a17edd40bb2c0274004d92ca3

Features:
* Stairs: Use one recipe matching inventory appearence
https://github.com/minetest/minetest_game/commit/175a9f8ff5d5d93299a7aa39daff297e5444c9b5
* Books: Limit the size of books
https://github.com/minetest/minetest_game/commit/b3f17cda9ff0250600c3fe88e9bcf2b569ae9982
* Books: Also limit the max size of the title
https://github.com/minetest/minetest_game/commit/502720b14de91a356fff7cd69f64d254d8c69022
* TNT: Track TNT owner in metadata for protection mods
https://github.com/minetest/minetest_game/commit/0f7d0bfd7ab647ac61158d69176a47ec26b5dd87
* Mushroom spread: Optimise and make overridable
https://github.com/minetest/minetest_game/commit/bcf98df5fac3eb59b02d9fdb066ab92c6228d787
* TNT: Add explode_center flag
https://github.com/minetest/minetest_game/commit/fe67ffda7ca4326c85f114bd02797f25348931f9
* Bones: Return bones when taking the last ItemStack
https://github.com/minetest/minetest_game/commit/3611af1dda0897354cd1e36aea5e48721d4389aa
* TNT: Add tnt.boom defaults
https://github.com/minetest/minetest_game/commit/3ff296961e903325084b9e9a07a6cf7ce44bf1e7
* Creative: Cache inventory items on load
https://github.com/minetest/minetest_game/commit/47d6fbf884f82639e096250bb3f8fb5960550cb3
* Book textures: Replace with more original textures
https://github.com/minetest/minetest_game/commit/0c841771a75e6688c99814d4314d491986d7f0cb
* creative: Add missing tooltips.
https://github.com/minetest/minetest_game/commit/5b57815af164325c6e6cc5cd37c68dcc9add23e8

Useful commands:
* convert description of this project to list of commits that need to be cherry picked

`sed -nr 's|.*/commit/([0-9a-f]+)|\1|gp' text.txt | while read h; do git show -s --format="%ct %H %s" $h; done | LANG=C sort >commits.txt`
* compare list of commits to current state of branch

`diff <(cut -d " " -f 3- commits.txt) <(git log --format="%s" | head -$(wc -l commits.txt|cut -d " " -f 1) | tac)`

### CODE REVIEW

**Comment by paramat** [comment]
TODO:
#2039

**Comment by paramat** [comment]
As of today, the TODO list above is still correct and up to date.

**Comment by sfan5** [comment]
@SmallJoker 
the guidelines I'd written for this say "no purely cosmetic changes", however you backported commit 0c84177
do we want to keep this or not?

**Comment by SmallJoker** [comment]
@sfan5 You are totally right. I removed 0c84177 and the follow-up commit 62d5d59 from the backport history.

**Comment by paramat** [comment]
Those aren't purely cosmetic, i included those because they are copies of MC textures.

**Comment by paramat** [comment]
Don't merge until those 2 are re-added.

**Comment by paramat** [comment]
Even if not a legal risk, almost exact MC copies are embarassing to leave in, so this would be done in 0.4.18 anyway.

**Comment by paramat** [comment]
Note: Book texture commits were included as they remove textures very similar to MC textures.

**Pull request merged**
