### PR TITLE
Migrate sethome mod to player attributes.

### PR DESCRIPTION
**Pull request by sofar**
Migrates settings safely and evacuates the `homes` file entirely over time.

### CODE REVIEW

**Comment by sofar** [comment]
I need to prefix the attribute - marking WIP

**Comment by sofar** [comment]
Made the attribute named "sethome_home". Should be conflict-free this way.

**Comment by sofar** [comment]
Needs review.

**Comment by sofar** [comment]
Changed to use `:` since that's what devs seem to agree on.

@paramat?

**Comment by sofar** [comment]
rebased to make luacheck clean again.

**Comment by paramat** [comment]
Sorry i'm avoiding reviewing this one as i'm not good with player attribute stuff.

**Comment by paramat** [comment]
Added SmallJoker's approval.

**Comment by paramat** [comment]
1c78fd346db7cd5bab4569d07ee2cb74e8e88047

**Pull request closed without merging**
