### PR TITLE
Flowers: Fix itemstack when waterlily is placed

### PR DESCRIPTION
**Pull request by kilbith**
Title says it all. I forgot to update the itemstack, sorry about that.

Cc: @paramat

### CODE REVIEW

**Comment by paramat** [comment]
Will test.

**Comment by sofar** [comment]
This looks OK. I usually like to see the unmodified itemstack returned after the creative check, but in this case it's irrelevant - just a very minor style issue.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by PilzAdam** [comment]
:+1: (if tested)

**Comment by paramat** [comment]
Will merge once tested.

**Comment by paramat** [comment]
Tested.

**Comment by paramat** [comment]
7be008936eab8e17bdc4de1811411071821eb294

**Pull request closed without merging**
