### PR TITLE
Seeds: use leaf sounds by default.

### PR DESCRIPTION
**Pull request by sofar**
There were no sounds attached to farming's seeds, causing placement
and digging/walking on them to be silent.

### CODE REVIEW

**Comment by sofar** [comment]
Fixes #997

**Comment by C1ffisme** [comment]
This is our 1000th issue/pull request!

**Comment by paramat** [comment]
Maybe make them much queter than leaves?

**Comment by sofar** [comment]
leaf placement has a gain of 1.0 in ```mods/default/functions.lua```, but yes this could be overridden.

**Comment by SmallJoker** [comment]
The sound definition should be moved above `on_place`, since individual node functions always have been defined on the bottom of the node definition.

**Comment by paramat** [comment]
I think this needs to be much quieter than leaves, considering how loud leaves are and how tiny seeds are.

**Comment by sofar** [comment]
I can update these to use the default sounds, but softer

**Comment by sofar** [comment]
Made sounds softer, and moved up the sound def above callbacks.

**Comment by paramat** [comment]
Do footstep and dig need to be specified as quiet sounds too?

**Comment by sofar** [comment]
immediate digging seems kind of weird, it's not a simple object you could pick up quickly. The footstep sounds should be the same level as walking on e.g. soil perhaps, but I didn't check the level.

**Comment by paramat** [comment]
Good points. I still think dig and dug should be very quiet. Does walking on seeds actually trigger the footstep for the node underneath? it might do. otherwise it should be that of the most likely node underneath.

**Comment by paramat** [comment]
From how snow used to behave i believe walking on a thin nodebox will trigger the footstep of the node below it, so seed footstep can probably be disabled.

**Comment by sofar** [comment]
If at a certain point in time the footstep code would become smart enough to not play the sound _under_ the feet, but first look at the node the feet are _in_ (like, when the player is standing in 1-node deep water) and play those sounds (water sounds, in the former case) then having the sounds in the seed sounds would be preferable.

**Comment by paramat** [comment]
I agree.

**Pull request closed without merging**
