### PR TITLE
Default: New aspen tree schematics

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160622_052059

screenshot_20160622_054208

^ This PR

screenshot_20160622_051803

^ Tallest and shortest

screenshot_20160621_225935

^ Current aspens

I find the current aspens are ugly due to the way they get wider towards the top (with my apologies to sofar). So i have spent an hour or two looking through images of aspens and found they are a little like pines in being slightly conical and often tall, especially in forest. The general shape of the leaf cluster is slim, cylindrical or conical, with a rounded base and pointed top.

quaking_aspen_half

aspens 3

aspen-trees

I created new schematics in this shape, they are fairly tall and can be equal in height to pines. The schematic design is similar to pines, using per-node randomness to create rounded corners. The base of the leaf cluster is always rounded to suggest branches going up at a fairly steep angle. The design is more consistent in style with the other trees. I find the height and pointed tops make a refreshing contrast in deciduous forest.

### CODE REVIEW

**Comment by sofar** [comment]
> The design is more consistent in style with the other trees.

Keeping shape diversity isn't a bad thing. The proposed shape is like a pine tree, we already have that shape. The short version is like an apple tree, we already have that shape too.

When I made the schematic, I tried to make something new and original. This is just more of the same.

**Comment by pithydon** [comment]
Here is something new and original.
screenshot_20160622_155012

**Comment by sofar** [comment]
@pithydon this is a PR, and not a "suggestion box". Please discuss the PR first. It's disruptive to the discussion to post a seemingly random idea, and not helpful.

The discussion should focus on whether Paramat's design is better, or not. If you want to suggest a different design, then make a PR yourself.

**Comment by paramat** [comment]
pithydon that's certainly new and original but a mess and completely unlike an aspen tree.

**Comment by pithydon** [comment]
My point exactly, no one wants new and original they want trees.
IRL pine trees have needles and aspens have leaves which makes them look different even with the same shape.
It is hard to make the textures look different with such small resolutions though.

**Comment by paramat** [comment]
:D

**Comment by sofar** [comment]
>My point exactly, no one wants new and original they want trees.

That's a "hyperbole" argument, and completely nonsense. By that logic all trees should use exactly the same schematic.

**Comment by sofar** [comment]
@paramat I have no issues with improvements, but I feel like this is not an improvement, but a small step backwards. It removes a bit of diversity and makes Aspen trees either look like apple trees or like pine trees.

To be honest, I'd have no problems with *all* the trees using more shapes or provide more variation, and some part of this PR does add a little bit more variation (after all due to the schematic choices you end up with two sufficiently different shapes), but it takes the current shape away and replaces it for two shapes that are similar enough to existing schematics, so I consider that a reduction.

As for @pithydon's hyperbole argument, I'd like to stress that *I* was the one who added the Aspen trees. If you really feel like "no one wants new and original" then please consider reverting your minetest_game back to 0.4.13 and be happy with the trees you have there.

**Comment by pithydon** [comment]
I admit my argument is exaggerated.
Your tree looks like oriental plane, which is still a tree.
220px-platanus_orientalis_tree
Using the same schematic is exaggerated to, different types of trees have different shapes.

**Comment by paramat** [comment]
> Keeping shape diversity isn't a bad thing. The proposed shape is like a pine tree, we already have that shape. The short version is like an apple tree, we already have that shape too.

> It removes a bit of diversity and makes Aspen trees either look like apple trees or like pine trees.
replaces it for two shapes that are similar enough to existing schematics

> Using the same schematic is exaggerated to

The new schematic is significantly different from pine, the tallest possibility has alternating 3x3 / 5x5 levels like the shortest pine but that's the only similarity.
Each branch level isn't hollow, widely spaced and downward sweeping, the new schematic is solid and has a rounded base to suggest upward angled branches.
Aspens are similar in appearence to pines so a slightly similar schematic makes sense.
The existing schematic doesn't look remotely like an aspen, and doesn't have the height.

**Comment by sofar** [comment]
It would be nice if we could just *add* new shapes (multiple schematics) for trees instead of replacing them. This way we could go beyond the one-schematic-per-tree limitation. That would allow for schematics like these to be added (which btw is creative, and I like that aspect).

**Comment by Ekdohibs** [comment]
Yeah, having several schematics would be a good thing; can't we just do that for now with multiple decorations, until we have an engine change?

**Comment by paramat** [comment]
Note this is one schematic, it uses yslice to create the shorter version.

Certainly i have been considering a second smaller pine. But deciduous forest already has 2 tree schematics. We can't keep your schematic because, although it may be possible to very occasionally find an aspen that shape, it doesn't look like typical aspens.

I do feel bad about trying to replace your schematic.

**Comment by MarkuBu** [comment]
I would also like to see more bushes like trees. Build like a tree, but only a one or two node high trunk and leaves down to the ground

**Comment by paramat** [comment]
Ekdohibs we don't really need an engine change. We could have 2 schematics per tree type certainly, yslice probability does create quite a lot of variation already.

**Comment by sofar** [comment]
> We can't keep your schematic because, although it may be possible to very occasionally find an aspen that shape, it doesn't look like typical aspens.

I'm so tired of this reasoning. This was never mentioned when the PR was merged. I had zero feedback that the "unrealistic" shape would be reason for rejection. I generally do my best to find middle ground and come to address all concerns raised, including aesthetic ones.

For reference:

I designed the aspen tree shape to provide a tapered-down shape (upside down wedge) so that while walking through the forest you'd experience an "open" feel where you can look under the trees, and at the same time the "canopy" would nearly close up visually (especially when planted close enough). This was done by creating a non-circular top with little random extensions. This was done to mimic the atmosphere that aspen/birch forests have.

If I've failed at that design goal and circular trees with pine-like layers of leaves do a better job at it, then:

Go ahead and replace my schematic.

:+1:

I'm unsubscribing from this thread.

**Comment by paramat** [comment]
> This was never mentioned when the PR was merged. I had zero feedback that the "unrealistic" shape would be reason for rejection

Yes and i'm sorry, i found the shape weird and ugly but trusted you knew what aspens looked like so didn't check. It is important that a schematc looks like the tree it represents, creating a weird shape for this following reason is bizarre:

> I designed the aspen tree shape to provide a tapered-down shape (upside down wedge) so that while walking through the forest you'd experience an "open" feel where you can look under the trees, and at the same time the "canopy" would nearly close up visually

**Comment by tobyplowy** [comment]
I think you should do both of them the ones made by @sofar and your new trees ( it would give some more variation) also a new aspen forest biome would be nice

**Comment by tobyplowy** [comment]
@paramat I think you should do both of them the ones made by @sofar and your new trees ( it would give some more variation) also a new aspen forest biome would be nice

**Comment by paramat** [comment]
I explained why the current ones can't be used.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
84e4ae1881504153f7c3c9011fc612bb1d0469a6

**Pull request closed without merging**
