### PR TITLE
Stairs: Set world-aligned textures

### PR DESCRIPTION
**Pull request by paramat**
Stairs: Set world-aligned textures for all stairs and slabs

Fix 'stair_images' code to avoid 'stair_images' being empty in some
situations.
Change stairs back to nodeboxes to make world-aligned textures work.
////////////

Attends to #1931 
I carefully tested that the new nodebox definitions match the previous meshes in orientation.

### CODE REVIEW

**Comment by paramat** [comment]
PR has a bug. If i define 'align_style' (as either "node", "world" or "user") in the stair/slab registration:
```
stairs.register_stair_and_slab(
	"stonebrick",
	"default:stonebrick",
	{cracky = 2},
	{{name = "default_stone_brick.png", align_style = "world"}},
	"Stone Brick Stair",
	"Stone Brick Slab",
	default.node_sound_stone_defaults()
)
```
The slab appears as an 'unknown node'.

**Comment by paramat** [comment]
Just checked MTGame master, if i make the first texture a table and define 'backface_culling':
```
stairs.register_stair_and_slab(
	"stonebrick",
	"default:stonebrick",
	{cracky = 2},
	{{name = "default_stone_brick.png", backface_culling = false}},
	"Stone Brick Stair",
	"Stone Brick Slab",
	default.node_sound_stone_defaults()
)
```
The node appears as an 'unknown node'.
So this bug is not my PR it was already present and seems to be caused by the 'override using any other value' code:
```
function stairs.register_stair(subname, recipeitem, groups, images, description, sounds)
	local stair_images = {}
	for i, image in ipairs(images) do
		if type(image) == "string" then
			stair_images[i] = {
				name = image,
				backface_culling = true,
			}
		elseif image.backface_culling == nil then -- override using any other value
			stair_images[i] = table.copy(image)
			stair_images[i].backface_culling = true
		end
	end
	groups.stair = 1
	minetest.register_node(":stairs:stair_" .. subname, {
		description = description,
		drawtype = "mesh",
		mesh = "stairs_stair.obj",
		tiles = stair_images,
```

**Comment by sfan5** [comment]
yeah that part should be 
<pre>
	for i, image in ipairs(images) do
		if type(image) == "string" then
			stair_images[i] = {
				name = image,
				backface_culling = true,
			}
		else
			stair_images[i] = table.copy(image)
			if image.backface_culling == nil then -- override using any other value
				stair_images[i].backface_culling = true
			end
		end
	end
</pre>

**Comment by paramat** [comment]
Yes, or this:
```
	-- Set world-aligned textures
	local slab_images = images
	for i, image in ipairs(images) do
		if type(image) == "string" then
			slab_images[i] = {
				name = image,
				align_style = "world",
			}
		elseif image.align_style == nil then
			slab_images[i] = table.copy(image)
			slab_images[i].align_style = "world"
		end
	end
```
Will fix as a 2nd commit.

**Comment by paramat** [comment]
Code fixed but i need to test.

**Comment by paramat** [comment]
Done and tested.

**Comment by TumeniNodes** [comment]
Any chance someone could post some pics? I will not benefit from these changes, until the next release as I adhere strictly to stable releases. But I really want to see the results. Been waiting for this for a while

I also want to ask, is there no possible way this can work using the mesh nodes for stairs? Seeing as so much fuss was made in using mesh as opposed to nodeboxes when corner stair nodes were added.
Either way, I am glad this is another issue resolved. Nice work to all involved :+1:

**Comment by SmallJoker** [comment]
grafik
Left: current / this PR with meshes
Right: this PR with nodeboxes

World-aligned textures would be nice to have on meshes too, to save the superfluous drawn faces (#551).

**Comment by Fixer-007** [comment]
Looks wonderful in game, another example:
default

**Comment by TumeniNodes** [comment]
What a nice difference this makes. Although, is it just my eyes playing tricks on me or, are the brick edges a bit wonky?

@SmallJoker I fully agree with you regarding, finding some way to make this work with meshes.

thank you for the images guys

**Comment by DS-Minetest** [comment]
>Although, is it just my eyes playing tricks on me or, are the brick edges a bit wonky?

The same problem appears with cubic brick nodes. Maybe flipping the top texture would help.

**Comment by paramat** [comment]
@numberZero i guess this cannot work on meshes?

**Comment by numberZero** [comment]
> I guess this cannot be made to work on meshes?

Sadly that's true. That obviously can't work for a sphere, thus can't work for an arbitrary mesh.

Also note that while this fixes #1211, keeping solid nodes rotatable means a texture can't span several such nodes (see minetest/minetest#6105)

**Comment by paramat** [comment]
9d9e9b67090423ef8447b93af9109b87dc430d27

**Comment by Ezhh** [comment]
Not that I expect it to change anything, but I want to note this has guaranteed my servers will never move back to using unmodified MTG. 

Players have depended on the ability to rotate textures in order to make decorative and interesting builds. This completely breaks these builds. 

This might fix some visually less appealing uses of stairs, but that does not make breaking existing builds and removing the ability to do something in game which players have always been able to do okay.

**Comment by paramat** [comment]
It will change something, and this will get fixed. I agree with you completely.

**Comment by TumeniNodes** [comment]
I hope "fixing" it, will allow both options to remain?

**Pull request closed without merging**
