### PR TITLE
New appletree schematic

### PR DESCRIPTION
**Pull request by paramat**
I have been unhappy with the appletree schematic for a long time.
Screenshot shows a version with no per-node probability to show the form better (and no height variation). The PR has some of the outer leaves with probability 223 (7/8).

screenshot_20180815_014154

^ Sorry for opaque leaves but this shows the form better

Decoration density is reduced by the ratio of new to old tree schematic areas.

### CODE REVIEW

**Comment by Fixer-007** [comment]
No idea about those...

**Comment by paanrama** [comment]
It is a pretty little tree, but I think it can have more fruit positions (maybe it can be done on external leaves). 

Also can be an opportunity to use a slightly ligther green in the leaves.

**Comment by Fixer-007** [comment]
Updated comment: it simply feels like big same-looking umbrella, needs more variability?

**Comment by Napiophelios** [comment]
when walking around gathering things
you don't really notice much of a change;
but when you fly around, especially over dense areas,
its a more "aesthetically pleasing landscape".

:)

**Comment by paramat** [comment]
Fixer:
> All screenshots show a version with no per-node probability to show the form better. The PR has some of the outer leaves with probability 223 (7/8).

**Comment by paramat** [comment]
PR updated to version with height variation.

screenshot_20180819_193132

screenshot_20180819_193451
```

local M = {name = "default:leaves", prob = 255}
local N = {name = "default:leaves", prob = 223}
local F = {name = "default:apple", prob = 63}
local Y = {name = "default:tree", prob = 255, force_place = true}

mts_save("new_apple_tree_rand_slice", {
	size = {x = 7, y = 8, z = 7},
	data = {
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, N, M, N, _, _,
		_, _, _, N, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,

		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, M, M, F, M, M, _,
		_, N, M, M, M, N, _,
		_, _, N, M, N, _, _,
		_, _, _, _, _, _, _,

		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		N, M, _, _, _, M, N,
		_, M, Y, _, Y, M, _,
		_, N, M, M, M, N, _,
		_, _, _, N, _, _, _,

		_, _, _, Y, _, _, _,
		_, _, _, Y, _, _, _,
		_, _, _, Y, _, _, _,
		_, _, _, Y, _, _, _,
		M, F, _, Y, _, F, M,
		N, M, _, _, _, M, N,
		_, M, M, M, M, M, _,
		_, _, N, M, N, _, _,

		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		N, M, _, _, _, M, N,
		_, M, Y, _, Y, M, _,
		_, N, M, M, M, N, _,
		_, _, _, N, _, _, _,

		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, M, M, F, M, M, _,
		_, N, M, M, M, N, _,
		_, _, N, M, N, _, _,
		_, _, _, _, _, _, _,

		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
		_, _, N, M, N, _, _,
		_, _, _, N, _, _, _,
		_, _, _, _, _, _, _,
		_, _, _, _, _, _, _,
	},
	yslice_prob = {
		{ypos = 2, prob = 127},
	},
})
```

**Comment by paramat** [comment]
Added sapling version and updated table docs. Will do final test.

**Comment by paramat** [comment]
Had an idea to move 2 opposing branches down a node for a more interesting structure. A little like how the acacia tree has 2 branches a node lower.

screenshot_20180820_002536

screenshot_20180820_001947

screenshot_20180820_002256

I find this helps make the taller version not seem so high off the ground, because 2 branches are lower. The branches are now more visible from the side.

**Comment by Fixer-007** [comment]
Can you place branches more randomly somehow?

**Pull request merged**
