### PR TITLE
Default: Add cracked sandstone brick for dungeons

### PR DESCRIPTION
**Pull request by paramat**
Now that we have sandstone dungeons and have always had the ability to change some dungeon nodes into a modified state (like mossycobble) it would be good to have an alternative node for the sandstone dungeon structure. Cracked sandstone brick in dungeons has been an intention of hmmmm's for years.
Also good for building ancient sandstone ruins, pyramids etc.

WIP as texture needs improvement.

### CODE REVIEW

**Comment by C1ffisme** [comment]
That texture needs to look more like cracks. At the moment, it doesn't look very crack-like.

Something like this:

crack

**Comment by paramat** [comment]
Yeah they need to be darker, waiting to see them tiled before revising.

**Comment by paramat** [comment]
Yeah i might add 1 or 2 more cracks, waiting to judge it when tiled.

**Comment by Fixer-007** [comment]
Don't like the texture.

**Comment by benrob0329** [comment]
I personally like the texture, but perhaps it would look better withought the extra dark pixel.

**Comment by ExeterDad** [comment]
Since these are bricks, I have to disagree with @C1ffisme. The cracks would be less realistic if they spanned the bricks and motar. It may need some refining, but I think @paramat is on the right track.

**Comment by C1ffisme** [comment]
@ExeterDad They need more cracks than the current texture... At least a horizontal one.

**Comment by paramat** [comment]
Bricks are horizontally elongated so cracks are likely to be more vertical than horizontal due to mechanical stresses. They don't tend to be finely cracked into many small pieces.

**Comment by paramat** [comment]
screenshot_20160617_010033

Difficult texture.

**Comment by C1ffisme** [comment]
@paramat It depends on the kind of damage it has sustained. It could be that a battle has happened in here, or rubble from the ceiling smashed into the wall. It might even be water-based damage.

Besides that, why are we so concerned about how real a texture looks in a game where every texture is 16x16 pixels? (Excepting, of course, textures for meshes/models for obvious reasons.)

**Comment by paramat** [comment]
I think i'll add some highlighting to these to make them look more 3D and more like broken brick fragments.

**Comment by sofar** [comment]
Perhaps try to make at least one side-to-side connection so it looks a bit less tiled.

**Comment by paramat** [comment]
Yeah.

**Comment by Fixer-007** [comment]
Looks too simple and repetitive? Hard to judge for sure.

**Comment by tobyplowy** [comment]
@paramat i made this 
crack
default_desert_stone_brick
default_stone_brick
and upscale/tile
crack

**Comment by paramat** [comment]
Conflicts and is a small PR, so will open a new PR once i have a texture.

**Pull request closed without merging**
