### PR TITLE
Add screwdriver callbacks, and code them for doors and beds

### LINKED ISSUE #451: Using screwdriver on doors or beds seperates them
If you use a screwdriver on a door node or the “back” portion of a bed, only one part of the object actually rotates, resulting in weird floating half-doors and mis-aligned half-beds.

Maybe the screwdriver mod should allow nodes to defend themselves against rotation or to somehow react on an attempted rotation with an optional callback function in the node definition, by extending the subgame API.
The beds and doors should then implement these functions to handle these rotations.

Screenshot: https://i.imgur.com/L70diSa.png

### PR DESCRIPTION
**Pull request by Novatux**
Fixes #451

### CODE REVIEW

**Comment by ShadowNinja** [comment]
* The function should be more generic.  It should be called `on_rotate` and should use a generic indicator of what rotation will be done.
  * The documentation should be in the mod's documentation, instead of being grouped together with the whole game.

**Comment by Novatux** [comment]
@ShadowNinja: changed the name of the function, and added a new argument that is the param2 that would have been set if on_rotate wasn't there. However, I kept the documentation in game_api.txt because that is where the documentation of all mods are.

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/2824562dc94da588fd2bc21415bbc193972d93a0

**Comment by ShadowNinja** [comment]
This still isn't really generic because the `mode` argument depends on the screwdriver mod.  You have to define its values.  You could use a string instead of an int to make it more readable.

**Pull request closed without merging**
