### PR TITLE
Shorten chest open/close sounds.

### PR DESCRIPTION
**Pull request by jastevenson303**
Good for opening multiple chests one after another, omits some creaking, the length is shortened.  Further modification can be made.

### CODE REVIEW

**Comment by paramat** [comment]
I agree that our current chest sound has a little too much squeak to it.
Related #1824

**Comment by TumeniNodes** [comment]
these sound, and work well. I'm glad some squeak/creak was left in. +1

**Comment by paramat** [comment]
The open sound is much better, i don't like the end of the current creak, too long too (sorry sofar).
The close sound is fine too.

**Comment by jastevenson303** [comment]
>I assume the volume is unchanged?

Correct, only the length of the sounds were adjusted.

**Comment by paramat** [comment]
:+1:

**Comment by DS-Minetest** [comment]
Imho the squeak sounds good. :-1:

**Comment by TumeniNodes** [comment]
@jastevenson303 
I think, if you redo the close file, leaving a bit of the creak (reverse of the open file) and shorten it the same, this would probably push through quickly ; )
Seems some like the creak on both open and close. Which sort of makes sense. But the shorter sounds work well

**Comment by jastevenson303** [comment]
Yep, I just trimmed the originals a bit to suit, and tried it in-game and felt it was "good enough."  Then I created this pull request so that I could favorite minetest on my github dashboard.

Anywhos, I will gladly try your recommendations @TumeniNodes and post a link back here when I do.

My thinking behind these here open/close sounds was: slowly opening chest = creak; quickly slamming shut = thud.  I can totally get behind creaking on open and close and focus more on simply reducing duration, without altering so much of the "apparent" sound.  Thanks.

**Comment by paramat** [comment]
Since you seem to be updating, removed my +1, but will probably re-add it later.

**Comment by jastevenson303** [comment]
Updated @paramat @TumeniNodes @DS-Minetest 

screenshot from 2017-09-20 02-52-37

**Comment by jastevenson303** [comment]
@paramat please remove the wip label.  Thanks in advance.

**Comment by paramat** [comment]
:+1:

**Comment by NewbProgrammer101** [comment]
If this PR is approved, then why is it not being merged?????

**Comment by paramat** [comment]
PRs require 2 approvals from MTG core devs.

**Comment by NewbProgrammer101** [comment]
There are two approvals now.

Merge?

**Comment by paramat** [comment]
@NewbProgrammer101 please stop the unnecessary spammy comments, thnk you.

**Comment by NewbProgrammer101** [comment]
Fine.

**Comment by paramat** [comment]
Deleted the unnecessary comment.

**Comment by paramat** [comment]
7c3854de27d75defcaf91b4a4638387451bc1b65

**Pull request closed without merging**
