### PR TITLE
comment out combine slabs code

### PR DESCRIPTION
**Pull request by TumeniNodes**
We had talked about removing the code to combine slabs, in the last PR.

I think it best to simply 'comment out' those lines of code, so it leaves the feature accessible to server owners, and even end users, without having to rewrite the code.

### CODE REVIEW

**Comment by TumeniNodes** [comment]
How is 
`-- Slab facedir to placement 6d matching table
local slab_trans_dir = {[0] = 8, 0, 2, 1, 3, 4}`
impacted when this portion of the code is commented out?

**Comment by paramat** [comment]
`slab_trans_dir` is not affected because it's a function that is called. It's only called from the slab combine code so can also be removed.
I will approve removing the slab combining code, but not commenting it out. If code is not wanted in MTG it should be deleted. If the option was worth keeping it would have a setting added (but i would dissapprove that).

**Comment by Ezhh** [comment]
Full agreement with paramat. (Was actually about to post the same thing, but he was quicker.)

**Comment by TumeniNodes** [comment]
Ok, all removed then.

**Comment by Ezhh** [comment]
This shouldn't change crafting recipes at all - only auto-combining of slabs.

**Comment by paramat** [comment]
> You do still want the ability to craft a full node from two slabs left in though, correct?

Correct :]

**Comment by paramat** [comment]
Sorry hit wrong button.

**Comment by paramat** [comment]
:+1:

**Comment by TumeniNodes** [comment]
Thank you, again

**Comment by Fixer-007** [comment]
Can you explain better what was done in this PR/merge?

**Comment by paramat** [comment]
The code that causes a slab placed on a slab to automatically transform into the full cube version if the slabs are identical.

**Pull request merged**
