### PR TITLE
PB&J Pup: Remove mod

### PR DESCRIPTION
**Pull request by paramat**
Also delete nyancat API documentation from game_api.txt.
//////////////////////////////////////////

Addresses #1685 

I think the mod is well designed and coded, but feel it should be a separate optional mod.
I apologise to VanessaE and Sofar for this.
Those who loved the nyancat will be installing that now separate mod, those who didn't will not need an alternative in MTGame.
No aliases so that those who have been generating the PB&J Pup mod have their nodes preserved.

### CODE REVIEW

**Comment by sofar** [comment]
:+1:

no harm in removing this, it was added in this very cycle anyway.

**Comment by SmallJoker** [comment]
Nothing against removing it from MTG from my side.
@sofar it's quite sad to see that this work will be gone, thus I'd appreciate if it could be released as a regular mod. Just for those who would like to have their nyancat back in an alternative way.

**Comment by VanessaE** [comment]
If you want to delete it from mt_game, so be it.

If someone wants to import the PB&J Pup into some other mod, I'm fine with that (I think tenplus1 has a partial mod for this).

**Comment by paramat** [comment]
Yes certainly, please store this mod in Minetest Mods or somewhere prominent, as an 'official separate mod'.

**Comment by paramat** [comment]
Nore is neutral too.

**Comment by paramat** [comment]
d68d2c08ef1bef29b2d38520a26576cb301afe08

**Comment by VanessaE** [comment]
RIP, PB&J Pup :cry:

**Comment by XtremeHacker** [comment]
Still available if you want it, just not included by default.

**Comment by sofar** [comment]
See

https://github.com/minetest-mods/pbj_pup

**Pull request closed without merging**
