### PR TITLE
Bucket: Register river water and add texture

### PR DESCRIPTION
**Pull request by paramat**

### CODE REVIEW

**Comment by PilzAdam** [comment]
So we have two completely different water types now? At least add a common group to the buckets...

**Comment by paramat** [comment]
Yes. Okay i will add a 'water bucket' group to the water buckets, when i work out how to do this, good idea.

**Comment by paramat** [comment]
I added a 'groups' field to bucket registration, it seems to be backwards compatible with registrations missing this field (because the mod runs okay) but i'm not sure, any comments on the implementation?

**Comment by LeMagnesium** [comment]
The implementation seems fine : 

    groups = groups,

When this line in the table is reached, `groups` (affected to the `groups` field) is nil when not provided to the registration function, but a nil field isn't a problem in a table.

**Comment by Novatux** [comment]
Looks good

**Comment by paramat** [comment]
Approved by sfan5 on IRC http://irc.minetest.ru/minetest-dev/2015-06-13#i_4286112

**Comment by paramat** [comment]
c4fb5bd385961e1ed2da9d0826af13cadde58265

**Pull request closed without merging**
