### PR TITLE
Allow mossy cobble slabs to combine (#1790).

### LINKED ISSUE #1790: Mossycobble slabs to not combine.
This makes it is impossible to place one stairs:slab_mossycobble on top of another.

Steps to reproduce.

1. Place a stairs:slab_mossycobble on the ground (default horizontally).

2. Try to place another one on top of it and see that nothing happens.

### PR DESCRIPTION
**Pull request by jhcole**
Fix #1790

### CODE REVIEW

**Comment by sfan5** [comment]
:+1:

**Comment by SmallJoker** [comment]
:+1:

**Comment by paramat** [comment]
:-1: 
That was nil for a reason https://github.com/minetest/minetest_game/commit/2199be51087d0d9661d1b3f80c0bb2a55410458b will revert until another way to combine mossy slabs can be coded.

**Comment by paramat** [comment]
Well, i'm neutral and this fixes a bug, so no problem.

**Pull request merged**
