### PR TITLE
Move chests to a new file. Update credits for chests and torches

### LINKED ISSUE #2149: Move torch.lua credits and license to correct place. Also, chest suff
Currently in torch.lua.

### PR DESCRIPTION
**Pull request by paramat**
Move chests to a new file. Update credits for chests and torches

Move chests code out of nodes.lua and into a new file.
Credit torch code, and chest and torch models in README.txt.
Remove 'torches' mod text from torch.lua.
Minor cleanups in README.txt.
//////////////
Closes #2149

### CODE REVIEW

**Comment by paramat** [comment]
Agreed, will update.

**Comment by TumeniNodes** [comment]
just to ask, why not just it's own mod entirely? code and media

**Comment by paramat** [comment]
Updated as requested and tested.

Tumeni i agree, however that is difficult and messy to do for various reasons. We are very keen on making MTG as modular as possible, have split off what we can and make new stuff separate mods.
See #726

**Comment by TumeniNodes** [comment]
As much as I dislike overrides, they could be justified in this case.
But I agree with your statement

**Pull request merged**
