### PR TITLE
Faster find snow near sapling

### PR DESCRIPTION
**Pull request by tenplus1**
This is a quicker way to find snow near pine sapling.

### CODE REVIEW

**Comment by paramat** [comment]
:+1:
I was wrong about 'find nodes in area' being faster for leafdecay. 'find node near' searches outwards through shells of increasing radius and returns on finding the first one. 'find nodes in area' aways searches through the entire volume and returns a list of all positions.

**Comment by tenplus1** [comment]
Yup :) took a 1000 loop check to find that out on my side :P

**Comment by rubenwardy** [comment]
:+1: untested but checked against api docs

**Comment by paramat** [comment]
1b745d401df6a5fda7845dd080f0f0bdb948b4c8

**Pull request closed without merging**
