### PR TITLE
Default: Add coral nodes and death ABM

### PR DESCRIPTION
**Pull request by paramat**
Original code by Sofar.
Textures by Pithydon.
Exposure to air converts live coral to coral skeleton.
Live corals drop coral skeleton.
//////////////

screenshot_20161012_015445

screenshot_20161012_015720

New PR for part of #1160 
Mapgen code comes later. Coral colonies in warm seas are intended for 0.4.15.
As Sofar's PR except: i added Pithydon's orange coral, and used different node names.

### CODE REVIEW

**Comment by paramat** [comment]
I'm starting work on the new biome system, having the nodes merged will help a lot, then i can work with them in mapgen.

**Comment by sofar** [comment]
The orange coral looks nice. :+1: I don't care about the node naming much, assuming it's reasonable enough.

**Comment by pithydon** [comment]
This is not important but carols are not plants.

**Comment by paramat** [comment]
Indeed, they're plant/animal. Perhaps i'll add a special title for them.

**Comment by paramat** [comment]
3d26b33e5bad60ebb4fe459e011abefe130dbc3b

**Pull request closed without merging**
