### PR TITLE
Bones: New textures

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160709_192827

screenshot_20160709_192805

skull2128

torso2128

legs2128

arms2128

The current bones have no relation to the player model.
Background is dirt texture made grey scale and high contrast to feel similar to before.
Skeleton size matches player model in terms of pixels (actual player model is slightly smaller due to how it is scaled).
Skull eyeholes match most skins.
Base has no bones, just background.
Bones colour sampled ffrom previous textures.
Darker grey on skull is to suggest a jaw.
Darker grey on torso is the more distant spine, to differentiate it from the front of the ribcage.
Texture names unchanged to avoid breaking any mods dependent on them.

Another commit will make bones not ground content and cleanup code.

Old bones ..

screenshot_20160709_213814

### CODE REVIEW

**Comment by Fixer-007** [comment]
Interesting...

**Comment by DonBatman** [comment]
I like the texture better than existing but would rather the node be nodebox or meshnode. Having bones as a cube seems silly to me when better is possible.

**Comment by rubenwardy** [comment]
I'd much prefer a grave stone

**Comment by DonBatman** [comment]
I changed my mind. I think a gravestone would be better.

**Comment by paramat** [comment]
I dislike gravestones, not half as cute or full of character as a skeleton, the one now used in MC is so boring.
People build with bones cubes and use the skull as decoration so it should stay a simple cube, it's also a cute part of Minetest's character.
Meshnodes have no smooth lighting, are more complex to render and look less a part of the world, we should continue to resist nodes being changed to meshnodes.

**Comment by C1ffisme** [comment]
> I dislike gravestones, not half as cute or full of character as a skeleton, the one now used in MC is so boring.

The one what used in MC? The one gravestone used in MC? (Minecraft doesn't have a gravestone, you drop your items on death.) The one skeleton used in MC? (That's a mob.)

**Comment by rubenwardy** [comment]
I find the current bones very very ugly

**Comment by paramat** [comment]
I agree.

**Comment by paramat** [comment]
:+1: from nore http://irc.minetest.ru/minetest-dev/2016-07-10#i_4646786

**Comment by SmallJoker** [comment]
Too bad. I really liked the old textures because it clearly showed what it is - bones.

**Comment by Fixer-007** [comment]
It is harder for recognise it for sure

**Comment by paramat** [comment]
Heh it may look like a human skeleton but that's not suitable.

**Comment by paramat** [comment]
07141b4a2ea4892c55b1ea7d10e85e05bd73113b

**Pull request closed without merging**
