### PR TITLE
doors: make white parts of trapdoor side to wood

### PR DESCRIPTION
**Pull request by DS-Minetest**
Related: #1753 
Tested, the particles look good.

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by DS-Minetest** [comment]
Btw. if anyone wants to know, the default_wood texture in the middle is a bit moved up to make the whole texture look better.

**Comment by paramat** [comment]
Sorry, i just realised a better solution, use the trapdoor texture to fill in the white area, then all dig particles are of a trapdoor.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
7e9c5a35765406fa92a8514205156b776c0329c8

**Pull request closed without merging**
