### PR TITLE
Biomes: Remove some warm and humid biomes at altitude

### PR DESCRIPTION
**Pull request by paramat**
Remove:
Rainforest at y = 128 (cloud level).
Deciduous forest at y = 192.
Savanna at y = 256.
All with 16 nodes of vertical biome blend above.

Coniferous forests remain to provide wood resources.
/////////////////

screenshot_20180411_020012

screenshot_20180411_020508

screenshot_20180411_020918

^ The vertical blends.
Rainforest -> Savanna.
Deciduous forest -> Coniferous forest.
Savanna -> Desert.

WIP in reconsideration.

For #1993 
This is the return of #1996 but now with vertical biome blend.
'upper limit' is the y level of the base of floatlands, so floatland biomes are unaffected.

newbiomes9invert

^ Our biome system. The removed biomes are the 3 in the 'warm and humid' corner. Realistically, heat and humidity both fall with altitude so everything becomes Alpine tundra at altitude, but as discussed in the issue this would be boring for gameplay and would remove wood resources, so we only remove a few biomes.

### CODE REVIEW

**Comment by Fixer-007** [comment]
This will not affect floatlands?

**Comment by paramat** [comment]
Correct, whatever biomes are defined for the floatlands will be unaffected.

**Comment by Fixer-007** [comment]
Carpathian, interesting effect:
before PR:
default
after PR:
default

**Comment by paramat** [comment]
y = 294. Because Rainforest, Deciduous forest and Savanna have all been removed, Coniferous forest and Desert are now biome neighbours. The patches you see are just the normal horizontal biome blend occuring between those 2 biomes.

**Comment by Fixer-007** [comment]
It looks weird tbh.

**Comment by paramat** [comment]
The original PR was opened and closed 4 times, and we're still unsure about this :)

**Comment by Ezhh** [comment]
I'm leaning more toward varying decoration by height, though that of course has the issue that at least one of the surface nodes won't make sense without trees.

**Comment by paramat** [comment]
I'm still unsure about thiis, WIP. Needs more consideration and time.
I prefer to not change only decorations by altitude as then you essentially have new biomes, might as well have new biomes with the advantages of having named biomes.

**Comment by paramat** [comment]
Meh since we're so unsure best close for now for more consideration.

**Pull request closed without merging**
