### PR TITLE
Reexport the player model wiht split edges

### PR DESCRIPTION
**Pull request by TeTpaAka**
I hope this fixes it. I did what was said in https://github.com/minetest/minetest_game/issues/1846. It didn't help, so I also added a triangulate modifier and applied it.

I tested the model with the advanced lighting patch and it seemed to work. Someone else should test it, too, though. Maybe someone with more experience with exporting b3d files can look into it if it is still wrong.

### CODE REVIEW

**Comment by DS-Minetest** [comment]
>Someone else should test it, too, though.

Tested, it works.

>I did what was said in #1846. It didn't help

Hm, as I did the things described in #1848, it helped. Maybe you made a mistake.

**Comment by paramat** [comment]
Will test.

**Comment by paramat** [comment]
screenshot_20170725_221508

Fixes the issue.

**Comment by paramat** [comment]
#1848 also changes the .blend file, while this PR doesn't include that, is that the problem?

**Comment by paramat** [comment]
I prefer #1848 which works.

**Comment by paramat** [comment]
Player goes dark below y = 0.

**Comment by TeTpaAka** [comment]
If it works, I'm fine with https://github.com/minetest/minetest_game/pull/1848, so I close this PR. He probably knew better than I what needed to be done.

**Pull request closed without merging**
