### PR TITLE
Pine trees: Add small pine tree and mix into forests

### PR DESCRIPTION
**Pull request by paramat**
Pine trees: Add small pine tree and mix into forests

Use noises to create a varying mix in coniferous forest biomes:
Areas of large pines only, areas of small pines only, mixed areas.
While also having areas of high and low tree densities.
Saplings grow into large or small pines with equal chance.
///////////////////

screenshot_20180304_163315

screenshot_20180304_162445

^ Smallest and largest versions

screenshot_20180310_214640

^ Fancy leaves

Further work on #2026

### CODE REVIEW

**Comment by paramat** [comment]
Distribution might still be fine-tuned but is ready for review.

**Comment by Ezhh** [comment]
Small pines currently look too thin when using fancy leaves:
pines

**Comment by paramat** [comment]
Will make trunks 2 nodes shorter.

**Comment by paramat** [comment]
Updated, screenshot in first post.

**Comment by Ezhh** [comment]
Thank you, looks good now :+1:

**Comment by paramat** [comment]
160dc21bc14a9869fb1dcae30a2eed3f3112c004

**Pull request closed without merging**
