### PR TITLE
Schematics: Various improvements

### PR DESCRIPTION
**Pull request by paramat**
Acacia bush: Create a unique form different to normal bush, with more
leaf nodes at top than at base.
Acacia tree: Maximum height increased by 1 node. 2 extra nodes of
height variation.
Jungle tree: Add an extra node of height variation. Y-slices moved
downwards to be more balanced between trunk and branches, makes
branches more common.
Pine tree: Increase maximum height by 1 node. Add an extra node of
height variation.

Update sapling 'on place' protection checks for acacia and pine trees.
////////////////

screenshot_20180217_090335

^ The new maximum pine height

screenshot_20180217_090940

^ The new shorter acacia

screenshot_20180217_091100

^ The new maximum heght acacia

screenshot_20180217_091159

 Acacia bush has a more realistic (see below) 'inverted cone' shape now with more chance of leaves at top than at base.

69205166-beautiful-landscape-with-acacia-bush-and-hidden-antelope-in-the-kalahari-desert-at-evening-light-nam

Attends to part of #2026 plus random minor tweaks.

### CODE REVIEW

**Comment by Fixer-007** [comment]
Is it just me or some trees now literally grow through each other? Carpathian mapgen, coords and seed in pic.
default

**Comment by paramat** [comment]
That's normal and unavoidable and has always happened.
At one point we had a problem of trees growing on the exact same node, but i fixed that by adding 1 node of root.
Trees growing through each other is desirable and realistic, not doing so would look worse and make dense rainforest impossible.

**Comment by Ezhh** [comment]
Tested and seems good :+1: 
I especially like the shorter acacia trees.

**Comment by paramat** [comment]
094ad004a4f4e73928ecba64cf713f01b47ac37f

**Pull request closed without merging**
