### PR TITLE
ability to dye coloured wool white

### PR DESCRIPTION
**Pull request by tenplus1**
as above, the avility to dye coloured wool whilte again.

### CODE REVIEW

**Comment by sofar** [comment]
:+1: from a gameplay perspective, adding a consumer is always a good idea.

**Comment by rubenwardy** [comment]
Can you dye from color to color?
I think that dying should be a permanent decision, as it adds a cost to crafting.
However, if you can already dye from color to color it should probably be made consistent.

**Comment by sofar** [comment]
The wool mod uses 'group:wool' for its dye recipes, so colored wool can already be re-dyed to a new color.

Note that wool can endlessly be created (grown out of cotton) without limit, so making wool expensive isn't likely to change things.

Dyes however are almost entirely made of finite resources, like flowers, that never grow back.

**Comment by red-001** [comment]
@sofar fyi flowers *do* grow back, not using seeds but they spread over any dirt as long as there is not too many of them. This means it is possible to farm them but it is far more random and need large areas of land. In my option cotton is still more valuable as you don't find it randomly on grass.

**Comment by sofar** [comment]
@red-001

**Comment by sofar** [comment]
Actually, my wife dyes yarn professionally, and I can tell you that all yarn dye can only ever make yarn darker, not white again. Bleach may make it lighter, but yarn dyes are additive.

So from a realistic perspective, you can dye a red wool purple by re-dying it with blue dye. But you can't dye a green wool red, as that would make it black or dark gray.

Second, from a resource perspective, I actually agree that it's better to force a player to grow cotton AND make new dye for the color they want, as it's more consumptive than re-dying.

**Comment by sofar** [comment]
So I'm reversing my thumbs up. I'd actually rather have redying of wool behave like realistic wool does, where you can't redye a composite color into a primary color, etc..

**Comment by paramat** [comment]
:-1: It seems the whole wool dyeing logic is based on working from lighter to darker as is realistic.

**Comment by tenplus1** [comment]
Being only a game with floating dirt and weird water effects I dont think many players would complain about dye'ing coloured wool another colour, it would help use your current resources instead of producing waste colours you can't use :)

**Comment by Taknamay** [comment]
I don't mind if this were made consistent. As it stands, wool can be dyed any other color, so this just stands out.

**Comment by C1ffisme** [comment]
What about adding bleach?

It could add a bit of chemistry to minetest if a complicated recipe were involved, and could be a bit educational, as well add a little bit more exploration to vanilla Minetest Game.

**Comment by paramat** [comment]
Oops i misunderstood, removed my objection.

**Comment by sofar** [comment]
Yeah this is a bit of a toss-up decision. I don't know and I can't seem to make my mind up.

**Comment by tenplus1** [comment]
"Just do it!" - Shia LaBeouf

**Comment by sofar** [comment]
So how about we assume that for the default game, we don't emphasize reality and allow re-dying wool to white. Subgames can implement their own realistic dyeing scheme. We have the same situation with e.g. copper and steel already in minetest_game.

So, back to :+1: from me.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
f4512cb5b6ff3faf0f127f5a5b326823aa53f28a

**Comment by 0-afflatus** [comment]
@sofar 
> we assume that for the default game, we don't emphasize reality and allow re-dying wool to white. Subgames can implement their own realistic dyeing scheme. 

Exactly, so :open_hands: from me.

**Pull request closed without merging**
