### PR TITLE
default:code cleanup

### PR DESCRIPTION
**Pull request by TumeniNodes**
Probably needs a better name.
I went through 'default' entirely and changed all the  ' > " 

Talk about monotonous...

Going to go through the rest of the mods as well, I felt it was best to do this per mod. (unless someone feels differently) It's easy enough to just continue and add the other mods to this PR, if anything even needs to be done with those

### CODE REVIEW

**Comment by paramat** [comment]
Yes per mod is obviously best, otherwise this would be too exhausting to review.

I'll review, test and merge quickly.
This should be merged before any other PR that would cause a rebase to be required.

**Comment by TumeniNodes** [comment]
> Yes per mod is obviously best, otherwise this would be too exhausting to review.
> 
> I'll review, test and merge quickly.
Thank you

> This should be merged before any other PR that would cause a rebase to be required.
Yes... for the love of all that is holy... please. Rebasing is against my religion and morals

**Comment by paramat** [comment]
Changes look fine.

**Comment by TumeniNodes** [comment]
> Changes look fine.
> For any other PRs that do this, they can do several mods at once if the mods don't have many changes, but please keep the 'changed line count' to no more than roughly 200-250.

Yeh, this one was tedious, thank you for reviewing and testing... after about the 100th line & starts to resemble ' and looks totally normal.

Next will be up shortly

**Pull request merged**
