### PR TITLE
Beds: Improve on_rotate function

### PR DESCRIPTION
**Pull request by 12Me21**
The `on_rotate` function now checks the new param2 value to determine if a rotation is valid, rather than checking the rotation mode.
This is so screwdriver-like items with different rotation modes will not be able to rotate the bed into invalid orientations.

### CODE REVIEW

**Comment by TumeniNodes** [comment]
at line 124, shouldn't...
return false and end should be moved to their own lines in the code

line 125 return false
line 126 end
both using proper indentation

**Comment by 12Me21** [comment]
Alright

**Comment by paramat** [comment]
TumeniNodes is correct.
@sofar could you review?

**Comment by paramat** [comment]
:+1:

**Pull request merged**
