### PR TITLE
Rainforest: Add emergent jungle tree

### PR DESCRIPTION
**Pull request by paramat**
Height 20 to 32 nodes.
Dependent on chunksize >=4.
Base limited to maximum altitude y = 16.
Craft sapling from 9 jungle saplings.
//////////////////

screenshot_20180124_195532

screenshot_20180216_151923

Issues #1750 and #2026 
Design is kept as consistent to the existing jungle tree as possible.
3x3 trunk ensures a hole can be cut up the middle for a ladder.
Side branches roughly follow the phi angle rotation (137.5 degrees) seen in nature, here each branch is rotated 135 degrees relative to the one below.

bigtree2

^ Testing distribution over 2000x2000 nodes (flat mapgen so terrain is below y = 16).
Ensures occasional close clusters for multiple-treehouse builds.
Typical maximum density is 1 tree per 20x20 node area.

screenshot_20180205_025535

### CODE REVIEW

**Comment by paramat** [comment]
It seems this will have to be a separate sapling, because when planting a sapling the eventual volume of the tree is checked for intersection with protected volumes, so we need to know what size tree will result from the sapling.

**Comment by tenplus1** [comment]
You could use normal jungletree sapling with a check that looks for multiple saplings bunched together, if found then a HUGE jungletree is placed instead :)

**Comment by paramat** [comment]
I've seen that method used in MC. Problem is when placing those normal saplings each protection check volume would be the small one, so the checks would fail. We could however craft several saplings into one emergent sapling.

**Comment by paramat** [comment]
screenshot_20180125_202728

Added roots underground that taper back inwards. The purpose of this is that if this tree spawns on an edge, a steep slope or a small floating rock, the roots curl back inwards towards the edge / slope / rock and look good instead of hanging out into air.

**Comment by raymoo** [comment]
You could have size be random, but decided at planting time so protection can be checked.

**Comment by paramat** [comment]
Sapling stuff added.

**Comment by paramat** [comment]
Ready for review.

**Comment by paramat** [comment]
Will wait for testing by Ezhh.

**Comment by Ezhh** [comment]
@paramat Will try and test over the weekend.

**Comment by paramat** [comment]
WIP just needs a little more height variation, like 20-32 instead of 24-32, for more of a blend with normal trees. Will do soon.
Testing still welcome though.

**Comment by paramat** [comment]
Updated with more density variation, more height variation. See first post for distribution map.
No longer WIP.

**Comment by paramat** [comment]
New screenshot in first post, i'm fairly happy with this now.

**Comment by paramat** [comment]
Will improve sapling texture.
Will try adding some hanging leaves under the crown with lower chance.
For rarity, you were probably unlucky and were exploring rainforest with ground level above y = 16, where these cannot spawn due to their height and the top of the mapchunk. I can make these appear up to y = 32 but then they only appear with chunksize 5 (the default), i guess this is ok as few use chunksize 4 or smaller. Will do.

**Comment by Ezhh** [comment]
Perfect, thank you. With those changes it will definitely have my approval.

**Comment by paramat** [comment]
screenshot_20180216_151923

Look okay? (PR not yet updated though).

**Comment by paramat** [comment]
All changes made except updating sapling-grown version of tree, will do that if the mapgen version is approved.
The sapling texture was an experiment and unsuitable, replaced with a thicker, taller, leafier version of the jungle sapling texture.

**Comment by Ezhh** [comment]
@paramat Could you please avoid --amend when making changes? If I could easily see what changed since I first reviewed this, I would probably be able to add my approval right now, but because I can't, I don't have enough time.

**Comment by paramat** [comment]
Ok.
What i changed was:
Sapling texture.
Added extra leaves.
`if chunksize >= 4 then` to `if chunksize >= 5 then`
`y_max = 16,` to `y_max = 32,`

**Comment by paramat** [comment]
b90aabec80b427f84d0bf2da2fae9bcdfceb10ec

**Pull request closed without merging**
