### PR TITLE
Add protection support to seed placement and hoeing

### PR DESCRIPTION
**Pull request by codeandfix**
Add protection support to seed placement and hoeing

### CODE REVIEW

**Comment by C1ffisme** [comment]
Can we merge now?

**Comment by paramat** [comment]
Hi @codeandfix notifying you because a year since your last comment.

**Comment by paramat** [comment]
Looks like this has been updated with ShadowNinja's requests. I'm neutral about this, what do other devs think?

**Comment by PilzAdam** [comment]
This is important for protection to work properly. :+1:

**Comment by paramat** [comment]
Okay +1 will merge soon.

**Comment by paramat** [comment]
ff0973fa4fc3f7f5bfb4a79a1ee06df1c478e2b2

**Comment by ShadowNinja** [comment]
@paramat: None of the issues I mentioned were fixed, and you commited this with a message of just `Update api.lua`!

**Pull request closed without merging**
