### PR TITLE
Strip all remaining PNG metadata such as EXIF information and color profiles

### PR DESCRIPTION
**Pull request by mdoege**
An extension to my earlier pull request (https://github.com/minetest/minetest_game/pull/1515) about error messages, this one is just a file size optimization. It amounts to running "gm mogrify -strip" on all PNGs in minetest_game.

Processing these images should bring total PNG size down by another 58 kB (for a total savings of 114 kB).

### CODE REVIEW

**Comment by paramat** [comment]
I support doing this but need to test carefully.

**Comment by sofar** [comment]
Can we maybe not do this for every PNG but just for the 20-30 worst offenders? If the reduction is less than xx bytes, we shouldn't do this.

**Comment by mdoege** [comment]
@sofar I agree, especially because some file sizes seem to be increased (although the overall effect is a substantial decrease). Perhaps GM uses lower PNG compression by default than Gimp.

At any rate, I'm closing this pull request now; https://github.com/minetest/minetest_game/pull/1515 with the error fix should be the one to merge for now.

**Comment by mdoege** [comment]
P.S. A forum post prompted me to try optipng. As it turns out processing all PNGs with optipng brings even larger byte savings. (https://forum.minetest.net/viewtopic.php?p=246817#p246817)

before 300083
after 125217
saved 174866

More importantly, none of the PNGs seem to get larger by this. So optipng should also be considered for file size reduction if the resulting images do not produce problems in MT.

**Comment by mdoege** [comment]
P.P.S. Although it seems that optipng creates these space savings by palettizing images, so maybe that's not what we want.

**Comment by MT-Modder** [comment]
https://pnggauntlet.com/

Uses optipng (compresses) and pngcrush (removes color profiles) to make the smallest, and cleanest.

Worked for me. I was getting a bunch of errors and then cleaned my whole minetest folder.

**Comment by mdoege** [comment]
@MT-Modder Optipng creates indexed (palette-based) PNG images, which cause visual regressions in MT on some graphics cards: https://github.com/minetest/minetest_game/issues/1397 Therefore optipng is not such a good choice for cleaning up minetest_game.

**Comment by MT-Modder** [comment]
@mdoege I see. Well that's unfortunate. Glad I don't use an integrated Intel. Almost seems like a petty issue though. Besides working around a bug isn't necessarily the answer. Like the semi-transparent texture issue. What a shame.

**Pull request closed without merging**
