### PR TITLE
Remove beds/Changelog.txt & farming/API.txt

### PR DESCRIPTION
**Pull request by CraigyDavi**
- beds/Changelog.txt probably won't be updated because http://dev.minetest.net/Changelog is used instead
- The information in farming/API.txt is already documented in game_api.txt

### CODE REVIEW

**Comment by PilzAdam** [comment]
:+1:

**Comment by ShadowNinja** [comment]
I'd prefer if you removed `game_api.txt` and moved the API docs to the individual mods (since the mods are independent units).  In fact I did this, but didn't complete it and make a PR for it.

**Comment by CraigyDavi** [comment]
> I'd prefer if you removed game_api.txt and moved the API docs to the individual mods (since the mods are independent units). In fact I did this, but didn't complete it and make a PR for it.

Maybe I could do that in another PR (as this is uncontroversial whereas your suggestion could be...)?

**Comment by PilzAdam** [comment]
@ShadowNinja I think having a single file to document all the exposed API is better. I always found it difficult to find existing public APIs from minetest_game when developing mods; this document clearly helps here.

**Comment by C1ffisme** [comment]
What if we kept the ```game_api.txt``` file, and then made brief explanations of the APIs inside their mods, but ```game_api.txt``` is where you would go if you needed a more detailed explanation and some examples?

**Comment by PilzAdam** [comment]
@C1ffisme that would just be redundant? Whats the benefit?

**Comment by ShadowNinja** [comment]
@C1ffisme: The opposite sounds O.K.

**Comment by C1ffisme** [comment]
Well the thing is, if you want a brief documentation on whatever if you want to see what one function does, say you are fixing a bug in the mod, than it would be useful to find out what functions are what. If you are making a mod, you can use the main ```game_api.txt``` if you are making a mod and actually using the functions, not changing them and looking at their code.

**Comment by paramat** [comment]
+1 will merge soon.

**Comment by rubenwardy** [comment]
I'd like an overview in game_api.txt and full APIs in the mod's api.txt

**Comment by paramat** [comment]
b6c12010b1e2017a33e4f3a272edae04747cada4

**Pull request closed without merging**
