### PR TITLE
Add Backgrounds for Formspecs

### PR DESCRIPTION
**Pull request by C1ffisme**
I'm pretty sure the more asthetic people of minetest are tired of boring grey backgrounds for formspecs. These formspecs look a lot nicer, and add support for texture packs. If wanted, the textures can be changed.

Chest Background:

Chest Background

Furnace Background:

Furnace Background

Unfortunately, I'm only 13 and I can't really get onto a proper image website. So If you want screenshots, you'll have to download my fork.

### CODE REVIEW

**Comment by oleastre** [comment]
I don't know what you did with git, but it appears as if you modified every file in minetest_game; and then did a merge which resulted in several conflicts that you added as is.

I did some git magic to clean up this pull request: 
https://github.com/oleastre/minetest_game/tree/C1ffisme-add-background

If you want, I can help you updating this pull request to get something that minetest_game developers can properly merge.

**Comment by C1ffisme** [comment]
@oleastre Thanks, this is my first pull request, and I'm new to github.

**Comment by C1ffisme** [comment]
I think I'll try to close this and bring this back after doing it over.

**Comment by oleastre** [comment]
If you need help, do not hesitate to ask questions. (even on the minetest forum)

**Pull request closed without merging**
