### PR TITLE
Make flammable: flowers, grasses and several crafitems

### PR DESCRIPTION
**Pull request by Ferk**
Addresses #1338 and also allows for several items to be destroyed when they fall on lava/fire (after #1285).

This includes boats, sticks, paper, books, coal lump, wooden tools, seeds, wheat, flour, bread and cotton.

### CODE REVIEW

**Comment by sofar** [comment]
:+1:

Also add boats?

**Comment by Ferk** [comment]
Boats are included

**Comment by Ferk** [comment]
Do you think gunpowder should be flammable?

**Comment by sofar** [comment]
gunpowder, yes, that would certainly be highly flammable :)

**Comment by Ferk** [comment]
But I mean.. isn't it a bit strange that if you light up the gunpowder from one side, fire destroying the line of gunpowder would prevent the TNT from exploding?

Maybe this is another reason to have an "{{on_ignite}}" callback. Fire should trigger the {{on_ignite}} of a node instead (or in addition to) just destroying it.

**Comment by Fixer-007** [comment]
Wait, you can burn entities now? Nice!

**Comment by Fixer-007** [comment]
gunpowder is flammable.

**Comment by sofar** [comment]
Oh, I see, I was thinking about dropped gunpowder entities, not placed gunpowder nodes. Yes, you can only solve this with a callback.

**Comment by Ferk** [comment]
Minetest tnt is not flammable either.
And I can understand it's for the same reasons (it would be silly that fire would destroy the tnt without it exploding).

I've noticed there's already an `on_burn` being checked for when a flammable item catches fire, so we just need to make use of it.

I created another PR for that, also making the flint_and_steel trigger the `on_burn`: #1340

**Comment by Ferk** [comment]
I fixed the luacheck warnings, looks like dry_grass was already flammable but not green grass.

Anybody knows why? Is this perhaps intended? Green leaves are flammable, it seems strange to me that grass wouldn't, since it's basically made of leaves.

**Comment by paramat** [comment]
Yes it was intended by me, originally it was to help control forest fires, but i've changed my mind.

**Comment by paramat** [comment]
:+1:

**Comment by Fixer-007** [comment]
:+1: :fire: :fire: :fire:

**Comment by paramat** [comment]
3c9d71e6f7f770ca6039f4d43f11e319918f1916

**Pull request closed without merging**
