### PR TITLE
disallow beds destroying if used

### PR DESCRIPTION
**Pull request by bell07**
fix for #836 
Same behaviour like for chest or furnances, dissallow destroying if in use

### CODE REVIEW

**Comment by paramat** [comment]
I can still dig the bed and get stuck with this PR if player has all privs.

**Comment by bell07** [comment]
Alternative logic: Introduce new table `beds.bed_position[playername] = bed_pos` to be able to check if a bed is used.

Please note the `beds.player[name] = 1` could be removed because all use-cases could be done using checks against new beds.bed_position[playername]. My previous intention was to store the position in `beds.player[name] = bed_pos` but this would break compatibility for other mods like homedecor beds for example.

**Comment by paramat** [comment]
Just a note that the bug is low priority so we should consider benefit against complexity.

**Comment by paramat** [comment]
Tested and works.

**Comment by bell07** [comment]
I am unsure if we should remove the now redundant table beds.player.

Pro: If removed there is  no redundancy. No performance impact because just the value (int 1) is replaced by table reference (bed_pos). Ok. the bed_pos (table with 3 members) cannot be cleaned up by garbage collector till player sleep. oO
Contra: Breaks compatibility to homedecor beds and maybe other mods outsite the Minetest Game. But easy to update on homedecor site.

But waiting for dev's decidion

**Comment by sfan5** [comment]
My opinion:
Don't remove them in this PR. Later the beds api should be redesigned not to expose any tables.

**Comment by paramat** [comment]
> Don't remove them in this PR. Later the beds api should be redesigned

I agree.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
@sfan5 are you able to approve?

**Pull request merged**
