### PR TITLE
Make the player collision box settable

### PR DESCRIPTION
**Pull request by TeTpaAka**
Breaking changes with version 0.5

Corrects the player model so the feet are on ground level.

Requires https://github.com/minetest/minetest/pull/6007 to work properly.

### CODE REVIEW

**Comment by paramat** [comment]
Thanks.
We need to discuss when to make this breaking change, as many use MTdev and currently expect backwards compatibility.

**Comment by XtremeHacker** [comment]
Why should a _dev_ build expect to have backwards compatibility, the sneak code was largely changed in the dev builds between 0.4.15 & 0.4.16, so why is there problems with making the player collision box settable?

**Comment by paramat** [comment]
https://forum.minetest.net/viewtopic.php?p=278486#p278486
"We think we will start to merge breaking compat PR in 1 or 2 weeks." So in a few days.

**Comment by paramat** [comment]
Concept is approved, we tried merging the feature before but had to revert due to compatibility issues https://github.com/minetest/minetest/pull/2738

**Comment by TeTpaAka** [comment]
rebased

**Comment by paramat** [comment]
Tested here https://github.com/minetest/minetest/pull/6007#issuecomment-316852017
Approval already given in original merge.

**Comment by paramat** [comment]
886537ef50a6def0927676f1e1a7932c506fd6a6

**Pull request closed without merging**
