### PR TITLE
TNT: Avoid nan vectors

### LINKED ISSUE #1073: TNT: Server Crash
The following structure crashes the server with the following message:

```
minetest: /build/minetest-8aSVRa/minetest-201605031017/src/util/serialize.h:278: void writeF1000(irr::u8*, irr::f32): Assertion `i >= ((float)(s32)((-0x7FFFFFFF - 1) / 1000.0f)) && i <= ((float)(s32)((0x7FFFFFFF) / 1000.0f))' failed.
Abgebrochen (Speicherabzug geschrieben)
```
The last line means translated: Aborted (core image written)

### PR DESCRIPTION
**Pull request by Thomas--S**
Should fix #1073

### CODE REVIEW

**Comment by tenplus1** [comment]
Works fine for me :)

**Comment by HybridDog** [comment]
nan is 0/0, l guess this only happens if the distance is 0, if the distance is 0 no knockback should happen

**Comment by PilzAdam** [comment]
Why do you do the NAN check at the end of the function? Where do the NAN values come from?

Why is (10, 10, 10) a good value to return in this case?

**Comment by Thomas--S** [comment]
@PilzAdam: I don't know, where they come from, but I know, that they appear (see https://github.com/minetest/minetest_game/issues/1073#issuecomment-217714143 for details).

I decided to use (10,10,10) because it seems to be a good, unobtrusive average value. However, I have no problem, if someone has a better suggestion.

**Comment by Thomas--S** [comment]
@PilzAdam But it seems like @HybridDog has found a better solution: https://github.com/HybridDog/minetest_game/commit/d785f05397ef35efd1e1fe985deecf8bd8475a92

**Comment by PilzAdam** [comment]
@Thomas--S @HybridDog's solution seems better than your workaround.

**Comment by Thomas--S** [comment]
I think so, too. I will close this PR.

**Pull request closed without merging**
