### PR TITLE
add fall_damage_add_percent to farming:straw

### PR DESCRIPTION
**Pull request by cdqwertz**
You wont get so much fall damage if you fall on straw.

### CODE REVIEW

**Comment by paramat** [comment]
Is fall_damage_add_percent supported by the engine? I haven't heard of it.

**Comment by cdqwertz** [comment]
It is supported by the engine. It is also used in the game uforun and it works well.

**Comment by benrob0329** [comment]
+1

**Comment by tobyplowy** [comment]
@cdqwertz yes this is an amazing idea!

**Comment by paramat** [comment]
I support but i feel we can make this more significant by having -50% so you can fall from a significantly higher height.

**Comment by paramat** [comment]
:+1: 11 nodes doubles the height without damage.

**Comment by paramat** [comment]
Approved by nore and sfan5
http://irc.minetest.ru/minetest-dev/2016-06-16#i_4633486
http://irc.minetest.ru/minetest-dev/2016-06-16#i_4633475

**Comment by paramat** [comment]
5775c9147c71c3a110d8106afc281a1a5935219f

**Pull request closed without merging**
