### PR TITLE
Vessels: Use modified models and textures from homedecor by @VanessaE

### PR DESCRIPTION
**Pull request by red-001**
New models + textures:
screenshot_20161016_230933

### CODE REVIEW

**Comment by paramat** [comment]
:-1: Sorry, i think these are too fancy looking, in fact any mesh would be too inconsistently fancy for vessels.

**Comment by rubenwardy** [comment]
:-1: not voxel enough for my vision of MTG

**Comment by everamzah** [comment]
I can't be the only one who likes and adores the vessels mod, as it is.

**Comment by NathanSalapat** [comment]
@everamzah I like them, but I agree that they don't belong in MTG.

**Comment by C1ffisme** [comment]
Gonna have to agree with @paramat. I think if they were nodeboxes, they might be acceptable, but these are too... round.

**Comment by sofar** [comment]
I'm not in favor of using these (I'd prefer removing vessels over this PR, really).

I don't understand why the glass and bottles can even be put down as node, really, they could just be items and we'd avoid the ugliness. Sorry :)

**Comment by paramat** [comment]
Closing due to 3 disapprovals.

**Pull request closed without merging**
