### PR TITLE
Creative: Use icons for buttons.

### PR DESCRIPTION
**Pull request by kaeza**
Also adds missing tooltips for page buttons. I can remove this if it's not wanted.

Note: This comment shows the current state; comments below are for an older version.

### CODE REVIEW

**Comment by sfan5** [comment]
IMO those icons are a little too big, i'd prefer if they looked more like in the unicode PR

**Comment by Fixer-007** [comment]
Too big for me too, also, they look poorly anti-aliased.

**Comment by paramat** [comment]
Yes, now seen in a screenshot, too big and weird anti-aliasing.

**Comment by rubenwardy** [comment]
These icons should be added to https://github.com/minetest/minetest imo, and used in the main menu as well. Useful to share them

**Comment by tobyplowy** [comment]
@kaeza +1 but only if the icones can be changed with texture packs

**Comment by DS-Minetest** [comment]
@tobyplowy I think, they can, as well as every other texture in a mod.

**Comment by kaeza** [comment]
New version:

**Comment by paramat** [comment]
The arrows are fine, but the cross and search need to be pixelated in the same way, they still have weird edges that will probably be fixed by pixelation. They will be blocky but will look better,

**Comment by paramat** [comment]
The dustbin is only 16x16, maybe lower resolution will help?

**Comment by paramat** [comment]
I like it.

**Comment by paramat** [comment]
Please can you convert the textures to indexed colour for smaller files.
Also, i was thinking that the cross may look better if you add a single (3x3) pixel to the tip of each of the 4 bars to square-off the end. Perhaps you could try this and see if you like it?

**Comment by paramat** [comment]
Unfortunately new screenshots are showing ugly distortion on the icons, it's possible image icons will never look good. The dustbin is distorted too but is not so much of a problem as is dark grey.

dgasc48

**Comment by rubenwardy** [comment]
What if does it look like if you double the resolution?

**Comment by Ferk** [comment]
I think there are simply scaling issues. Did you actually made the pixel art image or just resized a bigger one?

I quickly drew a magnifier icon myself in piskel, it's 16px, you can use it.

http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgIC3sorbCAw/edit

**Comment by paramat** [comment]
The textures in this PR are 48x48, the dustbin is 16x16, both are distotred, a higher resolution might help.

**Comment by paramat** [comment]
:-1: due to distortion issues when the inventory is resized. I think the current font symbols look fine.

**Comment by sfan5** [comment]
The distortions are not too bad IMO

**Comment by paramat** [comment]
We could try increasing the resolution a bit, for example double it.

**Comment by paramat** [comment]
I tried doubling the size, no improvement of distortion, i tried 16x16 and the distortion was worse.
I'm neutral on this now though, removed my -1.

**Comment by paramat** [comment]
@kaeza the icons need converting to indexed colour.

**Comment by sfan5** [comment]
That can be done trivially on merge: `optipng -o5 -strip all mods/creative/textures/*`

**Comment by paramat** [comment]
@rubenwardy same opinion on this? We have one +1 from sfan5, SmallJoker is neutral http://irc.minetest.net/minetest-dev/2017-12-20#i_5173584 and i'm -1.

**Comment by rubenwardy** [comment]
I think it would look better if the icons were higher res

**Comment by paramat** [comment]
@sofar @Ekdohibs any comment? This has been hanging around too long.

**Comment by Ekdohibs** [comment]
I'm neutral on whether to use hi-res or low-res icons, but having the icons indeed seems like a good change to me, so :+1:.

**Comment by sfan5** [comment]
IMO this should be merged now, high-res icons can be added later.

**Comment by sofar** [comment]
I kinda like these icons. If someone wants to fine-tune them later that's OK, so, feel free to merge.

👍

**Comment by paramat** [comment]
Good, whoever merges remember to convert the textures to indexed colour on merge.

**Comment by sfan5** [comment]
dfe74948e298f6f9014e075512532c5fdd195a5e 5b57815af164325c6e6cc5cd37c68dcc9add23e8

**Pull request closed without merging**
