### PR TITLE
Fix TNT mod not calculating blast intensity.

### PR DESCRIPTION
**Pull request by red-001**
Currently the TNT mod uses a dummy value of 1 for this. Thanks to @sofar for help with this PR.

### CODE REVIEW

**Comment by paramat** [comment]
This line in lua_api.txt will need changing https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3516
Intensity 1 is now the maximum at blast centre, perhaps also mention intensity falls as inverse-square of distance.

**Comment by red-001** [comment]
@paramat  see minetest/minetest#3625

**Comment by paramat** [comment]
When distance is zero (when destroy is called for the tnt itself which has an 'on blast' function) thie PR might cause a 'divide by zero' error. If so you could do 'if dist = 0 then intensity = 1'.

**Comment by red-001** [comment]
@paramat that doesn't seem to happen but I could add a check.

**Comment by sofar** [comment]
right, perhaps doing it this way will help:

```local dist = math.min(vector.distance(bpos, npos), 0.5)```

The reason I put 0.5 in there is that 0.5 distance means the item is *within* the TNT block. It also would mean 2x amount of damage, a happy side effect ;)

Why not 1.0? Because the intensity should dissipate starting from the outer edge of the TNT block, not 0.5m away from the TNT block edge.

**Comment by red-001** [comment]
@sofar I think you mean `math.max`? I could just do `local dist = vector.distance(bpos, npos) or 0.5`. Not sure what is faster.

**Comment by sofar** [comment]
edited my comment, yes ```math.max```

**Comment by sofar** [comment]
I would do 0.5 and not 1.

**Comment by red-001** [comment]
Done.

**Comment by sofar** [comment]
Thinking about the math here again. We'd want the max to stay at 1, but the inverse square to apply from the edge of the tnt block. So we need to look at dist from 0.5 and up, such that the result is 1.0 or less.

The easiest way to do this is to offset ```dist``` by 0.5:

```
dist = math.max(vector.distance(a, b), 0.5) + 0.5
intensity = 1 / dist^2
```

resulting in intensity always being under or exactly 1.

**Comment by sofar** [comment]
I'd like my last comment to get addressed, and then I think it's OK. Please squash as well.

**Comment by sofar** [comment]
```intensity = 1 / math.pow(math.max(1, dist), 2)```

from our IRC discussion.

**Comment by paramat** [comment]
local dist = math.max(vector.distance(bpos, npos), 1.0)

Because math.pow is probably slower than x * x.

**Comment by ShadowNinja** [comment]
About intensity: I don' think 0-1 range is a good idea because the center of a TNT explosion and the center of a Mese nuke explosion have very different intensities, but they'll both get a value of 1.
A better idea, I think, would be for the maximum value to be the explosive's range (or range^2 or something like that).

**Comment by sofar** [comment]
We had a discussion on IRC and settled on not limiting the intensity at any level, but the distance would be capped at a minimum of 1.0.

Basically explosives will have a ```power``` value. TNT's power level is ```1.0```. This then results in:

```
dist = math.max(vector.distance(bpos, npos), 1.0)
intensity = power / (dist * dist)
```
For damage, we estimated this would be a good function
```
damage = 100 * intensity
```

What's left is deriving the actual search radii:
```
block_destroy_radius = sqrt(20) * power -- stops at intensity = 0.05 which is 4.4m
entity_damage_radius = sqrt(100) * power -- stops at intensity = 0.01 which is damage = 1.0
```

Now, if you make an explosive with higher power, all these functions work just fine, the explosion hole is bigger, the entities take more damage, etc. Just by making a tnt version with e.g. power = 10.

I think these base curves all work together well and they're directly derived from physics principles.

We could conceive adding a "resistance" value to blocks to make them more or less resistant against explosions, even, since we can calculate intensity pretty simply, and see if it exceeds resistance. With a higher tnt power value, the hole would get larger.

Also, smaller explosives would be possible. A power value of 0.1 could damage a person, but probably won't break any blocks, or maybe just one. All with the same set of curves and a single number.

The ```100``` number is something @red-001 proposed to also be modified, making a bomb more deadly to entities or blocks. A low value would make it break blocks, but be safer to entities, and a higher value would kill players and mobs, but make less of a hole. I'm not a fan of it, but I'd support it nonetheless, the game doesn't need to be entirely accurate of course.

**Comment by paramat** [comment]
> I don' think 0-1 range is a good idea because the center of a TNT explosion and the center of a Mese nuke explosion have very different intensities, but they'll both get a value of 1.

Agreed. The edge of the destruction radius should have constant intensity, because it's the minimum amount of intensity needed to destroy nodes, currently:
```intensity: 1.0 = mid range of regular TNT```
so lets call edge intensity 1.

**Comment by sofar** [comment]
@paramat You're making a derivative of power be the unit. From a SI perspective, that's equivalent to designing a new imperial system. Sorry, but that smells like yuck to me. Energy is expressed in Joule, Power is similarly expressed in Newton/m, etc..

The model I propose would read like a basic physics intro book. Increase power to get a bigger blast, the radius would be some square root function of the power, and everythng else falls naturally together. Even the 4.4 radius number can be tuned down to the wanted "3" number by using math.sqrt(10) as a block damage constant (e.g. 10% of the intensity a 1.0 distance, instead of 5%).

So, I strongly suggest abandoning numbers like 3 as a base radius as the Unit of power of TNT. Explosive power should be in N/m or J.

None of the internals would be exposed to mods, either, all this math would be 2-3 lines in the resulting code.

Don't be imperial and invent another foot! ;^)

**Comment by paramat** [comment]
> You're making a derivative of power be the unit

Yes but it's simple and much more meaningful to a player to use the existing radius parameter to define strength of explosion. We don't need strict science units here.

**Comment by sofar** [comment]
sigh, that's the same reason people submit things like "gnucydur"

**Comment by sofar** [comment]
Rebased and folded into #862

**Pull request closed without merging**
