### PR TITLE
Default: Make bricks edge-consistent

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160618_021455

A quick suggestion for feedback. Just stone brick to demonstrate. Can do the other textures later if popular.

3 textures used to suggest 2 bricks resting on 2 bricks, instead of the inconsistent use of a single texture we have now. Still a little messy due to mortar. Wall corners make more sense now. Appearence of brick paving from above is i feel nicer and on the right rotation allows a paving pattern.

### CODE REVIEW

**Comment by NathanSalapat** [comment]
+1 from me.

**Comment by paramat** [comment]
This has problems though. It will break texture packs and will change the appearence of existing paving.

Something i'd also like to do is make slabs actually single-piece slabs by using new textures, and stairs could become a brick on a slab. Again more texture pack breakage though.

**Comment by sofar** [comment]
Visuals are good, but, as you said, it'll break texture packs :/

**Comment by HybridDog** [comment]
What about using texture modifiers?

**Comment by RHRhino** [comment]
@paramat The new texturs look good and also make much more sense. I'd love to see them in minetest. Would it be possible to use only one side texture and rotate it upside down or would that break with the lighting of the texture?

@sofar nearly everything new added or changed breaks something in minetest, it's annoying but the only way to improve. If possible it should be avoided or at least considered if the new feature is really necessary, but it should never stop minetest from becoming better. :smile:

**Comment by Napiophelios** [comment]
maybe you should leave the original textures names' unchanged and just add your custom textures with unique names. That way texture packs wont be broken, just in need of an update.

my aligned_bricks mod attempts to do the same thing. but I used texture modifiers to try and get around the mortar issues.
https://forum.minetest.net/viewtopic.php?f=9&t=11179

**Comment by ExeterDad** [comment]
I really like the purposed change. But breaking texture packs is a showstopper.
It's too bad texture tiles couldn't be conditional.
default_improved_brick.png | default_brick.png

**Comment by Napiophelios** [comment]
they are only broken if he changes the name of the textures.
there is no reason to change the names of unaltered textures.

texture packs wont be broken..they will just be out dated which many already are.

**Comment by C1ffisme** [comment]
Why do we need to worry about any kind of community content? Any content that is still active will no doubt be updated. And if it's not active community material, then we don't really need to worry about breaking support.

**Comment by DonBatman** [comment]
I like it. Breaking texture packs is not a concern to me. The texture packs can be updated and the community will push to have them updated.

**Comment by paramat** [comment]
> you should leave the original textures names' unchanged

Yes i should have done this.
This will look better for sandstone brick and obsidian brick since tey have no mortar, i actually going to remove mortar from desert stone brick.

**Comment by yyt16384** [comment]
We should try to keep compatibility if possible, but it is fine to break if the change is good. Since this only breaks texture packs I think it is ok to make the change.

I find it ugly to have only some faces in a texture pack, so maybe we should make the texture name different. It's arguable, of course.

**Comment by paramat** [comment]
This will look a lot better if mortar is removed from stone and desert stone bricks, which i would like to do.

**Comment by paramat** [comment]
I'm removing mortar from stone bricks so this PR will be updated if we go ahead with this.

**Comment by Fixer-007** [comment]
We need to check how it works with moreblocks, x-decor cutting tools, columnia and castles mod as examples...

**Comment by Fixer-007** [comment]
You forgot to add slab and panel for it, it has no texture in mt.
I did few tests with this, I expect some mods will break with it...
Not everything is consistent:
2016-06-20 17_34_47-minetest opengl 4 5 13416
General look of rail way on top of this:
2016-06-20 17_49_35-minetest opengl 4 5 13416
Testing with moreblocks mod:
2016-06-20 17_54_55-minetest opengl 4 5 13416
Testing with xdecor mod:
2016-06-20 17_58_38-minetest opengl 4 5 13416
Testing with columnia mod:
2016-06-20 17_56_11-minetest opengl 4 5 13416

**Comment by paramat** [comment]
> Not everything is consistent:

So that is unavoidable. I'm not so sure about this PR now then. Thanks for testing.

**Comment by tobyplowy** [comment]
@paramat maybe it could be a new block (like the [stone slab](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/6/60/Double_Stone_Slab.png?version=ad3a22dc539e6f2a34199fb046c1d411) from minecraft)

**Comment by paramat** [comment]
Well i am considering adding new nodes: 'stone block' etc. which is a node-sized block with bevelled edges.

**Comment by tobyplowy** [comment]
@paramat I can't really imagine that in my head. could you show me a picture?

**Comment by tobyplowy** [comment]
@paramat thats from minecraft?

**Pull request closed without merging**
