### PR TITLE
Ability to add new Screwdrivers.

### PR DESCRIPTION
**Pull request by tenplus1**
A few screwdriver changes so that mod makers can add new screwdrivers with different wear levels.  Tried and tested with new diamond screwdriver :)

### CODE REVIEW

**Comment by tenplus1** [comment]
This pull contains the default uses as requested.

**Comment by paramat** [comment]
:+1:

**Comment by sofar** [comment]
I'm totally OK with this.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
51891122f2403abb102d149b79bdeeea5a66aa44

**Pull request closed without merging**
