### PR TITLE
Add boxes mod

### PR DESCRIPTION
**Pull request by niansa**

### CODE REVIEW

**Comment by paramat** [comment]
WIP?

**Comment by niansa** [comment]
No it's not WIP. The mod just adds some "box" blocks. They look like a empty box. Just some decoration.

**Comment by SmallJoker** [comment]
It is WIP because it obviously lacks a readme file. Moreover, what's the advantage of using this mod instead of moreblock's circular saw and node shapes that it offers?

**Comment by Ezhh** [comment]
In addition to the above:
- No license info.
- Problems with the textures (place one against another node and you'll get flickering).
- Unsuitable texture use (animated water and lava textures presented as static images...).
- No crafting recipes.

I really want to see more content added to MTG, but it needs to be suitable, and new mods need to contain all the required information (including a good reason to justify adding them).

**Comment by paramat** [comment]
Ok, thanks for the contribution, but i can't see good reason to add these, sorry :-1: 
These have no purpose as boxes, you can't store things inside them. Only the wood one makes sense, stone boxes are odd, and liquid boxes are very weird. The nodeboxes are completely flat when they could have some thickness.
I think these are best left to be optional mods.

**Comment by rubenwardy** [comment]
:-1:

**Pull request closed without merging**
