### PR TITLE
Change brake rail to red

### PR DESCRIPTION
**Pull request by hoodedice**
Apologies, I messed up a force-push and github closed the previous PR. Please see #2690 for the details of this PR.
Now has red color for all brake rails:

Screenshot from 2020-05-30 10-05-11

### CODE REVIEW

**Comment by paramat** [comment]
Although the previous textures were RGB format, please could you convert these to 'indexed alpha'?
When done i approve the PR.

**Comment by SmallJoker** [comment]
> please could you convert these to 'indexed alpha'?

I.e. Please run optipng/pngcrush on the textures to minimize the size.

**Comment by paramat** [comment]
I do not request using optipng/pngcrush programs, that may be too much to ask of some contributors.
Just convert to 'indexed' colour mode in your image editor, then export without unnecessary metadata or comments.

**Comment by paramat** [comment]
At least one texture is still in RGB mode.
if you do not know how to convert to indexed mode let us know and we can do that.

**Comment by sfan5** [comment]
I think it'd be easier for contributors if we just ran optipng on texture _ourselves_ before merging.

**Comment by paramat** [comment]
Easier, but it is still best that contributors learn to export in the correct colur format, and without unnecessary metadata. This helps them develop skills.
But yes, for some PRs we can do this ourselves.
I approve this PR if a core dev wants to convert the textures to indexed and merge.

**Comment by hoodedice** [comment]
I was just updating my fork with this repo. I tried with krita to convert to indexed and the process was a bit more detailed than necessary. Seems that gimp has a more automated flow for conversion so I'll be using that. Been a bit busy recently but if I can find some time I'll convert and push.

**Comment by hoodedice** [comment]
compressed using optipng, is this enough?

**Comment by sfan5** [comment]
That should have converted them to indexed, yes.

**Comment by paramat** [comment]
Confirmed indexed.
:+1:

**Pull request merged**
