### PR TITLE
Default: Add missing 'default_dig_snappy' sound

### PR DESCRIPTION
**Pull request by paramat**
Some nodes with the snappy group (wool, glass pane, seeds) were missing
sound when dug with a sword.
Adding the sound causes it to be used for glass pane, so define a 'dig'
sound in the 'node sound glass defaults' table, use the footstep sound.
Adding the sound also causes it to be used for seeds which deliberately
have no dig sound, so add an empty sound override for seed dig.

Reduce the gain of the glass footstep sound which was excessively loud.

Add some freesound members to license.txt.
///////////////////////////////////////////////////////

See #1430 
The 'ping ping' footstep sound at a higher gain is perfect for digging glass.

### CODE REVIEW

**Comment by sofar** [comment]
:+1: but it's not the sound I expected (I was thinking more of a box cutter cutting a sheet of paper really fast - "swish")

**Comment by paramat** [comment]
I was expecting many 'snappy' nodes to be without sound when dug with a sword, however most use the 'leaves' sound table and therefore have the leaves sound on dig. So this is not as essential as i first thought.
I hope the sound is different enough from the leaves sound to be useful.
Perhaps the most important issue here is that each of the 4 main dig groups 'cracky' 'crumbly' 'choppy' 'snappy' will now have a sound. This gives the option of using this sound instead of a leaves sound for certian nodes if desired.
The code sems to expect a sound for snappy:
https://github.com/minetest/minetest/blob/785a9a6c1af424b0a46f334de7176c9e67341cfb/src/game.cpp#L4131
```
	if (sound_dig.exists() && params.diggable) {
		if (sound_dig.name == "__group") {
			if (params.main_group != "") {
				soundmaker->m_player_leftpunch_sound.gain = 0.5;
				soundmaker->m_player_leftpunch_sound.name =
						std::string("default_dig_") +
						params.main_group;
```

**Comment by paramat** [comment]
Just saw that the dig sound for leaves is actually 'default_dig_crumbly', a dirt digging sound, not ideal.

**Comment by paramat** [comment]
So i'm not sure if this is essential enough to merge before release, will wait for feedback. Only wool is missing sound when dug with a sword.

**Comment by paramat** [comment]
Problems with this PR:
Digging with a sword: wool, glass pane and seeds all use the new sound, which is unsuitable for glass pane and should be quieter or silent for seeds.
Diggin with hand: seeds use the new sound, should be quieter or silent for seeds. Wool has a hard sound which is unsuitable (this happened before this PR too)

Solutions:
I can keep seeds silent dig by adding `dig = {name = "", gain = 0},` to the seed sound definition.

I can make glass dig sound more suitable for glass pane and all glass nodes by adding:
```
	table.dig = table.dig or
			{name = "default_glass_footstep", gain = 0.5}
```
to `function default.node_sound_glass_defaults(table)` Now all glass nodes use the 'ping ping' footstep sound when digging, which is cute and funny, as well as more suitable.

I can make wool sounds suitable with:
```
		sounds = default.node_sound_defaults({
			dig = {name = "default_dig_snappy", gain = 0.5},
			dug = {name = "default_place_node", gain = 0.5},
			place = {name = "default_place_node", gain = 0.5},
		}),
```
The footstep stays silent, which is suitable for wool and allows a way for a player to be stealthy.
The 'place node' sound is soft and suitable for node dug and place. The snappy sound is suitable for hacking at wool.

**Comment by paramat** [comment]
Updated, see first post for details of changes.

**Comment by rubenwardy** [comment]
:+1: looks (and sounds) good

**Comment by paramat** [comment]
55a16cd2c6c56e2b15b495fc5311e8cdc4ef8e47

**Pull request closed without merging**
