### PR TITLE
Dungeon loot fixes

### PR DESCRIPTION
**Pull request by sfan5**
don't squash
tested, of course

### CODE REVIEW

**Comment by paramat** [comment]
Interesting, this is similar to #2398 and a little simpler.
This won't work in mgv6, all dungeons will be 'normal', do you mind? I don't =)

**Comment by paramat** [comment]
Didn't test but :+1:

**Comment by paramat** [comment]
`minetest.get_biome_data()` probably returns nil in mgv6, does this cause an error?

**Comment by sfan5** [comment]
> This won't work in mgv6

that's okay

> returns nil in mgv6, does this cause an error?

It won't, I added an `or ""` for that case.

**Comment by paramat** [comment]
```
    * Returns the humidity at the position, or `nil` on failure.
* `minetest.get_biome_data(pos)`
    * Returns a table containing:
        * `biome` the biome id of the biome at that position
        * `heat` the heat at the position
        * `humidity` the humidity at the position
    * Or returns `nil` on failure.
```

**Comment by sfan5** [comment]
Well I guess it is then, "on failure" is not very specific though. It should mention <i>why</i> it can fail.

**Comment by sfan5** [comment]
Fixed the potential crash issue.

**Comment by paramat** [comment]
Looks good :+1:

**Pull request merged**
