### PR TITLE
Default: Remove mortar from stone bricks

### PR DESCRIPTION
**Pull request by paramat**
desstonebrick_nomort_vd25_vl25_rgb128

stonebrick_nomort_vd25_vl25_128

^ This PR

default_desert_stone_brick_mort128

default_stone_brick128

^ Current

Structures built from huge stone blocks look better, more solid and impressive without mortar.
Sandstone and obsidian brick nodes already have no mortar.

### CODE REVIEW

**Comment by kwolekr** [comment]
Could you take a screenshot of a large-scale structure such as a temple or a pyramid with and without this texture change?  That would make the decision easier.

**Comment by tobyplowy** [comment]
@ I think you should do this with normal bricks as well, i really like this, i dont like mortar.

**Comment by paramat** [comment]
Good point, structures made with huge stone blocks seem more suited to having no mortar, i'll add it as a seperate commit.
This would also make edge-matching textures look better.

**Comment by paramat** [comment]
Added updated stone brick texture as 2nd commit.

**Comment by Fixer-007** [comment]
Before:
2016-06-20 17_25_15-minetest opengl 4 5 13416
After:
2016-06-20 17_24_28-minetest opengl 4 5 13416

**Comment by paramat** [comment]
Thanks.

**Comment by kwolekr** [comment]
Yeah, the new texture does look a lot better.  :+1:

**Comment by sofar** [comment]
Agreed, this feels much more "coherent".

**Comment by tobyplowy** [comment]
The New texture looks a lot better :smile:

**Comment by paramat** [comment]
Approved by nore (by PM):
-ShadowBot- Sent 12 hours and 37 minutes ago: <nore> game#1146 looks good

**Comment by paramat** [comment]
1fafed33873ab499d9c0c44068fb2addee25b3e3

**Pull request closed without merging**
