### PR TITLE
Book textures: Replace with more original textures. Licenses: Cleanup

### PR DESCRIPTION
**Pull request by paramat**
Addresses #1970 
I have also made and added the matching bookshelf slot texture.
@CloudyProton i used CC BY-SA 3.0 for your texture.

### CODE REVIEW

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
I'm also going to move brunob.santos and tumeninodes' desert cobble texture to CC BY-SA 3.0, i found the forum thread and he is obviously fine with 3.0 but posted 4.0 in error.
Having an entire new license section for 4.0 is a pain.

**Comment by paramat** [comment]
Likewise our cobble textures should be moved from 2.0 to 3.0. The thread is https://forum.minetest.net/viewtopic.php?f=4&t=7651 and i expect the author does not mind 3.0. Will PM the author.

**Comment by BrunoMine** [comment]
I give full permission to move license to 3.0 of my textures.

**Comment by paramat** [comment]
Thanks.

Added 2nd commit to do the above. Also changed gravel from WTFPL to CC0, as part of removing all expletives from MTG.

**Comment by sfan5** [comment]
since that's just some license changes: yes my +1 still stands

**Comment by Fixer-007** [comment]
default

**Comment by paramat** [comment]
0c841771a75e6688c99814d4314d491986d7f0cb
21b3c841bdb6afe2b45dcc3d4273b27efdda7d89

**Comment by beyondlimits** [comment]
I wouldn't really care if the only originality reason was given, but the new  texture looks even better than MC one.

**Pull request closed without merging**
