### PR TITLE
Control whether leaves decay after placed in-game.

### PR DESCRIPTION
**Pull request by MT-Modder**
Hold shift while placing to preserve leaves, otherwise they'll decay like normal.
Original PR: https://github.com/minetest/minetest_game/pull/454

### CODE REVIEW

**Comment by paramat** [comment]
:-1: I prefer the original PR. It's more likely players will want to build hedges etc with undecaying leaves than to create tree schematics (which is often best done using lua tables anyway).

**Comment by MT-Modder** [comment]
If you go back and read everyone says :+1: to decay by default. I see your point though.

**Comment by paramat** [comment]
Well it was equal votes for each, but amongst the devs nore approved it being undecaying by default and ShadowNinja was sort of okay with it either way, plus i would prefer undecaying by default.
However yes wait for more consideration.

**Comment by MT-Modder** [comment]
@paramat What do you think of adding a ```placer:is_player()``` check to this function?

**Comment by paramat** [comment]
I'm not sure.

**Comment by MT-Modder** [comment]
I'm a little hesitant because I'm not entirely sure if it's needed or if it would break certain mods. If a mod like pipeworks was to place leaves it would have to choose the default option and in this case they would decay. But I would assume if someone was setting up a system like that they would place a tree under or near the placer to prevent decay...so IDK either :laughing:

**Comment by paramat** [comment]
Ok apparently that check is not needed so go ahead without it.

**Pull request closed without merging**
