### PR TITLE
Better trapdoor side appearance.

### PR DESCRIPTION
**Pull request by sofar**
We're using a normal wooden side texture to draw the sides
of trapdoors. But the side textures have only 2 edges that
have a nice texture for the 2px wide trapdoor. We can
either repaint the textures, or just rotate the texture
properly for the two sides that need it.

Because the side texture for wooden doors was just a default:wood
texture, it clashes with the colors in the trapdoor, and so
we add a wooden trapdoor-matching tile side texture as well.

This also improves the steel trapdoor side, but without a
texture change there since that was already a specially
drawn texture for that node.

We also increase the thickness of the trapdoor to 2px. Right
now the model is 0.4 large, but this causes the side textures
to look odd as there's a mismatch in pixel size. By scaling the
trapdoor side up to exactly 2px, the sides look natural.

Thanks to @kilbith for the suggestion.

### CODE REVIEW

**Comment by sofar** [comment]
@kilbith

**Comment by paramat** [comment]
:+1:

**Comment by sofar** [comment]
@paramat wrapped it nicely, thanks!

**Comment by Thomas--S** [comment]
:+1:

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.ru/minetest-dev/2016-01-20#i_4510332

**Comment by paramat** [comment]
322967d2d1c7cec46ce86beec59b7c0512f7fcc9

**Pull request closed without merging**
