### PR TITLE
Flood snow with either lava or water.

### LINKED ISSUE #1005: Liquids over snow nodes and nodeboxes
I've noticed that lava over snow block/nodebox does not affect it in any way, liquids over nodeboxes look incorrect (it is designed that way, I know).
Example:
fypznfi

Any workarounds/fixes viable?

### PR DESCRIPTION
**Pull request by sofar**
Fixes #1005

This doesn't flood snow or ice blocks.

### CODE REVIEW

**Comment by paramat** [comment]
How about also making flames floodable for faster extinguishing by fire? Although there would be no sound of course.

**Comment by sfan5** [comment]
:+1:

**Comment by ShadowNinja** [comment]
:+1:

**Comment by paramat** [comment]
Ok we'll just go with the PR as it is for now.

**Comment by paramat** [comment]
f4e77edcc6ed75cc29371b4527a6171b4679b01b

**Pull request closed without merging**
