### PR TITLE
Moss growth code cleanup

### PR DESCRIPTION
**Pull request by HybridDog**
This makes it look more like the moss in dungeons

### CODE REVIEW

**Comment by sofar** [comment]
Doesn't this make moss only spread once, after which the second moss node will always be near the first moss node.

**Comment by paramat** [comment]
:-1: for "and no other moss node is near it" it doesn't need to be patchy as in dungeons.
"Add moss only if the node is next to air" might be ok, considering.
Use of `local moss_correspondences` is good.
:-1: for `swap node`, this can only be used when we are 100% sure there is no metadata.

**Comment by HybridDog** [comment]
> Doesn't this make moss only spread once, after which the second moss node will always be near the first moss node.

No, the moss does not grow next to each other.

> it doesn't need to be patchy as in dungeons.

I think that it would look more random, thus more natural, because if it is not patchy, a large flat area full of moss can appear where the texture repeats itself regularly.

> [swap_node] can only be used when we are 100% sure metadata doesn't need clearing.

metadata should not disappear when moss grows on a node such as a chest or a sign.

**Comment by paramat** [comment]
> metadata should not disappear when moss grows on a node

That's an assumption, metadata may be added to a particular node and not wanted on the mossy version. Overuse of swap node is a common mistake, Tenplus1 does this a lot too, it should only be used in 100% certain cases, not the case here.

Large continuous areas of moss are natural, and the texture itself is patchy.
Not allowing 2 moss nodes next to each other will make it far too low density and create only isolated single mossy nodes, that will look much worse than large patches.
It will also greatly slow down the growth of moss, making the ABM effectively less efficient.

**Comment by paramat** [comment]
:-1: for "Add moss only if the node is next to air", underwater dungeons have moss. If air is required only a single thin line of moss will appear above water, againmaking the ABM less efficient and creating much less mossy nodes.

**Comment by HybridDog** [comment]
> -1 for "and no other moss node is near it" […]
Use of local moss_correspondences is good.
-1 for swap node […]
-1 for "Add moss only if the node is next to air" […]

I've applied the requested changes.

**Comment by paramat** [comment]
Thanks, no objections from me now.

**Comment by paramat** [comment]
Just noticed something, please could you update this to include stair inner/outer changing to the mossy versions?

**Comment by HybridDog** [comment]
> Just noticed something, please could you update this to include stair inner/outer changing to the mossy versions?

done

**Comment by paramat** [comment]
:+1: tested. Nice code cleanup.

**Pull request merged**
