### PR TITLE
Rename 'killme' mod to 'game_commands' and add missing files

### LINKED ISSUE #2033: Improve 'killme' mod
~~No idea why we added this, should be in builtin if it is that useful, it is not game-specific.~~
~~EDIT: It seems this might be a universally useful feature for all games so is perhaps best in builtin?~~
See https://github.com/minetest/minetest_game/issues/2033#issuecomment-414838401

### PR DESCRIPTION
**Pull request by paramat**
Closes #2033 
@Ezhh

### CODE REVIEW

**Comment by SmallJoker** [comment]
There are [two](https://forum.minetest.net/viewtopic.php?t=15078) [mods](https://forum.minetest.net/viewtopic.php?t=12771) with this name already. They're both WIP mods but former has notable fresh content. If you'd like to work around it, then "gamecommands" might be also a fitting name.

**Comment by paramat** [comment]
Ok, 'mtg_commands' to reduce chance of name conflicts?

**Comment by paramat** [comment]
Updated.

**Comment by Fixer-007** [comment]
game_commands, in case mtg gets renamed some day

**Comment by paramat** [comment]
Hmm good point thanks. Other core devs are ok with game_commands so i'll change it.

**Pull request merged**
