### PR TITLE
Add tool breaking sounds.

### PR DESCRIPTION
**Pull request by sofar**
These will autimatically play when tools break.

Requires https://github.com/minetest/minetest/pull/3605

### CODE REVIEW

**Comment by paramat** [comment]
Sounds seem okay.

**Comment by paramat** [comment]
:+1: 3605 is approved.

**Comment by sofar** [comment]
This can safely be merged without issues as it won't break anything by itself. Still need a second approval?

**Comment by paramat** [comment]
Yes i think a 2nd approval is needed, because whether a subgame uses what the engine makes possible is a seperate decision from the engine code itself.

**Comment by paramat** [comment]
Removed my +1 because the engine code is still being discussed.

**Comment by sofar** [comment]
sure

**Comment by paramat** [comment]
:+1: As 3605 seems ok.

**Comment by paramat** [comment]
This is waiting on engine 3605 which is under discussion.

**Comment by tobyplowy** [comment]
@sofar @paramat this would be a cool feature :D

**Comment by tobyplowy** [comment]
@paramat > Sounds seem okay

Pa dam tss

**Comment by tobyplowy** [comment]
@sofar @paramat this would be a cool feature :D

**Comment by sofar** [comment]
rebased.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
#3605 is merged.

**Comment by paramat** [comment]
In testing, sounds are too loud.

**Comment by paramat** [comment]
68192a17e9ce85950528778d2ff769dd4a8ec7f5

**Pull request closed without merging**
