### PR TITLE
Make fire permanent when param1 == 1, except when near water

### PR DESCRIPTION
**Pull request by bas080**

### CODE REVIEW

**Comment by C1ffisme** [comment]
This is a tiny addition. Why can we not add it in?

**Comment by C1ffisme** [comment]
@nerzhul I believe this pull has gone dead. It's a great idea, but maybe we should add it later.

Please close this.

**Comment by paramat** [comment]
+1. Permanent fire could be good for some uses, but this needs a new implementation. I think best as a separate node so it doesn't get scanned by the already slow fire ABMs.

**Comment by paramat** [comment]
Hi @bas080 notifying you because you haven't commented for 2 years.

**Comment by paramat** [comment]
See #676 and #681 discussion can continue there.

**Pull request closed without merging**
