### PR TITLE
Add sample texture with cape

### PR DESCRIPTION
**Pull request by Rogier-5**
I propose to add an example texture with cape.

screenshot_20161117_104149

NOTE: this will _not_ be the default texture. Just an additional png file that is included as an example of how to add a cape to the model.

### CODE REVIEW

**Comment by DS-Minetest** [comment]
i dont think, this has to be reported in minetest game

**Comment by sofar** [comment]
I'm ok with adding this template, and adding it here.

But please use `_` and not `-` in file names.

**Comment by C1ffisme** [comment]
Paramat talked about removing the cape altogether, but I don't remember what happened to that conversation.

**Comment by Rogier-5** [comment]
@sofar: I should have realized that... Fixed.

**Comment by DS-Minetest** [comment]
with this some players will just take the texture and replace it
maybe it would be good to
- make the cape to the texture by default
- or make a setting to enable capes

**Comment by Rogier-5** [comment]
@DS-Minetest I think that many people will prefer a character without cape. So I think it's better to not have a cape by default. However I personally wouldn't mind if the default character had a cape.

Having a cape or not is just a matter of choosing the right texture. See [this mod](https://forum.minetest.net/viewtopic.php?id=4147). I don't know if it would be possible to actually disable just the cape. Or an arm or leg for that matter. Anyway, if it's doable at all, then that would be a minetest-core change.

**Comment by paramat** [comment]
> make the cape to the texture by default
or make a setting to enable capes

I disapprove of both,

Since this is an example of how to add a cape to the player skin, if something like this is added perhaps better to include a large template with all texture sections labelled, like:

skinzones

However i'm still unsure whether something like this belongs here.

My general objection to capes is because they are a copy of something very Minecrafty, capes in Minecraft are very much associated with Minecon exclusives, so capes seem a little like distasteful copying, like Minecraft adding Mese block.

**Comment by DS-Minetest** [comment]
i agree @paramat's opinion to make a template like this
but capes arent really typical for minecraft. thats not comparable with mese

**Comment by rubenwardy** [comment]
Wouldn't this be better on the wiki?

**Comment by paramat** [comment]
Indeed i doubt this is the right place for templates.

**Comment by paramat** [comment]
ShadowNinja's opinion http://irc.minetest.net/minetest-dev/2016-11-28#i_4751640
Closing due to 3 -1s.

**Pull request closed without merging**
