### PR TITLE
Creative: New textures for less distortion

### PR DESCRIPTION
**Pull request by paramat**
Attends to #2019 
The texture scaling implementation of formspecs causes distortion, i have found the solution is to use a higher resolution texture (128px) with a slight blur that stops the scaling being so over-reactive to edges.
I find high-res textures more consistent with the inventory images.

### CODE REVIEW

**Comment by Ezhh** [comment]
This definitely looks better, though I still prefer how the buttons used to look. The images make them heavy and clunky looking to me which I don't really like, but at least that's more about personal preference than an actual flaw.

Is it possible to centre the images better so that the padding left around them is more consistent? For example, the magnifying glass icon is clearly closer to the bottom and righthand sides of the button than to the top/lefthand sides. (I know it might need to be slightly off centre for balance due to the shape of the image, but it seems too much right now).The other three buttons draw a nice line in terms of where the images end, but that one sticks out a bit too much to look right.

**Comment by Ferk** [comment]
I don't know if it'd look as good but an alternative to using big images could be using font icons.
I can see in the engine code that there are fonts compiled in with support for glyphs that could be used:

- https://github.com/minetest/minetest/blob/master/fonts/mono_dejavu_sans_28.xml#L2392   ▶
- https://github.com/minetest/minetest/blob/master/fonts/mono_dejavu_sans_28.xml#L2402  ◀
- https://github.com/minetest/minetest/blob/master/fonts/mono_dejavu_sans_28.xml#L2243  ⌕
- https://github.com/minetest/minetest/blob/master/fonts/mono_dejavu_sans_28.xml#L2485  ☓

There's both TTF fonts for when freetype is compiled in and png+xml for the fonts in without ttf support, so in theory this should be platform independent. If it isn't then that's a bug, imho.

**Comment by sfan5** [comment]
Looks much better :+1:

**Comment by paramat** [comment]
God input, i'll shift the cross up and left a little and merge.

**Comment by paramat** [comment]
Cross centralised.

**Comment by paramat** [comment]
41a4073d4c155d8286a81e7c6af6aadfd533d99b

**Pull request closed without merging**
