### PR TITLE
Change Vessels Textures

### PR DESCRIPTION
**Pull request by Thomas--S**
The following changes were made:
- Removed unneccessary inventory textures
- The drinking glass inventory image now differs from the node texture (see #1089)
- Smaller textures within the 16x16 canvas

**New Screenshot:**

**New inventory images:**

**New textures:**
Drinking Glass Inventory Image (current suggestion):

Drinking Glass Inventory Image (old suggestion):

Drinking Glass Texture:

Glass Bottle:

Steel Bottle (current suggestion):

Steel Bottle (old suggestion):

*Note: This PR replaces #1096.*

### CODE REVIEW

**Comment by Thomas--S** [comment]
Alternative texture for steel bottle:


Please tell me, what texture you prefer.

**Comment by paramat** [comment]
I prefer the alternative steel bottle, wider base.that matches the top.

**Comment by ExeterDad** [comment]
Without even seeing them within game, they look so much better! I also prefer the alternate steel bottle.

**Comment by paramat** [comment]
:+1: if alternative steel bottle texture used.

**Comment by paramat** [comment]
How about a wider opening at the top of the drinking glass? Currently it looks a little weird and doesn't match the curvature of the base.

vessels_drinking_glass_inv_wide128

**Comment by Thomas--S** [comment]
Ok. Thanks for your suggestion. I will make the changes in about half a day. I'm going to bed right now.

**Comment by Thomas--S** [comment]
Updated this PR to use the alternative steel bottle suggestion and the drinking glass inventory image by @paramat.

**Comment by paramat** [comment]
:+1:

**Comment by Thomas--S** [comment]
Minor update: Fix a little typo in README.txt

**Comment by paramat** [comment]
Approved by sfan5 http://irc.minetest.ru/minetest-dev/2016-05-20#i_4614775

**Comment by paramat** [comment]
b9422ed44e0a175278cd7e49909b385a94380e11

**Pull request closed without merging**
