### PR TITLE
Textures: Reduce contrast of snow ripples

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20170423_031438

^ Current

screenshot_20170423_032625

^ Commit

I have had many reports of players finding the snow ripples too dark, i agree.

### CODE REVIEW

**Comment by sfan5** [comment]
I still constantly confuse snow with sand, but whatever :+1:

**Comment by Ezhh** [comment]
Much better. :)

**Comment by tobyplowy** [comment]
@paramat +1 it looks alot better

**Comment by C1ffisme** [comment]
Looks good, since snow is basically just white. (Any gray would be just shading, which doesn't make a lot of sense because the texture is clearly flat.)

**Comment by paramat** [comment]
4d9fd7ad61fd9946e2ec7a09f1f107d4ef6ffedb

**Pull request closed without merging**
