### PR TITLE
Add recipe to craft clay block back into lumps

### PR DESCRIPTION
**Pull request by tenplus1**
Added a recipe to craft a clay block back into 4 clay lumps.

### CODE REVIEW

**Comment by MT-Modder** [comment]
:+1:

**Comment by C1ffisme** [comment]
Seems logical, rather than having to place it down and mine it back up.

(To anyone who replies: "What about the challenge of clay blocks being harder to make back into lumps?"

Answer: No. Just, no. Games should try to not require '_grinding_'. [e.g. Having to dig a gravel block several times to get flint. It should be a rare-ish drop, not a task for the player to suffer through.])

**Comment by paramat** [comment]
:+1: It's consistent with other materials.

**Comment by paramat** [comment]
Adding to milestone because it's simple to review.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
787ccb5747eb579a1fdb0cdad9b27e3d11ec5e67

**Pull request closed without merging**
