### PR TITLE
Added 4th lower row for creative inv, lengthened the search bar

### PR DESCRIPTION
**Pull request by Andrey2470T**
Screenshot_20191007_183125

#2509

### CODE REVIEW

**Comment by paramat** [comment]
Thanks, i'll review after release of 5.1.0.

**Comment by paramat** [comment]
Thanks, i'll review after release.

Just 1 request, please could the trash icon remain aligned to the inventory slots as before? The search buttons will have to be moved slightly to the left such that the right edge of the clear button aligns with the right edge of inventory slots.

With that done i'll probably +1 once i review and test.

**Comment by TumeniNodes** [comment]
Page indicator and back button should be realigned to the right more

**Comment by paramat** [comment]
No, those are ok and are unchanged from before.
The page number '1/14' only looks left-positioned because the screenshot is using a large game window, making the font small. With a small (1024x600) game window it is more centrally positioned.
It has to remain left positioned to cope with various game window sizes.

**Comment by paramat** [comment]
Screenshot from 2019-10-08 18-46-06

^ Master 1024x600

Indeed when on page 18 there isn't enough room even for '18/18'. '20/20' would be even worse.
So the page-back button needs moving to the left, such that its left edge aligns with the left edge of the slot above.

**Comment by paramat** [comment]
Screenshot from 2019-10-08 19-32-01

Testing PR.
Fits nicely on default/minimum game window 1024x600.
Vertical spacing of elements is good, all that needs adjusting is horizontal positioning of search, trash and page navigation, as described above.

**Comment by Andrey2470T** [comment]
> Just 1 request, please could the trash icon remain aligned to the inventory slots as before? The search buttons will have to be moved slightly to the left such that the right edge of the clear button aligns with the right edge of inventory slots.
> 
If I align the trash icon with the upper close slot and move left the clear and search buttons, I can imagine after that a little space would remain between those trash and left arrow buttons is what would look like not nice.

> One thing I will add, which may be out of scope of this PR, it would be very nice to switch through the pages of inv using the mouse wheel when hovered over.
>
Adding a scroll bar along the horizontal row would be also ok to switch the pages.

**Comment by paramat** [comment]
>  I can imagine after that a little space would remain between those trash and left arrow buttons is what would look like not nice.

I'm also requesting this:
> So the page-back button needs moving to the left, such that its left edge aligns with the left edge of the slots above and below.

See https://github.com/minetest/minetest_game/pull/2517#issuecomment-539626884

**Comment by Andrey2470T** [comment]
> > I can imagine after that a little space would remain between those trash and left arrow buttons is what would look like not nice.
> 
> I'm also requesting this:
> 
> > So the page-back button needs moving to the left, such that its left edge aligns with the left edge of the slots above and below.
> 
> See [#2517 (comment)](https://github.com/minetest/minetest_game/pull/2517#issuecomment-539626884)

Here:

Screenshot_20191010_000312

**Comment by paramat** [comment]
Needs some changes:
* The search bar, search button and search clear button are now touching, please leave the spaces between them unchanged.
* The search clear button right edge is not quite aligned with the slot right edges (as requested).
* The page back arrow button left edge is not aligned with slot left edges (as requested).
* The page number is now centred between the arrows, but this will only be centred when using the large game window you are using for the screenshot.
See https://github.com/minetest/minetest_game/pull/2517#issuecomment-539626884
Please use the default game window of 1024x600 and place the page number text box such that a page number such as '20/20' or even '100/100' will fit between the arrows.
This means that the page number text box should have its left edge close to the back arrow.

**Comment by Andrey2470T** [comment]
> Better but needs some changes:
> 
> * The search bar, search button and search clear button are now touching, please leave the spaces between them unchanged.
> * The search clear button right edge is not quite aligned with the slot right edges (as requested above).
> * The page back arrow button left edge is not aligned with slot left edges (as requested above).
> * The page number is now centred between the arrows, but this will only be centred when using the large game window you are using for the screenshot, which makes the font relatively small.
>   See [#2517 (comment)](https://github.com/minetest/minetest_game/pull/2517#issuecomment-539626884)
>   Please use the default game window of 1024x600, default font, and place the page number text box such that a page number such as '20/20' or even '100/100' will fit between the arrows.
>   This means that the page number text box should have its left edge close to the back arrow.

I don't know how to shift the current my size of the text font and the game window to 1024x600.

**Comment by paramat** [comment]
Do not set either in .conf. If .conf contains lines like:
```
screenW = 1024
screenH = 600
```
then disable them:
```
#screenW = 1024
#screenH = 600
``` 
likewise for any font size settings.

However, this is really not essential, you can improve the page number text box without altering game window size:
> the page number text box should have its left edge close to the back arrow.

**Comment by Andrey2470T** [comment]
> Do not set either in .conf. If .conf contains lines like:
> 
> ```
> screenW = 1024
> screenH = 600
> ```
> 
> then disable them:
> 
> ```
> #screenW = 1024
> #screenH = 600
> ```
I have no set those params. 

> likewise for any font size settings.
I also have no set size settings `font_size`, `mono_font_size` and `fallback_font_size`. Those don`t switch to default fonts sizes.

> the page number text box should have its left edge close to the back arrow.
What is meant by 'box'? I can not reproduce where the one`s boundaries are.

**Comment by paramat** [comment]
> What is meant by 'box'?

Sorry, i mean the formspec co-ordinates here:
```
"label[6.2,4.15;" .. minetest.colorize("#FFFF00", tostring(pagenum)) .. " / " .. tostring(pagemax) .. "]" ..
```
The page number doesn't have a 'text box', it only has a co-ordinate.
My request is that the page number is moved close to the 'back arrow' for the reasons given above.

**Comment by paramat** [comment]
@Andrey2470T i am keen to see this updated and merged, it only needs a few things moved a little.

**Comment by Andrey2470T** [comment]
Sorry, I seemed to forget about this PR and what I need to change. I'll do fixes tomorrow.

**Comment by Andrey2470T** [comment]
@paramat, I`ve made all changes which you requested:
Screenshot_20191104_002246

**Comment by sfan5** [comment]
There are lots of unrelated/incorrect changes in the pull request now.

**Comment by paramat** [comment]
Yes this looks good now, thanks.
Will review, test and probably +1 once all the unrelated changes are removed from the PR.

**Comment by paramat** [comment]
Feel free to open a new PR for this if it is difficult to clean up the mess.

**Comment by paramat** [comment]
screenshot_20191109_180531

^ With default game window size

Works fine, +1 for the relevant changes, just needs the translation changes removing from the PR.

**Comment by paramat** [comment]
@Andrey2470T

**Comment by Andrey2470T** [comment]
I`ve solved those conflicts just removed these outdated russian translations files.

**Comment by paramat** [comment]
Thanks, but now there are 82 changed files, so it got worse =)
You are welcome to redo this in a new PR.

**Comment by paramat** [comment]
@Andrey2470T

**Comment by Andrey2470T** [comment]
Well, why can you not merge it with 82 changed files? It contains just lots of appends/deletions and no matter it will contain what it should contain and make a same new PR only due to that reason...

**Comment by paramat** [comment]
This cannot be merged with unrelated and possibly unapproved changes added by accident.
I know that you have added commits to try to fix this PR, but they were unsuccessful, see the 'Files Changed' tab here https://github.com/minetest/minetest_game/pull/2517/files , those are the changes this PR makes, that should only contain the desired changes to creative inventory.

It looks like you are having difficulty with your PR branch, so i suggest making a new PR for this.

**Comment by paramat** [comment]
I will approve the PR once fixed.

**Comment by paramat** [comment]
Thanks sfan5, i will retest and approve very soon. Any more approvals?

**Comment by paramat** [comment]
Retested and fine :+1:

**Pull request merged**
