### PR TITLE
Added bugnet to butterflies if fireflies can't be found

### PR DESCRIPTION
**Pull request by Extex101**
If fireflies mod can't be found then the butterflies mod will register it's own bug net

### CODE REVIEW

**Comment by MoNTE48** [comment]
Why not combine these two very similar mods?

**Comment by DS-Minetest** [comment]
:-1: 
- Both mods can be found in minetest_game, if they are used solely somewhere else, then there can be made changes.
- An optional dependency would make sense.
- If fireflies mod can be found again, there will be dozens of unknown items.
- Why is this even needed?

**Comment by paramat** [comment]
:-1: This could result in an item duplicated in 2 mods. And aliases are best avoided.

We did consider combining these 2 mods but decided against it.

**Comment by SmallJoker** [comment]
I can see that both mods could make use of the net, but it's very unlikely to see `butterflies` used alone. Make it a hard-dependency if you really want to glue these mods together since code duplication is not necessary here IMO. :-1:

PS: You need to use the override prefix (`:`) to register content from another mod.

**Pull request closed without merging**
