### PR TITLE
Fix nil deref issue with people hitting chests too often.

### PR DESCRIPTION
**Pull request by sofar**

### CODE REVIEW

**Comment by sofar** [comment]
Fixes #1727

**Comment by sofar** [comment]
Added a second, trivial UV map fix for the backside of the OPEN chest.

**Comment by GreenXenith** [comment]
:+1: (not that my opinion matters :P)

**Comment by sofar** [comment]
It would if you tested it :)

**Comment by GreenXenith** [comment]
Tested. LGTM. :+1:

**Comment by paramat** [comment]
:+1: will trust you on this.

**Pull request merged**
