### PR TITLE
play a sound if someone tries to open a locked chest that doesn't belong to him/her/it

### PR DESCRIPTION
**Pull request by HybridDog**
sound file from http://freesound.org/people/nhaudio/sounds/192416/ (CC0), edited with audacity
https://github.com/minetest/minetest_game/pull/456/files?w=1

### CODE REVIEW

**Comment by kilbith** [comment]
Basically agree with the idea but :-1: with the sound itself, that has nothing to do with a latch sound.

**Comment by SmallJoker** [comment]
This is like the toilet from homedecor. People love to make sounds and those can get very noisy.

**Comment by HybridDog** [comment]
>People love to make sounds and those can get very noisy.

as far as l know this is realistic

**Comment by PilzAdam** [comment]
Why only a sound for this case? Chests should also have sounds when normally opening them.

**Comment by HybridDog** [comment]
>Chests should also have sounds when normally opening them.

but when someone opens the chest it looks closed

**Comment by tenplus1** [comment]
Realistic would be if owner opens chest, chest looks opened, and other players can take stuff while chest is open :))))

**Pull request closed without merging**
