### PR TITLE
Bookshelf recipe: Use group 'book'

### LINKED ISSUE #1466: make bookshelf craftable with written books
wouldnt it be more logical to craft a bookshelf with written books, too?

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #1466

### CODE REVIEW

**Comment by paramat** [comment]
But if you write a book then use it in crafting, the written book disappears :-1:

**Comment by DS-Minetest** [comment]
yes, but the empty books disappear, too
it would be more logical to craft empty bookshelves
but this wouldnt be nice to look at
and **you can also make the written book disappear by using it as fuel, its the same**

**Comment by paramat** [comment]
Hm, i guess if a player has written books they want to destroy it would be a good use. So, maybe.

**Comment by sofar** [comment]
I'm not very positive about this. Then again, I think it's weird that book shelving requires books to be crafted in the first place.

**Comment by C1ffisme** [comment]
@sofar It used to make some sense when bookshelves didn't have an inventory. (Which was also a lot more pleasant, because bookshelves didn't have extra metadata, making them free for decoration.)

**Comment by SmallJoker** [comment]
Pizza huts wouldn't be crafted with pizzas either but the possible recipe fields are limited to 3x3. A bookself is made of wood and nails. Using the books to craft it is not realistic but easy to remember for players.

**Comment by paramat** [comment]
One danger is accidently using written books to craft a bookshelf.
So i'm still neutral, unsure.

**Comment by DS-Minetest** [comment]
you have the same danger when you accidentally put a written book into furnace fuel...
the only more danger is the listring

**Comment by paramat** [comment]
:+1:

**Comment by numberZero** [comment]
Nice. Some mods define own (e.g. colored) books, this way they should become usable for crafting automagically.
Also, crafted bookshelf could retain the books (using `on_craft`) in the metadata... well, it wouldn’t be stackable then...

**Comment by paramat** [comment]
:-1: Instead i think we should change the bookshelf recipe to not need books.

**Comment by DS-Minetest** [comment]
But then it would be empty and not that nice to use as furniture.

**Comment by paramat** [comment]
Oops i forgot it contains books.

**Comment by paramat** [comment]
:-1: The bookshelf contains empty books.

**Pull request closed without merging**
