### PR TITLE
Replace Travis CI with GitHub actions

### LINKED ISSUE #2653: Change to GitHub actions
GitHub actions is faster, better and easier to use.
I think it would be nice to change to GitHub actions.

Besides, the [Minetest](https://github.com/minetest/minetest) repository is [now using](https://github.com/minetest/minetest/pull/9641) GitHub actions.

### PR DESCRIPTION
**Pull request by Panquesito7**
Closes #2653.

### CODE REVIEW

**Comment by MoNTE48** [comment]
@sfan5 up!

**Comment by Panquesito7** [comment]
Ping?

**Comment by Panquesito7** [comment]
@sfan5 @SmallJoker can you please review? Anyone else?

**Comment by Panquesito7** [comment]
Ping?

**Comment by sfan5** [comment]
I suppose the workflow won't actually run once before we merge this?

**Comment by Panquesito7** [comment]
> workflow won't actually run once before we merge this?

https://github.com/Panquesito7/minetest_game/actions

**Review by sfan5 — APPROVED** [review]
Okay looks good: https://github.com/Panquesito7/minetest_game/runs/2014291716

**Review by LoneWolfHT — APPROVED** [review]

**Comment by HybridDog** [comment]
There could be a way to make the CI much faster:
Currently installing luacheck and its dependencies takes 28 s, while executing it takes only 1 s. Overall it takes 33 s. (see https://github.com/minetest/minetest_game/runs/3703838380).
If we bundle luacheck and all its dependencies into an appimage and upload it somewhere, it would be possible to replace the luarocks luacheck installation and slow apt installation with a step which downloads the luacheck appimage and makes it executable. Since a luacheck appimage is probably quite small, downloading it should take much less than 28 s.

**Comment by Panquesito7** [comment]
> There could be a way to make the CI much faster: Currently installing luacheck and its dependencies takes 28 s, while executing it takes only 1 s. Overall it takes 33 s. (see https://github.com/minetest/minetest_game/runs/3703838380). If we bundle luacheck and all its dependencies into an appimage and upload it somewhere, it would be possible to replace the slow apt installations and luarocks luacheck installation with a step which downloads the luacheck appimage and makes it executable. Since a luacheck appimage is probably quite small, downloading it should take much less than 28 s.

I know another action that does this and runs even faster. We could use that. 🙂

**Comment by Firestar-Reimu** [comment]
How is building Appimage working now?

**Pull request merged**
