### PR TITLE
Per-tree burn times, flammability and choppy values for trees and related nodes

### PR DESCRIPTION
**Pull request by Wuzzy2**
Implements #882.

Also: Custom burn time for saplings.
Custom flammability times, “hotter” trees have higher flammability.
Acacias are harder to dig (longer time), aspen trees are easier to dig. Reason: Acacias are in remote areas and it should be hard to get wood there. Aspen trees are rather rare, so the faster digging time is seen as a “bonus” for finding some. The player might be motivated to even “farm” aspen trees later because of the reduced digging times.
All trees are still diggable by hand.

But please check for yourselves and check whether the new numbers are more or less balanced.

### CODE REVIEW

**Comment by paramat** [comment]
Some differences seem a good idea to me.

For burn times it might make more sense to have hardwoods (acacia, jungle) burning longer, softwoods shorter, including saplings, @sofar ?

I may be wrong but i don't think the flammable values are used by anything.
But assuming they are, for example by mods, @sofar what is your experience of flammability of woods? I'm tempted to consider all tree types equal in flammability, ie more similar than different considering we have only 3 levels of flammability.

**Comment by Wuzzy2** [comment]
What? I thought flammability is treated differently depending on value. Higher = burns faster. At least that's what `lua_api.txt` promised me. :-(

Also, straw has `flammable=4` the last time I've checked.

Also, I have chosen the fuel burn times loosely on the amount of wood you get from a single tree. More wood = burns shorter. It's loosely adjusted for gameplay, not neccessarily for logic or realism.

If you suggest different burn times, that means I would have to redo half of this PR because of consistency. :-(

**Comment by sofar** [comment]
I would tune for gameplay: rare trees (acacia/aspen) should burn longer, and trees that are in the densest forests (jungle, but also apple) should burn shorter. This is opposite of the actual hardness of most wood types in nature, where apple wood is usually harder, and pine is one of the softest woods around, and jungle woods are usually tropical hardwoods.

OT/separate topic:
The `flammable` group is used by the `fire` mod, but it doesn't use the value. We should certainly change that and make the `fire` mod spread fire quicker to nodes with higher `flammable` value. We could also create an `igniter = <value>` mechanism group where the igniter value is used to see if nodes can be put on fire. E.g. :

- an `igniter` value of 1 will set things on fire that are 1 node away and have flammable = 5
- an `igniter` value of 2 will set things on fire that are 1 node away and have flammable = 4, or 2 nodes away with flammable = 5
- an `igniter` value of 3 will set things on fire that are 1 node away and have flammable = 3, or 2 nodes away with flammable = 4, or 3 nodes away with flammable = 5

This way you could even have a furnace or torch be an igniter.

Maybe file a separate issue?

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/master/mods/fire/init.lua#L304
This code was disabled when we first started taming the fire mod, perhaps ignition over a distance could be re-introduced depending on combinations of 'igniter' and 'flammable' values. The node searches are much slower for larger radii so this ABM needs to trigger less often.

Currently a flame node can bridge a 1 node gap, a 2 node gap is needed to stop fire spread, perhaps we can allow rare ignition over 2 and 3 node gaps.

**Comment by paramat** [comment]
We can't give nodes bizarre properties based on rarity, Minetest node properties are fairly realistic and independent of rarity.

My requests for this PR are:
Burn times:
For trees, wood, fences and saplings: For realism make burn times longer for denser woods, shorter for lighter woods, i'll leave it to you to research the order but it looks like aspen, pine, apple, acacia, jungle (rosewood) https://cedarstripkayak.wordpress.com/lumber-selection/162-2/

Flammability:
It looks like we may be reworking the flammability/igniter stuff soon so i feel best leave any changes until then. The original issue was for burn times and dig times only.

Choppy:
For trees, woods, fences, doors, stairs: These are all choppy 2 currently (cactus and bookshelf are choppy 3). For realism, choppy 3, 2 and 1 in the order of softer woods to harder woods, not sure what the order would be but my guess is pine, aspen, apple, acacia, jungle (rosewood).

**Comment by paramat** [comment]
Also good is how the woods harder to dig reward with longer burn times.

For flammability:
Currently trees are 2, woods are 3, fences are 2, signs, ladders, doors, trapdoors 2, bookshelf 3.
A bt of a mess, woods should be 2, the same as fences, signs, ladders, doors, trapdoors.
Bookshelf 3 makes sense.

If we make a distinction between different tree types i think use values 2 and 3 according to realism, which is soft woods (aspen amd pine) being more flammable (3), harder woods less flammable (2). Then use these values for everything solid wood.

**Comment by sofar** [comment]
I'm OK with any differentiation here, so the last two comments by @paramat sound fine with me.

**Comment by paramat** [comment]
@Wuzzy2 I get the feeling you don't want to change this? if so i'll make a PR of my version.

**Comment by Wuzzy2** [comment]
Yes, please.
To be honest, I was a little bit pissed off when you posted all those change requests not in the original issue but *after* I posted the PR. So my motivation was low. :P I hope you understand.

**Comment by paramat** [comment]
Yes sorry i can understand it's annoying.

**Comment by paramat** [comment]
I corrected inconsistent wood flammability in #1270

**Comment by paramat** [comment]
#1270 is merged and partly replaces this. Burn times to be done in another commit.

**Comment by paramat** [comment]
https://github.com/paramat/minetest_game/tree/woodburntimes

But there may be a problem.
We need to support 'group:tree' so that's left in, but then each wood is a member of 'group:tree' but also has it's own unique burn time defined, so which burn time is used?

**Comment by sofar** [comment]
@paramat unsure, but I think that `getCraftResult()` loops over craft recipes to try and find a match in the list of crafting recipes, and returns if a match is found. That suggests that the *first* hit is the one that decides the output time, which means that it is dependent on the ordering or crafting recipes.

So in reality, it's probably a tossup. We may have to consider removing the `group:tree` fuel recipes to make sure this doesn't happen.

**Comment by paramat** [comment]
Thanks i'll test to see the order.

**Comment by paramat** [comment]
The specific node takes precedence over group, independent of order. So i can continue with my PR.
Group burn times are needed to support mods that use it.

**Comment by sofar** [comment]
@paramat that's nice, I'm surprised (pleasantly).

**Comment by paramat** [comment]
See #1276

**Comment by paramat** [comment]
#1276 is merged.

**Pull request closed without merging**
