### PR TITLE
rename dyelocal to dye.collection for global access

### PR DESCRIPTION
**Pull request by cornernote**
Can we get global access to `dyelocal` ?  I need it for the mini craft guide in skyblock.

I also renamed it to `dye.collection` as the string `local` didn't make sense any more.

### CODE REVIEW

**Comment by PilzAdam** [comment]
Why do you need it and how do you use it?

I am not happy with exposing this as an API, since future implementation changes may not be able to provide it. Please specify which information you need that you can't get via the `minetest.registered_*` tables.

**Comment by LeMagnesium** [comment]
[This] is the line causing the global error which led to that pull-request. It can be converted to parse `minetest.registered_items' and detect all of dye's items, even though that would slow down a bit the mod.

**Comment by PilzAdam** [comment]
@LeMagnesium then it should be rewritten; see my concerns above. The slowdown is probably not note worthy, since it's only done once at mod startup.

**Comment by Sokomine** [comment]
Many mods use dye and colored items. It is a pain for other mods (like my colormachine) to act if naming conventions do not exist and everyone calles his/her colors differently. The dye mod fails its job if it does not supply a list of commonly used dye names. dye and wool already come with the same colors but use diffrent *local* tables to store these names. So do other color-using mods. Everyone uses his/her own copy of that table. Do you honestly think that's good style? The dye mod is a helper mod for other colored items. Thus, it's necessary to know which common colors there are. And yes, there are those common colors. The mod just hides them so that everyone has to re-invent them again.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by 0-afflatus** [comment]
:+1: @Sokomine

**Comment by sofar** [comment]
I'm all for this. I was coding up colored wool and found myself copying the table in the wool mod, and then throwing up because that's just stupid - this really should be a directly accessible table that contains color names, associated Dye's and a "color name" written in a human language.

Oh and then I decided to add colored glass xpanes too. Guess I'll just copy another table, again :(

However,

I disagree on exposing the dyelocal.dyes table. It makes very little sense to expose *that* table

I want a table more like this:

colors.dyecolors = {
    { id = "gray", name = "Gray", rgb = 0x808080, dye = "dye:gray" },
}

explanation of fields:

id - needed to construct a variant item ID - e.g. "wool:carpet_<id>"
name - needed to describe a variant item: - e.g. "<name> Wool Carpet"
dye - item needed to combine in a crafting table
rgb - color value base of the dye/item. Needed to color items in formspecs (could be different format, of course, I haven't checked what makes sense for a formspec)

I do not see a need for all the dye combo's - if I want to dye an item in extcolor, I'll have the player make that extcolor first.

**Comment by paramat** [comment]
:-1: For this PR. But i agree with Sokomine and sofar that some sort of global table is needed.
Please discuss what you need in this table as modders.

**Comment by paramat** [comment]
Added gloval table to PR #898

**Pull request closed without merging**
