### PR TITLE
Snow footsteps: lower volume

### PR DESCRIPTION
**Pull request by sofar**
There were several complaints that snow footstep sounds
are too loud, and they sound as loud as e.g. a door opening.

I deamplified these by only 3dB, but that's enough to lower
them audibly enough to sound a lot softer, and more
appropriate for something that you'd expect to be a softish
sound.

### CODE REVIEW

**Comment by red-001** [comment]
+1

**Comment by sofar** [comment]
Adjusted to change gain value instead of audio file editing.

**Comment by MoNTE48** [comment]
+1

**Comment by paramat** [comment]
Will test.

**Comment by paramat** [comment]
Footstep volume seems good to me, 'dug' gain still seems to high, i tried 0.35 and liked it but now the initial 'dig' sound seems too loud.

**Comment by paramat** [comment]
For snow and snowblock i'm trying:
```
	sounds = default.node_sound_dirt_defaults({
		footstep = {name = "default_snow_footstep", gain = 0.15},
		dug = {name = "default_snow_footstep", gain = 0.3},
		dig = {name = "default_dig_crumbly", gain = 0.2}
	}),
```

**Comment by sofar** [comment]
Yes, dig sounds are still quite loud, especially if you compare it to e.g. sand dig sounds, which are very whimsy.

**Comment by paramat** [comment]
Talking of sand, the footstep is too loud too, something for another PR perhaps.

**Comment by sofar** [comment]
I wonder if we should just expand the PR to balance these out, and do it by the numbers, and not just by ear.

We can measure peak amplitudes on all the samples, and make a coherent sound volume profile, and adjust the outliers that way with some backing data.

**Comment by sofar** [comment]
@paramat updated to include your suggestion as well, which seems to fit well.

**Comment by paramat** [comment]
I'm wondering that too. It might be better to spend some time with headphoones on balancing several sounds in one go, i might do this sometime. I recommend not bothering doing it by numbers, by ear is better due to 'perceived volume' often being different to peak dB.

**Comment by sofar** [comment]
I used headphones in my testing. I mostly looked for outliers, and snow was the biggest one. I think we should just start with this PR, I didn't find any other sounds that were outliers, the rest all seemed ok.

**Comment by paramat** [comment]
Please can 'dig' and 'dug' be the same for snow as it is for snowblock? And yes i'm happy to +1 this and work on other sounds separately.

**Comment by sofar** [comment]
Made them the same. It's better, but a bit weird. Still an improvement.

**Comment by paramat** [comment]
Weird, i can't see any change in the code, the 'dig' and 'dug' lines for snowblock are not present for snow.

**Comment by sofar** [comment]
dumb me, only did snowblock....

**Comment by sofar** [comment]
@paramat I think this is what you wanted.

**Comment by paramat** [comment]
:+1:

**Comment by 0-afflatus** [comment]
'only' 3dB should make a noticeable difference. Frankly most of the samples used in minetest are appalling and need replacing. Ultimately the whole set needs working on in relationship to each other. I feel it's fatuous for me to say any more until I find time to get the microphone out, but it's been on my ToDo for a while.

**Comment by paramat** [comment]
We're now adjusting using node definition 'gain' so it's not -3dB.

**Comment by 0-afflatus** [comment]
Yes, I got that. It makes far more sense to normalise the samples and then adjust the 'gain' in the def.

**Comment by ShadowNinja** [comment]
The snow sounds are a bit loud, although I haven't checked if the specific levels in this PR are better.
The snow sounds really are awful though, they should be replaced outright.

**Comment by sofar** [comment]
@0-afflatus normalizing doesn't take into account whether the actual sound is abnormally loud or not. If you normalize the sound of someone whispering, it'll make it sound like they're talking out loud weirdly. Similarly, most people feel that footsteps in snow should sound soft and fluffy, and the snow sounds were more like frosted over snow cracking under someone's stomping feet.

I personally think the sounds are fine, but they are not fluffy soft sounds, and normalizing (I tried!) didn't meaningfully reduce the actual amplitude for them.

**Comment by 0-afflatus** [comment]
@sofar precisely. So then you adjust the gain in the def appropriately, which is the equivalent of the output fader. It means you're working on a level playing field as far as input gain is concerned and it means you can perform the final mix in-game, rather than trying to guess what it should be in an audio editor. If you adjust the samples individually then you should aim to set all the outputs to 0dB. I think that's the wrong way round.

You can't make a silk purse out of a pig's ear; most of the samples sound 'cheap' at best. The dirt footsteps are unbearable.

**Comment by 0-afflatus** [comment]
We also should set a standard (e.g. -0.1dB) to normalise to.

**Comment by sofar** [comment]
@ShadowNinja agreed that replacing sounds also helps, but perhaps we can merge this first? If this is an improvement, then letting it sit unmerged is just silly.

**Comment by paramat** [comment]
Yes this should be merged first, it takes a while to find new sounds.

**Comment by paramat** [comment]
Normalising sounds doesn't make them the same perceived loudness, that depends on how much the sound has been compressed or limited.

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.ru/minetest-dev/2016-02-21#i_4540339 will merge soon.

**Comment by paramat** [comment]
73d998ccdf73d2193b5e83f791ebbd422e2dedaf

**Pull request closed without merging**
