### PR TITLE
added new locked chest and mese crystal craft

### PR DESCRIPTION
**Pull request by tenplus1**
added new recipe for locked chest (chest + steel ingot) and mese crystal (9x mese crystal fragments)

### CODE REVIEW

**Comment by benrob0329** [comment]
+1

**Comment by C1ffisme** [comment]
I have often crafted a normal chest as a mistake, so this is a good idea.

**Comment by sofar** [comment]
neutral. wood is cheap enough, and you don't lose iron ingots by mistake.

**Comment by paramat** [comment]
Seems ok.

More useful would be https://github.com/minetest/minetest_game/issues/788#issuecomment-220759365

**Comment by paramat** [comment]
:+1: For 2nd commit.

**Comment by paramat** [comment]
:+1: For both commits.

**Comment by sofar** [comment]
Both commits are fine, but really, it's not OK to combine PRs like these IMO. You're just making it harder to get your changes merged yourself.

**Comment by paramat** [comment]
It's okay, they're affecting the same file and at least they are seperate commits.

**Comment by numberZero** [comment]
+1 for locked chest recipe
neutral on mese crystal recipe, although it is consistent with obsidian shards. Anyway, there is a separate discussion #788

**Comment by HybridDog** [comment]
to have a reason to bump this PR, my thoughts:

mese crystal recipe:
for:
* consistency with the obsidian crystal recipe

against:
* no avail in vanilla minetest (or just negligible ones)
* mods can do it
* more code
* it's a kind of spam for craft guides and similar

  
locked chest recipe:
for:
* recipe makes sense (realism)
* if you are poor (beginning playing), have a wooden chest and are getting your first steel, you can add a lock to it and don't have to collect more wood to make a second chest
* if you craft usual chests by a mistake, you can add locks to them

against:
* a bit more code
* slightly simplifies gameplay

**Comment by C1ffisme** [comment]
@HybridDog 

> a bit more code

It's not that much work to add another function call, we do much bigger code changes than this on a daily basis.

 >  slightly simplifies gameplay

Minetest is a pretty simple game right now, and even with that simplicity, people still make tutorials for people who just don't know how to play this game. This game really can't be too much more simple.

Maybe I'm misunderstanding, though. Maybe you could define 'simple'?

And for the Mese Crystal recipe:


    no avail in vanilla minetest (or just negligible ones)

Why? Mese crystals are useless right now, seems like this is a gift to those who accidentally crafted some, without looking for uses on the Minetest Wiki, etc.

    mods (with specialization on mese) can do it

Please don't say this. The [Minecraft Suggestions forum](http://www.minecraftforum.net/forums/minecraft-discussion/suggestions/44096-posting-there-is-a-mod-for-that-is-a-warnable) dislikes people saying that.

An open source project is supposed to do things by itself, while allowing the community to freely fork or modify the project. Not for the community to make content to 'finish' the project.

    more code

See above.

    it's a kind of spam for craft guides and similar

This is already a problem with blocks. Adding one more crafting recipe like this does no harm.

**Comment by HybridDog** [comment]
>This game really can't be too much more simple. […] define 'simple'?

You also don't allow farming on usual dirt, which would be realistic and simplifies gameplay.

> […] seems like this is a gift to those who accidentally crafted some, without looking for uses on the Minetest Wiki, etc.

You could remove the crystal fragment recipe instead.

>Please don't say this.

ln my experiences the devs don't want to add new stuff, l think they even don't want to make the falling entity play a sound when it sets its node and cause damage, l made a mod for this https://github.com/HybridDog/falling_extras
So you want a crystal fragment recipe to be added but not anything the fragment can be used for, don't you?

**Comment by Ekdohibs** [comment]
:+1: for chest; but I don't really like the crystal recipe: it's difficult to turn shards into a crystal... However, it raises a valid point: we need recipes that use crystal shards.

**Comment by paramat** [comment]
Obsidian shards can be reverse crafted though, as can mese crystals into blocks, so it's unrealistic but consistent.

**Comment by paramat** [comment]
@sofar do you +1 this?

**Comment by sofar** [comment]
I'm :+1: on both recipes. The shard/gem recipe is fine as well since it will allow people to reduce stack size for storage.

**Comment by paramat** [comment]
Great will merge in a moment.

**Comment by paramat** [comment]
be918d2d98b5af15f0d99b271e1e29e5c53fac2c
f15f35c6042e61f27c32eaad5d24a1b9c143110e

**Pull request closed without merging**
