### PR TITLE
Default: New jungletree_top texture

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160322_193344

new_jungletree_top_cross4ind128

^ Submitted

new_jungletree_top_octagonal5_128

^ Current

new_jungletree_top_cross5_128

^ Alternative if preferred

Improvement of the current texture, with thicker lianas.
More of a diamond shape than a round-looking octagon. It could also be thought of as a squarish trunk rotated by 45 degrees.
See #611 and #880 for discussion and explanation of the structure, there are 4 thick (4x4 pixels) lianas at the corners of the node, made clearer by blurring the side texture:

f0967c46-3e9a-11e5-9976-84a8758d5c61

rosewood-stump-and-wastage-560x260

^ Rosewood

### CODE REVIEW

**Comment by Rui914** [comment]
screenshot_20160312_144012
default_jungletree_top
How about this?

**Comment by Napiophelios** [comment]
I prefer the octagonal one to this one.

**Comment by kilbith** [comment]
Why all your PRs are privileged with a milestone while they don't really need to ?

**Comment by PilzAdam** [comment]
Is it possible to make it less symmetrical?

**Comment by Napiophelios** [comment]
I think the inner "gold" band needs to be the darker green color of the outer bark of the tree.
otherwise I think Rui's is more fitting

 default_jungletree_top
screenshot_20160312_095044

**Comment by paramat** [comment]
Napiophelios i find that and the current one too round-looking.
The bright ring is present in wenge and rosewood, which are the 2 closest matches to our jungletree.

I like the symmetry of mine because all our trunks are squarish and symmetrical. From the side texture the corner-lianas are 4 pixels wide in both dimensions, i made them square in cross section because all out trees are, this inevitably leaves a cross shape core.

**Comment by Napiophelios** [comment]
I can appreciate symmetry but it cant trump aesthetics.
Your latest proposal is very odd looking.

By putting so much detail into the vines you are detracting from the tree's core wood,
which is the point of the tree_top textures IMHO

No offense..just my opinion, but both textures (yours and mine) look more like kitchen floor tiles.


I think Rui19's proposed texture is the best suggestion thus far;
it incorporates the light color band of inner bark and the rosewood core 
and still adheres to the spirit/familiarity of the original cubic texture.

**Comment by tenplus1** [comment]
+1 for this: https://cloud.githubusercontent.com/assets/8843475/13721157/64074e7a-e860-11e5-81b4-1964a61ded97.png

**Comment by C1ffisme** [comment]
@Napiophelios 
> but both textures (yours and mine) look more like kitchen floor tiles.

That might be more of an upside than a downside. It has a creative use besides being a tree block.

**Comment by paramat** [comment]
Rui's texture ignores the lianas completely and flattens them to 1 pixel. Please read through #611 and #880 for why my textures are like this. The lianas, which i am considering to be Strangler Fig, are really thick, 4 pixels, and at each corner. It's in-character for them to have a square cross-section as all our trees do. If i made the central trunk square and smaller then there would be large areas of void seen from the top (as in our classic texture, areas of black pixels), which is difficult to blend into the side textures, this was the problem i had with my first attempt:

new_jungletree_toprgb2_128

**Comment by C1ffisme** [comment]
Currently, we are making very symmetrical textures.

However, if you look at the picture of Rosewood, it is not symmetrical in 4 directions. It's a sort of blob thing, not a circle.

**Comment by npmaier** [comment]
Longtime reader first time poster:

A blob, pixelated, would still be fitting for minetest, imo.
Also, an asymmetrical blob would fit more aesthetically with the wild
jungle vines already designed around the trunk and also the idea of a
jungle object.
Nate
--Bikemare

On Mon, Mar 14, 2016 at 11:59 AM, C1ffisme <notifications@github.com> wrote:

> Currently, we are making very symmetrical textures.
>
> However, if you look at the picture of Rosewood, it is not symmetrical in
> 4 directions. It's a sort of blob thing, not a circle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minetest/minetest_game/pull/908#issuecomment-196383182>
> .
>



-- 
"to have dismantled love in order to become capable of loving. To have
dismantled one's self in order finally to be alone and meet the true double
at the other end of the line. A clandestine passenger on a motionless
voyage." *Gilles Deleuze - Thousand Plateaus *p *197*

**Comment by paramat** [comment]
I'll try working on this to have rounded corners like our other trees.

**Comment by paramat** [comment]
Updated with lots of anti-aliasing, smoothness etc.

**Comment by ObaniGemini** [comment]
:+1: for @Rui914

**Comment by paramat** [comment]
Rui's texture, like BlockMen's, removes the lianas completely, as if they are just areas of different coloured bark, and so are inconsistent with the side texture.

**Comment by ShadowNinja** [comment]
Seems to me that the trunk should be round, not diamond-shaped.

**Comment by paramat** [comment]
I find round looks really out of place in Minetest.

**Comment by DonBatman** [comment]
@paramat if you are tweaking it can you contrast it a little more? Would look nicer for bumpmapping.

**Comment by paramat** [comment]
Updated. I think it has enough contrast, too much for some devs.

**Comment by DonBatman** [comment]
I was referring to the center section. The edges is great. If the inner part looked more like rings with a  bit of contrast then I think it would look nicer.

**Comment by ObaniGemini** [comment]
PS : I don't think adding your own approval is legit.

**Comment by PilzAdam** [comment]
@ObaniGemini it is legit.

**Comment by paramat** [comment]
I want to keep the core rings subtle like the other trees.
I'll add an alternative texture similar to the diamond one, in case the latest one is unpopular.

**Comment by paramat** [comment]
Returned to my previous submission, the diamond one, but i have left a sample of the latest one in the first post as an alternative.

**Comment by paramat** [comment]
Unpopular so closing.

**Comment by paramat** [comment]
rosewood-logs-500x500

Heh just saw this image of rosewood logs.

**Pull request closed without merging**
