### PR TITLE
Change obsidian glass drawtype to glasslike_framed_optional

### PR DESCRIPTION
**Pull request by MT-Modder**
More info held here: #383

### CODE REVIEW

**Comment by paramat** [comment]
Concerning a point in the other PR, I very much want obsidian glass to remain completely clear, it's the only default glass i use, i can't stand the shine on normal glass.

**Comment by MT-Modder** [comment]
I do as well. I just don't like having only one of the two glasses connect. It's just a personal taste.

**Comment by An-dz** [comment]
You can use the same texture for both normal & details texture this way the behaviour & look is still the same as before. It goes up to the texturepack team to choose how they want it.

**Comment by paramat** [comment]
+1 seems obvious to match normal glass.

**Comment by paramat** [comment]
f5c8f881d708fdd84a10a1ba724601b40045d0c0

**Pull request closed without merging**
