### PR TITLE
Add nil object check to boat "after"

### LINKED ISSUE #2342: Potential crash in boats mod
`mods/boats/init.lua`:

```
                 minetest.after(0.2, function()
                         player_api.set_animation(clicker, "sit" , 30)
                 end)
```
If `clicker` is gone, server goes BOOM.

Version 5.0.0.

### PR DESCRIPTION
**Pull request by misterskullz**
Fixes #2342

Added basic nil check to scheduled after functions

### CODE REVIEW

**Comment by rubenwardy** [comment]
Minetest doesn't clean up trailing references. This code is an example of the most common of the common mistakes: https://rubenwardy.com/minetest_modding_book/en/quality/common_mistakes.html

**Comment by misterskullz** [comment]
Would it be better to store player name as a string and then re-lookup clicker in the after bits?

**Comment by sofar** [comment]
No, please don't convert to string and then re-unconvert. Just pass the playerref, and after, check if it is nil:

````
function minetest.register_on_playerjoin(function(player)
    minetest.after(1, function() -- no need to pass `player` as it's already known inside the function
        if not player then
            return
        end
        print(player:get_player_name())
    end)
end)
```

**Comment by misterskullz** [comment]
@sofar, if the player disconnects will the playerref always be null / nil or could it be in some zombie state? 0.1 and 0.2 seconds is a long time.

**Comment by misterskullz** [comment]
Unrelated but related, does boats need a mod.conf file as well?

**Comment by sofar** [comment]
it will always be `nil`. guaranteed.

**Comment by sofar** [comment]
I really prefer the `nil` check on `clicker` right where the problem is. This is just lots of extra code for no reason.

**Comment by sofar** [comment]
The original commit was imho better. Needs consistent indentation though (tabs).

**Comment by rubenwardy** [comment]
It would be great if you could test this, because I was pretty sure that objectrefs contain a pointer to the object which is not freed when invalidated

**Comment by sofar** [comment]
I've used this method for resolving many of these crashes. In all cases, the ref was `nil`. The lua stack traces confirm this.

**Comment by misterskullz** [comment]
Roll the dice and go with a pointer?

Sorry about the spacing, I had no idea.  ZeroBrane let me down.

**Comment by sofar** [comment]
It's not a dice roll.

**Comment by HybridDog** [comment]
The object reference is a function parameter, which is something like a local variable in Lua.
How exactly is the reference set to nil, and are all references to the object set to nil or only this parameter?

**Pull request closed without merging**
