### PR TITLE
Default: Recolour desert cobble to be consistent with desert stone

### PR DESCRIPTION
**Pull request by paramat**
default_desert_stone128 default_desert_cobblelmind128 default_desert_stone_brick128

^ Stone. Submitted cobble. Stone brick

default_desert_cobble_128

^ Current

I colourised the stone fragments in Gimp to have hue and saturation identical to desert stone and desert stone brick. Mortar is unchanged.
Since i have only colourised, credit remains unchanged.
Adding my own approval.

### CODE REVIEW

**Comment by C1ffisme** [comment]
Hmmm... Can I see a screenshot with the new texture and desert stone next to each other?

**Comment by paramat** [comment]
You can if you do that yourself :)

**Comment by paramat** [comment]
Updated on request of sfan5 to have mortar unchanged.

**Comment by paramat** [comment]
Approved by sfan5 http://irc.minetest.ru/minetest-dev/2016-03-15#i_4557124

**Comment by paramat** [comment]
f18871d60c84cdbb68990521911c001b14c56c7d

**Pull request closed without merging**
