### PR TITLE
[REDO] Accelerate water/river water animations.

### PR DESCRIPTION
**Pull request by Andrey2470T**
I closed #2571 as this contains lots of unrelated commits. Sets animation loop length of water and river water to 0.4 since in the former PR they looked like too fast.
water_columns

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
That looks a lot nicer :+1:

**Comment by An0n3m0us** [comment]
Looks good +1
#2572

**Comment by paramat** [comment]
This PR uses 0.5 not 0.4, but 0.5 is fine.
I support the change for flowing water, but disapprove the change for water sources, it looks too fast.

**Comment by Andrey2470T** [comment]
@paramat, can it be merged now? I set animation loop length of water sources to 2.0 again.

**Comment by paramat** [comment]
:+1: thanks.

**Comment by Andrey2470T** [comment]
@paramat, can you please merge it now?

**Comment by paramat** [comment]
The delay is because PRs need 2 core dev approvals.

**Comment by paramat** [comment]
I will merge this as trivial in a few hours.

**Pull request merged**
