### PR TITLE
Default: Add damage sounds

### PR DESCRIPTION
**Pull request by paramat**
Damage and falling damage sounds.
No volume balancing or license / credits yet.

### CODE REVIEW

**Comment by sofar** [comment]
Pretty good. Update `README.txt` with origin and license?

**Comment by paramat** [comment]
This is from a set of 10 sounds, i'll might be able to find a more thumpy one for fall damage.

**Comment by paramat** [comment]
Falling damage sound is now a different sound, similar but deeper and more 'thud'.
I'll wait for a little more dev input before setting volume and adding credits, license stuff.

**Comment by Fixer-007** [comment]
first sound - hard to say for sure
second one seems good.

**Comment by paramat** [comment]
@sofar is the fall damage sound okay too?

**Comment by paramat** [comment]
I've been using this in-game, the damage sound is really good.

**Comment by sofar** [comment]
:+1: these are great.

**Comment by paramat** [comment]
Sounds with better editing, normalised (-1dB), added credits and license.

**Comment by paramat** [comment]
9b62d8a504ef8a446cd2a1cbb2239a03b52cab5b

**Pull request closed without merging**
