### PR TITLE
Make furnace work even when unloaded

### PR DESCRIPTION
**Pull request by Kalabasa**
This, in effect, makes the furnace work as if it was loaded all the time even when no one is around.

This makes the furnace simulate the seconds that were lost during the time the furnace is unloaded by fast-forwarding furnace time to the critical points (such as when the item is ready, or when the current fuel runs out) until furnace time catches up with game time.

The main cooking procedure is embedded in a `repeat...until` loop.

The number of iterations of the loop is equal the number of operations (cook, fuel, and replace fuel) needed. That means when there is nothing to cook or no fuel to use, the loop only goes once, no matter how long it has been unloaded.

### CODE REVIEW

**Comment by 0-afflatus** [comment]
Why?

**Comment by PilzAdam** [comment]
Duplicate of #200.

**Comment by Kalabasa** [comment]
> Why?

Because current implementation breaks expectations. When you leave a furnace to cook 99 iron lumps for an hour to do something somewhere else, and you return, you expect it to be done already. But you see it's still cooking the third iron lump.

> Duplicate of #200 

Oh I see. But that branch contains merge conflicts. And the implementation is different. In there, the procedure iterates for each second of lost game time; i.e., a furnace that was not loaded for a very long time will take many loops, even if it was empty.

In this implementation, the iteration is per operation (cook, fuel), not per second; i.e., a furnace will take only a limited number of loops (at most 99*3=297 iterations I think, if full of items).

**Comment by MT-Modder** [comment]
:+1:

**Comment by ShadowNinja** [comment]
:+1:  Far better than #200, although I haven't reviewed the code closely.

**Comment by 0-afflatus** [comment]
Gotcha. One one hand that's brilliant.

**Comment by 0-afflatus** [comment]
My reservation is that walking away from a super-heated furnace and expecting ingots to make themselves, let alone the forge be still standing when you get back is highly unrealistic. I accept that minetest is about good game-play over realism, so this isn't really an objection.

**Comment by HybridDog** [comment]
ln my opinion minetest_game doesn't offer a good game-play without additional mods. On servers without mods l see lots of bones, lava and destroyed houses.

**Comment by Sokomine** [comment]
That's a feature I've been missing for some time. It doesn't add to gameplay if players have to stand around waiting for their furnaces to melt the ingots. It's better if it's finished after a certain time, no matter how many people keep the chunk loaded.

**Comment by 0-afflatus** [comment]
:+1: then

**Comment by thatgraemeguy** [comment]
:+1:

**Comment by rubenwardy** [comment]
:+1:

**Comment by VanessaE** [comment]
+1 works fine in dreambuilder also.

**Comment by C1ffisme** [comment]
:+1:

**Comment by Megaf** [comment]
:+1:

**Comment by NathanSalapat** [comment]
:+1:

**Comment by ExcaliburZero** [comment]
:+1:

**Comment by VanessaE** [comment]
There may be a glitch with this new code:

"[05-09 03:14] <goto@VESv> VE-Survival is going mad. Default furnaces going faster than MV ones, Fuel and Item going below 0%, what's going on? :-)"

The server he refers to runs Dreambuilder, which uses this patch, and MV refers to a device in technic mod.  The patch worked fine for me when I tried it

**Comment by MirceaKitsune** [comment]
:+1: to the idea. I also don't agree that if the area in which an active furnace is located unloads, that furnace should stop working. The best fix would be a way to keep furnace node individually active in unloaded areas, but optimally without having to load the entire chunk... not sure if the engine allows the later option right now.

**Comment by paramat** [comment]
I assume +1 from Ekdohibs due to #200.

**Comment by paramat** [comment]
I assume +1 from Ekdohibs due to #200. +1 from ShadowNinja. So i'll merge this soon.

**Comment by t4im** [comment]
I hate to be the killjoy :/ The feature itself is great, and obviously wanted by everyone.

1. But this really should be implemented using [node timers](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3249).
Changing the already problematic ABM to additionally fake nodetimer behavior, still deserves a :-1:

  Reasons:
  * Timers are being called deterministically with the time since the last call
     This means you have the cooking time, no matter how bad the lag is or not. (ABM's are great if things just need to happen "eventually", different usecase!)
  * Timers can be stopped and started on demand instead of running for every unused furnace
    A restart of the timer can be done when inventory movement happens. You could finally build a huge tower out of furnaces without having any CPU penalities due to additional ABM work.
  * They seem to be [literally designed](https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/src/nodetimer.h#L30) for the furnace use case 
  * ABM's cannot decide to run based on individual node states; which forces early manual function returns, which you additionally overlooked to do (see 2.)

2. Your implementation additionally does a lot of unnecessary metadata lookups and crafting recipe lookups for every furnace every second _in the best case scenario_, whether active or not
This deserves a second :-1: 

3. You don't cache within the loop, what could be cached. Like crafting recipe lookups, which historically have been quite some bottlenecks (some patch was applied against that, but i still would cache it, if you can)

Again, sorry for being the killjoy :(

**Comment by HybridDog** [comment]
>Again, sorry for being the killjoy :(

ln my opinion it's better than the current furnace behaviour.

**Comment by t4im** [comment]
> ln my opinion it's better than the current furnace behaviour.
It's pretty much like the current furnace behavior, just put into a loop to be potentially run multiple times.

**Comment by paramat** [comment]
Thanks for the input i was hoping someone would check this. I'm not knowledgeable about node timers and furnaces. These points should be considered. Personally i'm not too bothered about furnaces catching-up after being left unattended.

**Comment by HybridDog** [comment]
Does using node timer make furnaces work in unloaded areas?

**Comment by t4im** [comment]
It doesn't forceload them. But it keeps track of the time that it was unloaded to give the node an opportunity to catch up (which this patch basically copies by saving away the gametime and comparing it later on)
The player won't know the difference though.

**Comment by HybridDog** [comment]
>Compared to a version before the patch, the nodemetadata will now have to constantly being resend (if it wasn't before). Which apparently, according to @RealBadAngel also triggers complete resends of the block and even mesh updates.

l think it should be sent after returning from Lua, sending a block to players every time meta:set_* is executed doesn't make sense.

**Comment by Ferk** [comment]
> Timers can be stopped and started on demand, instead of running for every unused furnace

Doesn't the ABM only apply to the active furnace? That's one of the reasons why the node is swapped.

> Contrary to nodetimers, this is done every abm-second for every furnace (active or not) into the node metadata.

If you have a nodetimer, don't you have to still compare the gametime on every dtime that the timer gets called?

How often do timers trigger? If it's faster than each second then you would be using much more CPU. I guess that whenever you don't actually need real precision an ABM is always gonna be more efficient than a timer.

But please correct me if I'm wrong, I'm interested on this as well for my project. I could use timers for several nodes if they actually turn out to be more efficient.

**Comment by t4im** [comment]
> Doesn't the ABM only apply to the active furnace?

That would be even closer to the "should be" behavior, but at this time and this PR the abm is applied to both.
```lua
nodenames = {"default:furnace", "default:furnace_active"},
```

> If you have a nodetimer, don't you have to still compare the gametime on every dtime that the timer gets called?

The dtime passed _is_ the time since the last call. Gametime should become rather unimportant then. You still might have to save something to the nodemetadata (like any time you haven't used up for cooking, to be added to the next dtime) But at least you would do that only if needed, and not for every inactive furnace.

> I guess that whenever you don't actually need real precision an ABM is often gonna be more efficient than a timer

Don't compare speed of an airplane and a submarine.
They are build for very different situations and usually perform in their own matter better.

An abm's is great where you don't care for deterministic time and have a lot of nodes that need to be treated "eventually" like dirt->grass... if that takes a minute longer, noone will really care.

But when you have a small amount of nodes (like active furnaces) with precision requirements a nodetimer is better suited and more optimized for that case. You can turn it on when needed and leave it off most of the time. (Just consider the amount of active furnaces vs. inactive ones on a multiplayer server.)

> I could use timers for several nodes if they actually turn out to be more efficient.

But don't use nodetimers for everything now, because Submarines don't fly very good either.
Instead use them what they were built for.

**Comment by Dragonop** [comment]
:+1:

**Comment by sofar** [comment]
This needs rebasing on the NodeTimer code that's now merged.

**Comment by HybridDog** [comment]
l think this can be closed because NodeTimers work even when unloaded, don't they?

**Comment by C1ffisme** [comment]
It would probably be better to replace this code, than repair it to make it fit with the new code. Starting from scratch is probably easier than trying to work with this.

**Comment by paramat** [comment]
@Kalabasa Please can you rebase and rework on the new nodetimer code?
Will close in 1 month if no reply.

**Comment by HybridDog** [comment]
https://github.com/HybridDog/minetest_game/commit/8c89398fe68909f20ab42f8c1b06328eae716e2b

**Comment by paramat** [comment]
@Kalabasa ^

**Comment by paramat** [comment]
@HybridDog could you open a PR with your code?

**Comment by paramat** [comment]
New PR for this submitted #1279

**Comment by paramat** [comment]
Closing in favour of #1279

**Pull request closed without merging**
