### PR TITLE
Tree schematics: Alter jungletree, aspen, pine, appletree 

### PR DESCRIPTION
**Pull request by paramat**
Denser jungletree for darker rainforest:
Highest 'jungletree' nodes now prob 255.
Add a 5th lower branch layer.
Increase lower branch layer y-slice prob to 191.

Aspen:
Extend trunk upwards by 1 node to reduce leafdecay radius to 2.

Pine:
Make lower trunk 1 node longer so that lowest branches are more often
higher off the ground, also to make pines taller.

Appletree:
Make 2 opposite branches prob 255, the other 2 prob 127, to avoid
trees with 1 or 0 branches. Therefore also add random rotation.
////////////////////////////////////////////////

screenshot_20170307_122703

The new lightcurve has made rainforest brighter, this PR makes minor changes to jungletrees to make them denser to increase the attenuation of light.

### CODE REVIEW

**Comment by sofar** [comment]
I'm fairly positive - especially about the jungle tree. I would actually like to see them become larger horizontally as well (7x7 footprint).

Can you pastebin/gist the saveschems diffs so we can see the detailed diff?

**Comment by rubenwardy** [comment]
Tried this out, the look good in-game. Jungles should be dense - it's part of the atmosphere

:+1:

**Comment by paramat** [comment]
Unfortunately rainforest still isn't dark enough but i'm not sure how much more i can boost the tree density.
I also want to make pine trunk a node higher so that they're not always so close to the ground, WIP for that.

**Comment by paramat** [comment]
Jungletree diff:
https://gist.github.com/paramat/fee68a2135659c61ccd15ff1089ee295
Only structural change is slice 8 is copied to replace slice 12 to create a 5th lower branch layer.

**Comment by paramat** [comment]
Updated pine:

Pine:
Make lower trunk 1 node longer so that lowest branches are more often
higher off the ground, also to make pines taller.

**Comment by paramat** [comment]
Sofar, the reason i like jungletrees 5x5 is because we are limited to a height of 16 nodes, 5x5 makes the tree appear narrow and tall as a rainforest tree should be, 7x7 would create an appearence of shorter and wider. Same applies for pines. I like the idea of 7x7 appletrees though.

**Comment by MarkuBu** [comment]
So it isn't really possible to place schematics taller than 16 nodes? I mean, it is possible, but with a chance to get cut

**Comment by paramat** [comment]
If you want schematics to be placable at any altitude they cannot be taller than 16 nodes.
This is due to the mapgen voxelmanip always being the mapchunk plus a 1-mapblock thick surrounding shell. Trees placed on terrain surface at y = 47 can extend up to y = 63 but no higher.

**Comment by paramat** [comment]
WIP Just remembered i need to alter appletree too, currently it's possible for them to have zero branches, better i think to have a minimum of 2 opposite branches.

**Comment by paramat** [comment]
Updated appletree:

Appletree:
Make 2 opposite branches prob 255, the other 2 prob 127, to avoid
trees with 1 or 0 branches. Therefore also add random rotation.

**Comment by dsohler** [comment]
Jungle trees should have a wider variety ranging from very small 1 node wide trunk and not very high up to 4x4 node wide trunk and a few per jungle biome being up to 100 nodes high.

**Comment by paramat** [comment]
0f0dd0f6e817f58e6501549ab6d34bbfdc1d6548

**Pull request closed without merging**
