### PR TITLE
Lava cooling: Increase interval to 2

### PR DESCRIPTION
**Pull request by paramat**
An excessive load has been reported caused by the node searching, so even
when no lava is present.
/////////////

This load was profiled and reported by sofar.

### CODE REVIEW

**Comment by tenplus1** [comment]
Would using the on_flood feature be any better in turning lava into stone/obsidian ?

**Comment by paramat** [comment]
Not sure, we'll consider it though.

**Comment by raymoo** [comment]
I feel like `on_flood` would improve performance more. If lava cooling is an excessive load then this changes a once per second lag spike to a once per two seconds lag spike.

**Comment by raymoo** [comment]
Actually just noticed the API has a warning against making liquid nodes floodable. I'm guessing this is because they will flood into themselves?

**Comment by paramat** [comment]
> I'm guessing this is because they will flood into themselves?

Yeah. I wouldn't want to disallow it though in case someone wants a special behaviour.

**Comment by paramat** [comment]
Approval by SmallJoker (Krock) http://irc.minetest.net/minetest-dev/2017-07-31#i_5029018

**Comment by paramat** [comment]
7ffd176f48c4c74a9e5a14e700f720f279dcee9f

**Pull request closed without merging**
