### PR TITLE
new cobblestone/mossycobblestone texture (textures inside)

### PR DESCRIPTION
**Pull request by tobyplowy**
i didn't like the current cobblestone texture so i made a new one
(NOTE)i hope it looks good i did my best to mimic the minetest style 
default_mossycobble
default_cobble
default_desert_cobble
cobble

### CODE REVIEW

**Comment by C1ffisme** [comment]
Oops. You just made a commit that included all the files of Minetest Game, rather than just the ones you have changed.

**Comment by tobyplowy** [comment]
Ohno did i fuck Something up?

**Comment by paramat** [comment]
Best open a new PR.

**Comment by C1ffisme** [comment]
[You should probably learn a bit of git.](https://help.github.com/articles/good-resources-for-learning-git-and-github/)

**Comment by paramat** [comment]
In Github help section there is the 'Bootcamp' section that takes you through forking and submitting PRs step by step, it's how i learnt.

**Comment by tobyplowy** [comment]
@paramat so will it get added? If Not still fun to help :D

**Pull request closed without merging**
