### PR TITLE
Internationalization support

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by C1ffisme** [comment]
While I do like where this is going, the problem is that all of these item descriptions will be server side, meaning that a client that joins this server will have to read the names in that language. I wonder if it would be possible to allow handling item descriptions on the client side instead...

**Comment by kaeza** [comment]
Also :+1: for concept, but adding `intllib` is not the proper solution at this point. It's filling the gap until support for client-side modding is somewhat stable and has the required functionality.

**Comment by sofar** [comment]
Can't we solve this problem with client-side modding? I fail to see how we can ever do this server-side.

**Comment by Wuzzy2** [comment]
No, this is the wrong approach. The biggest problem is that clients will all be exposed to the language of the server which is a no-go for me.

IMO the real solution would be to first fix https://github.com/minetest/minetest/issues/2270, then utilize *that* to include translations for Minetest Game.

**Comment by paramat** [comment]
:-1:

**Comment by sofar** [comment]
:-1: lets see what we can do once CSM lands first

**Comment by paramat** [comment]
There's also https://github.com/minetest/minetest/issues/5274

**Pull request closed without merging**
