### PR TITLE
Doors: Disable client dig prediction for protected doors

### PR DESCRIPTION
**Pull request by sfan5**
helps with (now closed) #1888 and #954

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
But how about:
"If you want to prevent players from lagging through protected walls, you can just set node_dig_prediction to a walkable invisible node ("ignore"?) instead of air.

This way players couldn't lag through protected walls, but they still get the feeling that they actually dug it,"
?

**Comment by sfan5** [comment]
Invisible walls (even if temporary) are going to confuse players more than the server just being "laggy" when digging steel doors.

**Comment by paramat** [comment]
Ok, and placing 'ignore' is not advisable anyway in case it stays.
:+1:

**Comment by sfan5** [comment]
edba1dcb028f1bfd8831cd69ab77a6a730fdc90d

**Pull request closed without merging**
