### PR TITLE
Biomes: Make coastal grassy dune biomes larger

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20180101_081436

^ With PR

Until now, the 2 coastal grassy dune biomes have only been at a single y value (y = 5) so have been too small.
Reduce their minimum limits to y = 4 to double their vertical and horizontal size.
The only change to existing worlds is that grass decorations will now extend down to y = 4 on beaches, the distribution of sand nodes is unchanged, the visual change will be barely noticeable.

### CODE REVIEW

**Comment by Fixer-007** [comment]
Do you know what is really missing too on low altitudes with views like that?
default

Blending, vertical and horizontal, and more grass.

**Comment by Fixer-007** [comment]
Maybe that grass should appear even lower at Y=3.

**Comment by paramat** [comment]
Blending is coming.

**Comment by paramat** [comment]
f52085a40f682c68c54936de7d5451d990245090

**Pull request closed without merging**
