### PR TITLE
Remove `default:dirt_with_grass_footsteps` and add alias.

### PR DESCRIPTION
**Pull request by red-001**
This node look almost identical to dirt with grass and didn't seem to have any use.

### CODE REVIEW

**Comment by paramat** [comment]
I think it may be used on some servers.

**Comment by Calinou** [comment]
> I think it may be used on some servers.

xkcd: Workflow

**Comment by paramat** [comment]
If i remember correctly, when i last worked on the grass texture i suggested removing grass with footsteps, and was told it's in use on servers. need more input on this @VanessaE 
Personally i'm neutral about it.

**Comment by VanessaE** [comment]
Some servers still use grass/footsteps (most notably, those which run skyblock).  Keep it.

**Comment by rubenwardy** [comment]
Then skylands can have it in their game. There is no reason to keep it here.

**Comment by Dragonop** [comment]
Is it breaking something? No? Then why would you remove it...

**Comment by red-001** [comment]
@Dragonop It's useless and trivial to add using a mod.

**Comment by paramat** [comment]
:-1: It's in use, aliasing it means those who use it lose their footsteps, or, they would have to go around beforehand replacing all footsteps with a mod version.

**Comment by red-001** [comment]
Could someone name a mod that uses it then?

**Comment by red-001** [comment]
Shouldn't code to make footsteps be added to minetest game then?

**Comment by paramat** [comment]
Maybe it coulld be an option in future, with engine changes to support lightweight changing of nodes to footstep versions. It can be done in Lua but is a little heavy (see my trail mod).
Anyway, note we have default:cloud which is not used in MTGame but we keep it anyway.

**Comment by paramat** [comment]
Nore, sfan5 and i agree to close.

**Pull request closed without merging**
