### PR TITLE
new chest open and close sounds

### PR DESCRIPTION
**Pull request by tobyplowy**
the opening sound had a anoying cheaky noise so i removed it
these are also a bit shorter

### CODE REVIEW

**Comment by paramat** [comment]
I agree that our current chest sound has a little too much squeak to it.
Related #1892

**Comment by paramat** [comment]
:-1: The opening sound is too short.

**Comment by tobyplowy** [comment]
@paramat this is mostly an example to bring attention to the problem

I probably won't be spending more time on this (I have to work on farlands so I don't really have alot of time for MTG)

**Comment by paramat** [comment]
Ok we'll go with the other PR.

**Pull request closed without merging**
