### PR TITLE
Leafdecay: Register leafdecay for bush leaves 

### PR DESCRIPTION
**Pull request by paramat**
Addresses #1531 

Tested.

### CODE REVIEW

**Comment by paramat** [comment]
Now tested.

**Comment by sofar** [comment]
Trivial, :+1:

**Comment by Thomas--S** [comment]
:+1: for leafdecay for bushes.
However, I would prefer it, if you can place decaying bush leaves, too. This is the only way to create "natural" bushes because there are no saplings for bushes.

**Comment by paramat** [comment]
Maybe, i'll see what other devs think.

**Comment by paramat** [comment]
Updated to behave like tree leaves.

**Comment by paramat** [comment]
Failed to apply, will rebase.

**Comment by paramat** [comment]
Rebased, retested.

**Comment by paramat** [comment]
07a5fca432747043b3df067d4703b471072dce77

**Pull request closed without merging**
