### PR TITLE
New hotbar textures

### LINKED ISSUE #2195: Replace hotbar textures
Just realised how bad the hotbar slot frames texture looks (doubled in size with no interpolation):

badhotbar

The borders around each slot vary in width from slot to slot and from edge to edge. The texture itself is not irregular (doubled in size with no interpolation):

gui_hotbarx2

~~It seems an unavoidable alignment mismatch between the texture and the shaded squares.
If we remove this texture it can look like this, which is cleaner and less visually intrusive when a slot is empty:~~

Now see the selection frame (doubled in size with no interpolation):

gui_hotbar_selectedx2

It's a rather fancy, rounded, smoothed, blurry, high-res stone effect by BlockMen which obviously goes with the old header image by BlockMen last used in 0.4.13 and replaced 3 years ago (actual size):

header

Which was embarassingly similar to the MC logo:

ripoff

MTG has a low-res header now. I feel that this selection frame needs changing to be more consistent with MTG's now cleaner, crisper and low-res general appearence.
Now see the hotbar from MC:

qa7

The stone frame selector is again an almost identical copy, but at least MC's is clean and crisp instead of blurry like ours.

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20180912_141819

^ Against brightness. Note selector frame clears the edge of a 2-digit number.

screenshot_20180912_141833

^ Against darkness. Note selector frame clears the edge of a 16x16 item texture.

gui_hotbar_selected_4_2_4_x2

^ Double size

Closes #2195
See issue for old textures.

Selector frame:
For some continuity i sampled the lightest and darkest greys from the previous selector and added a shade halfway between. This preserves the colouring and form but is now abstract and without so obviously being a MC clone stone frame.
The shading is now consistent with inventory items: light comes from top-left.
The frame is thick, clear and crisp for clarity of selection. To further increase clarity of selection i have made the the central square solid black instead of translucent black. Previously the combination of 2 stacked translucent blacks was near solid black anyway.

8 slot frame:
Colour and alpha of dark slot squares is not changed.
Frame colour is balanced to be darker than selector frame but light enough to keep the dark slot squares distinguishable from each other when seen against a light background.

### CODE REVIEW

**Comment by random-geek** [comment]
I like the texture, but it does seem a bit bright in lower light.

**Comment by SmallJoker** [comment]
`gui_hotbar.png` looks overall way too bright because there is almost no contrast to the "selected" texture border.

**Comment by Ezhh** [comment]
I have to agree about the brightness.

**Comment by paramat** [comment]
Good point. I did try a darker shade for the 8-slot texture but it made the 8 slots unclearly defined from each other, but i'll tune and balance the brightness for some contrast.

**Comment by paramat** [comment]
Updated 8 slot frame. See new screenshots.

See the 'against brightness' screenshot, this is why the 8 slot frame can't be too dark, because it then lacks contrast against the dark squares and the slots become less distinct from each other (i tried it earlier).
This updated version is a nice balance and i agree it improves contrast against the selector frame.

**Comment by paramat** [comment]
I've been using this for a few days and am quite happy, but want to tweak the selector frame, WIP.

**Comment by ClobberXD** [comment]
Looks pretty good in its current state :+1:

**Pull request merged**
