### PR TITLE
Improved Iron Bar texture

### PR DESCRIPTION
**Pull request by kilbith**
Before / after : 

screenshot_20150614_110403
screenshot_20150614_110455

### CODE REVIEW

**Comment by Novatux** [comment]
Looks good

**Comment by est31** [comment]
:+1:

**Comment by sfan5** [comment]
:+1:

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/d8dd9332edf8e37d5d0effe6c14d07447f216955

**Pull request closed without merging**
