### PR TITLE
Flowers: Add black tulip, green chrysanthemum

### PR DESCRIPTION
**Pull request by paramat**
Flowers: Add black tulip, green chrysanthemum

Adds a direct resource of green dye, and a flower resource of black dye.
Completes the colour sequence: red, orange, yellow, green, blue, violet.
Makes all base dyes cultivatable and sustainable, without the presence
of coal.

Add the new flowers to the world with the same density variation as the
others, but obviously with different noise seeds. Results in more flowers
in a world and more variety of flower combinations.
//////////////

screenshot_20171125_011050

screenshot_20171125_011644

Attends to #1509

### CODE REVIEW

**Comment by C1ffisme** [comment]
Wow, that's a really long word.

Is there a non-scientific sounding (or just one or two syllable long) name for a chrysanthemum?

**Comment by Napiophelios** [comment]
I thought Black Tulips were a myth?
Has such a flower ever appeared naturally?

Hmm..maybe the Oerkkis brought them https://github.com/minetest/minetest_game/issues/1949

**Comment by paramat** [comment]
Tested, fixed selectionbox, added screenshots, no longer WIP.

**Comment by Fixer-007** [comment]
Feels like textures need more work.

**Comment by paramat** [comment]
I'm happy with the tulip texture, it's no less complex than the orange tulip, and far better coloured. I'm also fairly happy with the chrysanthemum texture. It's entirely possible i will improve them later but i consider them good enough for merge.
What are your specific issues with them?

**Comment by paramat** [comment]
Ok will improve the colour variation on stems and chrysanthemum leaves.

**Comment by ThomasMonroe314** [comment]
> I thought Black Tulips were a myth?
Has such a flower ever appeared naturally?

Maybe these can be inserted into the lore of MTG somehow

**Comment by ExeterDad** [comment]
The black tulip does exist. But is a man made species that's been around just over 125 years. http://www.amsterdamtulipmuseum.com/en/faq/tulips/do-black-tulips-exist/

**Comment by Napiophelios** [comment]
I am pretty sure all black flowers are man made
and none of them are actually black in color.

**Comment by paramat** [comment]
Yeah they're very dark purple / red, which is represented in my texture.

ThomasMonroe314, it's possible that they are made 'special' in some way in future, but that idea doesn't exist yet, so we can't really 'add them to backstory' right now. Also see the dreaded backstory thread, we're not going to plan or discuss or add to backstory in some abstract way right now. I see no need to add to backstory, but we will of course work creatively with the very small amount of backstory we already have.

**Comment by Ezhh** [comment]
I like the tulip a lot, but do worry about the amazing spelling-variations of "chrysanthemum" soon to blight our servers.

**Comment by paramat** [comment]
Updated textures and screenshots. Tulip has a per-pixel smooth shading gradient on the stem. Chrysanthemum has per-pixel colour/shading variation on stems and leaves.

**Comment by sofar** [comment]
:+1: from me. Dutch guy needs his tulips.

**Comment by paramat** [comment]
2c5670563adac0286828fafcf71f66ebf38b7d6f

**Pull request closed without merging**
