### PR TITLE
Add /killme chat command

### LINKED ISSUE #857: Needed fair mechanic which would let player unstuck
Since minetest_game includes many blocks which are unbreakable by bare hands there are situations when player stuck in hole and cannot escape (e.g. no pickaxe in inventory).

It would be good to have build-in solution rather than depend from mods who gives whole pack of "cheats" commands.

My suggestions:
1. If you pushing long enought "unbreakable by bare hands" block you start losing health. Probably would require loot of work to intruduce it, but it would add some spice to game.
2. Include into minetest_game "seppuku / killme" (or whaever name) command which would let kill himself. Better not instantly let say after 15-30 seconds (or configurable in case of pvp servers).
3. ??? 

There are teleport and sethome/home but these commands feels like cheats (and does not fit into minetest proposed logic. You can't break stone by bare hands but you can perform teleportations like pro?).

### PR DESCRIPTION
**Pull request by rubenwardy**
Added as a new mod as it doesn't fit anywhere else.

This is a game play change, so it better suited to
Minetest Game rather than builtin

Fixes #857

### CODE REVIEW

**Comment by octacian** [comment]
Tested, works fine. +1

I'd suggest though that a `/kill` command be added along with this. This way players with the `kill` privilege (or something like that) could execute a command like `/kill <playername>`. Looks good anyways, just doesn't make sense to only have `/killme`.

**Comment by Fixer-007** [comment]
Yeah, unfortunately if you are on server without spawn or anything other, falling into a trap means you are stuck forever...

**Comment by paramat** [comment]
I agree to the concept. Will test.

**Comment by paramat** [comment]
I guess /home is not a solution because home may not be set.

**Comment by DS-Minetest** [comment]
This is unrealistic, how should you kill yourself with bare hand?
I'd suggest something like a selfattack command to hurt yourself with the weapon you are holding in your hand.

**Comment by sofar** [comment]
I'd allow this command even with damage disabled. It may be useful to players in creative that wish to jump back to spawn and can't find their way, or to make screenshots with a dead player, etc..

**Comment by paramat** [comment]
DS, then those without a weapon couldn't kill themselves.

I agree this would be good to use with damage disabled.

**Comment by rubenwardy** [comment]
If there is no static_spawnpoint defined, it doesn't seem like it's possible to get a respawn position using the API

**Comment by rubenwardy** [comment]
See code changes

**Comment by tobyplowy** [comment]
@sofar 

> I'd allow this command even with damage disabled. It may be useful to players in creative that wish to jump back to spawn and can't find their way, or to make screenshots with a dead player, etc..

+1 Totally agree but that last bit sounds a bit disturbing doesn't it XD

**Comment by C1ffisme** [comment]
> I'd suggest though that a `/kill` command be added along with this. This way players with the `kill` privilege (or something like that) could execute a command like `/kill <playername>`. Looks good anyways, just doesn't make sense to only have `/killme`.

Agreed. Could be useful for administrators, or for mesecon commandblocks.

**Comment by DS-Minetest** [comment]
> useful for [...] mesecon commandblocks

The `mesecons_commandblock` mod already adds a `hp` command but this is offtopic.

**Comment by rubenwardy** [comment]
It seems that Server::findSpawnPos() isn't exposed to Lua, so there's no good way for a mod to respawn a player if damage is disabled

I suggest merging without support for damage disabled, and then adding support if engine support is added

**Comment by JurajVajda** [comment]
killing yourself just because you are lost or trapped - what is most of the time the case - with intention of going to spawn doesn't make sense to me since you will loose all your stuff (survival). /spawn teleport you to spawn makes more sense to me. When i look at it from the other side, you kill your self (survival loose your stuff) and you get teleported anyway to some kind of "spawn" point or even worse.. you will respawn on the same spot where you got stuck and wanted to get out from which makes /killme pointless again. Maybe i dont understand the usefulness of this command therefore i was never a fan of it :)

**Comment by paramat** [comment]
Merge as is is ok with me.

**Comment by C1ffisme** [comment]
@JurajVajda Occasionally, you may find yourself falling down a hole. This hole is not deep enough to kill you, but it traps you in and you cannot get out, nor can you dig out because either A) You have not gotten a pickaxe yet or B) Your pickaxe has broken. You are also not able to place blocks, either because you have no blocks or the area is protected.

In this case, the best option is to use a /kill command to escape, and try and find your bones. Sure, you could try and ask an admin for help, but most likely they have better things to do or are offline. And chances are the person owning the protected area hasn't logged on in three months. (Because it's rare that a server has an automatic property cleaning system.)

Assuming the server allows the placement of bones in protected areas (Or even better, dying in a protected area does not take your items), then you can simply find your items and be on your way. In the event that dying in a protected area just deletes your items, at least you have a chance to restart, rather than not be able to continue playing.

Even if it isn't a protected area, the most common use of /killme would be by a new player with an empty inventory exploring the world, and falling down pits. He has nothing to lose, so using /killme is perfectly justified.

**Comment by octacian** [comment]
Looks nice. Code looks good, I agree with how damage enabled and static respawn points are being dealt with. Still think that a /kill command should go along with this, but if it doesn't, I'll open a PR.

On second thought, why isn't this in builtin? This just seems like one of those things that should, considering the discussion I had related to another like command yesterday.

**Comment by rubenwardy** [comment]
> why isn't this in builtin

This relates to game play, rather than utilities
Same reason why sethome is a mod in MTG too

**Comment by paramat** [comment]
> If there is no static_spawnpoint defined, it doesn't seem like it's possible to get a respawn position using the API

Ah this is why you wanted to access the 'find spawnpont' function.

**Comment by paramat** [comment]
:+1: tested. We could improve this later if necessary.

**Comment by ShadowNinja** [comment]
I think `/die` sounds better, especially if `/kill` isn't actually a valid command.

**Comment by paramat** [comment]
Killme works well with grantme, giveme.

**Comment by ShadowNinja** [comment]
But `/grant` and `/give` exist and there isn't really a more appropriate name for then AFAIK.

**Comment by paramat** [comment]
cadc8b34d7d5666dccd42031f57e140d4e311f90

**Comment by paramat** [comment]
Further discussion #1506

**Pull request closed without merging**
