### PR TITLE
Beds: Make non pointable by pointable definition

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by PilzAdam** [comment]
Why?

**Comment by Rui914** [comment]
This definition is simple than before.

**Comment by rubenwardy** [comment]
In what way simpler?

**Comment by ExcaliburZero** [comment]
From what I can tell it looks like the original definition made beds non pointable by setting their selection box to consist of all coordinates being 0. This commit removes that selection box definition and replaces it by setting `pointable = false`.

The commit takes the former four lines 98-101 and simplifies them down into one line at the new line 91.

**Comment by paramat** [comment]
:+1:

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by ShadowNinja** [comment]
This removes commas at the ends of lists, which should be left.
Otherwise, :+1:.

**Comment by paramat** [comment]
I agree, commas at end of lists are missing elsewhere, perhaps they can be cleaned up later, so i'll go ahead and merge this.

**Comment by paramat** [comment]
1d8def5c06346aad7f400156be95f50b67ceee48

**Pull request closed without merging**
