### PR TITLE
Default/trees: Combine sapling ABMs into one ABM

### PR DESCRIPTION
**Pull request by paramat**
A single ABM on "group:sapling" instead of 4 individual ABMs, this should reduce the processing load due to ABM searches.

### CODE REVIEW

**Comment by PilzAdam** [comment]
Do other mods put their saplings in the sapling group? If this is the case, then your code would cause a lot of useless C -> Lua calls.

**Comment by C1ffisme** [comment]
Good idea, but do consider PilzAdam's note.

What about adding a group called ```defaultsapling```?

**Comment by paramat** [comment]
Thanks PilzAdam, Moretrees uses the sapling group and other mods probably do too, so i will not use "group:sapling" but will list the 4 default mod saplings to restrict the search to those.

**Comment by paramat** [comment]
Updated.

**Comment by PilzAdam** [comment]
:+1:

**Comment by paramat** [comment]
6194f9ffeaf0dd9a757979af0f8936e8625552b5

**Pull request closed without merging**
