### PR TITLE
Add Pies

### PR DESCRIPTION
**Pull request by C1ffisme**
The idea is to add another food to minetest. Right now, it's a big hassle to grow wheat, it's not really worth it. But, if you craft a pie, you get two slices of **YUM!** which heal 5 hearts each. It also adds sugar, which can support mods.

Pros:
* Helps new modders to make slice-based food
* Creates a new food to improve gameplay
* Adds a new craftitem to use in mods

Cons:
* The pie dosen't have very good textures (but, I'm proud of my sugar texture, and someone can make a new pie texture)
* I had a little trouble and I did 3 commits, because of my fork. (Someone help me!)
* This isn't really a con, but I'm using my master branch again. I'm going to need to fork minetest_game again after this gets merged or closed and the backgrounds pull request gets merged or closed.

So, 3 real pros, and 2 real cons. And the cons can be worked around or fixed. Sounds good, right? 

### Adding a cookable item

Now, as some people want, I could add a cookable item. However, this would add an entirely useless item that you can only use for one thing. Minetest should have some multi-tasking involved. So why make a pie without cooking it? Well, for one, minecraft does it, and that may help those newbies, for another, it would add an item that gets used for only one thing, since I can't really see the use of a ```default:uncooked_pie``` in crafting recipes. Even flour to make bread has other uses because it's called flour, not bread dough or "Mr.Player's famous bread mix" which has only one purpose, to make bread.

However, a cookable item would be more realistic, and might be better gameplay. Why? Because pies are cooked, and cooking pies adds another level of hard.

#### Why did I use wheat?

Flour is hard to get. You need 4 wheat. Now, to get wheat, you need to make sure that they grow, which means making sure they are updating. (Do NOT say that you can use the ```forceloadanchor``` mod. It has been said many times, people do not just go to minetest.net and get mods.) So why use wheat? Wheat is less expensive, since flour requires 4 wheat. Consider that you are 13, and still living with your parents. For some reason you have minetest at it's version right now. If you have tended to your wheat well and got your first batch, I think you want to craft something right then and there.

If you want me to use flour, then I will, but I will change each slice to heal 10 hearts rather than 5, because we need to balance this game a little bit.

### CODE REVIEW

**Comment by Heybye44** [comment]
:+1:



—

**Comment by PilzAdam** [comment]
* Since when can you make sugar from papyrus?
* Why don't you use flour?
* Why isn't the pie baked in the furnace?

**Comment by LeMagnesium** [comment]
It could be good to add pies or new foods, but as said @PilzAdam , the way you create it is not logic. Papyrus can't give sugar, but most people think it can. And there is also bread, and even if it takes long to make, it gives a reason to grow wheat. Improve your code by changing illogic ways to create sugar and pies, and it could be merged.

**Comment by MT-Modder** [comment]
@PilzAdam and @LeMagnesium What do you suggest sugar be made of? The choices we have are limited. Maybe cactus.

**Comment by LeMagnesium** [comment]
To be the most realistic, we should create another plant to grow, a sugar cane, but we would have to choose the conditions required for it to grow. Then, sugar could be randomly given when a player dig another plant, or another node, but there is not really any node in minetest_game that could give sugar... At least, if we keep papyrus giving sugar, we should at least force the player to cook a raw pie before eating them.

**Comment by MT-Modder** [comment]
I agree it needs to be cooked and flour should be used. I also agree papyrus doesn't make sense but then we would have to add a whole new plant just for a simple pie recipe. @C1ffisme Did you make that texture? It looks just like the minecraft texture.

**Comment by C1ffisme** [comment]
@PilzAdam Sorry, I've been playing too much minecraft. ALTHOUGH...

- Adding a cookable item wouldn't do much good. It can't be used by mods.
- We can use another commit to change the wheat to flour, but that would be very expensive. Maybe keep it at wheat? Flour is very expensive since wheat takes too long to grow and then you need 4 wheat.

**Comment by LeMagnesium** [comment]
> It can't be used by mods.

What do you mean by that? Mods can always use items, for example there could be a mod that allows you to take the default pies, and craft pieces of them to cook these pieces (less long to cook, cost less). And everyone of the default item's goal isn't to be necessarily used by other mods.

> Flour is very expensive since wheat takes too long to grow and then you need 4 wheat.

That's why there is flour, it costs to craft it, so the player have to do more things to get the precious item which will be crafted.

> Papyrus can be renamed sugar cane if we want.

That would make no sense : papyrus is used to craft papers, and I've never crafted books out of sugar... A sugar plant is an idea, because a lot of food mods do the mistake of allowing us to craft sugar out of papyrus. I will probably work on something like that, probably using pieces of your code (sugar's definition) to create what you need there.

**Comment by PilzAdam** [comment]
> Adding a cookable item wouldn't do much good. It can't be used by mods.

What?

Also the whole point of wheat is that it's hard to get. For the beginning you can eat apples, which only doesn't heal as much as the wheat based food. Later in the game you can create your own wheat farm and getting wheat is pretty easy then.

**Comment by C1ffisme** [comment]
How long has it been since any of us has played vanilla minetest?

That's not to say that some of us are much younger than other players.

**Comment by MT-Modder** [comment]
I just wanted to make sure :-). I would have never knew if I hadn't looked up papyrus.

**Comment by HybridDog** [comment]
l have a cake with cream.
https://github.com/HybridDog/extrablocks/blob/master/textures/extrablocks_to_t.png
https://github.com/HybridDog/extrablocks/blob/master/textures/extrablocks_to_b.png
https://github.com/HybridDog/extrablocks/blob/master/textures/extrablocks_to_s.png
https://github.com/HybridDog/extrablocks/blob/master/textures/extrablocks_to_s2.png

**Comment by Sokomine** [comment]
New plants make the game more intresting. In order to get sugar for cakes, how about adding sugar beets? They could be used for sugar, alcohol, animal food and as fertilizer. The plant as such is not particulary spectacular and might be found when digging dirt_with_grass. We also ought to have a plant that gives some sort of oil, because oil would be very useful as a craft item for a lot of other materials.

**Comment by C1ffisme** [comment]
@Sokomine Maybe, but I like to think that those people from minecraft are going, "Oh, well, I got papyrus, so I can make sugar.", plus, I think digging dirt for beets would give a lot of beets to the person who just needs dirt for their desert wheat farm. However, maybe beets could be used as an alternative, and they might be found a different way...

**Comment by JBBgameich** [comment]
Yes! I think sugar beets are good. At the moment minetest GAME just has two farming plants. Why not make one more?

**Comment by Heybye44** [comment]
@JBBgameich :+1:



—

**Comment by paramat** [comment]
-1 as it is currently. See points by PilzAdam. I don't approve of sugar from papyrus.

**Comment by 0-afflatus** [comment]
:-1:
papyrus != sugar cane
Sugar isn't a particularly useful ingredient. I have beets in Grail Test, which could be a better addition. But I think recipes involving sugar should not be in the default game.

**Comment by C1ffisme** [comment]
Then what foods *do* belong in default, @0-afflatus ? We have 2 fungi, one of which is poisonous, a fruit and a bread. The variation in the game is very poor already!

It seems like adding many foods isn't important, but really that's what makes it fun... having many of them. As well as the need to learn things such as...

- How do I cook this food?
- How do I grow this food?
- How can I use this in other recipes to increase my health more?

Actually, the reason we don't have many foods in minetest is because we don't have hunger. No wonder people complain about the game being static! If you don't need food except when you are hurt, why eat it at all? Just don't get hurt! Or even better, just turn bones off.

But back to the point. Sugar. Why can't we have sugar? It's used in more than just candy recipes, and if we don't add sugar, than why have flour? Flour is only used in baking, which is less recipes than sugar is used in!

**Comment by rubenwardy** [comment]
The name should be "Apple Pie".
"Pie" to me suggests a steak pie.

:-1: in its current form:

* Papyrus isn't sugar
* Apple pies are cooked.

However, I agree with the ability to process apples into another kind of food - apples and wheat for a food should make a better food than just apples or bread.

**Comment by C1ffisme** [comment]
Ugh... Sorry about this but when I get this done I'm going to be doing a lot of work. This repository is either on one of my desktop computers, or my old laptop. And even then, I messed it up pretty bad. If you look at the commits, I had to remove my background pull request from this one. I'm not real good at pull requests.

Papyrus isn't sugar, that doesn't mean it can't be. After all, bronze isn't iron and copper.

If you want to add beets or sugar cane, then you're going to have to add tin first.

@rubenwardy Hmm... That's true, although we could have steak pies in the game too. If we had mobs. I'll change the name when I get the repository work done (eventually... ugh.) as said above.

**Comment by rubenwardy** [comment]
I'd personally change the inconsistency of bronze and tin.

**Comment by Ferk** [comment]
Maybe there could be a "dough" craftitem for cooking in the oven.
Something like:

    flour+apple -> apple dough --cook--> apple pie
    flour+seeds -> nutty dough --cook--> nut tart

The dough wouldn't be a very useful item (only for being cooked into the respective pie), but it would contribute to the "how do I cook things?" exploration of the game that you talked about.

Flour might be more expensive, but you are using more wheat than what it costs to produce 1 flour. Also, your pie costs the equivalent of 11.5 health points to produce (1.5 bread and 2 apples), but you are only providing a total of 10 health out of it, it's not worth it to make your pie. Remember that 1 heart = 2 health points.

You can give it 10 health points instead and just use 2 flour + 2 apple (which is worth 14 points so you get extra 6 for the effort of crafting, cooking and having to place it as a node to eat uncomfortably, not suitable to carry around in an adventure).

**Comment by 0-afflatus** [comment]
There is a place for decorative food nodes. Players love throwing parties, but the default game only needs to provide the most basic foods, yeah it's boring, but there are some excellent food mods out there mentioning no names @rubenwardy cough ;-)

**Comment by Ferk** [comment]
Well, there's no decorative food at all in minetest_game. Not even a basic one. You can't use the foods that are currently in default as decoration.

Considering that default minetest_game has nothing that can hurt you other than fall damage and fire, having at least one food that has decorative uses would make it already the most useful food of the lot.

But it's entirely up to the devs to decide.

**Comment by C1ffisme** [comment]
If I were to make sugar cane, I want to know several things about it:

* Where would it grow?
* How would it grow? (Like papyrus, or like a crop?)
* Why would you add an entire node type just for the sake of realism? (Which is not the point of minetest.)
* If you want crops, why is it you don't add more commonly seen crops, like carrots or potatoes or even just putting bananas on jungle trees? (Bananas grow in tropical areas, but I think jungle trees are the closest we get to banana trees.)
* Why are we asking for more realism for my pull request, but we turn a blind eye on mese?

**Comment by 0-afflatus** [comment]
@C1ffisme we are discussing pies.
Your pies in fact.

It's not about realism here, I just don't think pies or sugar add anything to the game.
Please could you try to keep discussions on topic or I may have to kill you. :godmode:

**Comment by HybridDog** [comment]
sugar isn't healthy, once ragnar's drugs mod, which added health to the player, was edited by john because of that

**Comment by rubenwardy** [comment]
It does contain energy, and isn't poisonous. Any unhealthiness is through
long-term consumption, not individual consumption.

**Comment by C1ffisme** [comment]
Sugar is like vessels, they are meant for mod support, and have a feature useful ingame.

Pies are just another tier of food. Just like steel, mese, diamond, we have apples, bread, pie. Eating lots of pie makes you feel like you are on the top tier with your diamond sword, steel bow, obsidian armored house, and now you can make your food top-tier, with pie.

**Comment by paramat** [comment]
Please improve or close, otherwise i will close this in 1 month.

**Comment by C1ffisme** [comment]
@paramat Probably best. My Repository really needs to be deleted and redone.

**Pull request closed without merging**
