### PR TITLE
Papyrus, Cactus: Only make them grow in bright places

### PR DESCRIPTION
**Pull request by SmallJoker**
Pull for #1471
EDIT: Trees require a light level of >= 13 to grow - what should papyrus and cacti need to grow?

### CODE REVIEW

**Comment by sofar** [comment]
Both Cacti and Papyrus remind me of tropical, hihg-sunlight plants. I'd change this to `< 13` myself.

**Comment by paramat** [comment]
Yes 13 should be required. All flowers, grass and farming crops have always needed level 13 to grow, this was done deliberately, so that torchlight cannot be used to grow them, which would be unreasonable. Grow lamps have to be full-spectrum and high power, the specialness of mese-derived lamps are ideal for this.

However the discussion over sapling growing raises the issues of whether the meselamp recipe can be more generous, and whether we perhaps need another type of mese light that can be crafted without glass (from sand which doesn't exist deep underground). Essentially we might need to compensate by somehow making underground farming by mese lights easier.

**Comment by DS-Minetest** [comment]
> (from sand which doesn't exist deep underground)

wasnt somewhen sand generated in underground?

and if veins of sandstone would be generated in underground the player had access to sand (and it would also look not that bad (if its not everywhere generated))

**Comment by paramat** [comment]
The original mgv5 had dirt, sand and gravel blobs throughout the underground, the new mgv5 had these for a while but they were replaced by the the blob ores of mgv7 with only gravel blobs underground.
As far as i remember classic mgv6 only had gravel blobs underground, dirt and sand blobs were only near the surface.
We could perhaps consider having dirt and sand blobs throughout the underground, for resources, although this may be a little unrealistic.

**Comment by paramat** [comment]
I'm ok with sand blobs throughout the world, that's somewhat realistic (i think, sofar?) and will provide resources for making glass for meselamps underground.
Dirt though is organic matter and i'm not keen on having that deep underground, that would be the one precious resource you would need to carry from the surface.

**Comment by paramat** [comment]
:+1:

**Comment by DS-Minetest** [comment]
looks like sand and sandstone doesnt appear in deep underground. but this is a bit offtopic
sure is that cactus and papyrus should need light to grow :+1:

**Comment by paramat** [comment]
Approval from ShadowNinja http://irc.minetest.net/minetest-dev/2016-12-30#i_4773574

**Comment by juhdanad** [comment]
I have tested this, and it worked! It should be merged.

**Comment by Zeno-** [comment]
> All flowers, grass and farming crops have always needed level 13 to grow, this was done deliberately, so that torchlight cannot be used to grow them, which would be unreasonable. 

Unreasonable? You're changing the spirit of minetest!

**Comment by paramat** [comment]
Ideally this should be merged with or after #1481

**Comment by paramat** [comment]
8bc93598c625f18950eff402bc54030b426b5db9

**Pull request closed without merging**
