### PR TITLE
Balance sounds, remove silent water footstep

### LINKED ISSUE #2749: Sounds files need volume balance
Hey

One thing I noticed while playing is that some sounds are very loud compared to others. The first one that is very prominent is footsteps. Googling this show I'm not the only one. Also when watching Minetest Youtube videos, this really stands out. The other one (that I found so far) is doors opening/closing. 

In general I think maybe sounds files need to be balanced a bit. I was also thinking about options for controlling volume for difference categories of sounds but that wouldn't really help if sounds in the same category are not balanced.

For now, I ended up deleting the footstep sound files just because it got kind of annoying. No complaints or disrespect to the sound themselves, they are fine, just the volume in comparison to other sounds in the game is a problem.

I'm not a sound guy so not sure the best solution would be. Editing the sound files directly or change the playback volume in the code if there's support for it?

### PR DESCRIPTION
**Pull request by paramat**
Closes #2749 

I created a sound testing area for my PR #2768 so i decided to make more use of it and check and balance all other MTG sounds.
Some new sounds were added recently and some of these needed a little adjustment.
All MTG sounds were tested for balance, any not appearing in this PR were therefore already balanced.

Many positional sounds were too loud because testing was not done at a close distance.
To balance positional sounds i moved the player as close as possible to the sound, then adjusted for a 'fairly loud but suitably and not uncomfortably loud' volume.

Changes:

* Many footsteps were too loud (as reported in a recent issue):
Wood. Often complained about as a too-loud 'player is wearing clogs' sound.
Dirt.
Stone 'hard footstep'.
Ice footstep.
Metal footstep. The high volume made metal sound thin, hollow and 'tinny', not solid.
* Gravel footstep was actually too quiet =) Gravel is loud to walk on.
* 'default dig choppy' was slightly too loud. It was left undefined so fell back to its engine default gain of 0.5. Now it is defined in the wood sound defaults table as 0.4.
* 'default dig crumbly' was slightly too loud. It was left undefined so fell back to its engine default gain of 0.5. Now it is defined in the dirt sound defaults table as 0.4.
* Active furnace sound was too loud.
* Furnace item smelt was too loud.
* Torch 'on flood' was too loud.
* 'cool lava' was too loud.
* 'item smoke' had undefined gain, defaulting to 1.0, now it is specified as 1.0 for clarity.
* Flint and steel was too loud.
* 'gunpowder burning' was set at gain 2.0. Any value exceeding 1.0 results in a volume that to some extent does not reduce with distance. Now set to 1.0 and volume changes suitably with distance.
* 'tnt ignite' had undefined gain, defaulting to 1.0, now it is specified as 1.0 for clarity.
* Hoe on use was too loud, now balanced with 'default dig crumbly' (note: as this is a positional sound, the balance occurs at 0.3, not 0.4).
* The silent water footstep sound (4) is removed as it often causes swimming sounds to be excessively delayed when first entering the water. Also, excessively long silences can occur when 2 silent sounds are played in sequence.

### CODE REVIEW

**Comment by KaylebJay** [comment]
Nice work, I'll have to test this.

**Comment by paramat** [comment]
This is probably boring and tedious to test, but is an easy PR and has a huge benefit to very many users.
Perhaps a core dev can trust me enough to just approve this?
I have sensitive hearing and have a history of working on music production, so i am good at sound levels.
Also see #2768

**Comment by paramat** [comment]
Simple and easy to review PR with a large benefit to very many users. Many sound levels are poorly balanced, and further balancing was also needed for the new sounds recently added. Therefore seems a fairly important PR.

**Comment by paramat** [comment]
1 year bump =D
This PR really should be merged, it is high priority fundamental maintenance.

The new footstep sounds were merged without their sounds being properly balanced, the intention was too balance the sounds in a follow up PR, which is this PR.
This PR also fixes some broken stuff related to sounds code, and fixes the silent water problem.
Apart from the above, all other sounds have been checked and were balanced if necessary, some were in a very bad state.

I was a core dev when i submitted this PR so i think my approval should still count, meaning only 1 extra approval is needed.
If no-one has time to review, just merge it long before a release and check the levels are ok as you subsequently use MTG, you can always adjust later if necessary. This is very good work and i could be trusted at the time i submitted this.

**Review by sfan5 — APPROVED** [review]
Tested a few, sounds good.

**Review by appgurueu — APPROVED** [review]
Literally sounds well.

**Pull request merged**
