### PR TITLE
Make registered doors and trapdoors public

### PR DESCRIPTION
**Pull request by HavenMKing**
It would be nice to be able to get a list of the doors that have been registered from a global table for modding purposes. A small change, leaves the private _doors table for toggling.

### CODE REVIEW

**Comment by SmallJoker** [comment]
The idea is good. Mods should have a possibility to check what doors are registered.
Please document the two tables in `game_api.txt`, so modders know that these exist and what they contain.

**Comment by paramat** [comment]
@sofar what's your opinion?

**Comment by sofar** [comment]
Needs doc change and the second patch for sure.

I'm neutral. I prefer somewhat opaque APIs unless there is a clear usage, and then I'd prefer a method instead of a global table. The door API was designed that way.

But, *shrug*. mtg is already littered with this way of accessing mod-private data and we've made worse things public.

**Comment by paramat** [comment]
No response for a month, will reopen on progress.

**Pull request closed without merging**
