### PR TITLE
Add patches of bare 'dry dirt' to savanna

### PR DESCRIPTION
**Pull request by paramat**
Tune noise to appear where long dry grass is least dense and shortest.
////////////////////////////

screenshot_20190727_211556

patchy8IND

^ 2000x2000, with no long dry grass to clearly show bare patches

### CODE REVIEW

**Comment by TumeniNodes** [comment]
That looks good.
Now we just need Timon and Pumbaa mobs

Not using `spawn_by` ?

**Comment by sfan5** [comment]
:+1: Very nice

**Comment by paramat** [comment]
Using 'spawn_by' in what way?

**Comment by TumeniNodes** [comment]
> Using 'spawn_by' in what way?

Sorry, nvm I was talking out of my butt. (I had been awake 27 hrs when I made that comment)
I was unsure why these patches of dry dirt were being done as decoration, rather than as a blob. But I _think_ I get it now.

**Comment by paramat** [comment]
Ok =)

Now tuned, new map in first post.
Bare patches now don't get quite as bare, there's always a few dry grass nodes scattered around.

**Pull request merged**
