### PR TITLE
Add Indonesian translations

### PR DESCRIPTION
**Pull request by srifqi**
This PR adds Indonesian translations. Most translations are copied from `mtg_i18n` Weblate project ([link to Indonesian translations](https://hosted.weblate.org/projects/minetest/mtg_i18n/id/)). There are differences from the Weblate version, mostly because of inability to find better translations back then.

**Notes for Indonesian translators:** Please still refer to [the glossary in Weblate](https://hosted.weblate.org/dictionaries/minetest/id/) while translating Minetest. Any discussions about choice of words etc. can be started in [forum](https://forum.minetest.net/viewforum.php?f=32).

**Catatan untuk penerjemah Indonesia:** Mohon tetap rujuk [glosarium di Weblate](https://hosted.weblate.org/dictionaries/minetest/id/) ketika menerjemahkan Minetest. Diskusi tentang diksi dll. dapat dimulai di [forum](https://forum.minetest.net/viewforum.php?f=32).

**Final checks before merge:** (done)
<details>
<summary>List of mods</summary>

- [x] `beds`
- [x] `binoculars`
- [x] `boats`
- [x] `bones`
- [x] `bucket`
- [x] `butterflies`
- [x] `carts`
- [x] `creative`
- [x] `default`
- [x] `doors`
- [x] `dye`
- [x] `farming`
- [x] `fire`
- [x] `fireflies`
- [x] `flowers`
- [x] `game_commands`
- [x] `map`
- [x] `screwdriver`
- [x] `sethome`
- [x] `sfinv`
- [x] `stairs`
- [x] `tnt`
- [x] `vessels`
- [x] `walls`
- [x] `wool`
- [x] `xpanes`
</details>

### CODE REVIEW

**Comment by srifqi** [comment]
(probably off-topic) I found that some strings are not added/updated in `templates.txt`.

4243d288464f9a2d364643ad27c21965c65bda5c (changed string)
- `default:dirt_with_dry_grass`
- `default:dry_dirt`
- `default:dry_dirt_with_dry_grass`
- `default:dry_grass_x`
- `farming:dry_soil`
- `farming:dry_soil_wet`

36b2bcb5f3379cfc28b74974ce74e965821d1493
- `fire:basic_flame` (new string)
- `fire:permanent_flame` (changed string)

e5a7af1c4abaf06ad764bf7c5da058fd136871c0 (new string)
- `farming:cotton_wild`

Do those strings need to be updated first?

**Comment by sfan5** [comment]
> Do those strings need to be updated first?

No. We'll hopefully remember to do this ourselves when feature freeze starts.

**Comment by srifqi** [comment]
This PR is ready.

**Comment by Wuzzy2** [comment]
Did you remember to update the translations for the items with new names (Savanna Dirt, Wild Cotton, etc.)?

**Comment by srifqi** [comment]
Do you mean this PR? I haven't checked for translation updates since my last commit.

**Comment by Wuzzy2** [comment]
List of new strings:
* `fire`:
    * Permanent Fire=
    * Fire=
* `farming`:
    * Savanna Soil=
    * Wet Savanna Soil=
    * Wheat=
    * Cotton=
    * Hoe=
    * Seed=
    * Wild Cotton=
* `default`:
    * Savanna Grass=
    * Dirt with Savanna Grass=
    * Savanna Dirt with Savanna Grass=
    * Savanna Dirt=

**Comment by srifqi** [comment]
Thank you for the list. Translations have been updated.

**Comment by srifqi** [comment]
Thank you for the merge!

**Pull request merged**
