### PR TITLE
Update dirt footstep sounds

### PR DESCRIPTION
**Pull request by jastevenson303**
Fixes a negative DC offset start to the second sound,
adjusts start/end amplitudes.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Your changes look good. Not that it makes an audible difference: in both files there are a few ~8 Hz underlying waves that can't be heard at all.
Perhaps apply a 20 Hz high-pass filter with maximum roll-off?

**Comment by jastevenson303** [comment]
Most of this message went over my head.  At first, I thought you were
saying there wasn't an audible difference between these , and the sounds as
they are now in HEAD.

HAHA!  I'll click the 20 Hz high-pass filter with maximum roll-off button
and push changes (just as soon as I find it.  : )  Glad you spotted this!

**Comment by jastevenson303** [comment]
>Perhaps apply a 20 Hz high-pass filter with maximum roll-off?

Hm, the plugin I chose looked as you said, with a dropdown for roll-off and I selected 6 dB.  (I have no clue what I'm doing, lol.)

**Comment by paramat** [comment]
> Fixes a negative DC offset start to the second sound

You did this by editing or by vertical waveform shifting?

**Comment by SmallJoker** [comment]
Just a little excursion into signal processing:
rolloff demonstration
As the name indicates, the filter lets High frequencies Pass through. The lower frequencies are filtered out by the roll-off amount each decade. In your sample, this means -6 dB (amplifies by factor 0.5) for 2 Hz and -12 dB for 0.2 Hz.
The human ear can not hear such deep sound waves, which makes their existence in these files superfluous.

@paramat I guess that was done by the Audacity plugin that centers it automatically.

The sound files now look better :+1:

**Comment by paramat** [comment]
> Fixes a negative DC offset start to the second sound,

How did you do this? Shifting the whole waveform vertically may not be a good idea as the end of the sound is then not centred.

> adjusts start/end amplitudes.

What do you mean by this?

I used Audacity to apply a 48dB HPF at 20Hz, that would be preferable as your waves still have too much sub frequency in them

**Comment by jastevenson303** [comment]
LOL Krock you knew I'd love the MS Comic Sans.  : )

Paramat I dunno exactly the vocabulary here, but I can tell you I have probably twenty HPF plugins installed on this system, that was just the first one I selected:

screenshot from 2017-12-14 02-55-39

If you want me to alter the sounds further, or differently, just let me know; it's no big deal.  : D

**Comment by jastevenson303** [comment]
>Fixes a negative DC offset start to the second sound,

>How?

Again, probably my poor vocabulary here.  Simply put, this sound file starts out at a non-zero Y.  This means "Click!"

**Comment by paramat** [comment]
Yes i know, i was wondering how you fixed it.
6 dB isn't enough for HPF, it still leaves a large amount of sub-frequency.

My suggestion is:
Start with a HPF at 20Hz and around 48dB.
Then work on the non-zero start after that if necessary, but not by shifting the waveform vertically. A very short fade-in will do the job.

**Comment by jastevenson303** [comment]
That's what I did, paramat.  You want me to do it twice?  Because I can and
will lol.

**Comment by paramat** [comment]
No, first you did:
'Fixes a negative DC offset start to the second sound,
adjusts start/end amplitudes.'
(Both of which i've asked for more details on but you haven't answered).
Then afterwards you did:
'Apply HPF 20 hZ 6dB rolloff.'
As i wrote, the HPF should be applied first because that changes the offset of the waveform start, and may even remove it. Also as i wrote, 6dB is not enough, it's a minor change as youcan see from the waveform and from SmallJoker's waveform.
Any more nonsense and unresponsiveness and i'll close this PR.

**Comment by jastevenson303** [comment]
Yeah I'm confused.

**Comment by jastevenson303** [comment]
Probably krock has the way you want.  I guess I didn't understand and by
all means close this.

**Comment by paramat** [comment]
This has highlighted the 8Hz problem which is good because that needs fixing. Because the audible part of the sound is so small compared to the sub frequencies the sound is used at a high gain, which means the sub frequencies are then at extreme gain, causing possible problems.
So a powerful HPF is needed and this can't be merged as-is.

I'll work on these myself and make a PR.

**Comment by paramat** [comment]
PR #1979

**Comment by jastevenson303** [comment]
Thank you.  I was hoping it wouldn't be too difficult.

**Pull request closed without merging**
