### PR TITLE
fix players in bed counter

### LINKED ISSUE #2111: Sleeping player count keeps getting higher on entering and exiting bed
Player can get messages such as "88/6 players in bed." If someone gets in bed then gets out, the number never goes down, and when the count reaches total player count (such as 6 in this case), the player can optionally skip night (if they opt to not skip, they can keep making number higher), even if only one player is doing this. My server was updated to latest git version less than 2 weeks ago, but the clients have a git version from about 5-7 weeks ago.

### PR DESCRIPTION
**Pull request by bell07**
Do not set players in bed counter up if player already in bed before. This should fix #2111

### CODE REVIEW

**Comment by paramat** [comment]
@poikilos could you test this?

**Comment by poikilos** [comment]
I've manually patched my server and I'll be able to test it soon. I'll make sure I find out which type of bed was being used.

**Comment by poikilos** [comment]
OK so unfortunately...I could not reproduce the bug with the beds from the beds mod (beds:bed_bottom, beds:fancy_bed_bottom), with or without the patch. As it turns out, the player was using a bed from homedecor (was reproducible with homedecor:bed_regular, homedecor:bed_kingsize) and after updating homedecor, my problem went away--I'll post any further info but only homedecor beds were causing the problem for me apparently.

**Comment by bell07** [comment]
Homedecor does not use the minetest_game functionality. The bug in homedecor was fixed in other way: https://github.com/minetest-mods/homedecor_modpack/pull/404 - Just re-count the playes if needed

**Comment by paramat** [comment]
@bell07 so is this bug actually present in MTG beds?

**Comment by bell07** [comment]
The change is based entirelly on the bug report. I was not able to reproduce the issue byself. 
Agree the fix #1969 for #1964 maybe did not work because of this issue, forcing night skip can happen if "9 of 4 player are in bed": https://github.com/minetest/minetest_game/pull/1969#issuecomment-390338187

**Comment by paramat** [comment]
Hmm ok more input needed on whether this PR is useful, i have no idea, @sofar ?

**Comment by bell07** [comment]
This PR get the code more robust against the lay_down() function is called multiple times for the same user with "lay down" parameters even the player is already in bed. 
But I do not see the constellation this can happen, the call from beds mod is "secured" by 
```
if not beds.player[name] then
		lay_down(player, ppos, pos)
```

So if the issue does not appear and does not help for #1969 , we can close this PR unmerged

**Comment by bell07** [comment]
I was runing to the same issue with homedecor and fixed them without understanding the reason for the issue. For "beds" I tried an alternative solution ...

Looking more to the code I understand the issue with homedecor + beds oO
Homedecor uses `beds.kick_players()` that count down bed's player_in_bed variable for standing.
But for sleeping in homedecor's bed count up and show the homedecor's player_in_bed variable.

The homedecor solution is just to give up own player_in_bed and recount the beds.player table each time if needed.

I prefer the homedecor solution for now. The get_player_in_bed() function should be implemented in beds mod and the player_in_bed should be given up. This allow other mods to manipulate the beds.player table without issues.

They are some redundancies in beds and homedecor because beds functions are local only. Propose to enhance beds API by exposing all local functions in beds to beds namespace
```
beds.get_look_yaw(pos)
beds.is_night_skip_enabled()
beds.check_in_beds(players)
beds.get_player_in_bed()
beds.lay_down(player, pos, bed_pos, state, skip)
beds.update_formspecs(finished)
```
Maybe some of them needs to be renamed before gets to be a part of API

**Comment by bell07** [comment]
Issue found with beds vs. homedecor, with fixed homedecor:
2 or more players, enable_bed_night_skip is off to be more flexible in test

Player 1 uses homedecor bed: "1 of 2 in bed"
Player 2 uses beds bed:  "1 of 2 in bed" (wrong)
Player 2 leave the bed: "0 of 2 in beds" by Player 1
Player 2 uses beds bed:  "1 of 2 in bed" (wrong)
Playing around both beds it is easy to get the counter out of sync.
I do not see any way to solve the issue on homedecor site without proposed changes.

**Comment by bell07** [comment]
Updated the fix to the homedecor solution. Tested with both beds and two players, get the counter out of sync not possible anymore

**Comment by paramat** [comment]
Thanks, seems useful then.

**Comment by bell07** [comment]
Upstream changes merged to get PR mergeable again

**Comment by paramat** [comment]
@sofar

**Comment by poikilos** [comment]
@bell07 
Wait a minute, shouldn't
```lua   
	for k,v in pairs(beds.player) do
		player_in_bed = player_in_bed + 1
	end
```
be changed to
```lua
	for k,v in pairs(beds.player) do
        if v then
		  player_in_bed = player_in_bed + 1
	end
```
since variable is set to nil (not removed from table) when laying down?
...the code is same as homedecor so I commented there--see also <https://gitlab.com/VanessaE/homedecor_modpack/commit/a4ca53cc051837201667f598fefc3aafad59f8bf>

**Comment by paramat** [comment]
@sofar could you review?

**Comment by paramat** [comment]
@sofar could you review?

**Comment by sofar** [comment]
#2327 is a rebased version on top of `stable-5`

**Pull request closed without merging**
