### PR TITLE
Spawn mod: Add spawn search API

### LINKED ISSUE #2117: Spawn mod: make the spawning code a global function usable by mods
With a good spawnpoint finding algorithm in place, it could be utilized in order to teleport multiple players apart in a specific radius with a specific coordinate as center point. It can be part API function, part chat command:
- `minetest.spreadplayers(x, z, min_range, max_range, player)`
- `/spreadplayers x z min_range max_range player`

(the player variable would be optional)
////////////////////

EDIT by paramat: Request changed, see new thread title and discussion.

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20181101_124805

For #2630 and part of #2117 
To test, use chat command as shown in screenshot to spawn in an ungenerated part of the world.
Testing code below, mod must depend on 'spawn':
```
core.register_chatcommand("spawn", {
	params = "<X>,<Z>",
	description = "Spawn at position",
	func = function(name, param)
		local teleportee = nil
		local p = {}
		p.x, p.z = string.match(param, "^([%d.-]+)[, ] *([%d.-]+)$")
		p.x = tonumber(p.x)
		p.y = 0
		p.z = tonumber(p.z)
		if p.x and p.z then
			local lm = 31000
			if p.x < -lm or p.x > lm or p.z < -lm or p.z > lm then
				return false, "Cannot teleport out of map bounds!"
			end
			teleportee = core.get_player_by_name(name)
			if teleportee then
				local result = spawn.search(p)
				if result then
					teleportee:set_pos(result)
					return true, "Spawning at "..core.pos_to_string(result)
				end
			end
		end
	end,
})
```

### CODE REVIEW

**Comment by paramat** [comment]
Ready for review, docs added and tested with a testing chat command.

**Comment by rubenwardy** [comment]
I think this would be well suited as a builtin function (although not necessarily used by default)

**Comment by paramat** [comment]
Any more opinions about whether this should go straight into 'builtin'? I would be ok with that.

**Comment by paramat** [comment]
Yes i agree, the API should go in builtin as many games will find this useful (HW).
So WIP and for after 5.0.0 release.

**Comment by paramat** [comment]
I'm also considering adding an option for a worldwide scattered spawn, as this would create very interesting new multiplayer dynamics.

**Comment by paramat** [comment]
Closing for now, i will need to rework this if part of this is moved to engine 'builtin'.

**Comment by paramat** [comment]
@sfan5 i reopened this to not waste this large amount of work.
Perhaps it could be merged and some of the code moved to builtin later?
I do not feel like working on this so perhaps you or another core dev could adopt this PR and alter it if needed?

**Comment by sfan5** [comment]
I planned to work on this feature some time. Might take some inspiration from here.

**Comment by paramat** [comment]
Ok good. Feel free to close this later if necessary.

**Pull request closed without merging**
