### PR TITLE
Farming: allow LBM's for other mods as well.

### LINKED ISSUE #1114: [register_lbm farming api] Name  farming:start_nodetimer_ does not follow naming conversation
Hi,
I have troubles to get a mod working with minetest 0.4.14 which worked fine in 0.4.13
I found out that the problem seems to be in the new farming API line 352.
if you register a new plant with farming.register_plant("mymod:myplant",{...}) you will get an error because lbm does not following "naming conventions"

reproducable: yes

Code from logfile:
```
2016-05-28 18:30:32: ERROR[Main]: ModError: Failed to load and run script from /home/minetest/minetest/bin/../games/minetest/mods/beer_test/init.lua:
2016-05-28 18:30:32: ERROR[Main]: /home/minetest/minetest/bin/../builtin/game/register.lua:62: Name farming:start_nodetimer_beer_test_oats does not follow naming conventions: "beer_test:" or ":" prefix required
2016-05-28 18:30:32: ERROR[Main]: stack traceback:
2016-05-28 18:30:32: ERROR[Main]: 	[C]: in function 'error'
2016-05-28 18:30:32: ERROR[Main]: 	/home/minetest/minetest/bin/../builtin/game/register.lua:62: in function 'check_modname_prefix'
2016-05-28 18:30:32: ERROR[Main]: 	/home/minetest/minetest/bin/../builtin/game/register.lua:85: in function 'register_lbm'
2016-05-28 18:30:32: ERROR[Main]: 	...test/bin/../games/minetest/mods/mtg_core/farming/api.lua:352: in function 'register_plant'
2016-05-28 18:30:32: ERROR[Main]: 	...in/../games/minetest/mods/beer_test/mod_files/plants.lua:242: in main chunk
2016-05-28 18:30:32: ERROR[Main]: 	[C]: in function 'dofile'
2016-05-28 18:30:32: ERROR[Main]: 	...t/minetest/bin/../games/minetest/mods/beer_test/init.lua:21: in main chunk
```

I assume line 353 schould look like this:
```LUA
		name = mname..":start_nodetimer_" .. mname .. "_" .. pname,
```
instead of 
```LUA
		name = "farming:start_nodetimer_" .. mname .. "_" .. pname,
```

### PR DESCRIPTION
**Pull request by sofar**
Fixes #1114

### CODE REVIEW

**Comment by adrido** [comment]
Works. :+1: 
Thanks much for your fast response!

**Comment by paramat** [comment]
:+1:

**Comment by Ekdohibs** [comment]
@sofar: why do you need to override modname checking convention? (the ":" in front). It should work without it...
Else, :+1:

**Comment by paramat** [comment]
Yes i wondered why too.

**Comment by adrido** [comment]
AFAIK this would not work if you want to use this to register from another's mod namespace. 
If you try to register with a leading ":" the [Split function from line  243](https://github.com/sofar/minetest_game/blob/abe59e5c223e96c59ad61bf6e0742b1f416bd95d/mods/farming/api.lua#L243-L244) would make mname = nil. and pname = <modname>
 So the ":" is required for correct registering over modnamespaces

**Comment by sofar** [comment]
lbm registration code does strict mod name checking - I've run into this several times now already, so this is required.

**Comment by paramat** [comment]
Ok :+1: will merge soon.

**Comment by paramat** [comment]
dcf2465441c69550b4a41f8446abdc3981bd5a85

**Pull request closed without merging**
