### PR TITLE
New crack animation texture with more frames

### PR DESCRIPTION
**Pull request by Calinou**
This makes the digging animation smooth (16 frames) – smoother than in Minecraft, which only has 10 frames.

### CODE REVIEW

**Comment by Ombridride** [comment]
This crack animation texture is in my server since 6 or 7 months and i had only heard positives return about it. 
The number of frames isn't too hight, compared to the default crack animation texture wich has just not enough frames, it's not pleasant...

**Comment by paramat** [comment]
-1. I find the cracks too finely detailed, doesn't look like cracks more like fast mould.
I like the smoothness but apparently every frame updates the mesh so less frames is actually better.

**Comment by paramat** [comment]
Hi @Calinou notifying because no comment from you for a year.

**Comment by Cyberpangolin** [comment]
+1 looks really good ingame on Ombridride's server.

I had noticed a difference with the vanilla but I didn't know what until today.

I think it's GREAT, so I want to give my advice.

**Comment by xeranas** [comment]
> This crack texture only darkens nodes, making it hard to see on darker nodes. Can you add some white to the crack?

@ShadowNinja I hope this is not a reason to have those ugly white crack pixels when I punching trees. There are much more blocks in game who would visually benefit from added white alpha channel in crack texture.

Talking about this pull request. I do not like it. Its adds too much cracks making feel that I am in process of  transforming coal block when punshing tree (or any other block). 

IMO adding white alpha channeld alone for existing `crack_anylength.png` would be good enought improvement. But that should be separate pull request if somebody manages to convince minetest devs.

@paramat 
I think it safe to discard this pull request since it has been too long with labels "controversial", "needs improvement" without active participation from pull request op.

**Comment by ShadowNinja** [comment]
This has been dormant a long time and has no sign of being merged.
I'd suggest re-submitting with a compromise number like 8/10 for the number of frames.
The white addition has been done in #338.

**Pull request closed without merging**
