### PR TITLE
Default: Add stone / desert stone / sandstone / obsidian blocks

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160624_031839

screenshot_20160624_032524

screenshot_20160624_025056

screenshot_20160624_030520

default_stone_block128

default_desert_stone_block128

default_sandstone_block128

default_obsidian_block128

This seems an obvious omission, for when players want to build with blocks but without the 'brick wall' visual effect. For example pyramids or any exotic structure. Larger blocks have a more impressive and massive appearence.
Blocks have identical edge-shading to bricks.
Crafting recipes are consistent with other block recipes, i checked some node mods on the forum for recipe conflicts, but please let me know of any missed conflicts.

### CODE REVIEW

**Comment by Fixer-007** [comment]
Finally...

**Comment by tobyplowy** [comment]
@paramat +1 for new building blocks amazing (smile)

**Comment by sofar** [comment]
These look great. Is everyone OK with a 1:1 conversion rate, though? It conserves volume, but I'm not sure that's really needed, since I don't see why there would be a conversion back to normal blocks.

**Comment by Fixer-007** [comment]
>Is everyone OK with a 1:1 conversion rate

I'm ok with it since it is just stone with slightly polished edges :}

**Comment by paramat** [comment]
Brick recipe conserves volume too. It has nothing to do with whether there is a backwards conversion.

**Comment by sfan5** [comment]
Very nice :+1:

**Comment by paramat** [comment]
The stone and desert stone textures could be better i think, but that's for later as bricks would have to be changed too to match. What i'm thinking is reducing the contrast of the surface texture (like Minecraft does) to make the surface look more smooth and polished, i'm not keen on how it looks exactly like rough natural stone.

**Comment by NathanSalapat** [comment]
Nice looking.

**Comment by tobyplowy** [comment]
@paramat the Desert Stone already looks really smooth

**Comment by paramat** [comment]
Indeed i'm unsure, something to consider later.

**Comment by C1ffisme** [comment]
Ooh... I can see some pretty interesting designs made from this.

**Comment by paramat** [comment]
9d6df824d6062fdf8bfd7c6c204753f13b3b1ac7

**Comment by Fixer-007** [comment]
Everyone forgot about slabs and panels... https://i.imgur.com/MssKkUO.png

**Comment by tobyplowy** [comment]
@Fixer-007 true :P

**Comment by sofar** [comment]
Just make a new PR that adds them, or file a feature request.

**Comment by paramat** [comment]
I'm going to do this very soon.

**Pull request closed without merging**
