### PR TITLE
Default: New mese texture. Add missing texture credits

### PR DESCRIPTION
**Pull request by paramat**
Mese texture is a classic-mese-yellow version
of celeron55's texture used in MTv0.4.0
Add missing texture credits for mese crystal
and mese crystal fragment
///////////////////////////////////

screenshot_20160529_075740

screenshot_20160529_075950

screenshot_20160529_080045

mese6ind128

^ Submitted

default_mese_crystal128

^ Current mese crystal for comparison

default_mese_2nd128

default_mese_1st128

^ Classic mese textures by celeron55 used in Minetest 0.4.0

As requested by PilzAdam and sfan5 this has normal lettering.
The letters are raised areas of a single piece of pure material, instead of being seperate from the material, so are only visible due to edge-shine and shadows.
Shadows are very similar to the shadows used in the mese crystal texture.
The texture is faithful to the classic mese textures, being a combination of the two.

### CODE REVIEW

**Comment by MT-Modder** [comment]
Yeah...this seems like a good compromise.

**Comment by benrob0329** [comment]
What if it was a bit darker of a yellow (like the Mese crystal) and the shading was darker to match?

I may be wrong but I fell like it'll look weird in dark areas.

**Comment by Ekdohibs** [comment]
@paramat What if you kept this texture, but with the colors of the current mese texture?

**Comment by paramat** [comment]
Nope, this is a pure yellow like the crystal, i'm not keen on adding a dirty surface using noise, that's too metallic.

**Comment by benrob0329** [comment]
The crystal isn't pure yellow though, it has a greenish tint.

**Comment by Thomas--S** [comment]
How about this as a compromise?


It wouldn't be such an extreme yellow, but it looks quite similar to @paramat's suggestion.

**Comment by paramat** [comment]
That's possibly good, the bright yellow is moved to the highlights. Maybe i'll add something very similar as an alternative.

**Comment by paramat** [comment]
Updated with a texture inspired by Thomas--S's suggestion. See first post for preview.

**Comment by benrob0329** [comment]
+100 !!

**Comment by paramat** [comment]
I might make the edge-shadow slightly darker, also i need to see this in-game to judge.

**Comment by paramat** [comment]
Updated with in-game screenshots, see first comment, i'm happy with this and PR is ready for review/merge.

**Comment by Ekdohibs** [comment]
Seems good now!

**Comment by paramat** [comment]
So happy you like it.

**Comment by paramat** [comment]
541b2d79c7813663feaa50c64151c175aef0f95f

**Pull request closed without merging**
