### PR TITLE
Coniferous litter: Improve textures, greyer and lighter

### PR DESCRIPTION
**Pull request by paramat**
Coniferous litter: Improve textures

Greyer, lighter, reduce lines, remove dark patches.
Shorter and more consistent side texture.
//////////////

screenshot_20180203_220557

### CODE REVIEW

**Comment by benrob0329** [comment]
Judging from the screenshot (I don't have a dev build on this machine yet) it looks like it may be too grey, but I think more importantly it does not blend into the dirt from the side (its a solid line with no color gradient).

**Comment by TumeniNodes** [comment]
I'm working on this. Right now, it's almost seizure inducing : /
sorry if that sounds harsh, it's not meant to be, it's simply an observation.

I have reworked the pattern a bit to reduce that curved bit... give me a day or two to tweak this thing

**Comment by paramat** [comment]
Concerning my submitted texture, it still has brown and orange, dead needles are fairly greyish.

conlitter_lp10_sn55_128

coniferous-pine-needles-16286082

The flicker isn't that bad, we can't remove contrast from textures to try to avoid it, try mip-mapping or some effect.
I'm ok with the blend of the side texture, other side textures are quite abrupt too and that is ok due to the voxel style.

Concerning your new WIP texture, too dark and too grey, but will try anything you come up with.

**Comment by paramat** [comment]
Your new side texture doesn't really need overhang shadow because needles are loose and don't tend to create wide overhangs like grass does.

**Comment by TumeniNodes** [comment]
default_grass
default_grass_side

Sorry, I had my filters still off when I was taking a look at the bed bug, duh.
I think my memory is getting worse again, oh well.

Shadow removed from side.
But I still really wanted to clean up that "banana-is" repeating curve in the original texture for the top.
Do you folks think this looks better or, just stick with my original?

**Comment by paramat** [comment]
I'll try it.

**Comment by TumeniNodes** [comment]
I wonder if the sides for this should be shorter?

**Comment by Ferk** [comment]
Maybe a way to reduce repetitive patterns would be to use world-aligned overlay_tiles so the texture could span 2x2 nodes.

**Comment by TumeniNodes** [comment]
here is a shorter version of the side, it has a very faint hint of a shadow, just enough to express a difference. It's very subtle, and improves the overall look IMO.

![default_grass_side_short[(https://image.ibb.co/ghaxJm/default_grass_side.png)

**Comment by TumeniNodes** [comment]
> Maybe a way to reduce repetitive patterns would be to use world-aligned overlay_tiles so the texture could span 2x2 nodes.

But, would that have an impact on community created texture packs, current and future?
That is something which needs to be taken into consideration
If this were not a voxel/cubic styled game, that might be reasonable.
The more complex situations which are added, the more difficult things start to get in a chain reaction, and the less likely people will want to contribute, and more and more the software becomes less compatible with lesser machines.

Maybe I am being overly dramatic but... when looking at it from a graphics view, simple goes a long way

**Comment by paramat** [comment]
Shorter sides is good, like roughly quarter-coverage, gives more impression of needles dropped on top of dirt. I'll try your texture, the slight shadow is fine.
For these latest textures of yours how did you create the colouring, did you work from the PR texture?

**Comment by TumeniNodes** [comment]
yes, from the PR texture. So this is all still the same texture, just reworked
the colouring is what you chose (which does look good)
I touched up a few pixels to eliminate that horrible swoop-ish line that was in there, and a couple of the large dark patches.
The side, I simply removed 3 pixels up along each row

I still don't like the way the edges work out atm, they needs some more varied colour here and there to eliminate that "blurred line" effect but I will work on that a bit later tonight

**Comment by paramat** [comment]
'Blurred line' effect?

**Comment by TumeniNodes** [comment]
default_grass fixed blurred line

default_grass_side fixed contrast/brightness diff

Blurred line effect: areas where the pixels an array of mostly monotone clolours, with zero abstracting colours, this tends to give off a "blurred line" as in the images below. It is the same row from 2 diff viewpoints.
view 1
view 2

**Comment by paramat** [comment]
Ok will probably use these new textures once tested.

**Comment by paramat** [comment]
Updated PR with new top texture.
Side texture was still darker than the top, and the side length was 1 pixel too long for quarter coverage so i created a new side texture from the new top texture but with identical fringe pattern and shadow shading to TumeniNodes' submission.
New screenshot in first post. Looks even better now, thanks for your work TumeniNodes.

**Comment by TumeniNodes** [comment]
Thank you paramat, just glad I can help.
It does look much better now, and the 1 px shorter is much better.

**Comment by Ezhh** [comment]
Looks good :+1:

**Comment by paramat** [comment]
ca81e9b8c633578b2f42b730a59fcb04412e8779

**Pull request closed without merging**
