### PR TITLE
Properly count players in beds.

### PR DESCRIPTION
**Pull request by sofar**
This is a rebased and slightly rewritten version of mtg #2125.

This applies cleanly on top of `stable-5` and therefore should be ready for merge.

The code looks sane. Other mods can modify `beds.players[<name>]` without issues, so this should address the issue. I have not tested this, however, with other bed mods.

### CODE REVIEW

**Comment by sofar** [comment]
@bell07 can you retest this? Code looks OK. @smalljoker already approved it, this is just cleaned up.

**Comment by paramat** [comment]
Added SmallJoker's approval.

**Comment by bell07** [comment]
Tested with homedecor beds. Does work as expected

**Comment by paramat** [comment]
Note this isn't an urgent bugfix so doesn't need to be added to stable-5.

**Pull request merged**
