### PR TITLE
Add tin block slab and stair

### PR DESCRIPTION
**Pull request by Fixer-007**
Adds long awaited tin block's slab and stair into the game.
default

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by TumeniNodes** [comment]
You beat me too it. This is perfect.
Can a request be made to also add diamond, and clay stairs to this PR? Just asking

**Comment by paramat** [comment]
Clay is too soft and mud-like i think, and seems fairly useless.
Our default texture for diamond will not work well as slab and stair, and it seems too precious to use as a shaped building material. I think i'd rather keep it special and not shapable.

**Comment by Fixer-007** [comment]
Compatible with #1820:
default

**Comment by TumeniNodes** [comment]
I think diamond looks nice but,  will drop the issue now so I am not PR-bombing : )
https://ibb.co/dv3D0F

**Comment by ExeterDad** [comment]
These are very nice. People will be very happy with them.

**Comment by paramat** [comment]
1aafcdd7e0f0c5723b882195aad5b0ffd7293104

**Pull request closed without merging**
