### PR TITLE
Use travis' container-based infrastructure

### PR DESCRIPTION
**Pull request by sfan5**
- we can't use sudo there
- build times should be even faster

### CODE REVIEW

**Comment by xunto** [comment]
Tested it with my game. It looks like it faster without those changes. 

Without:  Elapsed time 28 sec
With: Elapsed time 35 sec

I restated it several times but nothing has changed.

**Comment by xunto** [comment]
Or you can look at [this](https://travis-ci.org/minetest/minetest_game/builds/165636368) and [this](https://travis-ci.org/minetest/minetest_game/builds/165364954).

**Comment by sfan5** [comment]
It seems that it's mostly better if you need multiple builds quickly after eachother.

**Comment by sofar** [comment]
:+1:

squash and merge, I'd say.

**Comment by sofar** [comment]
This is too banal to let sit around. If this breaks travis, we can just revert quickly anyway.

**Comment by sofar** [comment]
b0ae488 (squashed merge)

**Pull request merged**
