### PR TITLE
strip bad color profiles from textures

### PR DESCRIPTION
**Pull request by mdoege**
Removes the annoying "iCCP: known incorrect sRGB profile" error messages on the console when starting minetest_game by stripping offending color profiles.

See forum post at https://forum.minetest.net/viewtopic.php?f=4&t=16351#p246693

### CODE REVIEW

**Comment by paramat** [comment]
What exactly is the change made to the textures? We tried fixing this by converting some to indexed before but it caused visual bugs.

**Comment by paramat** [comment]
Does this change RGBA to indexed alpha? That caused bugs when tried #1397

**Comment by mdoege** [comment]
I basically did "gm mogrify -strip something.png" for the affected images, see my two forum posts (the one I linked to and the one above that). That image operation should simply strip color profiles and comment fields from the image without changing anything else about it.

By the way, I've noticed some of the other textures in minetest_game include EXIF information ("Made with Gimp", etc.), perhaps we should strip that too in the same way to decrease image sizes.

**Comment by paramat** [comment]
Ok this might be ok then, needs testing with leaves set to all 3 qualities, also try enabling mip-mapping to see if anyhting gets worse.

**Comment by mdoege** [comment]
Everything seems to look as before to me in all tests.

Should I amend my pull request with all the other PNGs than can be stripped for size or should that become a separate PR? It would cover an additional 335 images.

**Comment by paramat** [comment]
Separate PR since the others don't produce error messages.

**Comment by mdoege** [comment]
OK. I've just let Python do the math how many bytes stripping all PNGs in minetest_game would save:

before 300083
after 183206
saved 116877

So in other words, about 39%. Not too bad.

**Comment by paramat** [comment]
Surprisingly much actually. Certainly all the 'created with Gimp' comments can go.

**Comment by mdoege** [comment]
Well, some of the 16x16 textures should only be 400 bytes or so, but are over 4k due to embedded color profiles. It quickly adds up.

OK, I've created https://github.com/minetest/minetest_game/pull/1517

**Comment by paramat** [comment]
Reading up on colour profiles it seems they are completely pointless in MT textures?

**Comment by mdoege** [comment]
Yes, color profiles are really only useful e.g. for professional photographers taking photos with expensive cameras in Adobe RGB, combined with proper monitor color calibration tools and a monitor color profile, calibrated printing equipment, etc. For everyone else the assumption that all computer images are in sRGB unless declared otherwise works well enough these days.

**Comment by paramat** [comment]
Ok i support doing this then. i still need to test this though.

**Comment by sofar** [comment]
Fine with this, we've done attempts to clean it up before, and new incorrectly marked color profiles have been used, so this is worth doing.

**Comment by paramat** [comment]
Tested and fine :+1:

**Comment by octacian** [comment]
:+1: 

Will make it so much easier trying to keep track of logs while debugging mods...

**Comment by paramat** [comment]
eb1805ea0a4a91ab755b5665b22de6b8d6c7f184

**Comment by paramat** [comment]
For future reference, in Gimp do:

image > mode > assign colour profile > assign 'RGB workspace (sRGB built-in)'

You can check the colour profile in
image > image properties > colour profile

The 2 textures causing this issue had a different colour profile to 'RGB workspace (sRGB built-in)'.

**Pull request closed without merging**
