### PR TITLE
Rename to Minetest Game

### PR DESCRIPTION
**Pull request by paramat**
Rename in game.conf and documentation
Update game_api.txt documentation for bucket API and tree functions
Fix tab, space and comment formatting in game_api.txt
Rename in mod READMEs

See issue #480 
Similar to #489 but without a new header image (to be changed in a separate PR, the new header must read 'Minetest Game', as 'Minetest' is the engine name. I might attempt a new image myself).
'minetest_game' is changed to 'Minetest Game'.
'Minetest' is changed to 'the Minetest engine'.
'gamemode' is changed to 'subgame'.

### CODE REVIEW

**Comment by paramat** [comment]
From IRC http://irc.minetest.ru/minetest-dev/2015-09-30#i_4409710

ShadowNinja 	paramat: The mods can be separated from the game, so they really are "Minetest 0.4" mods.
03:39 		Otherwise seems good.

So i guess i will change the mod titles to 'Minetest mod: xxx', removing the 0.4 because we may soon be 0.5.

**Comment by PilzAdam** [comment]
IMO the "Game" in the mods header can be kept, since they are part of Minetest Game.

:+1:, regardless of your decision on the mods headers.

**Comment by paramat** [comment]
Thanks for the review, will merge soon as is.

**Comment by paramat** [comment]
8e51f318b3ac9130bb1be4644b379f64e8f60b02

**Pull request closed without merging**
