### PR TITLE
i18n support using gettext logic

### PR DESCRIPTION
**Pull request by netfab**
Hi,

Here is a mod that allows i18n support using gettext tools and logic. I started to translate mods/beds into french as example. I don't know if there's others strings to translate in this mod.

Template po files can be generated using a bash script in scripts/ directory.
Gettext tools xgettext and msgfmt are required to run it.
Packagers can also use this script to build mo files.

Ebuild for gentoo is available on my personal overlay  \:
https://github.com/netfab/overlay/blob/master/games-action/minetest_game/minetest_game-9999-r1.ebuild

### CODE REVIEW

**Comment by Calinou** [comment]
Is this translation client-side? I doubt it…

**Comment by PilzAdam** [comment]
This is server side and it requires to execute a shell script to work properly, so this doesn't work on windows.
This is not acceptable.

**Comment by netfab** [comment]
> it requires to execute a shell script to work properly
No. It requires a shell script to update po templates and to build mo files (developers and packagers stuff), because currently there is no build system. Once the mo files are built, you do not need the script.

**Comment by PilzAdam** [comment]
@netfab So windows guys can't translate their mods?

**Comment by Zeno-** [comment]
@PilzAdam Is this about mods or default_game?

**Comment by netfab** [comment]
@PilzAdam \: Of course they can.
If they want to they simply need to use appropriate tools for their OS, and to create files manually.
Example \: http://gnuwin32.sourceforge.net/packages/gettext.htm

The bash script is there to help developers and packagers to update po templates and to build mo files *all at the same time*. But you can always run commands manually in each mod directory if you want.

I do not use Windows, but you will not accept to translate the entire game juste because Windows can't run a script ?

**Comment by Calinou** [comment]
This is server-side. We need client-side translations done in the engine, not in mods.

**Comment by netfab** [comment]
> This is server-side. We need client-side translations done in the engine, not in mods.

Sorry, I don't get it. Please explain me how strings which are currently
hardcoded in mods/ source code files in this repository could be translated
directly from the engine in another repository using gettext, since these
strings are not available over there. Real question.

All that I know is that my minetest_game version is starting to talk me
in my mother tongue.

**Comment by PilzAdam** [comment]
@netfab This pull request will send the strings in the language of the server to all clients. A proper way to implement translation for servers would be that clients tell the server about their proffered language, and the server sends them the strings in their desired language.

With this pull request a French server would send item descriptions in French to all clients, whether they want French or not.

**Comment by netfab** [comment]
Ok, I got it, thanks. I just found this bug :
https://github.com/minetest/minetest/issues/2270

I think it should be a priority. I know that the game is not finished, but even if the game is improving day by day, it is simply not playable nor testable by someone who do not understand english.

**Comment by paramat** [comment]
@netfab Needs rebase.

**Comment by Wuzzy2** [comment]
Whaaaaat? Are you seriously saying you are accepting this PR?
Wow, I am surprised.
Are there any plans what to do with this as soon Minetest implements *proper* internationalization for mods (https://github.com/minetest/minetest/issues/2270)?

**Comment by paramat** [comment]
Now i read it this doesn't seem acceptable.

**Comment by paramat** [comment]
:-1: From myself and sfan5 http://irc.minetest.ru/minetest-dev/2016-08-16#i_4681579

**Pull request closed without merging**
