### PR TITLE
Avoid error when 'get_player_information' returns 'nil'

### PR DESCRIPTION
**Pull request by paramat**
MTG robustness fix for issue https://github.com/minetest/minetest/issues/9352 , as that may take some time to fix in the engine.

### CODE REVIEW

**Comment by rubenwardy** [comment]
This is terrible

**Comment by paramat** [comment]
Why? What do you suggest?

**Comment by rubenwardy** [comment]
This is a hack which hides the problem. It is much better for a program to crash than to enter an invalid state

**Comment by sfan5** [comment]
A problem with this is that the correct formspec prepend won't be set when player information becomes available later on, it will just stay on the legacy default.

Fixing this in the engine would be much better, of course.

**Comment by paramat** [comment]
Actually yes, this is probably terrible, my mistake =) I do not understand formspec prepend and remember that compatibility was tricky before. I has assumed that `"background[5,5;1,1;gui_formbg.png;true]"` was harmless for clients with older formspec version, that the only result would be the missing of corners on formspecs, which seemed preferable to a crash.

Also of course, there is no point doing this yet when the engine bug may be fixed soon.
Instead i will create an issue to remind us to check whether a workaround is needed for release of 5.2.0 (a workaround probably will not be needed, as the engine bug is fairly high priority).

**Pull request closed without merging**
