### PR TITLE
Fix an issue with the screwdriver being used on glass.

### PR DESCRIPTION
**Pull request by Amaz1**
This "fixes" https://forum.minetest.net/viewtopic.php?f=6&t=13438

When glass has a param2 set, then it has a random amount of a random colour inside it, because no "special_tiles" are defined. This fixes this by setting special_tiles to a blank texture.

I don't know if this is a proper fix, or whether it would be better if things were done in the engine, either disabling the feature, or setting the texture to a blank one when no special tiles are given.

### CODE REVIEW

**Comment by PilzAdam** [comment]
A proper fix would be to change the screwdriver to only rotate nodes with `paramtype2 = "facedir"`.

Maybe adding this additionally would be good, though, for other unintentional changes of param2.

**Comment by est31** [comment]
The only thing what I think the engine has to do is to define a proper `paramtype2` for the volume indicator. Once that is there the engine can perhaps also automatically check whether "special_tiles" is defined, and if not, print a warning or stacktrace or so.

**Comment by RealBadAngel** [comment]
@est31, thats the only way

**Comment by Ekdohibs** [comment]
I think that there should be something in the engine too for checking param2, and that the screwdriver mod should be fixed, not the glass definition.

**Comment by paramat** [comment]
> The only thing what I think the engine has to do is to define a proper paramtype2 for the volume indicator.

Maybe, but glasslike nodes should be facedir if wanted, being rotatable is more important than having the liquid tank feature.
Glass nodes are meant to be solid glass, this liquid tank idea should never have been allowed.

**Comment by sofar** [comment]
Posted a (tested) patch that nop's the screwdriver actions on any node that isn't a facedir paramtype2.

Mods can still make glass "facedir" by changing the nodedef for glasslike nodes, to get screwdriver functionality back.

I'm not sure this is the proper solution, but thought it may help to signal users that the fluid level in glasslike nodes is a "special" thing and not something the screwdriver is supposed to manipulate.

**Pull request closed without merging**
