### PR TITLE
Use default.after_place_leaves() for apple

### PR DESCRIPTION
**Pull request by MT-Modder**
Does the same thing with less code.

### CODE REVIEW

**Comment by paramat** [comment]
Possibly good but 'default.after_place_leaves' does not have 'if placer:is_player() then'. Not sure if that's important or if the leaves function should have that too.

**Comment by sofar** [comment]
No, this doesn't do the same thing as the original code. It omits checking if placer:is_player().

Now, I realize that there's likely not very many mods around that call minetest.place_node() to place an apple, but if that exists, then that apple would never leafdecay+drop. The intent of the original code was to allow that to happen.

So, I'm neutral about this. It's a tiny code cleanup that removes a far-fetched scenario.

**Comment by MT-Modder** [comment]
I didn't think of that. Maybe the check should be added to the function instead.

**Comment by sofar** [comment]
That sounds like an entirely reasonable change to me, and then you can keep the current patch change as well.

**Comment by MT-Modder** [comment]
This is an unneeded change...pointless.

**Pull request closed without merging**
