### PR TITLE
Strip metadata from PNG `mods/default` textures

### PR DESCRIPTION
**Pull request by Zweihorn**
Reduces significantly the size of PNG texture files found being sized 4 kB and above.
The selected files were processed with the `optipng -o2 -strip all <file>` command line.

_The [OptiPNG](http://optipng.sourceforge.net/) program shall attempt to optimize PNG files, i.e. reduce their size to a minimum, without losing semantic information. In addition, this program shall perform a suite of  auxiliary  functions like integrity checks, metadata recovery and pixmap-to-PNG conversion._

A brief test with a MT 5.0.1 client with digging dirt and emptying buckets of lava, river water and water showed no apparent issues but burned all trees nearby.

Hope this helps.

### CODE REVIEW

**Comment by Calinou** [comment]
If we're going to optimize all images (and increase Git history size), we might want to optimize it even further. Using [oxipng](https://github.com/shssoichiro/oxipng), this can be done with `oxipng -o6 --strip --zopfli **/*.png`.

**Comment by Zweihorn** [comment]
Oh sorry, the listing inside the commit was only ment for transparency.

1. Does this bother you or GitHub?
1. Is a reduction of texture files a pointless task?
However, the file `heart.png` showed a 97.81% decrease.

Naturally, there may be other tools. The [`optipng` tool has other options too](https://forum.minetest.net/viewtopic.php?f=4&t=16351&p=348322#p347125) and I intentionally avoided to touch all files.

**Comment by Calinou** [comment]
> Does this bother you or GitHub?

By "history size", I meant the total file size of the repository once you clone it. Unlike text files, Git doesn't handle binary files using delta compression; all revisions of a binary file will be downloaded when you clone a repository. A large repository takes more time to clone for people with slower connections; hence, we should try to optimize images once and do it well :slightly_smiling_face:

> Is a reduction of texture files a pointless task?

Definitely not, it matters when people join a server for the first time.

**Comment by sofar** [comment]
It's best done right before a major release :)

**Comment by Zweihorn** [comment]
> we should try to optimize images once and do it well

> It's best done right before a major release

So you propose to delay for an indefinite period?

You must be joking.  No offence but I would call it rather unfortunate that this was missed for the 5.x major release and you want to wait for 6.x apparently.

Please note there are several more files to be reduced in size by 50% or more which are in other folders of the mods tree besides the 'default' mod.

**Comment by paramat** [comment]
> we might want to optimize it even further.

Depends what this further optimisation includes.

Stripping metadata is well worth doing as it can cause a large file size reduction. However, apart from that, these textures have been optimised several times in the past and small additional optimisations are not important.
So this PR is probably fine as it is, but indeed it might be better to wait until just before release of 5.1.0, which will only be a few months.

**Comment by paramat** [comment]
So what exactly does `optipng -o2 -strip all <file>` do, just removes comments?

**Comment by Zweihorn** [comment]
Thank you all for the consideration and the advice. I appreciate the 'maintenance' tag.
Easily understood and waiting for a minor release seems to be reasonable.

This PR and the list of files took already into account the majority of the PNG files can be called optimized.  The optimization rates are 80% and better for all of the 20 files selected. So 'mods/default' was overlooked in the past release apparently.

IMHO one should not seek to optimize too far and should avoid tinkering too much with the optimization levels of the tools.  AFAIK from some tests on the mods tree the outcome may be limited to the majority of files.

What about an optimization threshold?  Taking into account the a.m. 'history size' argument I would propose to set a 10% threshold. Thus intentionally ignoring the huge majority of the PNG files and aim for a reasonable list of files which can be sufficiently optimized.

See you again just before release of 5.1.0 in a few months hopefully. Happy hacking.

**Pull request closed without merging**
