### PR TITLE
Jungle plant aliases

### PR DESCRIPTION
**Pull request by godisgood4**
Adds aliases to allow jungle plants to be accessed using the new node
naming convention

### CODE REVIEW

**Comment by paramat** [comment]
:-1: I think it's best people get used to the one version in use, 2 is more confusing to remember. Aliases are best avoided if possible.

**Comment by godisgood4** [comment]
My idea here was to reduce confusion in the case that a non-programmer downloads Minetest and does /give that they wouldn't be confused when pine_tree works but jungle_tree doesn't. It wasn't specifically meant for programmers and I would totally expect the old name to be used in all programming related cases. 😊

**Comment by sfan5** [comment]
:-1: Agree, we have a creative inventory, we don't need aliases in different naming conventions.

**Comment by godisgood4** [comment]
Will be closing

**Pull request closed without merging**
