### PR TITLE
Default: Bookshelf has 2 openings instead of 4

### PR DESCRIPTION
**Pull request by paramat**
Make rotatable with 'paramtype2 = facedir'
///////////////////////////////

screenshot_20160524_053611

See #1104 
Has a surprising amount of support in the issue thread.

### CODE REVIEW

**Comment by benrob0329** [comment]
+1

**Comment by sofar** [comment]
@paramat we could consider adding an LBM that automatically rotates bookshelves if we find that the 2 open sides are blocked.

**Comment by paramat** [comment]
Nah, i'd rather avoid LBM code, any auto-rotate will still get it wrong in many cases so players will still usually have to manually rotate.

**Comment by paramat** [comment]
Approved by sfan5 http://irc.minetest.ru/minetest-dev/2016-05-25#i_4619699

**Comment by paramat** [comment]
37347d40f4668ab2ed2e231e3008fd0bbb947df5

**Comment by WSDguy2014** [comment]
Worst texture change i have ever seen in newest update 0.4.15. You NERVED bookshelf texture sides to prevent look like a Minecraft-like texture? Bookshelf texture on 2 sides makes sense in real-life instead of look like odd/weird on 4 sides? I hate you, and some contributes like sofar, merged "torches" mod at "minetest_game" subgame. 3D torches, kinda cool, but it sucks, it has also 2D flame part are still here at standing torches (https://forum.minetest.net/viewtopic.php?f=11&t=14359), better use particle spawner for smoke instead of extra 2D flame part. celeron55 is really good main developer of Minetest, but contributes like paramat and sofar sucks. Worst update ever in 0.4.15... :-1: 




I rather to install Minecraft subgame for Minetest, but not yet...

**Comment by rubenwardy** [comment]
It may be hard to believe, but some people don't think about Minecraft when designing this game. MTG does not aim to be loyal at all to MC. I support this change, it makes the bookcases look nicer

Having paramat and sofar as MTG developers is probably the best thing to happen to this subgame in terms of progress - we're actually seeing it become more complete.

**Comment by NathanSalapat** [comment]
@WSDguy2014 I mean, minecraft is a thing, if you want to play something that is like minecraft, just play it.

**Pull request closed without merging**
