### PR TITLE
Make walls connect to nodes in a new `wall_connected` group

### PR DESCRIPTION
**Pull request by alek13**
`walls`: add ability to specify group `wall_connected` for blocks to which the walls will be connected

### CODE REVIEW

**Comment by sfan5** [comment]
What's the use case here? I don't get it.

**Comment by alek13** [comment]
@sfan5 , any chance that it will be merged ?

**Comment by alek13** [comment]
@sfan5 ?

**Comment by alek13** [comment]
@sfan5 / @appgurueu , add info into `game_api.txt`

**Review by appgurueu — APPROVED** [review]
There are a couple unrelated trailing whitespace changes and the group list is for some reason indented by 1 space but I don't care

**Comment by alek13** [comment]
@sfan5 / @appgurueu merge ?

**Pull request merged**
