### PR TITLE
grass spread without ABM

### PR DESCRIPTION
**Pull request by MarkuBu**
This PR includes a method to spread dirt_with_grass and dirt_with_dry_grass without ABM. But it includes some other features.

I don't know if this is useful for MTG. I don't want to maintain it, but maybe someone else can use this for an ABM less approach

### CODE REVIEW

**Comment by paramat** [comment]
Ew i don't like this, our grass spreading method is quite new and works really well fo many soil surface types.

**Comment by MarkuBu** [comment]
I agree that my code is is a bit hacky. Will optimize it a bit. But it was necessary to remove the default ABMs for my full grass blocks, so I decided to try it with node timers

**Comment by sfan5** [comment]
> node timers for every single grass node

pls no

**Comment by MarkuBu** [comment]
Well, maybe you are right and node timer is not the best idea for this. I can't tell this yet because the profiler doesn't measure node timers

But is it possible to run these checks without a pull request? It is helpful to check the code

**Comment by paramat** [comment]
I watched your video and as part of your full grass code it is impressive, but just not for MTGame i feel.

**Comment by 0-afflatus** [comment]
I wouldn't call this 'hacky', it's just over-complicated and not generalised enough. I have considered this approach too, but I think grass spread is exactly the sort of thing that ABMs are designed for.

**Comment by MarkuBu** [comment]
You are right. Maybe not everything makes sense with node timers. It was an experiment. Maybe I try something different

And it is only complicated because of the full grass blocks with half grass below

**Comment by paramat** [comment]
This belongs in issues since it is not coded for merging.

**Comment by sofar** [comment]
I'm open for exploring other ways of spreading grass, but this is really rough code - indentation is wrong, we shouldn't change mapgen decoration, vmanip use should not be needed, etc. I feel that it's way too much code to achieve this, too.

Either this should be marked WIP or we should close.

**Comment by paramat** [comment]
3 disapprovals, closing.

**Comment by MarkuBu** [comment]
> I feel that it's way too much code to achieve this, too.

It is much code because it does more than just spread grass

But I'm not sure myself if an ABM wouldn't be the better solution. I'll leave this branch for inspiration

**Pull request closed without merging**
